- core-infrastructure/main.tf
- core-infrastructure/output.tf
- core-infrastructure/pipelines/build.yaml
- core-infrastructure/pipelines/terraform.yaml
- core-infrastructure/provider.tf
- core-infrastructure/terraform.tfvars
- core-infrastructure/variables.tf
1.  Add core infrastructure terraform (App Insights & Key Vault)
2.  Manual pipeline (with no triggers, etc) for initial setup - will require devops library to pass parameter to pipeline
> Add terraform for core infrastructure and build / deployment pipeline

- platform/src/db/EducationBenchmarking.Platform.Database/EducationBenchmarking.Platform.Database.csproj
- platform/src/db/EducationBenchmarking.Platform.Database/packages.lock.json
- platform/src/search/EducationBenchmarking.Platform.Search/EducationBenchmarking.Platform.Search.csproj
- platform/src/search/EducationBenchmarking.Platform.Search/packages.lock.json
- platform/tests/EducationBenchmarking.Platform.Tests/EducationBenchmarking.Platform.Tests.csproj
- platform/tests/EducationBenchmarking.Platform.Tests/packages.lock.json
- web/src/EducationBenchmarking.Web/EducationBenchmarking.Web.csproj
- web/src/EducationBenchmarking.Web/packages.lock.json
- web/tests/EducationBenchmarking.Web.A11yTests/EducationBenchmarking.Web.A11yTests.csproj
- web/tests/EducationBenchmarking.Web.A11yTests/packages.lock.json
- web/tests/EducationBenchmarking.Web.E2ETests/EducationBenchmarking.Web.E2ETests.csproj
- web/tests/EducationBenchmarking.Web.E2ETests/packages.lock.json
- web/tests/EducationBenchmarking.Web.Integration.Tests/EducationBenchmarking.Web.Integration.Tests.csproj
- web/tests/EducationBenchmarking.Web.Integration.Tests/packages.lock.json
- web/tests/EducationBenchmarking.Web.Tests/EducationBenchmarking.Web.Tests.csproj
- web/tests/EducationBenchmarking.Web.Tests/packages.lock.json
Clean up - adding package lock setting to csproj files
> Adds package lock setting to csproj files

- core-infrastructure/main.tf
- core-infrastructure/pipelines/jobs-core-deployment.yaml
Adds service to core resources
> Adds service to core resources

- web/EducationBenchmarking.Web.sln
- web/nuget.config
- web/pipelines/build.yaml
- web/pipelines/jobs-web-deployment.yaml
- web/pipelines/steps-web-build.yaml
- web/terraform/main.tf
- web/terraform/provider.tf
- web/terraform/terraform.tfvars
- web/terraform/variables.tf
- Terraform for web app (resource group + app service & plan)
- Build & deploy pipeline for web app
> Adds terraform and pipeline for web app

- platform/pipelines/build.yaml
Add conditions for pr in platform pipeline.
> Add conditions for pr in platform pipeline

- platform/EducationBenchmarking.Platform.sln
- platform/src/abstractions/EducationBenchmarking.Platform.Domain/EducationBenchmarking.Platform.Domain.csproj
- platform/src/abstractions/EducationBenchmarking.Platform.Domain/LocalAuthority.cs
- platform/src/abstractions/EducationBenchmarking.Platform.Domain/School.cs
- platform/src/abstractions/EducationBenchmarking.Platform.Domain/Trust.cs
- platform/src/abstractions/EducationBenchmarking.Platform.Domain/packages.lock.json
- platform/src/abstractions/EducationBenchmarking.Platform.Infrastructure/EducationBenchmarking.Platform.Infrastructure.csproj
- platform/src/abstractions/EducationBenchmarking.Platform.Infrastructure/EducationBenchmarking.Platform.Infrastructure.csproj.DotSettings
- platform/src/abstractions/EducationBenchmarking.Platform.Infrastructure/Search/ISearchService.cs
- platform/src/abstractions/EducationBenchmarking.Platform.Infrastructure/Search/LocalAuthoritySearchService.cs
- platform/src/abstractions/EducationBenchmarking.Platform.Infrastructure/Search/Requests/PostSearchRequest.cs
- platform/src/abstractions/EducationBenchmarking.Platform.Infrastructure/Search/Requests/PostSuggestRequest.cs
- platform/src/abstractions/EducationBenchmarking.Platform.Infrastructure/Search/SchoolSearchService.cs
- platform/src/abstractions/EducationBenchmarking.Platform.Infrastructure/Search/SearchOptions.cs
- platform/src/abstractions/EducationBenchmarking.Platform.Infrastructure/Search/SearchOutput.cs
- platform/src/abstractions/EducationBenchmarking.Platform.Infrastructure/Search/SearchService.cs
- platform/src/abstractions/EducationBenchmarking.Platform.Infrastructure/Search/TrustSearchService.cs
- platform/src/abstractions/EducationBenchmarking.Platform.Infrastructure/packages.lock.json
- platform/src/apis/EducationBenchmarking.Platform.Api.Establishment/EducationBenchmarking.Platform.Api.Establishment.csproj
- platform/src/apis/EducationBenchmarking.Platform.Api.Establishment/LocalAuthoritiesFunctions.cs
- platform/src/apis/EducationBenchmarking.Platform.Api.Establishment/SchoolsFunctions.cs
- platform/src/apis/EducationBenchmarking.Platform.Api.Establishment/TrustsFunctions.cs
- platform/src/apis/EducationBenchmarking.Platform.Api.Establishment/packages.lock.json
- platform/src/apis/abstractions/EducationsBenchmarking.Platform.Infrastructure/packages.lock.json
Initial scaffold for platform search
> Initial scaffold for platform search

- web/src/EducationBenchmarking.Web/Constants.cs
- web/src/EducationBenchmarking.Web/Controllers/Api/SchoolExpenditureController.cs
- web/src/EducationBenchmarking.Web/EducationBenchmarking.Web.csproj
- web/src/EducationBenchmarking.Web/Extensions/HttpClientBuilderExtensions.cs
- web/src/EducationBenchmarking.Web/Extensions/ServiceCollection.cs
- web/src/EducationBenchmarking.Web/Infrastructure/Apis/ApiSettings.cs
- web/src/EducationBenchmarking.Web/Infrastructure/Apis/SchoolApi.cs
- web/src/EducationBenchmarking.Web/Program.cs
- web/src/EducationBenchmarking.Web/Properties/launchSettings.json
- web/src/EducationBenchmarking.Web/appsettings.Development.json
- web/src/EducationBenchmarking.Web/packages.lock.json
- web/terraform/main.tf
- web/tests/EducationBenchmarking.Web.Integration.Tests/packages.lock.json
- web/tests/EducationBenchmarking.Web.Tests/packages.lock.json
Add school expenditure end point to web api client
[AB#187930](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/187930)
> Adds school expenditure end point to api client

- .gitignore
- web/src/EducationBenchmarking.Web/AssetSrc/scss/main.scss
- web/src/EducationBenchmarking.Web/EducationBenchmarking.Web.csproj
- web/src/EducationBenchmarking.Web/Views/Shared/_Layout.cshtml
- web/src/EducationBenchmarking.Web/gulpfile.js
- web/src/EducationBenchmarking.Web/package-lock.json
- web/src/EducationBenchmarking.Web/package.json
Upgrades web app to use govuk frontend v5
> Upgrades web app to use govuk frontend v5

- front-end-components/pipelines/front-end.yaml
> yaml file 

- web/tests/EducationBenchmarking.Web.A11yTests/EducationBenchmarking.Web.A11yTests.csproj
- web/tests/EducationBenchmarking.Web.A11yTests/Features/Accessibility.feature
- web/tests/EducationBenchmarking.Web.A11yTests/Features/Accessibility.feature.cs
- web/tests/EducationBenchmarking.Web.A11yTests/Steps/AccessibilitySteps.cs
- web/tests/EducationBenchmarking.Web.A11yTests/TestSupport/Config.cs
- web/tests/EducationBenchmarking.Web.A11yTests/appsettings.json
- web/tests/EducationBenchmarking.Web.A11yTests/packages.lock.json
added accessibility tests for newly build pages for ticket  [AB#188095](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/188095)
> added accessibility tests for the newly build pages.

- web/src/EducationBenchmarking.Web/Controllers/ErrorController.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/WhenViewingErrors.cs
> Clean up error controller

- platform/src/apis/EducationBenchmarking.Platform.Api.Establishment/SchoolsFunctions.cs
- platform/src/apis/EducationBenchmarking.Platform.Api.Establishment/TrustsFunctions.cs
- web/src/EducationBenchmarking.Web/AssetSrc/js/findOrganisation/findOrganisationView.jsx
- web/src/EducationBenchmarking.Web/Constants.cs
- web/src/EducationBenchmarking.Web/Controllers/FindOrganisationController.cs
- web/src/EducationBenchmarking.Web/Controllers/SchoolController.cs
- web/src/EducationBenchmarking.Web/Controllers/SchoolExpenditureController.cs
- web/src/EducationBenchmarking.Web/Controllers/TrustController.cs
- web/src/EducationBenchmarking.Web/Infrastructure/Apis/EstablishmentApi.cs
- web/src/EducationBenchmarking.Web/Services/FinanceService.cs
- web/src/EducationBenchmarking.Web/ViewComponents/OrganisationHeader.cs
- web/src/EducationBenchmarking.Web/ViewModels/Components/OrganisationHeaderViewModel.cs
- web/src/EducationBenchmarking.Web/ViewModels/FindOrganisationViewModel.cs
- web/src/EducationBenchmarking.Web/ViewModels/TrustViewModel.cs
- web/src/EducationBenchmarking.Web/Views/School/Index.cshtml
- web/src/EducationBenchmarking.Web/Views/Shared/Components/OrganisationHeader/Default.cshtml
- web/src/EducationBenchmarking.Web/Views/Trust/Index.cshtml
- web/tests/EducationBenchmarking.Web.Integration.Tests/BenchmarkingWebAppClient.cs
Refactor find organisation and school views
> Refactor find organisation and school views

- front-end-components/src/chart-dimensions.tsx
- front-end-components/src/components/school-expenditure/administrative-supplies.tsx
- front-end-components/src/components/school-expenditure/catering-staff-services.tsx
- front-end-components/src/components/school-expenditure/educational-ict.tsx
- front-end-components/src/components/school-expenditure/educational-supplies.tsx
- front-end-components/src/components/school-expenditure/non-educational-support-staff.tsx
- front-end-components/src/components/school-expenditure/other-costs.tsx
- front-end-components/src/components/school-expenditure/premises-staff-services.tsx
- front-end-components/src/components/school-expenditure/teaching-support-staff.tsx
- front-end-components/src/components/school-expenditure/total-expenditure.tsx
Adds calculation for different chart dimensions
[AB#187078](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/187078)
> Adds calculation for different chart dimensions

- front-end-components/src/components/chart-wrapper.tsx
- front-end-components/src/components/horizontal-bar-chart/horizontal-bar-chart.test.tsx
- front-end-components/src/components/horizontal-bar-chart/horizontal-bar-chart.tsx
- front-end-components/src/components/school-expenditure/administrative-supplies.tsx
- front-end-components/src/components/school-expenditure/catering-staff-services.tsx
- front-end-components/src/components/school-expenditure/educational-ict.tsx
- front-end-components/src/components/school-expenditure/educational-supplies.tsx
- front-end-components/src/components/school-expenditure/non-educational-support-staff.tsx
- front-end-components/src/components/school-expenditure/other-costs.tsx
- front-end-components/src/components/school-expenditure/premises-staff-services.tsx
- front-end-components/src/components/school-expenditure/teaching-support-staff.tsx
- front-end-components/src/components/school-expenditure/total-expenditure.tsx
- front-end-components/src/components/table-chart/table-chart.tsx
- front-end-components/src/services/school-api.tsx
- front-end-components/src/types.tsx
- platform/src/apis/EducationBenchmarking.Platform.Api.Insight/Models/PagedSchoolExpenditure.cs
- platform/src/apis/EducationBenchmarking.Platform.Api.Insight/Models/SchoolExpenditure.cs
- web/src/EducationBenchmarking.Web/Domain/SchoolExpenditure.cs
- web/src/EducationBenchmarking.Web/EducationBenchmarking.Web.csproj
Adds additional data to the view as table option [AB#185872](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/185872)
> Adds additional data to the view as table option

- front-end-components/src/components/toggle-chart-mode.tsx
- front-end-components/src/types.tsx
- front-end-components/src/views/compare-your-school.tsx
Refactor chart mode toggle to reusable component
> Refactor chart mode toggle to reusable component

- web/src/EducationBenchmarking.Web/Controllers/SchoolWorkforceController.cs
- web/src/EducationBenchmarking.Web/ViewModels/SchoolWorkforceViewModel.cs
- web/src/EducationBenchmarking.Web/Views/SchoolWorkforce/Index.cshtml
- web/src/EducationBenchmarking.Web/Views/Shared/Components/BenchmarkWorkforce/Default.cshtml
Adds razor view, and controller, etc, for workforce data
[AB#185925](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/185925)
> Adds razor view, and controller, etc, for workforce data

- web/src/EducationBenchmarking.Web/Controllers/SchoolInvestigationAreaController.cs
- web/src/EducationBenchmarking.Web/Controllers/SchoolPlanningController.cs
- web/src/EducationBenchmarking.Web/Program.cs
- web/src/EducationBenchmarking.Web/ViewModels/SchoolInvestigationViewModel.cs
- web/src/EducationBenchmarking.Web/ViewModels/SchoolPlanningViewModel.cs
- web/src/EducationBenchmarking.Web/Views/SchoolInvestigationArea/Index.cshtml
- web/src/EducationBenchmarking.Web/Views/SchoolPlanning/Index.cshtml
- web/src/EducationBenchmarking.Web/Views/Shared/_Layout.cshtml
- web/tests/EducationBenchmarking.Web.A11yTests/EducationBenchmarking.Web.A11yTests.csproj
- web/tests/EducationBenchmarking.Web.E2ETests/EducationBenchmarking.Web.E2ETests.csproj
- web/tests/EducationBenchmarking.Web.E2ETests/Program.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/BenchmarkingWebAppClient.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/BenchmarkingWebAppFactory.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/ClientBase.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/DocumentAssert.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/EducationBenchmarking.Web.Integration.Tests.csproj
- web/tests/EducationBenchmarking.Web.Integration.Tests/HtmlExtensions.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/WhenViewingSchoolWorkforce.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/WhenViewingServiceHome.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/packages.lock.json
- web/tests/EducationBenchmarking.Web.Tests/EducationBenchmarking.Web.Tests.csproj
Adds initial integration tests for workforce benchmark page.
Plus, coverage for home page and placeholder for additional test cases
[AB#185925](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/185925)
> Initial integration tests

- front-end-components/src/components/school-expenditure/expenditure-accordion.tsx
- front-end-components/src/components/school-expenditure/utilities.tsx
- front-end-components/src/services/school-api.tsx
- platform/src/apis/EducationBenchmarking.Platform.Api.Insight/Models/SchoolExpenditure.cs
- web/src/EducationBenchmarking.Web/Domain/SchoolExpenditure.cs
Adds utilities charts to school cost comparison page.
[AB#186925](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/186925)
> Adds utilities charts to school cost comparison page

- bau/README.md
- bau/src/config/config.py
- bau/src/controllers/data_load_controller.py
- bau/src/controllers/metricrag_controller.py
- bau/src/helpers/area_benchmark_set_calculator_helper.py
- bau/src/helpers/pupil_benchmark_set_calculator_helper.py
- bau/src/helpers/sp_my_comparison_area.py
- bau/src/helpers/sp_my_comparison_area_mix.py
- bau/src/helpers/sp_my_comparison_area_ms.py
- bau/src/helpers/sp_my_comparison_pupils.py
- bau/src/helpers/sp_my_comparison_pupils_mix.py
- bau/src/helpers/sp_my_comparison_pupils_ms.py
- bau/src/main.py
A quick rewrite of the stored procedures used by the VMFI in the generation of their benchmark comparator sets. 
Used as a workaround to bypass issues present in the existing VMFI pipelines.
> adding VMFI comparator script rewrite

- platform/src/apis/EducationBenchmarking.Platform.Api.Establishment/Db/SchoolDb.cs
- platform/src/apis/EducationBenchmarking.Platform.Api.Establishment/SchoolsFunctions.cs
- platform/tests/EducationBenchmarking.Platform.ApiTests/Features/EstablishmentSchools.feature
- platform/tests/EducationBenchmarking.Platform.ApiTests/Features/EstablishmentTrusts.feature
- platform/tests/EducationBenchmarking.Platform.ApiTests/Steps/EstablishmentLocalAuthoritiesSteps.cs
- platform/tests/EducationBenchmarking.Platform.ApiTests/Steps/EstablishmentSchoolsSteps.cs
- platform/tests/EducationBenchmarking.Platform.ApiTests/Steps/EstablishmentTrustsSteps.cs
Adds functional tests for establishment endpoints
[AB#185789](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/185789)
> Adds functional tests for establishment endpoints

- bau/README.md
added description of bau vmfi script rewrite and simple instructions on how to run.
> updated readme

- web/tests/EducationBenchmarking.Web.Integration.Tests/BenchmarkingWebAppClient.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/Paths.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/WhenViewingSchool.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/WhenViewingSchoolComparison.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/WhenViewingSchoolWorkforce.cs
integration tests added to confirm behaviour of the schools, comparison, workforce, and investigation pages
> integration tests added

- documentation/testing/Decisions/Testing-Pipeline-SetupOptions.md
The decision regarding our testing pipeline strategy will significantly impact the efficiency and effectiveness of our development process. I propose that we review these options collectively, considering our project's specific needs, infrastructure capabilities, and desired testing outcomes.
Please feel free to provide your feedback and preferences, and let's collaborate to arrive at a consensus on the most suitable approach for our testing pipelines.
> Testing Pipeline decision document

- web/tests/EducationBenchmarking.Web.A11yTests/Features/Accessibility.feature
- web/tests/EducationBenchmarking.Web.A11yTests/Features/Accessibility.feature.cs
- web/tests/EducationBenchmarking.Web.A11yTests/Steps/AccessibilitySteps.cs
added checked for workforce page, compare your costs page and refactored the output of the tests
[AB#185925](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/185925)
> added checks for the workforce page

- core-infrastructure/terraform/main.tf
Updates the Application Insights to a Log Analytics Workspace as Classic Application Insights is deprecated
> Updates App Insights to use Log Analytics Workspace

- web/tests/EducationBenchmarking.Web.A11yTests/EducationBenchmarking.Web.A11yTests.csproj
- web/tests/EducationBenchmarking.Web.A11yTests/Features/Accessibility.feature
- web/tests/EducationBenchmarking.Web.A11yTests/Features/Accessibility.feature.cs
- web/tests/EducationBenchmarking.Web.A11yTests/Hooks/Hook.cs
- web/tests/EducationBenchmarking.Web.A11yTests/Hooks/PageHook.cs
- web/tests/EducationBenchmarking.Web.A11yTests/Steps/AccessibilitySteps.cs
- web/tests/EducationBenchmarking.Web.A11yTests/TestSupport/Config.cs
- web/tests/EducationBenchmarking.Web.E2ETests/Hooks/Hook.cs
- web/tests/EducationBenchmarking.Web.E2ETests/Hooks/PageHook.cs
- web/tests/EducationBenchmarking.Web.E2ETests/Pages/BenchmarkWorkforcePage.cs
- web/tests/EducationBenchmarking.Web.E2ETests/Pages/CompareYourCostsPage.cs
- web/tests/EducationBenchmarking.Web.E2ETests/Pages/SchoolHomePage.cs
- web/tests/EducationBenchmarking.Web.E2ETests/Pages/SearchOrganizationPage.cs
- web/tests/EducationBenchmarking.Web.E2ETests/Pages/ServiceLandingPage.cs
- web/tests/EducationBenchmarking.Web.E2ETests/Steps/BenchmarkWorkforceSteps.cs
- web/tests/EducationBenchmarking.Web.E2ETests/Steps/CompareYourCostsSteps.cs
- web/tests/EducationBenchmarking.Web.E2ETests/Steps/SchoolHomePageSteps.cs
- web/tests/EducationBenchmarking.Web.E2ETests/Steps/SearchOrganizationSteps.cs
- web/tests/EducationBenchmarking.Web.E2ETests/Steps/ServiceLandingPageSteps.cs
- web/tests/EducationBenchmarking.Web.E2ETests/TestSupport/Config.cs
Ensures browser is closed after test scenarios. 
PageHook is used to access current page, rather than  SpecFlow DI handle IPage instanace.
> chore: ensures browser is closed after test scenarios

- web/tests/EducationBenchmarking.Web.E2ETests/Features/BenchmarkWorkforce.feature
- web/tests/EducationBenchmarking.Web.E2ETests/Pages/BenchmarkWorkforcePage.cs
- web/tests/EducationBenchmarking.Web.E2ETests/Steps/BenchmarkWorkforceSteps.cs
moved the business logic into specflow.
[AB#185925](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/185925)
> moved business logic of workforce page into the specflow file

- front-end-components/src/views/compare-your-workforce/partials/auxiliary-staff.tsx
- front-end-components/src/views/compare-your-workforce/partials/non-classroom-support.tsx
- front-end-components/src/views/compare-your-workforce/partials/senior-leadership.tsx
- front-end-components/src/views/compare-your-workforce/partials/teaching-assistants.tsx
- front-end-components/src/views/compare-your-workforce/partials/total-teachers.tsx
Changed total to Pupils per staff role
> issue 1 amended

- web/pipelines/build.yaml
- web/pipelines/jobs-web-deployment.yaml
Switch web pipeline to use ubuntu-latest vm image
All the required dependencies should be installed. 
https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md
> chore: swtich web pipeline to use ubuntu-latest vm image

- platform/pipelines/build.yaml
- platform/pipelines/jobs-platform-deployment.yaml
Switch platform pipeline to use ubuntu-latest
> Switch platform pipeline to use ubuntu-latest

- front-end-components/copy-js.ps1
- front-end-components/copy-js.sh
Update local front-end build scripts for copying assets to wwwroot
> Update local front-end build scripts for copying assets to wwwroot

- web/pipelines/steps-web-build.yaml
- web/terraform/main.tf
- web/terraform/variables.tf
Replace redundant resource type and switch to ReadyToRun output
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service_plan
https://learn.microsoft.com/en-us/dotnet/core/deploying/ready-to-run
> Replace redundant resource type and switch to readytorun output

- platform/Directory.Packages.props
- platform/src/abstractions/EducationBenchmarking.Platform.Functions/EducationBenchmarking.Platform.Functions.csproj
- platform/src/abstractions/EducationBenchmarking.Platform.Functions/Extensions/ServiceCollectionExtensions.cs
- platform/src/abstractions/EducationBenchmarking.Platform.Functions/packages.lock.json
- platform/src/apis/EducationBenchmarking.Platform.Api.Benchmark/Startup.cs
- platform/src/apis/EducationBenchmarking.Platform.Api.Benchmark/host.json
- platform/src/apis/EducationBenchmarking.Platform.Api.Benchmark/packages.lock.json
- platform/src/apis/EducationBenchmarking.Platform.Api.Establishment/Startup.cs
- platform/src/apis/EducationBenchmarking.Platform.Api.Establishment/host.json
- platform/src/apis/EducationBenchmarking.Platform.Api.Establishment/packages.lock.json
- platform/src/apis/EducationBenchmarking.Platform.Api.Insight/Startup.cs
- platform/src/apis/EducationBenchmarking.Platform.Api.Insight/host.json
- platform/src/apis/EducationBenchmarking.Platform.Api.Insight/packages.lock.json
- platform/terraform/main.tf
- platform/terraform/modules/functions/README.md
- platform/terraform/modules/functions/main.tf
- platform/terraform/modules/functions/variables.tf
- platform/tests/EducationBenchmarking.Platform.Tests/packages.lock.json
Corrects logging to use app insights connection string (key is becoming redundant).
Adds structured logging using Serilog.
> Corrects logging set in function apps

- platform/pipelines/steps-platform-build.yaml
- platform/src/abstractions/EducationBenchmarking.Platform.Functions/EducationBenchmarking.Platform.Functions.csproj
- platform/src/abstractions/EducationBenchmarking.Platform.Functions/packages.lock.json
- platform/src/abstractions/EducationBenchmarking.Platform.Infrastructure/EducationBenchmarking.Platform.Infrastructure.csproj
- platform/src/abstractions/EducationBenchmarking.Platform.Infrastructure/packages.lock.json
- platform/src/apis/EducationBenchmarking.Platform.Api.Benchmark/EducationBenchmarking.Platform.Api.Benchmark.csproj
- platform/src/apis/EducationBenchmarking.Platform.Api.Benchmark/packages.lock.json
- platform/src/apis/EducationBenchmarking.Platform.Api.Establishment/EducationBenchmarking.Platform.Api.Establishment.csproj
- platform/src/apis/EducationBenchmarking.Platform.Api.Establishment/packages.lock.json
- platform/src/apis/EducationBenchmarking.Platform.Api.Insight/EducationBenchmarking.Platform.Api.Insight.csproj
- platform/src/apis/EducationBenchmarking.Platform.Api.Insight/packages.lock.json
Set ReadyToRun option on publish and update proj settings to ensure package locks are up to date.
> chore: set ReadyToRun option on publish

- core-infrastructure/pipelines/build.yaml
- core-infrastructure/pipelines/steps-core-fmt-validate-terraform.yaml
- platform/EducationBenchmarking.Platform.sln
- platform/pipelines/build.yaml
- platform/pipelines/steps-platform-fmt-validate-terraform.yaml
- prototype/pipeline/build.yaml
- prototype/pipeline/steps-prototype-fmt-validate-terraform.yaml
- web/EducationBenchmarking.Web.sln
- web/pipelines/build.yaml
- web/pipelines/steps-web-fmt-validate-terraform.yaml
Adds terraform linting (via fmt -check) and validate to build stage in pipelines
> Add terraform linting and validate to pipelines

- front-end-components/src/components/charts/horizontal-bar-chart/component.tsx
- front-end-components/src/views/compare-your-costs/partials/accordion-sections/teaching-support-staff.tsx
- bug fixes for chart title 
- adds placeholder for alt text
> fix: bug fixes for chart title and adds placeholder for alt text

- core-infrastructure/pipelines/build.yaml
Add automated test environments to core pipelines for;
- Functional testing
- Accessibility testing
> Add automated test environments to core pipelines

- platform/pipelines/build.yaml
- platform/pipelines/jobs-platform-deployment.yaml
Add automated test environments to platform pipelines for;
Functional testing
Accessibility testing
> Add automated test environments to platform pipeline

- web/src/EducationBenchmarking.Web/AssetSrc/js/findOrganisation/findOrganisationView.jsx
role assigned to radio inputs to fix accessibility issue identified in A11y test - WhenViewingFindOrganisation
> Find Organisation - A11y issue - adds role to radios

- platform/terraform/README.md
- platform/terraform/main.tf
- platform/terraform/variables.tf
Additional configuration to support use of serverless cosmos for pre-prod environments
> Additional configuration to support use of serverless cosmos

- front-end-components/package-lock.json
- front-end-components/src/components/charts/horizontal-bar-chart-wrapper.tsx
- front-end-components/src/components/charts/horizontal-bar-chart/component.test.tsx
- front-end-components/src/components/charts/horizontal-bar-chart/component.tsx
- front-end-components/src/components/charts/horizontal-bar-chart/types.tsx
- front-end-components/src/components/charts/types.tsx
- front-end-components/src/views/compare-your-costs/partials/accordion-sections/administrative-supplies.tsx
- front-end-components/src/views/compare-your-costs/partials/accordion-sections/catering-staff-services.tsx
- front-end-components/src/views/compare-your-costs/partials/accordion-sections/educational-ict.tsx
- front-end-components/src/views/compare-your-costs/partials/accordion-sections/educational-supplies.tsx
- front-end-components/src/views/compare-your-costs/partials/accordion-sections/non-educational-support-staff.tsx
- front-end-components/src/views/compare-your-costs/partials/accordion-sections/other-costs.tsx
- front-end-components/src/views/compare-your-costs/partials/accordion-sections/premises-staff-services.tsx
- front-end-components/src/views/compare-your-costs/partials/accordion-sections/teaching-support-staff.tsx
- front-end-components/src/views/compare-your-costs/partials/accordion-sections/utilities.tsx
- front-end-components/src/views/compare-your-costs/partials/total-expenditure.tsx
- front-end-components/src/views/compare-your-workforce/partials/auxiliary-staff.tsx
- front-end-components/src/views/compare-your-workforce/partials/headcount.tsx
- front-end-components/src/views/compare-your-workforce/partials/non-classroom-support.tsx
- front-end-components/src/views/compare-your-workforce/partials/school-workforce.tsx
- front-end-components/src/views/compare-your-workforce/partials/senior-leadership.tsx
- front-end-components/src/views/compare-your-workforce/partials/teaching-assistants.tsx
- front-end-components/src/views/compare-your-workforce/partials/total-teachers-qualified.tsx
- front-end-components/src/views/compare-your-workforce/partials/total-teachers.tsx
edited the chartId to chartName, edited in types
> Tech debt/place holder

- front-end-components/src/views/compare-your-workforce/partials/headcount.tsx
changed default dimensions for workforce
> changed default dimensions

- web/src/EducationBenchmarking.Web/AssetSrc/js/findOrganisation/findOrganisationView.jsx
- web/src/EducationBenchmarking.Web/Controllers/SchoolPlanningController.cs
- web/src/EducationBenchmarking.Web/Controllers/SchoolPlanningYearController.cs
- web/src/EducationBenchmarking.Web/PageTitles.cs
- web/src/EducationBenchmarking.Web/Program.cs
- web/src/EducationBenchmarking.Web/ViewModels/SchoolPlanViewModel.cs
- web/src/EducationBenchmarking.Web/Views/SchoolPlanning/SelectYear.cshtml
- web/src/EducationBenchmarking.Web/Views/SchoolPlanningYear/Index.cshtml
- web/src/EducationBenchmarking.Web/Views/Shared/_Layout.cshtml
- web/src/EducationBenchmarking.Web/gulpfile.js
- web/src/EducationBenchmarking.Web/package-lock.json
- web/tests/EducationBenchmarking.Web.A11yTests/PageBase.cs
- web/tests/EducationBenchmarking.Web.A11yTests/Pages/WhenViewingFindOrganisation.cs
- web/tests/EducationBenchmarking.Web.A11yTests/Pages/WhenViewingSchoolBenchmarkWorkforceData.cs
- web/tests/EducationBenchmarking.Web.A11yTests/Pages/WhenViewingSchoolCompareYourCosts.cs
- web/tests/EducationBenchmarking.Web.A11yTests/Pages/WhenViewingSchoolCurriculumFinancialPlanningHelp.cs
- web/tests/EducationBenchmarking.Web.A11yTests/Pages/WhenViewingSchoolCurriculumFinancialPlanningPrePopulatedData.cs
- web/tests/EducationBenchmarking.Web.A11yTests/Pages/WhenViewingSchoolHome.cs
- web/tests/EducationBenchmarking.Web.A11yTests/TestConfiguration.cs
- web/tests/EducationBenchmarking.Web.A11yTests/appsettings.json
- web/tests/EducationBenchmarking.Web.Integration.Tests/WhenViewingSchool.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/WhenViewingSchoolComparison.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/WhenViewingSchoolWorkforce.cs
Adds initial page layout for using pre-populated data in CFP plan
[AB#191578](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/191578)
> Adds initial page layout for using pre-populated data in CFP plan

- web/src/EducationBenchmarking.Web/Controllers/SchoolPlanningYearController.cs
Adds initial pages for CFP journey
[AB#191581](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/191581)
[AB#191583](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/191583)
> Adds initial pages for CFP journey

- prototype/terraform/main.tf
Resolve warnings on prototype tf
> Resolve warnings on prototype tf

- front-end-components/src/views/compare-your-workforce/partials/headcount.tsx
- front-end-components/src/views/compare-your-workforce/partials/total-teachers-qualified.tsx
removed dimensions, changed to 'percentage' and back to (%)
> reverted to old changes

- web/tests/EducationBenchmarking.Web.A11yTests/Pages/WhenViewingSchoolFinancialPlanning.cs
- web/tests/EducationBenchmarking.Web.A11yTests/Pages/WhenViewingSchoolFinancialPlanningHelp.cs
- web/tests/EducationBenchmarking.Web.A11yTests/Pages/WhenViewingSchoolFinancialPlanningPrePopulatedData.cs
- web/tests/EducationBenchmarking.Web.A11yTests/Pages/WhenViewingSchoolFinancialPlanningSelectYear.cs
- web/tests/EducationBenchmarking.Web.A11yTests/Pages/WhenViewingSchoolFinancialPlanningStart.cs
added for 
financial-planning
financial-planning/start
financial-planning/select-year
Renamed all financial planning tests
> financial planning a11y tests

- core-infrastructure/pipelines/jobs-core-deployment.yaml
- shared/steps-run-terraform.yaml
Refactor run terraform so they can be reused
> Refactor run terraform so they can be reused

- platform/pipelines/jobs-platform-deployment.yaml
- prototype/pipeline/jobs-prototype.yaml
- web/pipelines/jobs-web-deployment.yaml
Update pipelines to use refactored terraform steps
> chore: update pipelines to use refactored terraform steps

- web/src/EducationBenchmarking.Web/Constants.cs
- web/src/EducationBenchmarking.Web/Controllers/ErrorController.cs
- web/src/EducationBenchmarking.Web/Controllers/SchoolInvestigationAreaController.cs
- web/src/EducationBenchmarking.Web/Controllers/SchoolPlanningController.cs
- web/src/EducationBenchmarking.Web/Program.cs
- web/src/EducationBenchmarking.Web/ViewModels/SchoolPlanViewModel.cs
- web/src/EducationBenchmarking.Web/Views/SchoolPlanning/SelectYear.cshtml
- web/tests/EducationBenchmarking.Web.A11yTests/Pages/WhenViewingFindOrganisation.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/DocumentAssert.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/Paths.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/WhenViewingSchool.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/WhenViewingSchoolComparison.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/WhenViewingSchoolPlanning.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/WhenViewingSchoolPlanningSelectYear.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/WhenViewingSchoolPlanningStart.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/WhenViewingSchoolWorkforce.cs
Integration tests for select year stage in financial plan journey
[AB#191585](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/191585)
> Integration tests for select year stage in financial plan journey

- web/tests/EducationBenchmarking.Web.A11yTests/Pages/WhenViewingSchoolFinancialPlanningTotalNumberTeachers.cs
Before submitting this PR as ready for review, please make sure:
***********
Adds a11y test cases for total number of teachers data entry
[AB#193613](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/193613)
> Adds a11y test cases for total number of teachers data entry

- web/tests/EducationBenchmarking.Web.A11yTests/Pages/WhenViewingSchoolFinancialPlanningTotalExpenditure.cs
Before submitting this PR as ready for review, please make sure:
***********
Adds a11y test cases for total expenditure data entry
[AB#194754](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/194754)
> Adds a11y test cases for total expenditure data entry

- web/tests/EducationBenchmarking.Web.A11yTests/Pages/WhenViewingSchoolFinancialPlanningTotalIncome.cs
Before submitting this PR as ready for review, please make sure:
***********
Adds a11y test cases for total income data entry
[AB#191581](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/191581)
[AB#194753](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/194753)
> Adds a11y test cases for total income data entry

- web/README.md
- web/tests/EducationBenchmarking.Web.A11yTests/TestConfiguration.cs
- web/tests/EducationBenchmarking.Web.E2ETests/TestConfiguration.cs
Ensure web solution includes steps for running test suite locally.
Updated readme with a breakdown for each test suite.
Proof read and sense check that the steps can be followed with _minimal_ confusion.
_*no ticket reference_
> Update web readme to include running test suite

- web/src/EducationBenchmarking.Web/Views/SchoolPlanningYear/TotalIncome.cshtml
Ticket 194273
Added html to TotalIncome.cshtml
Large gap between back and home button
[AB#194273](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/194273)
[AB#191581](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/191581)
> total income page

- web/src/EducationBenchmarking.Web/Views/SchoolPlanningYear/TotalExpenditure.cshtml
[AB#194274](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/194274)
populated the page with basic html layout to TotalExpenditure.cshtml
NA
> added total exp html

- web/tests/EducationBenchmarking.Web.E2ETests/Features/CompareYourCosts.feature
- web/tests/EducationBenchmarking.Web.E2ETests/Pages/CurriculumFinancialPlanning/SelectYearPage.cs
[AB#194908](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/194908)([AB#185925](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/185925))
Fixes broken e2e test case
none
> Fix: reorder test results to match new chart data ordering

- web/src/EducationBenchmarking.Web/Views/SchoolPlanningYear/TotalExpenditure.cshtml
- web/src/EducationBenchmarking.Web/Views/SchoolPlanningYear/TotalIncome.cshtml
- web/src/EducationBenchmarking.Web/Views/SchoolPlanningYear/TotalTeacherCost.cshtml
[AB#191583](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/191583)
[AB#194275](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/194275)
TotalTeacherCost.cshtml  - html rendered
Small changes:
- TotalIncome.cshtml, TotalExpenditure.cshtml - added hint text
- TotalExpenditure.cshtml - amended ids
Following pages altered: 
- TotalTeacherCost.cshtml
- TotalIncome.cshtml
- TotalExpenditure.cshtml
> html for TotalTeacherCost and small fixes

- web/src/EducationBenchmarking.Web/Views/SchoolPlanningYear/TotalNumberTeachers.cshtml
[AB#194276](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/194276)
Added html to totalNumbersTeachers.cshtml page
NA
> totalNumberTeachers.cshtml page updated with html

- platform/README.md
- platform/tests/EducationBenchmarking.Platform.ApiTests/Drivers/ApiDriver.cs
- platform/tests/EducationBenchmarking.Platform.ApiTests/Drivers/BenchmarkApiDriver.cs
- platform/tests/EducationBenchmarking.Platform.ApiTests/Drivers/EstablishmentApiDriver.cs
- platform/tests/EducationBenchmarking.Platform.ApiTests/Drivers/InsightApiDriver.cs
- platform/tests/EducationBenchmarking.Platform.ApiTests/TestConfiguration.cs
- platform/tests/EducationBenchmarking.Platform.ApiTests/appsettings.json
Ensure platform solution includes steps for running test suite locally.
Updated readme with a breakdown for each test suite.
Proof read and sense check that the steps can be followed with minimal confusion.
_*no ticket reference_
> Readme instructions needed for running tests

- web/src/EducationBenchmarking.Web/Controllers/SchoolPlanningYearController.cs
- web/src/EducationBenchmarking.Web/Views/SchoolPlanningYear/TotalIncome.cshtml
- web/src/EducationBenchmarking.Web/Views/SchoolPlanningYear/TotalNumberTeachers.cshtml
- web/tests/EducationBenchmarking.Web.Integration.Tests/Paths.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/WhenViewingSchoolPlanningTotalIncome.cs
[AB#194945](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/194945) ([AB#191581](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/191581))
Wire up back link action for total income page
Includes integration tests
> Adds failing test cases for back link navigation

- web/src/EducationBenchmarking.Web/Controllers/SchoolPlanningYearController.cs
- web/src/EducationBenchmarking.Web/Views/SchoolPlanningYear/TotalTeacherCost.cshtml
- web/tests/EducationBenchmarking.Web.Integration.Tests/Paths.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/WhenViewingSchoolPlanningTotalTeacherCost.cs
[AB#191583](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/191583)
[AB#195269](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/195269)
Wired up back link in TotalExpenditure.cshtml
Created integrated test: WhenViewingSchoolPlanningTotalTeacherCost.cs
NA
> wired back link and added integration tests

- web/src/EducationBenchmarking.Web/Controllers/SchoolPlanningYearController.cs
- web/src/EducationBenchmarking.Web/Views/SchoolPlanningYear/TotalNumberTeachers.cshtml
- web/tests/EducationBenchmarking.Web.Integration.Tests/Paths.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/WhenViewingTotalNumberTeachers.cs
[AB#195271](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/195271)
Wired up back link in TotalNumberTeachers.cshtml
Created integrated test: WhenViewingSchoolPlanningTotalNumberTeachers.cs
NA
> wired back link and tests

- platform/src/abstractions/EducationBenchmarking.Platform.Domain/Responses/School.cs
- web/src/EducationBenchmarking.Web/Controllers/SchoolPlanningYearController.cs
- web/src/EducationBenchmarking.Web/Domain/OverallPhaseTypes.cs
- web/src/EducationBenchmarking.Web/Domain/School.cs
- web/src/EducationBenchmarking.Web/Infrastructure/Apis/Requests/PutFinancialPlanRequest.cs
- web/src/EducationBenchmarking.Web/Program.cs
- web/src/EducationBenchmarking.Web/ViewModels/SchoolPlanViewModel.cs
- web/src/EducationBenchmarking.Web/Views/SchoolPlanningYear/Index.cshtml
- web/tests/EducationBenchmarking.Web.Integration.Tests/BenchmarkingWebAppClient.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/ClientBase.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/DocumentAssert.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/Paths.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/WhenViewingErrors.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/WhenViewingSchool.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/WhenViewingSchoolComparison.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/WhenViewingSchoolPlanning.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/WhenViewingSchoolPlanningHelp.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/WhenViewingSchoolPlanningPrePopulatedData.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/WhenViewingSchoolPlanningSelectYear.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/WhenViewingSchoolPlanningStart.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/WhenViewingSchoolPlanningTotalIncome.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/WhenViewingSchoolWorkforce.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/WhenViewingServiceHome.cs
- web/tests/EducationBenchmarking.Web.Tests/Identity/WhenSetActiveRoleCalled.cs
Before submitting this PR as ready for review, please make sure:
***********
Integration test for Prepopulate Data Page in CFP journey
[AB#191578](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/191578)
[AB#194314](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/194314)
> Integration test for Prepopulate Data Page

- web/tests/EducationBenchmarking.Web.Integration.Tests/Pages/School/FinancialPlanning/WhenViewingSchoolPlanningTotalIncome.cs
[AB#191581](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/191581)
[AB#194757](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/194757)
Added the following integration tests:
- CanDisplayNotFound
- CanDisplayProblemWithService
- ShowsErrorOnInValidSubmit
to WhenViewingSchoolPlanningTotalIncome.cs
NA
> integration tests total income implemented

- web/tests/EducationBenchmarking.Web.Integration.Tests/Pages/School/FinancialPlanning/WhenViewingSchoolPlanningTotalExpenditure.cs
Context
[AB#194758](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/194758)
Change proposed in this pull request
Added the following integration tests:
CanDisplayNotFound
CanDisplayProblemWithService
ShowsErrorOnInValidSubmit
to WhenViewingSchoolPlanningTotalExpenditure.cs
Guidance to review
NA
> tests added

- web/tests/EducationBenchmarking.Web.Integration.Tests/Pages/School/FinancialPlanning/WhenViewingSchoolPlanningTotalNumberTeachers.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/Pages/School/FinancialPlanning/WhenViewingSchoolPlanningTotalTeacherCosts.cs
Context
[AB#191583](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/191583)
[AB#194759](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/194759)
Change proposed in this pull request
Added the following integration tests:
CanDisplayNotFound
CanDisplayProblemWithService
ShowsErrorOnInValidSubmit
to WhenViewingSchoolPlanningTotalTeacherCost.cs
Guidance to review
NA
> tests implemented

- web/src/EducationBenchmarking.Web/Views/SchoolPlanningSteps/TotalNumberTeachers.cshtml
- web/tests/EducationBenchmarking.Web.Integration.Tests/Pages/School/FinancialPlanning/WhenViewingSchoolPlanningTotalNumberTeachers.cs
Context
[AB#194760](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/194760)
Change proposed in this pull request
Added the following integration tests:
CanSubmit
CanDisplayNotFound
CanDisplayProblemWithService
ShowsErrorOnInValidSubmit
to WhenViewingSchoolPlanningTotalNumberTeachers.cs
Guidance to review
ShowsErrorOnInValidSubmit keeps failing
> integrated tests all pass

- prototype/src/app/config.json
Updating prototype to use proposed service name, but mostly just a test commit to both see if this works and a chance for the devs to tell me if I'm doing the GitHub side wrong…
> Prototype: Update service name

- prototype/src/app/config.json
- prototype/src/app/routes.js
- prototype/src/app/views/layouts/main.html
- prototype/src/app/views/manage-prototype/copy-url-to-clipboard.html
- prototype/src/app/views/manage-prototype/sharestate.html
- prototype/src/app/views/manage-prototype/view-data.html
- prototype/src/package-lock.json
- prototype/src/package.json
Adding some useful utilities to make the prototype kit easier to use.
> Prototype: Setup

- core-infrastructure/pipelines/build.yaml
No backlog reference
Adds stage to core pipeline to provision test environment (in test subscription)
Other pipeline to follow
> Provision test environment in core pipeline

- platform/pipelines/build.yaml
- platform/pipelines/steps-platform-build-api-tests.yaml
- platform/tests/EducationBenchmarking.Platform.ApiTests/EducationBenchmarking.Platform.ApiTests.csproj
- platform/tests/EducationBenchmarking.Platform.ApiTests/packages.lock.json
No backlog reference
Adds build steps for API tests
Review pipeline artifacts to ensure successfully published
> Add build steps for API tests

- front-end-components/index.html
- front-end-components/package-lock.json
- front-end-components/package.json
- front-end-components/src/components/charts/vertical-bar-chart/component.tsx
- front-end-components/src/components/charts/vertical-bar-chart/index.tsx
- front-end-components/src/components/charts/vertical-bar-chart/types.tsx
- front-end-components/src/constants.tsx
- front-end-components/src/index.css
- front-end-components/src/main.tsx
[AB#195070](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/195070)
New component added to `front-end-components` containing the same features as those in the above ticket.
`npm run dev` in the `front-end-components` to view the new component at `http://127.0.0.1:5173/`.
> Created generic `<VerticalBarChart />` component

- prototype/src/app/views/cost-reduction-resources.html
- prototype/src/app/views/index.html
> Prototype - Adding commercial resources

- platform/src/abstractions/EducationBenchmarking.Platform.Domain/DataObjects/FinancialPlanDataObject.cs
- platform/src/abstractions/EducationBenchmarking.Platform.Domain/Requests/FinancialPlanRequest.cs
- platform/src/abstractions/EducationBenchmarking.Platform.Domain/Responses/FinancialPlan.cs
- platform/src/apis/EducationBenchmarking.Platform.Api.Benchmark/Db/FinancialPlanDb.cs
Story - [AB#191586](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/191586)
Task - [AB#194091](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/194091)
This PR updates the api endpoint for a Financial Plan to contain a property for timetable as required for the icfp timetable page
N/A
> updated api endpoint for icfp timetable

- web/pipelines/build.yaml
- web/pipelines/steps-web-build-tests.yaml
No backlog reference
Adds steps for building web tests
Review pipeline artifacts to ensure successfully published
> Adds steps for build web tests

- web/tests/EducationBenchmarking.Web.A11yTests/Pages/Schools/WhenViewingDetails.cs
- web/tests/EducationBenchmarking.Web.E2ETests/Pages/BenchmarkWorkforcePage.cs
- web/tests/EducationBenchmarking.Web.E2ETests/Pages/CompareYourCostsPage.cs
- web/tests/EducationBenchmarking.Web.E2ETests/Pages/CurriculumFinancialPlanning/HelpPage.cs
- web/tests/EducationBenchmarking.Web.E2ETests/Pages/CurriculumFinancialPlanning/SelectYearPage.cs
- web/tests/EducationBenchmarking.Web.E2ETests/Pages/CurriculumFinancialPlanning/StartPage.cs
- web/tests/EducationBenchmarking.Web.E2ETests/Pages/ServiceLandingPage.cs
[AB#185601](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/185601) ([AB#195877](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/195877))
Adds a11y tests for school contact details.
Minor update to ensure pages wait after navigation
None
> Adds a11y tests for contact details.

- platform/pipelines/build.yaml
- shared/steps-dotnet-format.yaml
- web/pipelines/build.yaml
- web/tests/EducationBenchmarking.Web.A11yTests/Pages/Schools/WhenViewingDetails.cs
Improve checks on build PR
Add `dotnet format` step to both web & platform solutions
N/A
> Adds dotnet format step to pipelines

- web/src/EducationBenchmarking.Web/Views/SchoolPlanningSteps/TimetableCycle.cshtml
- web/tests/EducationBenchmarking.Web.Integration.Tests/Pages/Schools/FinancialPlanning/WhenViewingPlanningTimetableCycle.cs
Story - [AB#191586](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/191586)
Task - [AB#195879](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/195879)
- adds integration tests to confirm behaviour of this page
- renames error field id in view for consistency 
N/A
> CFP Timetable cycle - integration tests

- web/src/EducationBenchmarking.Web/Constants.cs
- web/src/EducationBenchmarking.Web/Controllers/SchoolPlanningStepsController.cs
- web/src/EducationBenchmarking.Web/Domain/FinancialPlan.cs
- web/src/EducationBenchmarking.Web/TagHelpers/NavigationTagHelper.cs
- web/src/EducationBenchmarking.Web/ViewModels/SchoolComparisonViewModel.cs
- web/src/EducationBenchmarking.Web/ViewModels/SchoolPlanViewModel.cs
- web/src/EducationBenchmarking.Web/ViewModels/SchoolWorkforceViewModel.cs
- web/src/EducationBenchmarking.Web/Views/SchoolPlanningSteps/PrimaryHasMixedAgeClasses.cshtml
- web/tests/EducationBenchmarking.Web.Integration.Tests/Pages/Schools/FinancialPlanning/WhenViewingPlanningHasMixedAgeClasses.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/Paths.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/Proxy/WhenRequestingEstablishmentSuggest.cs
[AB#192525](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/192525) ([AB#195883](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/195883) & [AB#194043](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/194043))
Add MVC views and controller actions, includes integration tests
N/A
> Adds has mixed classes question page

- CONTRIBUTING.md
Meet github community standards
Adds basic contributing page
N/A
> Create basic CONTRIBUTING.md

- web/tests/EducationBenchmarking.Web.A11yTests/Pages/Schools/FinancialPlanning/WhenViewingFinancialPlanningHasMixedClasses.cs
- web/tests/EducationBenchmarking.Web.A11yTests/Pages/Schools/FinancialPlanning/WhenViewingFinancialPlanningMixedClasses.cs
[AB#192525](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/192525) ([AB#195884](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/195884))
Adds a11y tests for mixed classes pages
N/A
> Adds a11y tests for mixed classes pages

- prototype/src/app/views/cost-reduction-resources.html
> Prototype: Adding guidance resources

- platform/Directory.Packages.props
- platform/src/abstractions/EducationBenchmarking.Platform.Domain/DataObjects/FinancialPlanDataObject.cs
- platform/src/abstractions/EducationBenchmarking.Platform.Domain/Requests/FinancialPlanRequest.cs
- platform/src/abstractions/EducationBenchmarking.Platform.Domain/Responses/FinancialPlan.cs
- platform/src/abstractions/EducationBenchmarking.Platform.Functions/EducationBenchmarking.Platform.Functions.csproj
- platform/src/abstractions/EducationBenchmarking.Platform.Functions/Extensions/JsonExtensions.cs
- platform/src/abstractions/EducationBenchmarking.Platform.Functions/Extensions/ServiceCollectionExtensions.cs
- platform/src/abstractions/EducationBenchmarking.Platform.Functions/JsonContentResult.cs
- platform/src/abstractions/EducationBenchmarking.Platform.Functions/Result.cs
- platform/src/abstractions/EducationBenchmarking.Platform.Functions/packages.lock.json
- platform/src/apis/EducationBenchmarking.Platform.Api.Benchmark/Db/FinancialPlanDb.cs
- platform/src/apis/EducationBenchmarking.Platform.Api.Benchmark/packages.lock.json
- platform/src/apis/EducationBenchmarking.Platform.Api.Establishment/packages.lock.json
- platform/src/apis/EducationBenchmarking.Platform.Api.Insight/packages.lock.json
- platform/tests/EducationBenchmarking.Platform.ApiTests/packages.lock.json
- platform/tests/EducationBenchmarking.Platform.Tests/packages.lock.json
- web/src/EducationBenchmarking.Web/Infrastructure/Apis/Requests/PutFinancialPlanRequest.cs
[AB#192525](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/192525) ([AB#194044](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/194044))
Updates API end points with additional props to support mixed classes data in financial plan
N/A
> Additional props to support mixed classes data in financial plan

- web/src/EducationBenchmarking.Web/Views/SchoolPlanningSteps/TotalEducationSupport.cshtml
- web/tests/EducationBenchmarking.Web.Integration.Tests/Pages/Schools/FinancialPlanning/WhenViewingPlanningTotalEducationSupport.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/Pages/Schools/FinancialPlanning/WhenViewingTotalEducationSupport.cs
[AB#192517](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/192517)
[AB#195881](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/195881)
Following tests implemented: 
- CanDisplay
- CanSubmit
- CanNavigateBack
- CanDisplayNotFound
- CanDisplayProblemWithService
- ShowsErrorOnInValidSubmit
- CanDisplayWithPreviousValue
> Adds integration tests for total education support staff costs

- front-end-components/index.html
- front-end-components/package-lock.json
- front-end-components/package.json
- front-end-components/src/components/charts/line-chart/component.tsx
- front-end-components/src/components/charts/line-chart/index.tsx
- front-end-components/src/components/charts/line-chart/types.tsx
- front-end-components/src/components/charts/stat/component.tsx
- front-end-components/src/components/charts/stat/index.tsx
- front-end-components/src/components/charts/stat/types.tsx
- front-end-components/src/components/charts/types.tsx
- front-end-components/src/components/charts/vertical-bar-chart/component.tsx
- front-end-components/src/components/charts/vertical-bar-chart/types.tsx
- front-end-components/src/constants.tsx
- front-end-components/src/index.css
- front-end-components/src/main.tsx
[AB#196192](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/196192)
Addition of a generic Line Chart component using Recharts. Addition of `<Stat>` component for highlighting specific key/value pair. Refactor of shared chart props.
Run `front-end-components` to see the new chart in action
> Addition of a generic Line Chart component using Recharts

- web/src/EducationBenchmarking.Web/Controllers/SchoolPlanningStepsController.cs
- web/src/EducationBenchmarking.Web/ViewModels/SchoolPlanViewModel.cs
- web/src/EducationBenchmarking.Web/Views/SchoolPlanningSteps/PrimaryMixedAgeClasses.cshtml
- web/tests/EducationBenchmarking.Web.A11yTests/Pages/Schools/FinancialPlanning/WhenViewingFinancialPlanningMixedClasses.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/Pages/Schools/FinancialPlanning/WhenViewingPlanningMixedAgeClasses.cs
[AB#192525](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/192525)
Add missing validation
Should display error message when no checkboxes selected
> feat: adds missing input validation, includes tests

- web/src/EducationBenchmarking.Web/Attributes/StringValueAttribute.cs
- web/src/EducationBenchmarking.Web/Constants.cs
- web/src/EducationBenchmarking.Web/Extensions/EnumExtensions.cs
- web/src/EducationBenchmarking.Web/Extensions/HtmlExtensions.cs
- web/src/EducationBenchmarking.Web/ViewModels/TrackedAnchorViewModel.cs
- web/src/EducationBenchmarking.Web/Views/SchoolDetails/Index.cshtml
- web/src/EducationBenchmarking.Web/Views/Shared/_TrackedAnchor.cshtml
- web/tests/EducationBenchmarking.Web.Tests/Extensions/GivenAnEnum.cs
Support tracking of clicked links
Adds extension method to standardise tracked anchor tags
N/A
> Adds html helper extensions to standardise tracked anchors

- .github/dependabot.yml
Reduce dependabot noise
Reduce checks to weekly
N/A
> chore: tweak dependabot config to check weekly

- platform/Directory.Packages.props
- web/Directory.Packages.props
Bump coverlet version
Update dependencies
N/A
> Tech debt/bump coverlet

- web/tests/EducationBenchmarking.Web.A11yTests/FinancialPlanFixture.cs
- web/tests/EducationBenchmarking.Web.A11yTests/appsettings.json
Extend test fixtures
Add additional financial plan fixture to support steps that require minimal data
N/A
> chore: add additional financial plan fixture

- front-end-components/src/components/charts/line-chart/component.tsx
- front-end-components/src/components/charts/vertical-bar-chart/component.tsx
- front-end-components/src/index.css
- front-end-components/src/main.tsx
[AB#196685](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/196685)
Modified charts slightly to conform with recommendations at https://analysisfunction.civilservice.gov.uk/policy-store/data-visualisation-charts/
Generic charts in `front-end-components` should be more accessible
> Accessibility improvements to charts based on recommendations in ADO ticket

- web/src/EducationBenchmarking.Web/Controllers/SchoolPlanningStepsController.cs
- web/src/EducationBenchmarking.Web/Domain/FinancialPlan.cs
- web/src/EducationBenchmarking.Web/ViewModels/SchoolPlanning/SchoolPlanViewModel.cs
- web/src/EducationBenchmarking.Web/Views/SchoolPlanningSteps/PrimaryPupilFigures.cshtml
- web/src/EducationBenchmarking.Web/Views/SchoolPlanningSteps/_PrimaryPupilFigures.cshtml
- web/src/EducationBenchmarking.Web/Views/SchoolPlanningSteps/_PrimaryPupilFiguresMixed.cshtml
- web/tests/EducationBenchmarking.Web.Integration.Tests/Pages/Schools/FinancialPlanning/WhenViewingPlanningPrimaryPupilFigures.cs
[AB#191587](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/191587) ([AB#194254](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/194254) & [AB#195885](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/195885))
Adds GET action for primary pupil figures (POST to follow on in a separate PR)
N/A
> feat: adds get action for primary pupil figures

- web/tests/EducationBenchmarking.Web.A11yTests/FinancialPlanFixture.cs
- web/tests/EducationBenchmarking.Web.A11yTests/Pages/Schools/FinancialPlanning/WhenViewingFinancialPlanningPrimaryPupilFigures.cs
- web/tests/EducationBenchmarking.Web.A11yTests/Pages/Schools/FinancialPlanning/WhenViewingFinancialPlanningPupilFigures.cs
[AB#191587](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/191587) ([AB#195886](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/195886))
Adds a11y test cases for new pages
N/A
> feat: adds a11y tests

- platform/src/abstractions/EducationBenchmarking.Platform.Domain/DataObjects/FinancialPlanDataObject.cs
- platform/src/abstractions/EducationBenchmarking.Platform.Domain/Requests/FinancialPlanRequest.cs
- platform/src/abstractions/EducationBenchmarking.Platform.Domain/Responses/FinancialPlan.cs
- platform/src/apis/EducationBenchmarking.Platform.Api.Benchmark/Db/FinancialPlanDb.cs
[AB#191587](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/191587) ([AB#194278](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/194278))
Additional props for pupil figures
N/A
> feat: update api end point with additional properties for pupil figures

- web/src/EducationBenchmarking.Web/Controllers/SchoolPlanningStepsController.cs
- web/src/EducationBenchmarking.Web/Extensions/StringExtensions.cs
- web/src/EducationBenchmarking.Web/Infrastructure/Apis/Requests/PutFinancialPlanRequest.cs
- web/src/EducationBenchmarking.Web/ViewModels/SchoolPlanning/PostPrimaryPupilFiguresViewModel.cs
- web/src/EducationBenchmarking.Web/ViewModels/SchoolPlanning/PostPupilFiguresViewModel.cs
- web/src/EducationBenchmarking.Web/ViewModels/SchoolPlanning/SchoolPlanPrimaryPupilFiguresViewModel.cs
- web/src/EducationBenchmarking.Web/Views/SchoolPlanningSteps/PrimaryPupilFigures.cshtml
- web/src/EducationBenchmarking.Web/Views/SchoolPlanningSteps/_PrimaryPupilFigures.cshtml
- web/src/EducationBenchmarking.Web/Views/SchoolPlanningSteps/_PrimaryPupilFiguresMixed.cshtml
- web/tests/EducationBenchmarking.Web.Integration.Tests/Pages/Schools/FinancialPlanning/WhenViewingPlanningPrimaryPupilFigures.cs
[AB#191587](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/191587) ([AB#194254](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/194254) & [AB#195885](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/195885))
Add post action for primary pupil figures
N/A
> feat: post action for primary pupil figures

- web/src/EducationBenchmarking.Web/Constants/PageTitles.cs
- web/src/EducationBenchmarking.Web/Constants/PlanSteps.cs
- web/src/EducationBenchmarking.Web/Controllers/SchoolComparatorSetController.cs
- web/src/EducationBenchmarking.Web/Controllers/SchoolPlanningCreatePlanController.cs
- web/src/EducationBenchmarking.Web/Domain/FormAction.cs
- web/src/EducationBenchmarking.Web/ViewModels/SchoolPlanCreateViewModel.cs
- web/src/EducationBenchmarking.Web/ViewModels/SchoolPlanOtherTeachingPeriodsViewModel.cs
- web/src/EducationBenchmarking.Web/Views/SchoolComparatorSet/Index.cshtml
- web/src/EducationBenchmarking.Web/Views/SchoolPlanningCreate/OtherTeachingPeriods.cshtml
[AB#191592](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/191592) ([AB#198232](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/198232))
Adds initial UI for other teaching periods
TODO : validator and posting to API - will be in a separate PR
> feat: initial ui for other teaching periods

- web/src/EducationBenchmarking.Web/Controllers/SchoolPlanningCreatePlanController.cs
- web/src/EducationBenchmarking.Web/Validators/CreatePlanValidator.cs
- web/src/EducationBenchmarking.Web/ViewModels/SchoolPlanOtherTeachingPeriodsViewModel.cs
- web/src/EducationBenchmarking.Web/Views/SchoolPlanningCreate/OtherTeachingPeriods.cshtml
[AB#191592](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/191592) ([AB#198232](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/198232))
Adds validation messages and ui dsiplay
TODO: Calling API to update data
> feat: adds ui validation messages for other teaching periods

- web/src/EducationBenchmarking.Web/Controllers/SchoolPlanningCreatePlanController.cs
- web/src/EducationBenchmarking.Web/Domain/FinancialPlan.cs
- web/src/EducationBenchmarking.Web/Infrastructure/Apis/Requests/PutFinancialPlanRequest.cs
- web/src/EducationBenchmarking.Web/Services/FinancialPlanService.cs
[AB#191592](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/191592) ([AB#198232](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/198232))
Additional props to put request for other teaching periods
N/A
> feat: adds other teaching periods prop to put request

- platform/src/abstractions/EducationBenchmarking.Platform.Domain/DataObjects/FinancialPlanDataObject.cs
- platform/src/abstractions/EducationBenchmarking.Platform.Domain/Requests/FinancialPlanRequest.cs
- platform/src/abstractions/EducationBenchmarking.Platform.Domain/Responses/FinancialPlan.cs
- platform/src/apis/EducationBenchmarking.Platform.Api.Benchmark/Db/FinancialPlanDb.cs
- web/src/EducationBenchmarking.Web/ViewModels/SchoolPlanCreateViewModel.cs
[AB#191592](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/191592) ([AB#198233](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/198233))
Adds additional props for other teaching periods
N/A
> feat: adds additional props for other teaching periods

- platform/src/abstractions/EducationBenchmarking.Platform.Domain/DataObjects/FinancialPlanDataObject.cs
- platform/src/abstractions/EducationBenchmarking.Platform.Domain/Requests/FinancialPlanRequest.cs
- platform/src/abstractions/EducationBenchmarking.Platform.Domain/Responses/FinancialPlan.cs
- platform/src/apis/EducationBenchmarking.Platform.Api.Benchmark/Db/FinancialPlanDb.cs
Story [AB#192529](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/192529)
Task [AB#195726](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/195726)
Adds properties for the api endpoints to function for cfp teaching assistant figures page
Outstanding for story - integration tests
> updates api for cfp teaching assistant figures

- platform/src/abstractions/EducationBenchmarking.Platform.Domain/DataObjects/FinancialPlanDataObject.cs
- platform/src/abstractions/EducationBenchmarking.Platform.Domain/Requests/FinancialPlanRequest.cs
- platform/src/abstractions/EducationBenchmarking.Platform.Domain/Responses/FinancialPlan.cs
- platform/src/apis/EducationBenchmarking.Platform.Api.Benchmark/Db/FinancialPlanDb.cs
[AB#191595](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/191595) ([AB#198552](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/198552))
Add additional props for management roles
N/A
> feta: update api endpoint with props for management roles with teaching responsibility

- platform/pipelines/steps-platform-run-unit-tests.yaml
- web/pipelines/steps-web-run-unit-tests.yaml
- web/src/EducationBenchmarking.Web/Constants/PageTitles.cs
- web/src/EducationBenchmarking.Web/Constants/PlanSteps.cs
- web/src/EducationBenchmarking.Web/Controllers/SchoolPlanningCreatePlanController.cs
- web/src/EducationBenchmarking.Web/Domain/FinancialPlan.cs
- web/src/EducationBenchmarking.Web/Infrastructure/Apis/Requests/PutFinancialPlanRequest.cs
- web/src/EducationBenchmarking.Web/Services/FinancialPlanService.cs
- web/src/EducationBenchmarking.Web/Validators/CreatePlanValidator.cs
- web/src/EducationBenchmarking.Web/ViewModels/SchoolPlanCreateViewModel.cs
- web/src/EducationBenchmarking.Web/Views/SchoolPlanningCreate/ManagementRoles.cshtml
- web/src/EducationBenchmarking.Web/Views/SchoolPlanningCreate/_ManagementRoles.cshtml
- web/src/EducationBenchmarking.Web/Views/SchoolPlanningCreate/_ManagementRolesPrimary.cshtml
[AB#191595](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/191595) ([AB#198551](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/198551))
Adds UI for management roles with teaching responsibility
Dropped quality gate due to dependencies in work
> feat: adds ui for management roles with teaching responsibility

- web/src/EducationBenchmarking.Web/Constants/PageTitles.cs
- web/src/EducationBenchmarking.Web/Constants/PlanSteps.cs
- web/src/EducationBenchmarking.Web/Controllers/SchoolPlanningCreatePlanController.cs
- web/src/EducationBenchmarking.Web/Domain/FinancialPlan.cs
- web/src/EducationBenchmarking.Web/Infrastructure/Apis/Requests/PutFinancialPlanRequest.cs
- web/src/EducationBenchmarking.Web/Services/FinancialPlanService.cs
- web/src/EducationBenchmarking.Web/Validators/CreatePlanValidator.cs
- web/src/EducationBenchmarking.Web/ViewModels/SchoolPlanCreateViewModel.cs
- web/src/EducationBenchmarking.Web/Views/SchoolPlanningCreate/ManagersPerRole.cshtml
[AB#191596](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/191596) ([AB#198651](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/198651))
Adds UI for number of managers per role
None
> feat: adds ui for number of managers per role

- platform/src/abstractions/EducationBenchmarking.Platform.Domain/DataObjects/FinancialPlanDataObject.cs
- platform/src/abstractions/EducationBenchmarking.Platform.Domain/Requests/FinancialPlanRequest.cs
- platform/src/abstractions/EducationBenchmarking.Platform.Domain/Responses/FinancialPlan.cs
- platform/src/apis/EducationBenchmarking.Platform.Api.Benchmark/Db/FinancialPlanDb.cs
[AB#191596](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/191596) ([AB#198650](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/198650))
Update end-point with additional props for number of managers per role
None
> feat: update api end-points

- web/Directory.Packages.props
- web/src/EducationBenchmarking.Web/packages.lock.json
- web/tests/EducationBenchmarking.Web.A11yTests/packages.lock.json
- web/tests/EducationBenchmarking.Web.Integration.Tests/packages.lock.json
- web/tests/EducationBenchmarking.Web.Tests/packages.lock.json
Dependency maintenance
Bump dep versions (AngleSharp.Css, Microsoft.FeatureManagement.AspNetCore & AngleSharp)
N/A
> chore: bump web deps

- web/tests/EducationBenchmarking.Web.Integration.Tests/Pages/Schools/FinancialPlanning/WhenViewingPlanningTeachingAssistantFigures.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/Paths.cs
Story [AB#192529](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/192529)
Task [AB#195730](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/195730)
Adds integration tests for this page
N/A
> adds integration tests for cfp teaching assistant figures page

- web/src/EducationBenchmarking.Web/Views/SchoolPlanningCreate/OtherTeachingPeriodsConfirm.cshtml
- web/tests/EducationBenchmarking.Web.Integration.Tests/Pages/Schools/FinancialPlanning/WhenViewingPlanningOtherTeachingPeriodsConfirm.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/Paths.cs
Story [AB#191593](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/191593)
Task [AB#198912](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/198912)
Adds integration tests for the confirm other teaching periods page. Part of the cfp journey.
Amends the ids on the view for this page to standardise capitalisation.
Confirm these tests cover the behaviour required for this page as per the story.
> adds integration tests for cfp confirm other teaching periods page

- web/src/EducationBenchmarking.Web/Domain/FinancialPlan.cs
- web/src/EducationBenchmarking.Web/ViewModels/SchoolDeploymentPlanViewModel.cs
- web/src/EducationBenchmarking.Web/Views/SchoolPlanning/View.cshtml
- web/src/EducationBenchmarking.Web/Views/SchoolPlanning/_CalculateCurriculumMetrics.cshtml
- web/src/EducationBenchmarking.Web/Views/SchoolPlanning/_CalculateFinancialMetrics.cshtml
- web/src/EducationBenchmarking.Web/Views/SchoolPlanning/_InputMetrics.cshtml
- web/src/EducationBenchmarking.Web/Views/SchoolPlanning/_ManagementStaff.cshtml
- web/src/EducationBenchmarking.Web/Views/SchoolPlanning/_ScenarioPlanner.cshtml
[AB#191678](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/191678) ([AB#195073](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/195073))
Adds scenario planner and management staff deployment sections
Split into sections to avoid monster PR
> feat: adds scenario planner and management staff deployment sections

- web/src/EducationBenchmarking.Web/Constants/PageTitles.cs
- web/src/EducationBenchmarking.Web/Controllers/SchoolPlanningCreatePlanController.cs
- web/src/EducationBenchmarking.Web/Views/SchoolPlanningCreate/OtherTeachingPeriodsReview.cshtml
Story [AB#191594](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/191594)
Task [AB#199111](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/199111)
Adds review other teaching periods page to the cfp journey
Adds backlink to management roles page ([AB#191595](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/191595))
N/A
> adds other teaching periods review page

- prototype/src/package-lock.json
- prototype/src/package.json
Dependency maintenance
Bump govuk-prototype-filters & govuk-prototype-components
N/A
> chore: bump deps

- web/tests/EducationBenchmarking.Web.Integration.Tests/Pages/Schools/FinancialPlanning/WhenViewingPlanningOtherTeachingPeriodsReview.cs
- web/tests/EducationBenchmarking.Web.Integration.Tests/Paths.cs
Story [AB#191594](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/191594)
Task [AB#199113](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/199113)
Adds integration tests to cover behaviour of the other teaching periods review page
N/A
> adds integration tests to review other teaching periods page

- web/tests/EducationBenchmarking.Web.Integration.Tests/Pages/Schools/FinancialPlanning/WhenViewingPlanningOtherTeachingPeriodsReview.cs
Story [AB#191594](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/191594)
Task [AB#199113](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/199113)
updates the expected title in tests for this page following updated service name
N/A
> amends expected title in tests for review other teaching periods page

- platform/Directory.Packages.props
- platform/pipelines/jobs-platform-deployment.yaml
- platform/src/db/Platform.Database/DbUpExtensions.cs
- platform/src/db/Platform.Database/Options.cs
- platform/src/db/Platform.Database/Platform.Database.csproj
- platform/src/db/Platform.Database/Program.cs
- platform/src/db/Platform.Database/packages.lock.json
Tool for maintain db schema
Adds db schema maintenance program
N/A
> chore: db schema maintainence program

- web/src/Web.App/ViewComponents/ComparatorSetDetailsViewComponent.cs
- web/src/Web.App/ViewModels/Components/ComparatorSetDetailsViewModel.cs
- web/src/Web.App/Views/School/Index.cshtml
- web/src/Web.App/Views/SchoolComparison/Index.cshtml
- web/src/Web.App/Views/SchoolDetails/Index.cshtml
- web/src/Web.App/Views/SchoolHistory/Index.cshtml
- web/src/Web.App/Views/SchoolPlanning/Index.cshtml
- web/src/Web.App/Views/SchoolWorkforce/Index.cshtml
- web/src/Web.App/Views/Shared/Components/ComparatorSetDetails/Default.cshtml
- web/src/Web.App/Views/Trust/Index.cshtml
- web/src/Web.App/Views/TrustComparison/Index.cshtml
- web/src/Web.App/Views/TrustWorkforce/Index.cshtml
- web/src/Web.App/Web.App.csproj
- web/tests/Web.Integration.Tests/Pages/Schools/WhenViewingComparison.cs
- web/tests/Web.Integration.Tests/Pages/Schools/WhenViewingWorkforce.cs
[AB#199626](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/199626) ([AB#200124](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/200124))
Adds comparator set details component to compare your costs & workforce benchmark
Also updates "Change school" to follow the same layout across all pages
n/a
> feat: adds comparator set details component

- platform/src/abstractions/Platform.Domain/Responses/Finances.cs
- platform/src/abstractions/Platform.Domain/Responses/School.cs
- platform/src/apis/Platform.Api.Insight/Db/AcademyDb.cs
- platform/src/apis/Platform.Api.Insight/Db/SchoolsDb.cs
- web/src/Web.App/AssetSrc/scss/_headline-figures.scss
- web/src/Web.App/AssetSrc/scss/_link-list.scss
- web/src/Web.App/AssetSrc/scss/_variables.scss
- web/src/Web.App/AssetSrc/scss/main.scss
- web/src/Web.App/Controllers/SchoolController.cs
- web/src/Web.App/Domain/Finances.cs
- web/src/Web.App/Domain/OfsedRatings.cs
- web/src/Web.App/Domain/School.cs
- web/src/Web.App/Extensions/DecimalExtensions.cs
- web/src/Web.App/ViewModels/SchoolDetailsViewModel.cs
- web/src/Web.App/ViewModels/SchoolViewModel.cs
- web/src/Web.App/Views/School/Index.cshtml
- web/tests/Web.Integration.Tests/Pages/Schools/WhenViewingDetails.cs
- web/tests/Web.Integration.Tests/Pages/Schools/WhenViewingHome.cs
[AB#199507](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/199507) ([AB#200080](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/200080))
Add headline information boxes to school homepage
Requires gulp task to be run to pick up SCSS changes
> Adds headline information to school homepage

- platform/terraform/main.tf
[AB#200089](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/200089) ([AB#199507](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/199507))
Fixes min capacity not matching minimum for chosen tier
> Fixes min capacity issue for selected tier

- platform/terraform/main.tf
[AB#200089](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/200089) ([AB#199507](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/199507))
Changes from vCore based SQL database to DTU based SQL for simplicity of deployment. Utilises Basic model for cost
> Changes from vCore model SQL DB to DTU model for simplicity

- platform/Platform.sln
- platform/pipelines/jobs-platform-deployment.yaml
- platform/src/db/Platform.Database/Options.cs
- platform/src/db/Platform.Database/Platform.Database.csproj
- platform/src/db/Platform.Database/Program.cs
- platform/src/db/Platform.Database/Scripts/001-CreateComparatorSetsTable.sql
- platform/terraform/storage.tf
[AB#199507](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/199507) ([AB#200090](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/200090))
Adds dbUp script and update pipeline
N/A
> feat: adds script for comparator sets table

- web/src/Web.App/package-lock.json
- web/src/Web.App/package.json
Resolve vulnerable package 
Adds override for glob-parent package
N/A
> fix: resolve glob-parent vulnerable

- documentation/developers/getting-started.md
First draft of developer getting started guide
> Developer getting started

- web/src/Web.App/AssetSrc/scss/main.scss
- web/src/Web.App/ViewComponents/SchoolHeadingViewComponent.cs
- web/src/Web.App/ViewModels/Components/SchoolHeadingViewModel.cs
- web/src/Web.App/Views/SchoolComparison/Index.cshtml
- web/src/Web.App/Views/SchoolDetails/Index.cshtml
- web/src/Web.App/Views/SchoolHistory/Index.cshtml
- web/src/Web.App/Views/SchoolPlanning/Index.cshtml
- web/src/Web.App/Views/SchoolSpending/Index.cshtml
- web/src/Web.App/Views/SchoolWorkforce/Index.cshtml
- web/src/Web.App/Views/Shared/Components/ComparatorSetDetails/Default.cshtml
- web/src/Web.App/Views/Shared/Components/SchoolHeading/Default.cshtml
- web/tests/Web.Integration.Tests/Pages/Schools/WhenViewingComparison.cs
- web/tests/Web.Integration.Tests/Pages/Schools/WhenViewingWorkforce.cs
[AB#199553](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/199553) ([AB#201372](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/201372))
Adds link to school name, navigating back to school home page
Applies change to all pages that follow this template.
> feat: update school name to be link to school home page

- platform/docker/docker-compose.yml
Updates docker compose to include sql server to support local dev
> chore: updates compose to include sql server

- front-end-components/index.html
- front-end-components/src/components/charts/horizontal-bar-chart-2/component.tsx
- front-end-components/src/components/charts/horizontal-bar-chart-2/types.tsx
- front-end-components/src/components/charts/line-chart-tooltip/component.tsx
- front-end-components/src/components/charts/line-chart-tooltip/index.tsx
- front-end-components/src/components/charts/line-chart-tooltip/types.tsx
- front-end-components/src/components/charts/line-chart/component.tsx
- front-end-components/src/components/charts/line-chart/types.tsx
- front-end-components/src/components/charts/school-tick/component.tsx
- front-end-components/src/components/charts/school-tick/types.tsx
- front-end-components/src/components/charts/school-workforce-tooltip/component.tsx
- front-end-components/src/components/charts/school-workforce-tooltip/index.tsx
- front-end-components/src/components/charts/school-workforce-tooltip/types.tsx
- front-end-components/src/components/charts/stat/component.tsx
- front-end-components/src/components/charts/stat/types.tsx
- front-end-components/src/components/charts/types.tsx
- front-end-components/src/components/charts/utils.test.ts
- front-end-components/src/components/charts/utils.ts
- front-end-components/src/composed/comparison-chart-summary/composed.tsx
- front-end-components/src/index.css
- front-end-components/src/main.tsx
- front-end-components/src/services/types.tsx
[AB#201447](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/201447) [AB#201366](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/201366)
Tooltip support in new `<HorizontalBarChart>`, anchored to top-left as per SFB.
Added value labels to end of bars on new `<HorizontalBarChart>`, also as seen in SFB.
New features visible in the `front-end-components` Vite dev server only at this time.
> Tooltip and Label support in new `<HorizontalBarChart>`

- web/Web.sln
- web/pipelines/build.yaml
- web/pipelines/steps-web-run-a11y-tests.yaml
- web/pipelines/steps-web-run-e2e-tests.yaml
- web/tests/Web.E2ETests/Features/School/BenchmarkWorkforce.feature
- web/tests/Web.E2ETests/Features/School/CompareYourCosts.feature
- web/tests/Web.E2ETests/Features/School/CurriculumFinancialPlanning.feature
- web/tests/Web.E2ETests/Features/School/SchoolHome.feature
- web/tests/Web.E2ETests/Pages/School/BenchmarkWorkforcePage.cs
- web/tests/Web.E2ETests/Pages/School/CompareYourCostsPage.cs
- web/tests/Web.E2ETests/Pages/School/CurriculumFinancialPlanningPage.cs
- web/tests/Web.E2ETests/Pages/School/DetailsPage.cs
- web/tests/Web.E2ETests/Pages/School/SpendingCostsPage.cs
- web/tests/Web.E2ETests/Steps/School/FinancialPlanningSteps.cs
[AB#201673](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/201673) ([AB#198014](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/198014))
updated yaml file to extract the zip files 
updated yaml to extract zip files for tests 
removed change school link 
updated urn to match with what we have in automated-test env
this PR is to test the extraction of files is done correctly. further work will follow once this is gone through.
> Tech debt/setup testing pipeline and update tests

- web/pipelines/build.yaml
- web/pipelines/steps-web-run-a11y-tests.yaml
- web/pipelines/steps-web-run-e2e-tests.yaml
[AB#201673](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/201673)
to replace the variables in appsettings with library group
> Tech debt/setup tests in pipeline

- web/README.md
Updates web readme to include templated secret sections rather than CLI commands
> chore: update web readme to include templated secret sections

- web/tests/Web.A11yTests/Web.A11yTests.csproj
[AB#201673](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/201673)
after reviewing copied artifacts it was spotted that appsettings is not getting copied. same has been checked in the bin folder locally. proposed changes is to copy appsettings for a11y to output directory.   
> setting up tests in pipeline

- web/src/Web.App/Domain/CostCategories.cs
- web/src/Web.App/ViewModels/FindOrganisationViewModelV2.cs
- web/src/Web.App/ViewModels/SchoolSpendingViewModel.cs
- web/src/Web.App/ViewModels/SchoolViewModel.cs
- web/src/Web.App/Views/SchoolSpending/Index.cshtml
Refactor building of cost categories
> refactor building of cost categories

- web/tests/Web.E2ETests/Pages/School/BenchmarkWorkforcePage.cs
- web/tests/Web.E2ETests/Selectors.cs
updated selectors for the new react charts
n/a
n/a
> updated selectors for charts to fix failing of tests

- platform/terraform/variables.tf
Development CosmosDB is currently running in Provisioned throughput cpapcity mode. Switching to Serverless will increase cost savings
Added Enableserverless capability to the dev DB
> Updates development CosmosDB capacity mode to Serverless

- web/src/Web.App/Domain/RatingCalculations.cs
- web/tests/Web.Tests/Domain/GivenValuesRatingCalculations.cs
Story [AB#199507](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/199507)
Task [AB#200093](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/200093)
Adds methods to RatingCalculations to calculate the rating for each category. See the story for the methodology.
Refer to the methodology in the story for the rules for the ratings
> adds methods to RatingCalculations

- front-end-components/src/components/chart-mode/component.tsx
- front-end-components/src/components/chart-mode/types.tsx
- front-end-components/src/views/school-history/partials/balance.tsx
- front-end-components/src/views/school-history/partials/income.tsx
- front-end-components/src/views/school-history/partials/index.tsx
- front-end-components/src/views/school-history/partials/spending.tsx
- front-end-components/src/views/school-history/partials/workforce.tsx
- front-end-components/src/views/school-history/view.tsx
- web/src/Web.App/Views/SchoolHistory/Index.cshtml
[AB#185907](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/185907) & [AB#185900](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/185900) ([AB#197644](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/197644), [AB#197645](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/197645), [AB#197647](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/197647), [AB#202367](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/202367))
Adds initial and basic layout for workforce and balance tabs in school history
> feat: adds initial layout for workforce and balance tabs

- documentation/testing/Test-Data-Preperation-Guide.md
[AB#199537](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/199537)([AB#198014](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/198014))
documentation of steps followed to prepare test data
> steps followed to prepare test data

- platform/src/abstractions/Platform.Domain/Responses/FinanceBalanceResponseModel.cs
- platform/src/abstractions/Platform.Domain/Responses/FinanceWorkforceResponseModel.cs
- web/src/Web.App/Controllers/ProxyController.cs
- web/src/Web.App/Domain/Balance.cs
- web/src/Web.App/Domain/FinanceYears.cs
- web/src/Web.App/Domain/Workforce.cs
- web/src/Web.App/Infrastructure/Apis/InsightApi.cs
- web/src/Web.App/Services/FinanceService.cs
- web/src/Web.App/ViewModels/SchoolComparisonViewModel.cs
- web/src/Web.App/ViewModels/SchoolWorkforceViewModel.cs
- web/tests/Web.E2ETests/Steps/School/SpendingCostsSteps.cs
- web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
- web/tests/Web.Tests/Infrastructure/GivenAnInsightApi.cs
[AB#185907](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/185907) & [AB#185900](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/185900) ([AB#202589](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/202589) & [AB#202590](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/202590))
Adds proxy controller end-points for workforce and balance history
> feat: adds proxy end-points for balance & workforce history

- web/tests/Web.E2ETests/Pages/School/BenchmarkWorkforcePage.cs
- web/tests/Web.E2ETests/Pages/School/CompareYourCostsPage.cs
fixed failing of e2e test.
n/a
n/a
> updated option.value to option.label for dropdown options

- platform/src/db/Platform.Database/Scripts/002-CreateRAGRatingsTable.sql
Creates the RAGRatings table in the SQL database to hold the RAG rating data from the VMFI database
> Creates RAGRatings Table

- documentation/testing/security-testing.md
- documentation/testing/test-strategy.md
Adds details for approach to security testing
> docs: adds details for approach to security testing

- web/tests/Web.E2ETests/Features/School/BenchmarkWorkforce.feature
- web/tests/Web.E2ETests/Features/School/CompareYourCosts.feature
- web/tests/Web.E2ETests/Pages/School/BenchmarkWorkforcePage.cs
- web/tests/Web.E2ETests/Pages/School/CompareYourCostsPage.cs
- web/tests/Web.E2ETests/Selectors.cs
- web/tests/Web.E2ETests/Steps/School/BenchmarkWorkforceSteps.cs
- web/tests/Web.E2ETests/Steps/School/CompareYourCostsSteps.cs
[AB#201366](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/201366) ([AB#201764](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/201764))
tests for bar chart interactions 
N/A
>  e2e tests for bar chart interactions

- web/tests/Web.E2ETests/Features/School/SchoolHome.feature
- web/tests/Web.E2ETests/Features/School/SpendingCosts.feature
- web/tests/Web.E2ETests/Pages/School/BenchmarkWorkforcePage.cs
N/A
- added wait for request so that page loaded fully before headers are extracted
-ignored the tests which are failing because of RAG data. will bring them back once we have RAG data imported in d02
if you are happy please merge the changes.
> Tech debt/fix flaky and ignore rag tests

- platform/pipelines/jobs-platform-deployment.yaml
- platform/src/db/Platform.Database/Options.cs
- platform/src/db/Platform.Database/Program.cs
- platform/terraform/README.md
- platform/terraform/data.tf
- platform/terraform/databases.tf
- platform/terraform/functions.tf
- platform/terraform/modules/functions/README.md
- platform/terraform/modules/functions/data.tf
- platform/terraform/modules/functions/main.tf
- platform/terraform/modules/functions/variables.tf
- web/tests/Web.Integration.Tests/packages.lock.json
Updates platform to use key vaults references in app settings.
> chore: updates platform to use key vault references

- documentation/developers/session-data.md
- web/Directory.Packages.props
- web/src/Web.App/Extensions/WebApplicationBuilderExtensions.cs
- web/src/Web.App/Infrastructure/Cosmos/ClientFactory.cs
- web/src/Web.App/Infrastructure/Cosmos/Settings.cs
- web/src/Web.App/Infrastructure/Redis/Settings.cs
- web/src/Web.App/Program.cs
- web/src/Web.App/Web.App.csproj
- web/src/Web.App/packages.lock.json
- web/tests/Web.Integration.Tests/packages.lock.json
- web/tests/Web.Tests/packages.lock.json
Adds Redis as an option for session state data
> chore: adds redis options for session service

- web/Web.sln
- web/src/Web.App/ViewComponents/DataSourceViewComponent.cs
[AB#201306](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/201306) ([AB#203856](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/203856))
Minor content update to data source text
> feat: updates data source text

- documentation/developers/branching-policy.md
Adds first draft of branching policy for the project
> chore: adds branching policy documentation

- web/tests/Web.E2ETests/Pages/FindOrganisationPage.cs
- web/tests/Web.E2ETests/Pages/School/BenchmarkWorkforcePage.cs
- web/tests/Web.E2ETests/Pages/School/CompareYourCostsPage.cs
- web/tests/Web.E2ETests/Selectors.cs
- web/tests/Web.E2ETests/Steps/School/BenchmarkWorkforceSteps.cs
updated selectors for similar schools
1. updated selectors for similar school sections 
2. added wait for dropdown/search results on find organisation page
3. added waitForRequest bool in test Change dimension in table view for total number of teachers as 3 tests needs it and one tests fails because of it
N/A
> Tech debt/update e2e tests

- CONTRIBUTING.md
> updated CONTRIBUTING.md documentation

- documentation/templates/feature.md
Adds template markdown for documenting features
> doc: adds template for documenting features

- documentation/templates/decision.md
Add markdown template for documenting Architecture Decision Records
> docs: adds ADR markdown template

- README.md
- documentation/developers/Cookies.md
- documentation/developers/cookies.md
> details about cookies being used.

- README.md
- documentation/developers/additional-resources.md
- documentation/developers/getting-started.md
- documentation/developers/troubleshooting.md
- platform/README.md
- web/README.md
Review of the following documents:
Added some minor text changes, and also comments to be addressed by the author. Comments are in the markdown files like so:
[comment]: <> (This is an example of a comment I have left.)
Review the text changes and comments
> document review

- core-infrastructure/terraform/key-vault.tf
- pipelines/common/destroy-terraform.yaml
- pipelines/core-infrastructure/build.yaml
- pipelines/core-infrastructure/destroy.yaml
- pipelines/destroy/destroy.yaml
- pipelines/destroy/release.yaml
- pipelines/front-end-components/build.yaml
- pipelines/platform/build.yaml
- pipelines/platform/deployment.yaml
- pipelines/platform/destroy.yaml
- pipelines/web/build.yaml
- pipelines/web/destroy.yaml
- platform/terraform/data.tf
- platform/terraform/storage.tf
- platform/terraform/variables.tf
- web/src/Web.App/package-lock.json
- web/terraform/data.tf
- web/terraform/variables.tf
ADO pipeline changes.
Ability to deploy development feature branches to Azure.
Deployment to a new feature is testable in ADO by running a manual Development release off this branch, and specifying the name of the feature. Unfortunately, testing of the 'Destroy' pipeline will not be possible until this branch has been merged to `main` ☹️ but the `terraform destroy` syntax has validated as part of another branch.
> Feature environment deployment and destruction

- web/src/Web.App/Middleware/CustomResponseHeadersMiddleware.cs
Fixes connect src for app insights
> bugfix: fixes csp for app insights

- platform/terraform/README.md
- platform/terraform/data.tf
- platform/terraform/modules/functions/README.md
- platform/terraform/modules/functions/output.tf
- platform/terraform/storage.tf
- platform/tests/Platform.ApiTests/packages.lock.json
- platform/tests/Platform.Tests/packages.lock.json
Prevents public access to platform storage access
> chore: prevent public access to platform storage access

- core-infrastructure/terraform/README.md
- core-infrastructure/terraform/key-vault.tf
- platform/terraform/README.md
- platform/terraform/databases.tf
- platform/terraform/modules/functions/main.tf
- platform/terraform/search.tf
- platform/terraform/storage.tf
- prototype/terraform/main.tf
- web/terraform/cache.tf
Updates checkov comments with references to tech debt backlog tickets
> chore: updates checkov comments with backlog references

- web/tests/Web.E2ETests/Features/School/HistoricData.feature
- web/tests/Web.E2ETests/Features/School/SchoolHome.feature
- web/tests/Web.E2ETests/Pages/School/HistoricDataPage.cs
- web/tests/Web.E2ETests/Pages/School/HomePage.cs
- web/tests/Web.E2ETests/Selectors.cs
- web/tests/Web.E2ETests/Steps/School/HistoricDataSteps.cs
- web/tests/Web.E2ETests/Steps/School/HomeSteps.cs
[AB#185882](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/185882) ([AB#205982](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/205982))
added e2e for the page
tests for other history pages will follow these tests.
> e2e tests for expenditure history

- documentation/developers/troubleshooting.md
- platform/README.md
- web/README.md
Adds prerequisites to platform & web. 
Updates builds tags in readme for platform & web.
_I believe the google document with setup instructions can be nuked_
> chore: adds prerequisites to platform & web

- README.md
- documentation/testing/Decisions/Test-Data-Storage-and-Retrieval.md
Test data storage and retrieval decision document
> test data storage decision document

- front-end-components/package-lock.json
Bumps front-end component package versions
> chore: bumps front-end component package versions

- pipelines/common/destroy-terraform.yaml
- pipelines/common/fmt-validate-terraform.yaml
- pipelines/common/run-terraform.yaml
- pipelines/feature/release.yaml
- web/terraform/app-service.tf
- web/terraform/front-door.tf
- web/terraform/variables.tf
[AB#206797](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/206797) [AB#206695](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/206695)
Remove 'Classic' Front Door infrastructure and replace with 'Standard', or 'Premium', based on environment configuration. Honour existing rules and routing from original implementation.
Original rules should be mapped as best as possible with the old. For ease of review, this feature has already been [deployed](https://portal.azure.com/#@platform.education.gov.uk/resource/subscriptions/f155d7d4-a235-4563-b077-c19686c7c92a/resourceGroups/s198d11-ebis-web/overview) to the `d11` feature infrastructure.
> **NOTE:** Entry point URLs to the application will mutate after this change is …
> Upgrade Front Door to Standard/Premium from Classic

- web/tests/Web.E2ETests/Pages/School/HistoricDataPage.cs
[AB#207003](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/207003)
fix e2e failure
n/a
> fix e2e failures

- front-end-components/src/main.tsx
Fixes bug. Attribute from dataset not being passed to a component correctly.
> fix to hasIncompleteData prop from dataset

- web/src/Web.App/Constants/OrganisationTypes.cs
- web/src/Web.App/Controllers/Api/SuggestProxyController.cs
- web/src/Web.App/Domain/LocalAuthority.cs
- web/src/Web.App/Infrastructure/Apis/EstablishmentApi.cs
- web/src/Web.App/Program.cs
- web/src/Web.App/Services/SuggestService.cs
- web/tests/Web.Integration.Tests/Proxy/WhenRequestingSuggest.cs
[AB#206189](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/206189) ([AB#206782](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/206782))
Adds proxy end points for Local Authority suggestions
N/A
> feat: adds local authority proxy suggest end point

- platform/src/abstractions/Platform.Domain/ComparatorSetTypes.cs
- platform/src/abstractions/Platform.Domain/CostCategoryMappings.cs
- platform/src/abstractions/Platform.Domain/DataObjects/QueryableFinancesDataObject.cs
- platform/src/abstractions/Platform.Domain/DataObjects/RatingsDataObject.cs
- platform/src/abstractions/Platform.Domain/Messages/PipelineMessage.cs
- platform/src/abstractions/Platform.Domain/Requests/PipelineJobRequestModel.cs
- platform/src/abstractions/Platform.Domain/Responses/FinancialPlanResponseModel.cs
- platform/src/abstractions/Platform.Domain/Responses/IncomeResponseModel.cs
- platform/src/abstractions/Platform.Domain/Responses/LocalAuthorityResponseModel.cs
- platform/src/abstractions/Platform.Domain/Responses/RatingResponseModel.cs
- platform/src/abstractions/Platform.Infrastructure/Search/SearchOptions.cs
- platform/src/abstractions/Platform.Infrastructure/Sql/ColumnMap.cs
- platform/src/apis/Platform.Api.Benchmark/Db/FinancialPlanDb.cs
- platform/src/apis/Platform.Api.Benchmark/Db/FinancialPlanFactory.cs
- platform/src/apis/Platform.Api.Establishment/LocalAuthoritiesFunctions.cs
- platform/src/apis/Platform.Api.Establishment/Search/LocalAuthoritySearchService.cs
- platform/src/apis/Platform.Api.Establishment/Search/SchoolSearchService.cs
- platform/src/apis/Platform.Api.Establishment/Search/TrustSearchService.cs
- platform/src/apis/Platform.Api.Establishment/Startup.cs
- platform/src/apis/Platform.Orchestrator/Platform.Orchestrator.csproj
- platform/src/apis/Platform.Orchestrator/packages.lock.json
- platform/tests/Platform.Tests/Establishment/LocalAuthoritiesFunctionsTestBase.cs
- platform/tests/Platform.Tests/Establishment/WhenFunctionReceivesSuggestLocalAuthoritiesRequest.cs
[AB#206189](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/206189) ([AB#206782](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/206782))
Adds local authority suggestion end point to platform API
Web App proxy end point to follow in a separate PR
> feat: adds local authority api suggest end point

- front-end-components/src/views/find-organisation/view.tsx
- web/src/Web.App/Constants/PageTitles.cs
- web/src/Web.App/Controllers/FindOrganisationController.cs
[AB#207555](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/207555) [AB#203291](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/203291)
Copy changes to the above page as per the linked work item.
Browse to `/find-organisation` and check the copy is accurate. Attempt to submit the form before school or trust selected to check validation error messages.
> Copy updates to Find Organisation page

- pipelines/supporting-data/build.yaml
- pipelines/supporting-data/deployment.yaml
- supporting-data/README.md
- supporting-data/terraform/README.md
- supporting-data/terraform/data-factory.tf
- supporting-data/terraform/data.tf
- supporting-data/terraform/main.tf
- supporting-data/terraform/provider.tf
- supporting-data/terraform/storage.tf
- supporting-data/terraform/terraform.tfvars
- supporting-data/terraform/variables.tf
[AB#207728](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/207728) [AB#207730](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/207730) [AB#207727](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/207727)
Terraform and associated pipeline for managing an Azure Data Factory and Blob Storage account.
> Supporting data terraform and pipeline

- pipelines/common/run-terraform.yaml
- pipelines/supporting-data/build.yaml
- pipelines/supporting-data/deployment.yaml
- supporting-data/terraform/data-factory.tf
- supporting-data/terraform/data.tf
- supporting-data/terraform/key-vault.tf
- supporting-data/terraform/storage.tf
[AB#207728](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/207728) [AB#207729](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/207729)
Git, Key Vault, Storage and Cosmos link configuration from Azure Data Factory.
> ADF linked services and Git configuration

- platform/src/abstractions/Platform.Domain/Responses/TrustResponseModel.cs
- web/src/Web.App/Controllers/TrustDetailsController.cs
- web/src/Web.App/Domain/Trust.cs
- web/src/Web.App/ViewModels/Components/ResourcesViewModel.cs
- web/src/Web.App/ViewModels/TrustDetailsViewModel.cs
- web/src/Web.App/Views/Shared/Components/Resources/Default.cshtml
- web/src/Web.App/Views/Trust/Index.cshtml
- web/src/Web.App/Views/TrustDetails/index.cshtml
- web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
- web/tests/Web.Integration.Tests/Pages/Trusts/WhenViewingDetails.cs
- web/tests/Web.Integration.Tests/Paths.cs
[AB#203998](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/203998) - [AB#203889](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/203889)
Adds trust details page to the service.
Adds model view and controller for web app.
Adds the required properties to the trust response for platform
Adds integration tests
Uid is required for the link to GIAS.
> adds trust details page

- supporting-data/terraform/data-factory.tf
[AB#207727](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/207727) [AB#208456](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/208456)
Terraform change to add SQL Server Database link to ADF
> Added Azure Data Factory linked service for SQL Database

- web/src/Web.App/Constants/ViewDataKeys.cs
- web/src/Web.App/Controllers/ErrorController.cs
- web/src/Web.App/Controllers/StaticContentController.cs
- web/src/Web.App/TagHelpers/NavigationTagHelper.cs
- web/src/Web.App/Views/Shared/_Layout.cshtml
- web/src/Web.App/Views/StaticContent/Accessibility.cshtml
- web/src/Web.App/Views/StaticContent/Contact.cshtml
- web/src/Web.App/Views/StaticContent/Cookies.cshtml
- web/src/Web.App/Views/StaticContent/Privacy.cshtml
- web/tests/Web.Integration.Tests/PageAssert.cs
- web/tests/Web.Integration.Tests/Pages/WhenViewingAccessibility.cs
- web/tests/Web.Integration.Tests/Pages/WhenViewingContact.cs
- web/tests/Web.Integration.Tests/Pages/WhenViewingCookies.cs
- web/tests/Web.Integration.Tests/Pages/WhenViewingPrivacy.cs
- web/tests/Web.Integration.Tests/Paths.cs
[AB#186930](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/186930) ([AB#208655](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/208655))
Adds standard footer links to layout page
Just placeholder pages at the moment - content to be provided later.
> feat: adds standard footer links

- web/src/Web.App/Constants/BreadcrumbNodes.cs
- web/src/Web.App/Constants/PageTitles.cs
- web/src/Web.App/Controllers/FindOrganisationController.cs
- web/src/Web.App/Controllers/LocalAuthorityController.cs
- web/src/Web.App/Domain/OverallPhaseTypes.cs
- web/src/Web.App/ViewModels/Components/ResourcesViewModel.cs
- web/src/Web.App/ViewModels/LocalAuthorityViewModel.cs
- web/src/Web.App/Views/LocalAuthority/Index.cshtml
- web/src/Web.App/Views/LocalAuthority/_SchoolsSection.cshtml
- web/src/Web.App/Views/LocalAuthorityResources/index.cshtml
- web/src/Web.App/Views/Shared/Components/EstablishmentHeading/Default.cshtml
- web/src/Web.App/Views/Shared/Components/Resources/Default.cshtml
[AB#199810](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/199810) - [AB#208281](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/208281)
Adds LA homepage.
Displays all school in an LA in four accordions
- Primary
- Secondary
- Special or PRU
- Other
Updates to OverallPhaseType to facilitate the above.
Completes the LA resources page.
Wires up la find organisation to direct to this homepage.
Integration tests for the homepage and the resources page will be added in the next PR.
> adds la homepage

- front-end-components/package-lock.json
> chore: bumps front-end deps

- pipelines/common/destroy-terraform.yaml
- pipelines/data-pipeline/deployment.yaml
- pipelines/data-pipeline/sync.yaml
- pipelines/destroy/destroy.yaml
- pipelines/destroy/release.yaml
- pipelines/feature/release.yaml
[AB#208909](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/208909) [AB#208907](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/208907)
Fixed issues feature releasing / destroying Data Pipelines resources.
> Fixed issues feature releasing / destroying Data Pipelines resources

- .pre-commit-config.yaml
- data-pipeline/poetry.lock
- data-pipeline/pyproject.toml
- documentation/developers/1_Getting-Started.md
initial hook for `black --check`.
Avoid repeated formatting issues in Python code.
Adding [`pre-commit`](https://pre-commit.com/) and initial hook for [`black`](https://github.com/psf/black).
Need to check if this is something collectively we want.
> build: add pre-commit hooks

- web/src/Web.App/Constants/PageTitles.cs
- web/src/Web.App/Controllers/SchoolCustomDataChangeController.cs
- web/src/Web.App/Domain/CustomData.cs
- web/src/Web.App/Extensions/DecimalExtensions.cs
- web/src/Web.App/Extensions/MvcOptionsExtensions.cs
- web/src/Web.App/Program.cs
- web/src/Web.App/Services/CustomDataService.cs
- web/src/Web.App/ViewModels/FinancialDataCustomDataViewModel.cs
- web/src/Web.App/ViewModels/NonFinancialDataCustomDataViewModel.cs
- web/src/Web.App/ViewModels/SchoolCustomDataChangeViewModel.cs
- web/src/Web.App/ViewModels/SchoolCustomDataViewModel.cs
- web/src/Web.App/ViewModels/WorkforceDataCustomDataViewModel.cs
- web/src/Web.App/Views/SchoolCustomDataChange/NonFinancialData.cshtml
- web/src/Web.App/Views/SchoolCustomDataChange/_AccordionSection.cshtml
- web/src/Web.App/Views/SchoolCustomDataChange/_CustomDataEntryTable.cshtml
- web/src/Web.App/Views/SchoolCustomDataChange/_CustomDataEntryTableRow.cshtml
- web/tests/Web.Tests/Extensions/GivenAnMvcOptions.cs
- web/tests/Web.Tests/ViewModels/GivenASchoolCustomDataChangeViewModel.cs
[AB#208015](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/208015) [AB#198080](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/198080)
Added the 'Non-financial data' step to the Custom Data journey.
As per #727, to run locally you will need to add a breakpoint to `SchoolAuthorizationAttribute` to skip the claims check after logging into DSI. Then browse to `https://localhost:7095/school/[URN]/custom-data/` and complete the forms. 'Back' button will be resolved as part of another ticket, as will the 'next' step after validation is successful on the final `POST`.
> Non-financial data Custom Data form

- core-infrastructure/terraform/storage.tf
- platform/terraform/storage.tf
- supporting-data/terraform/storage.tf
[AB#209058](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/209058) ([AB#209059](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/209059))
Updates TF to enable logging for storage queues on all accounts
N/A
> feat: enable storage queue logging

- front-end-components/src/composed/horizontal-bar-chart-wrapper/composed.tsx
[AB#200888](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/200888) ([AB#209237](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/209237))
Adjusts chart height based on rows to plot - ensures smaller datasets don't result in giant blocks.
N/A
> feat: adjust chart height based on rows to plot

- core-infrastructure/Core.sln
- core-infrastructure/Directory.Packages.props
- core-infrastructure/global.json
- core-infrastructure/nuget.config
- core-infrastructure/src/db/Core.Database/Core.Database.csproj
- core-infrastructure/src/db/Core.Database/DbUpExtensions.cs
- core-infrastructure/src/db/Core.Database/Options.cs
- core-infrastructure/src/db/Core.Database/Program.cs
- core-infrastructure/src/db/Core.Database/Scripts/001-CreateComparatorSetTable.sql
- core-infrastructure/src/db/Core.Database/Scripts/002-CreateUserDefinedComparatorSetTable.sql
- core-infrastructure/src/db/Core.Database/Scripts/003-CreateMetricRAGTable.sql
- core-infrastructure/src/db/Core.Database/Scripts/004-CreateLocalAuthorityTable.sql
- core-infrastructure/src/db/Core.Database/packages.lock.json
- core-infrastructure/terraform/README.md
- core-infrastructure/terraform/databases.tf
- core-infrastructure/terraform/variables.tf
- pipelines/core-infrastructure/build.yaml
- pipelines/core-infrastructure/deployment.yaml
- pipelines/core-infrastructure/steps/build.yaml
1. Adds core database infrastructure
2. Solution for dbUp program 
3. Initial table scripts for Comparator sets, User defined comparator sets, Metric RAG and Local authority
4. Update pipeline to build and deploy/execute db schema
> chore: adds core database and initial scripts

- core-infrastructure/src/db/Core.Database/Scripts/005-CreateTrustHistoryTable.sql
- core-infrastructure/src/db/Core.Database/Scripts/006-CreateFinancialPlanTable.sql
- core-infrastructure/src/db/Core.Database/Scripts/007-CreateTrustTable.sql
- core-infrastructure/src/db/Core.Database/Scripts/008-CreateSchoolTable.sql
Adds tables to core database for;
1. Schools
2. Trusts
3. Trust history
4. Financial plans
NB: Schools doesn't have address/location fields at the moment, as there discussion requiring what is actually required. Financial plans is a copy of the existing table
> chore: adds core organisation tables

- web/src/Web.App/Attributes/CompareDecimalValueAttribute.cs
- web/src/Web.App/Views/SchoolCustomDataChange/FinancialData.cshtml
- web/tests/Web.Integration.Tests/Pages/Schools/CustomData/WhenViewingCustomDataFinancialData.cs
- web/tests/Web.Integration.Tests/Pages/Schools/CustomData/WhenViewingCustomDataNonFinancialData.cs
- web/tests/Web.Integration.Tests/Pages/Schools/CustomData/WhenViewingCustomDataWorkforceData.cs
- web/tests/Web.Tests/Attributes/GivenACompareDecimalValueAttribute.cs
[AB#208019](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/208019) [AB#198080](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/198080)
UI bug fixes for Custom Data journey.
> Bug fixes to Custom Data journey so far

- web/src/Web.App/Controllers/SchoolPlanningCreatePlanController.cs
- web/tests/Web.Integration.Tests/Pages/Schools/FinancialPlanning/WhenViewingPlanningManagementRoles.cs
- web/tests/Web.Integration.Tests/Paths.cs
Increases test coverage
Adds integration tests for the cfp create page management roles
Confirm behaviour of this page is covered by these tests
~- [ ] Work items have been linked [(use AB#)](https://learn.microsoft.com/en-us/azure/devops/boards/github/link-to-from-github?view=azure-devops#use-ab-to-link-from-github-to-azure-boards-work-items)~
> adds integration tests for cfp create management roles

- web/README.md
- web/src/Web.App/AssetSrc/scss/_variables.scss
- web/src/Web.App/Views/Shared/Components/RagStack/Default.cshtml
- web/src/Web.App/package-lock.json
- web/tests/Web.A11yTests/Pages/Trust/WhenViewingHome.cs
- web/tests/Web.A11yTests/TestConfiguration.cs
- web/tests/Web.A11yTests/appsettings.json
[AB#210609](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/210609) [AB#188333](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/188333)
Implemented accessibility tests and configured to run during pipeline. Updated RAG colours to match latest designs.
Update the local a11y config file to include a `TrustCompanyNo` such as `149783` and then run the tests.
> A11y tests for Trust landing page

- platform/src/abstractions/Platform.Infrastructure/Search/SearchResourceNames.cs
- platform/src/search/Platform.Search/SchoolComparators/SchoolComparatorsIndex.cs
- platform/src/search/Platform.Search/SchoolComparators/SchoolComparatorsIndexBuilder.cs
- platform/src/search/Platform.Search/SearchMaintenanceService.cs
[AB#210705](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/210705) [AB#210736](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/210736)
Adds first pass for school comparator search index 
None
> feat: first phase on search index for school comparators

- web/terraform/variables.tf
[AB#210609](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/210609) [AB#188333](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/188333) #786 
Enabled all Web features in `automated-test` environment in order to a11y test platform features
> chore: Enabled `Trust` and other features in automated test environment

- platform/src/abstractions/Platform.Infrastructure/Search/SearchResourceNames.cs
- platform/src/search/Platform.Search/SchoolComparators/SchoolComparatorsAcademyDataSourceConnectionBuilder.cs
- platform/src/search/Platform.Search/SchoolComparators/SchoolComparatorsAcademyIndexerBuilder.cs
- platform/src/search/Platform.Search/SchoolComparators/SchoolComparatorsMaintainedDataSourceConnectionBuilder.cs
- platform/src/search/Platform.Search/SchoolComparators/SchoolComparatorsMaintainedIndexerBuilder.cs
- platform/src/search/Platform.Search/SearchMaintenanceService.cs
[AB#210705](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/210705)
Temporarily add indexers and data sources to seed school comparator index
> feat: add temporary indexer and data source

- web/src/Web.App/ViewModels/RagViewModel.cs
- web/src/Web.App/ViewModels/TrustViewModel.cs
- web/src/Web.App/Views/Trust/Index.cshtml
[AB#210823](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/210823) [AB#188333](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/188333)
UI fixes after A/Cs properly defined on parent story
All A/Cs should now be upheld
> Post-A/C refinement UI pass of Trust landing page

- web/src/Web.App/Domain/OverallPhaseTypes.cs
- web/src/Web.App/Views/Trust/_SchoolsSection.cshtml
- web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
- web/tests/Web.Integration.Tests/Pages/Trusts/WhenViewingHome.cs
[AB#210608](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/210608) [AB#188333](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/188333)
Integration tests for the above feature
> Integration tests for Trust homepage

- platform/src/abstractions/Platform.Domain/Requests/SchoolComparatorsRequestModel.cs
- platform/src/abstractions/Platform.Domain/Responses/SchoolComparatorResponseModel.cs
- platform/src/abstractions/Platform.Infrastructure/Search/Responses/ScoreResponseModel.cs
- platform/src/abstractions/Platform.Infrastructure/Search/SearchService.cs
- platform/src/apis/Platform.Api.Benchmark/ComparatorSetFunctions.cs
- platform/src/apis/Platform.Api.Establishment/SchoolsFunctions.cs
- platform/src/apis/Platform.Api.Establishment/Search/SchoolComparatorsSearchService.cs
- platform/src/apis/Platform.Api.Establishment/Search/SchoolSearchService.cs
- platform/src/apis/Platform.Api.Establishment/Startup.cs
- platform/src/search/Platform.Search/SchoolComparators/SchoolComparatorsAcademyIndexerBuilder.cs
- platform/src/search/Platform.Search/SchoolComparators/SchoolComparatorsIndex.cs
- platform/src/search/Platform.Search/SchoolComparators/SchoolComparatorsMaintainedIndexerBuilder.cs
- platform/tests/Platform.Tests/Establishment/SchoolsFunctionsTestBase.cs
- platform/tests/Platform.Tests/Establishment/WhenFunctionReceivesSearchSchoolsRequest.cs
- platform/tests/Platform.Tests/Establishment/WhenFunctionReceivesSuggestSchoolsRequest.cs
[AB#210705](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/210705) ([AB#210736](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/210736))
Adds search end-point for school comparators. Also includes dummy end-points for comparator sets.
N/A
> feat: adds end-points for custom comparators

- web/src/Web.App/Views/Home/Index.cshtml
[AB#210054](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/210054) - [AB#211418](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/211418)
Updates the start page with the proposed changes in the prototype.
N/A
> updates start page content

- web/src/Web.App/Views/Home/Index.cshtml
[AB#210054](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/210054) - [AB#211940](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/211940)
Update the At a school level list as per the the latest agreed changes to this page
N/A
> updates to start page

- web/src/Web.App/Views/Shared/Components/ComparatorSetDetails/Default.cshtml
[AB#210705](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/210705) - [AB#212065](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/212065)
Updates the ComparatorSetDetails component with the required content.
N/A
> updates to comparator set details

- web/src/Web.App/package-lock.json
bump front-end version
~- [ ] Work items have been linked [(use AB#)](https://learn.microsoft.com/en-us/azure/devops/boards/github/link-to-from-github?view=azure-devops#use-ab-to-link-from-github-to-azure-boards-work-items)~
> chore: bump front-end version

- data-pipeline/src/pipeline/config.py
- data-pipeline/src/pipeline/pre_processing.py
Include relevant motivation and context.
Include a summary of the change.
> Data pipeline/bfr logic

- platform/src/apis/Platform.Api.Benchmark/ComparatorSets/ComparatorSetsService.cs
- web/src/Web.App/Constants/PageTitles.cs
- web/src/Web.App/Controllers/SchoolComparatorsController.cs
- web/src/Web.App/Controllers/SchoolComparatorsCreateByController.cs
- web/src/Web.App/Domain/ComparatorSet.cs
- web/src/Web.App/Services/ComparatorSetService.cs
- web/src/Web.App/ViewModels/SchoolComparatorsViewModel.cs
- web/src/Web.App/Views/School/Index.cshtml
- web/src/Web.App/Views/SchoolComparators/Revert.cshtml
- web/src/Web.App/Views/SchoolComparators/UserDefined.cshtml
- web/src/Web.App/Views/SchoolComparatorsCreateBy/Name.cshtml
[AB#210705](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/210705)
Adds revert & change methods and links for comparators
N/A
> feat: adds revert and change links & actions

- front-end-components/index.html
- front-end-components/src/main.tsx
- front-end-components/src/views/find-organisation/partials/school-input.tsx
- front-end-components/src/views/find-organisation/types.tsx
- web/src/Web.App/Controllers/Api/SuggestProxyController.cs
- web/src/Web.App/Controllers/SchoolComparatorsCreateByController.cs
- web/src/Web.App/ViewModels/SchoolComparatorsByNameViewModel.cs
- web/src/Web.App/Views/SchoolComparatorsCreateBy/Name.cshtml
[AB#212383](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/212383) [AB#210705](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/210705)
Added additional validation to prevent more than 30 schools being manually compared against. Also prevented existing and current schools from appearing in the suggester.
This has a dependency on `front-end-components` and so to test locally, the latest build will need to be copied to `Web`. A subsequent commit will pull the new version, once published.
> Manual user defined comparator set validations

- web/src/Web.App/Controllers/SchoolComparatorsCreateByController.cs
- web/src/Web.App/ViewModels/SchoolComparatorsPreviewViewModel.cs
- web/src/Web.App/ViewModels/UserDefinedCharacteristicViewModel.cs
- web/src/Web.App/Views/SchoolComparatorsCreateBy/Characteristic.cshtml
- web/src/Web.App/Views/SchoolComparatorsCreateBy/Preview.cshtml
- web/src/Web.App/Views/SchoolComparatorsCreateBy/_LocalAuthorities.cshtml
[AB#212886](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/212886) [AB#210705](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/210705)
UI fixes for default selected characteristics; multiple LA selector and validation; individual school characteristics in comparator preview.
> UI fixes for user defined comparator set characteristics builder and preview

- web/src/Web.App/AssetSrc/scss/main.scss
- web/src/Web.App/Infrastructure/Apis/Requests/PostSchoolComparatorsRequest.cs
- web/src/Web.App/ViewModels/SchoolComparatorsPreviewViewModel.cs
- web/src/Web.App/ViewModels/UserDefinedCharacteristicViewModel.cs
- web/src/Web.App/Views/SchoolComparatorsCreateBy/Characteristic.cshtml
- web/src/Web.App/Views/SchoolComparatorsCreateBy/Preview.cshtml
- web/src/Web.App/Views/SchoolComparatorsCreateBy/_SchoolCategories.cshtml
[AB#212326](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/212326) [AB#210705](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/210705)
These were earlier omitted from this and subsequent screens. They are conditionally visible based on the 'Special' school category.
> Added SEN characteristics

- web/Web.sln.DotSettings
- web/src/Web.App/Infrastructure/Apis/ApiResults/JsonContent.cs
- web/src/Web.App/Infrastructure/Apis/Requests/PostSchoolComparatorsRequest.cs
- web/src/Web.App/ViewModels/UserDefinedCharacteristicViewModel.cs
- web/tests/Web.Tests/Infrastructure/ApiClientTestBase.cs
- web/tests/Web.Tests/Infrastructure/Apis/Requests/GivenAPostSchoolComparatorsRequest.cs
- web/tests/Web.Tests/Infrastructure/GivenACensusApi.cs
- web/tests/Web.Tests/Infrastructure/GivenAComparatorApi.cs
- web/tests/Web.Tests/Infrastructure/GivenAnEstablishmentApi.cs
- web/tests/Web.Tests/Infrastructure/GivenAnInsightApi.cs
[AB#212965](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/212965) [AB#210705](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/210705)
Unit tests
Tests should all be green when executed
> Comparator-related model mapping and API tests

- web/Directory.Packages.props
- web/src/Web.App/Views/SchoolComparatorsCreateBy/Characteristic.cshtml
- web/src/Web.App/Views/SchoolComparatorsCreateBy/Name.cshtml
- web/src/Web.App/Views/SchoolComparatorsCreateBy/Preview.cshtml
- web/src/Web.App/Views/SchoolComparatorsCreateBy/_ChosenSchools.cshtml
- web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
- web/tests/Web.Integration.Tests/HtmlExtensions.cs
- web/tests/Web.Integration.Tests/Pages/Schools/Comparators/WhenViewingComparatorsCreate.cs
- web/tests/Web.Integration.Tests/Pages/Schools/Comparators/WhenViewingComparatorsCreateBy.cs
- web/tests/Web.Integration.Tests/Pages/Schools/Comparators/WhenViewingComparatorsCreateByCharacteristic.cs
- web/tests/Web.Integration.Tests/Pages/Schools/Comparators/WhenViewingComparatorsCreateByName.cs
- web/tests/Web.Integration.Tests/Pages/Schools/Comparators/WhenViewingComparatorsCreatePreview.cs
- web/tests/Web.Integration.Tests/Paths.cs
- web/tests/Web.Integration.Tests/Web.Integration.Tests.csproj
- web/tests/Web.Integration.Tests/packages.lock.json
[AB#212325](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/212325) [AB#210705](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/210705)
Integration test coverage for the above feature
Integration tests should all be green when executed
> Integration tests for School Comparator pages

- data-pipeline/src/pipeline/main.py
Added fix to error caused by lack of correct reference to cfo files
Ensure fix is in line with existing functionality
> Data pipeline/de minimis rule

- platform/src/apis/Platform.Api.Benchmark/ComparatorSets/ComparatorSetsService.cs
- platform/src/apis/Platform.Api.Insight/Startup.cs
- platform/src/apis/Platform.Api.Insight/Trusts/TrustCharacteristic.cs
- platform/src/apis/Platform.Api.Insight/Trusts/TrustsFunctions.cs
- platform/src/apis/Platform.Api.Insight/Trusts/TrustsService.cs
[AB#206777](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/206777)
Adds end-point for trusts characteristics
N/A
> feat: adds trusts characteristics end-point

- data-pipeline/src/pipeline/main.py
> Fix CFO file naming

- web/src/Web.App/Domain/TrustCharacteristic.cs
- web/src/Web.App/Infrastructure/Apis/TrustInsightApi.cs
- web/src/Web.App/Views/TrustComparatorsCreateBy/_ChosenTrusts.cshtml
- web/src/Web.App/package-lock.json
[AB#213058](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/213058) [AB#206777](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/206777)
Also bumped `front-end` version
> Wired up Trust Characteristics endpoint

- web/src/Web.App/Controllers/StaticContentController.cs
- web/src/Web.App/Views/LocalAuthority/Index.cshtml
- web/src/Web.App/Views/School/Index.cshtml
- web/src/Web.App/Views/Shared/Components/GetHelp/Default.cshtml
- web/src/Web.App/Views/Shared/_Layout.cshtml
- web/src/Web.App/Views/StaticContent/Accessibility.cshtml
- web/src/Web.App/Views/StaticContent/AskForHelp.cshtml
- web/src/Web.App/Views/StaticContent/ServiceHelp.cshtml
- web/src/Web.App/Views/StaticContent/SubmitEnquiry.cshtml
- web/src/Web.App/Views/Trust/Index.cshtml
- web/tests/Web.Integration.Tests/Pages/LocalAuthorities/WhenViewingHome.cs
- web/tests/Web.Integration.Tests/Pages/WhenViewingAccessibility.cs
- web/tests/Web.Integration.Tests/Pages/WhenViewingAskForHelp.cs
- web/tests/Web.Integration.Tests/Pages/WhenViewingServiceHelp.cs
- web/tests/Web.Integration.Tests/Pages/WhenViewingSubmitEnquiry.cs
[AB#213169](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/213169) - [AB#213232](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/213232)
Removes static content pages that are currently not required
- Help with this service
- Ask for help SMRA
- Submit an enquiry
- Accessibility
Code is currently commented out awaiting a final decision to be made.
N/A
> removes static content pages no longer required from service

- web/src/Web.App/Views/StaticContent/Cookies.cshtml
[AB#213169](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/213169) - [AB#213269](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/213269)
also [AB#212849](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/212849)
Updates content for the cookies page
N/A
> updates content for cookies page

- web/src/Web.App/Constants/PageTitles.cs
- web/src/Web.App/Controllers/TrustComparatorsCreateByController.cs
- web/src/Web.App/ViewModels/TrustComparatorsPreviewViewModel.cs
- web/src/Web.App/Views/TrustComparatorsCreateBy/Preview.cshtml
- web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
- web/tests/Web.Integration.Tests/Pages/Trusts/Comparators/WhenViewingComparatorsCreateByCharacteristic.cs
- web/tests/Web.Integration.Tests/Pages/Trusts/Comparators/WhenViewingComparatorsCreatePreview.cs
- web/tests/Web.Integration.Tests/Paths.cs
[AB#213061](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/213061) [AB#206777](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/206777)
Preview for resultant Trusts from characteristic search. Includes integration tests
> Preview for matching trusts by characteristic

- data-pipeline/src/pipeline/main.py
remove the incorrect assignment-operator and opt for a simpler check.
relates #212505
> fix: correct user-defined comparator-set payload check

- web/src/Web.App/Views/School/Index.cshtml
- web/src/Web.App/Views/Trust/Index.cshtml
- web/tests/Web.A11yTests/Pages/Schools/Comparators/WhenViewingComparatorsPreview.cs
- web/tests/Web.A11yTests/Pages/Schools/Comparators/WhenViewingComparatorsRevert.cs
- web/tests/Web.A11yTests/Pages/Trust/Comparators/WhenViewingComparatorsBy.cs
- web/tests/Web.A11yTests/Pages/Trust/Comparators/WhenViewingComparatorsByCharacteristic.cs
- web/tests/Web.A11yTests/Pages/Trust/Comparators/WhenViewingComparatorsByName.cs
- web/tests/Web.A11yTests/Pages/Trust/Comparators/WhenViewingComparatorsPreview.cs
- web/tests/Web.A11yTests/Pages/Trust/Comparators/WhenViewingComparatorsRevert.cs
- web/tests/Web.A11yTests/Pages/Trust/Comparators/WhenViewingComparatorsSubmit.cs
[AB#213063](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/213063) [AB#206777](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/206777)
Additional automated a11y tests
> Axe tests for user defined Trust comparator sets

- data-pipeline/src/pipeline/comparator_sets.py
- data-pipeline/src/pipeline/database.py
- data-pipeline/src/pipeline/log.py
- data-pipeline/src/pipeline/main.py
- data-pipeline/src/pipeline/mappings.py
- data-pipeline/src/pipeline/pre_processing.py
- data-pipeline/src/pipeline/rag.py
- data-pipeline/src/pipeline/storage.py
- data-pipeline/tests/e2e/synthetic_data_test.py
- data-pipeline/tests/unit/pre_processing/conftest.py
- data-pipeline/tests/unit/pre_processing/test_mappings.py
- data-pipeline/tests/unit/rag/test_rag.py
- data-pipeline/tests/unit/rag/test_user_defined_comparator_sets.py
The `**/*.py` input to `isort` isn't matching anything; compare:
```sh
❯ poetry run isort --settings-path ./pyproject.toml --check-only **/*.py
```
…against:
```sh
❯ poetry run isort --settings-path ./pyproject.toml --check-only src/ tests/
ERROR: /home/roger/projects/dfe-fbs/git/education-benchmarking-and-insights/data-pipeline/src/pipeline/pre_processing.py Imports are incorrectly sorted and/or formatted.
ERROR: /home/roger/projects/dfe-fbs/git/education-benchmarking-and-insights/data-pipeline/src/pipeline/mappings.py Imports are incorrectly sorted and/or formatted.
ERROR: /home/roger/projects/dfe-fbs/git/education-benchmarking-and-insights/data-pipeline/src/pipeline/rag.py Imports are incorrectly sorted and/or formatted.
ERROR: …
```
> chore: correct isort path

- web/src/Web.App/Views/SchoolComparators/Revert.cshtml
- web/src/Web.App/Views/TrustComparators/Revert.cshtml
- web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
- web/tests/Web.Integration.Tests/Pages/Schools/Comparators/WhenViewingComparatorsCreateSubmit.cs
- web/tests/Web.Integration.Tests/Pages/Schools/Comparators/WhenViewingComparatorsRevert.cs
- web/tests/Web.Integration.Tests/Pages/Trusts/Comparators/WhenViewingComparatorsCreateSubmit.cs
- web/tests/Web.Integration.Tests/Pages/Trusts/Comparators/WhenViewingComparatorsRevert.cs
- web/tests/Web.Integration.Tests/Paths.cs
[AB#213064](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/213064) [AB#206777](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/206777)
Additional integration tests
> Integration tests for user defined Trust comparator sets

- web/src/Web.App/Controllers/DataSourceController.cs
- web/src/Web.App/ViewModels/Components/ResourcesViewModel.cs
- web/src/Web.App/Views/DataSource/Index.cshtml
- web/src/Web.App/Views/DataSource/_Catering.cshtml
- web/src/Web.App/Views/DataSource/_DataSources.cshtml
- web/src/Web.App/Views/DataSource/_EducationalSupplies.cshtml
- web/src/Web.App/Views/DataSource/_FinanceCosts.cshtml
- web/src/Web.App/Views/DataSource/_Ict.cshtml
- web/src/Web.App/Views/DataSource/_Interpretation.cshtml
- web/src/Web.App/Views/DataSource/_Premises.cshtml
- web/src/Web.App/Views/DataSource/_SpecialFacilities.cshtml
- web/src/Web.App/Views/DataSource/_TeachingCosts.cshtml
- web/src/Web.App/Views/DataSource/_Utilities.cshtml
- web/src/Web.App/Views/LocalAuthority/Index.cshtml
- web/src/Web.App/Views/School/Index.cshtml
- web/src/Web.App/Views/Shared/Components/Resources/Default.cshtml
- web/src/Web.App/Views/Trust/Index.cshtml
- web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
- web/tests/Web.Integration.Tests/Pages/WhenViewingDataSources.cs
- web/tests/Web.Integration.Tests/Paths.cs
[AB#212292](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/212292) - [AB#213457](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/213457)
Adds content for the data source page.
Allows download of the AAR and CFR data for the last 9 years from storage as excel files from this page.
adds a link for this page to the resources navigation section from school, trust and la home pages.
adds integration tests.
N/A
> adds data source page

- data-pipeline/Makefile
- data-pipeline/src/pipeline/main.py
`SetType` and `RunType` are somewhat interchanged.
Correct the `RunType` and `SetType` references throughout.
Should be entirely non-functional changes.
> Correct RunType/SetType references throughout

- web/src/Web.App/Views/TrustComparators/Index.cshtml
- web/src/Web.App/package-lock.json
- web/tests/Web.A11yTests/Pages/Trust/Comparators/WhenViewingComparators.cs
- web/tests/Web.Integration.Tests/Pages/Trusts/Comparators/WhenViewingComparators.cs
[AB#213660](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/213660) [AB#213661](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/213661) [AB#207092](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/207092)
Updated tests. Bumped `front-end` version.
> Integration and accessibility test updates

- front-end-components/index.html
- front-end-components/src/components/chart-mode/component.tsx
- front-end-components/src/components/chart-options-phase-mode/component.tsx
- front-end-components/src/components/chart-options-phase-mode/index.tsx
- front-end-components/src/components/chart-options-phase-mode/types.tsx
- front-end-components/src/composed/horizontal-bar-chart-wrapper/composed.tsx
- front-end-components/src/composed/horizontal-bar-chart-wrapper/types.tsx
- front-end-components/src/contexts/contexts.tsx
- front-end-components/src/contexts/hooks.tsx
- front-end-components/src/contexts/providers.tsx
- front-end-components/src/views/compare-your-census/view.tsx
- front-end-components/src/views/compare-your-costs/view.tsx
- front-end-components/src/views/compare-your-trust/partials/accordion-sections/administrative-supplies.tsx
- front-end-components/src/views/compare-your-trust/partials/accordion-sections/catering-staff-services.tsx
- front-end-components/src/views/compare-your-trust/partials/accordion-sections/educational-ict.tsx
- front-end-components/src/views/compare-your-trust/partials/accordion-sections/educational-supplies.tsx
- front-end-components/src/views/compare-your-trust/partials/accordion-sections/non-educational-support-staff.tsx
- front-end-components/src/views/compare-your-trust/partials/accordion-sections/other-costs.tsx
- front-end-components/src/views/compare-your-trust/partials/accordion-sections/premises-staff-services.tsx
- front-end-components/src/views/compare-your-trust/partials/accordion-sections/teaching-support-staff.tsx
- front-end-components/src/views/compare-your-trust/partials/accordion-sections/utilities.tsx
- front-end-components/src/views/compare-your-trust/partials/balance-section.tsx
- front-end-components/src/views/compare-your-trust/partials/balance.tsx
- front-end-components/src/views/compare-your-trust/partials/spending-section.tsx
- front-end-components/src/views/compare-your-trust/partials/total-expenditure.tsx
- front-end-components/src/views/compare-your-trust/view.tsx
[AB#213659](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/213659) [AB#207092](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/207092)
Also removed central services breakdown from Balance tab on trust-to-trust.
> Fixed issue importing refactored `ChartModeContext` on school cost/census data

- front-end-components/index.html
- front-end-components/package-lock.json
- front-end-components/package.json
- front-end-components/src/components/charts/line-chart/component.tsx
- front-end-components/src/components/charts/types.tsx
- front-end-components/src/constants.tsx
- front-end-components/src/index.css
- front-end-components/src/main.tsx
[AB#214019](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/214019) [AB#188391](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/188391)
Example implementation of two-series line chart with dummy forecast data:
> Two-series line chart example implementation

- data-pipeline/src/pipeline/database.py
- data-pipeline/src/pipeline/mappings.py
- data-pipeline/src/pipeline/pre_processing.py
- data-pipeline/tests/unit/pre_processing/test_bfr.py
- data-pipeline/tests/unit/pre_processing/test_mappings.py
Fixes [bug 214123](https://dfe-ssp.visualstudio.com/s198-DfE-Benchmarking-service/_workitems/edit/214123) for academies.
> Fix for Bug 214123 - Invalid company numbers

- web/src/Web.App/Constants/BreadcrumbNodes.cs
- web/src/Web.App/Constants/PageTitles.cs
- web/src/Web.App/Controllers/TrustForecastController.cs
- web/src/Web.App/ViewModels/TrustForecastViewModel.cs
- web/src/Web.App/Views/Shared/Components/TrustFinanceTools/Default.cshtml
- web/src/Web.App/Views/TrustForecast/Index.cshtml
- web/tests/Web.A11yTests/Pages/Trust/WhenViewingForecast.cs
- web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
- web/tests/Web.Integration.Tests/Pages/Trusts/WhenViewingForecast.cs
- web/tests/Web.Integration.Tests/Paths.cs
- web/tests/Web.Integration.Tests/TestAuth.cs
[AB#214180](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/214180)
Skeleton page for Trust forecast and risk to set up referral links, integration and accessibility tests.
Requires DSI to test.
> Skeleton page for Trust forecast and risks

- core-infrastructure/src/db/Core.Database/Scripts/043-CreateBudgetForecastTables.sql
[AB#188391](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/188391)
New migration script for revised schema
N/A
> feat: adds migration script for revised schema

- front-end-components/index.html
- front-end-components/src/components/chart-dimensions/component.tsx
- front-end-components/src/components/chart-dimensions/index.tsx
- front-end-components/src/components/chart-dimensions/types.tsx
- front-end-components/src/components/charts/line-chart/component.tsx
- front-end-components/src/composed/horizontal-bar-chart-wrapper/composed.tsx
- front-end-components/src/constants.tsx
- front-end-components/src/index.css
- front-end-components/src/main.tsx
- front-end-components/src/services/balance-api.tsx
- front-end-components/src/services/types.tsx
- front-end-components/src/views/budget-forecast-returns/index.tsx
- front-end-components/src/views/budget-forecast-returns/partials/index.tsx
- front-end-components/src/views/budget-forecast-returns/partials/types.tsx
- front-end-components/src/views/budget-forecast-returns/partials/year-end.tsx
- front-end-components/src/views/budget-forecast-returns/types.tsx
- front-end-components/src/views/budget-forecast-returns/view.tsx
- web/src/Web.App/Infrastructure/Apis/Insight/BalanceApi.cs
- web/src/Web.App/Views/TrustForecast/Index.cshtml
[AB#214183](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/214183) [AB#188391](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/188391)
Created new view in `front-end-components` and imported into relevant `Web` view. Added additional stub data to support dimension change to 'by pupil' from 'actuals'.
To test locally, build and copy from `front-end-components` to `Web`. The `front-end` version will be bumped in a future commit.
> Wire up BFR chart

- front-end-components/src/services/budget-forecast-api.tsx
- platform/src/apis/Platform.Api.Insight/BudgetForecast/BudgetForecastFunctions.cs
- platform/src/apis/Platform.Api.Insight/BudgetForecast/BudgetForecastModel.cs
- platform/src/apis/Platform.Api.Insight/BudgetForecast/BudgetForecastResponse.cs
- platform/src/apis/Platform.Api.Insight/BudgetForecast/BudgetForecastService.cs
- platform/src/apis/Platform.Api.Insight/Startup.cs
- web/src/Web.App/Controllers/Api/BudgetForecastProxyController.cs
- web/src/Web.App/Controllers/TrustForecastController.cs
- web/src/Web.App/Extensions/ServiceCollectionExtensions.cs
- web/src/Web.App/Infrastructure/Apis/Insight/BalanceApi.cs
- web/src/Web.App/Infrastructure/Apis/Insight/BudgetForecastApi.cs
- web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
- web/tests/Web.Integration.Tests/Pages/Trusts/WhenViewingForecast.cs
[AB#214807](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/214807) [AB#188391](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/188391)
Created new Platform function to return BFR and BFR metrics. Moved prior Web stubs into their own API and updated all affected references (may cause merge conflicts with other pending PRs).
Swagger may be use to test new endpoints but without any matching data in the respective database tables, an empty array will always be returned.
> Added BFR API endpoints to new Platform function

- front-end-components/src/services/balance-api.tsx
- front-end-components/src/views/budget-forecast-returns/partials/types.tsx
- front-end-components/src/views/budget-forecast-returns/partials/year-end.tsx
- web/src/Web.App/Infrastructure/Apis/Insight/BudgetForecastApi.cs
- web/src/Web.App/package-lock.json
[AB#214184](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/214184) [AB#188391](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/188391)
Updated view in `front-end-components` to include table for BFR data from API call.
Guidance to review
To test locally, build and copy from `front-end-components` to `Web`. The `front-end` version will be bumped in a future commit.
> Wired up BFR table

- platform/Platform.sln.DotSettings
- platform/src/abstractions/Platform.Functions/PipelineMessage.cs
- platform/src/apis/Platform.Api.Benchmark/CustomData/CustomDataRequest.cs
- web/Web.sln.DotSettings
- web/src/Web.App/Domain/Benchmark/CustomData.cs
- web/src/Web.App/Domain/CustomDataFactory.cs
- web/src/Web.App/Infrastructure/Apis/ApiRequests/PutCustomDataRequest.cs
- web/src/Web.App/Services/CustomDataService.cs
- web/src/Web.App/ViewModels/SchoolCustomDataChangeViewModel.cs
- web/src/Web.App/ViewModels/SchoolCustomDataViewModel.cs
- web/src/Web.App/ViewModels/WorkforceDataCustomDataViewModel.cs
- web/src/Web.App/Views/SchoolCustomDataChange/_CustomDataEntryTableRow.cshtml
- web/tests/Web.Integration.Tests/DocumentAssert.cs
- web/tests/Web.Integration.Tests/Pages/Schools/CustomData/WhenViewingCustomDataWorkforceData.cs
[AB#215069](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/215069) [AB#198080](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/198080)
Resolve QA feedback as per user story.
> Additional fields captured on Custom Data screens

- web/README.md
- web/src/Web.App/Identity/Models/DfeSignInSettings.cs
- web/src/Web.App/Program.cs
- web/src/Web.App/Views/Home/Index.cshtml
- web/src/Web.App/Views/SchoolComparatorsCreate/Index.cshtml
- web/terraform/app-service.tf
- web/terraform/terraform.tfvars
Adds configuration for DSI sign in URI
> chore: adds configuration for sign-in uri

- web/src/Web.App/Controllers/Api/CensusProxyController.cs
- web/src/Web.App/Controllers/Api/ExpenditureProxyController.cs
[AB#192482](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/192482)
Updates proxy end-points for expenditure and census to handle custom data requests
N/A
> feat: updates proxy end-points for custom data

- front-end-components/src/views/compare-your-costs/partials/accordion-sections/catering-staff-services.tsx
- front-end-components/src/views/compare-your-costs/partials/accordion-sections/non-educational-support-staff.tsx
- front-end-components/src/views/compare-your-costs/partials/accordion-sections/other-costs.tsx
- front-end-components/src/views/compare-your-costs/partials/accordion-sections/premises-staff-services.tsx
- front-end-components/src/views/compare-your-trust/partials/accordion-sections/catering-staff-services.tsx
- front-end-components/src/views/compare-your-trust/partials/accordion-sections/non-educational-support-staff.tsx
- front-end-components/src/views/compare-your-trust/partials/accordion-sections/other-costs.tsx
- front-end-components/src/views/compare-your-trust/partials/accordion-sections/premises-staff-services.tsx
[AB#215314](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/215314) [AB#214693](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/214693)
Fixed mismatched anchors in `front-end-components`
> Anchor mismatches

- platform/src/apis/Platform.Api.Insight/BudgetForecast/BudgetForecastFunctions.cs
- platform/src/apis/Platform.Api.Insight/BudgetForecast/BudgetForecastReturnParameters.cs
- platform/src/apis/Platform.Api.Insight/BudgetForecast/BudgetForecastService.cs
- web/src/Web.App/Controllers/TrustForecastController.cs
- web/src/Web.App/Infrastructure/Apis/Insight/BudgetForecastApi.cs
- web/src/Web.App/ViewModels/TrustForecastViewModel.cs
- web/src/Web.App/Views/TrustForecast/Index.cshtml
- web/src/Web.App/Views/TrustForecast/_RiskSummary.cshtml
- web/src/Web.App/package-lock.json
- web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
- web/tests/Web.Integration.Tests/Pages/Trusts/WhenViewingForecast.cs
[AB#214708](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/214708) [AB#214547](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/214547) [AB#188391](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/188391)
Added warning message when BFR unable to be loaded. Added query string support to BFR function to allow additional filtering within SQL query. Updated model to set 'in deficit' properties based on most recent year's BFR rows.
BFR stub is still in use until #998 is merged and wired up. SQL modifications can be validated by calling function via Swagger instead.
> BFR priority status updates

- data-pipeline/src/pipeline/main.py
- data-pipeline/src/pipeline/message.py
- data-pipeline/src/pipeline/pre_processing.py
- data-pipeline/tests/unit/pre_processing/test_custom_data.py
Error seen in dev:
```sh
too many values to unpack (expected 2)
```
Additionally, some fields to be added/removed in the custom-data payload.
[AB#213664](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/213664)
- add additional fields as per incoming message;
- remove extraneous fields (which will be derived);
- handle incomplete custom-data.
- correct parsing of custom-data payload.
- added/removed fields need double-(/triple-)checking.
> fix: correct custom-data message format/parsing

- web/tests/Web.E2ETests/Features/FindOrganisation.feature
- web/tests/Web.E2ETests/Features/School/BenchmarkCensus.feature
- web/tests/Web.E2ETests/Features/School/CommercialResources.feature
- web/tests/Web.E2ETests/Features/School/CompareYourCosts.feature
- web/tests/Web.E2ETests/Features/School/SchoolHome.feature
- web/tests/Web.E2ETests/Features/School/SpendingCosts.feature
- web/tests/Web.E2ETests/Pages/School/BenchmarkCensusPage.cs
- web/tests/Web.E2ETests/Pages/School/CompareYourCostsPage.cs
- web/tests/Web.E2ETests/Pages/School/DetailsPage.cs
- web/tests/Web.E2ETests/Pages/School/HomePage.cs
- web/tests/Web.E2ETests/Pages/School/SpendingCostsPage.cs
- web/tests/Web.E2ETests/Selectors.cs
- web/tests/Web.E2ETests/Steps/School/BenchmarkCensusSteps.cs
- web/tests/Web.E2ETests/Steps/School/CompareYourCostsSteps.cs
- web/tests/Web.E2ETests/Steps/School/SpendingCostsSteps.cs
Updated e2e tests with updated data. [AB#213960](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/213960) ([AB#215381](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/215381))
fixed and updated the e2e tests
This PR covers tests updates for all e2e tests besides CurriculumFinancialPlanning.feature and HistoricData.feature
> Tech debt/fix update e2e tests

- web/tests/Web.E2ETests/Extensions/LocatorExtensions.cs
- web/tests/Web.E2ETests/Features/School/CurriculumFinancialPlanning.feature
- web/tests/Web.E2ETests/Features/School/HistoricData.feature
- web/tests/Web.E2ETests/Steps/School/FinancialPlanningSteps.cs
- web/tests/Web.E2ETests/TestConfiguration.cs
- web/tests/Web.E2ETests/appsettings.json
[AB#213960](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/213960) ([AB#215727](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/215727) [AB#215728](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/215728))
added login for CFP tests and updated historic data tests
> Tech debt/dfe login for e2e tests

- pipelines/web/build.yaml
[AB#213960](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/213960)
added tests back in pipeline
> enable tests in pipeline

- web/src/Web.App/Attributes/RequestTelemetry/RequestTelemetryAttribute.cs
- web/src/Web.App/Constants/TrackedRequestType.cs
- web/src/Web.App/Controllers/LocalAuthorityCensusController.cs
- web/src/Web.App/Controllers/LocalAuthorityComparisonController.cs
- web/src/Web.App/Controllers/LocalAuthorityController.cs
- web/src/Web.App/Controllers/SchoolCensusController.cs
- web/src/Web.App/Controllers/SchoolComparatorsController.cs
- web/src/Web.App/Controllers/SchoolComparatorsCreateByController.cs
- web/src/Web.App/Controllers/SchoolComparatorsCreateController.cs
- web/src/Web.App/Controllers/SchoolComparisonController.cs
- web/src/Web.App/Controllers/SchoolController.cs
- web/src/Web.App/Controllers/SchoolCustomDataChangeController.cs
- web/src/Web.App/Controllers/SchoolCustomDataController.cs
- web/src/Web.App/Controllers/SchoolPlanningController.cs
- web/src/Web.App/Controllers/SchoolPlanningCreatePlanController.cs
- web/src/Web.App/Controllers/SchoolSpendingComparisonController.cs
- web/src/Web.App/Controllers/SchoolSpendingController.cs
- web/src/Web.App/Controllers/TrustCensusController.cs
- web/src/Web.App/Controllers/TrustComparatorsController.cs
- web/src/Web.App/Controllers/TrustComparatorsCreateByController.cs
- web/src/Web.App/Controllers/TrustComparisonController.cs
- web/src/Web.App/Controllers/TrustController.cs
- web/src/Web.App/Controllers/TrustForecastController.cs
- web/src/Web.App/Controllers/TrustPlanningController.cs
- web/src/Web.App/Controllers/TrustSpendingController.cs
- web/src/Web.App/ViewComponents/AnalyticsViewComponent.cs
- web/src/Web.App/ViewModels/Components/AnalyticsViewModel.cs
- web/src/Web.App/Views/SchoolComparatorsCreate/Index.cshtml
- web/src/Web.App/Views/Shared/Components/Analytics/Default.cshtml
[AB#215606](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/215606) [AB#198080](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/198080)
See also: https://github.com/microsoft/ApplicationInsights-JS/issues/574
> Added server side operation ID as parent ID in client AI SDK

- web/tests/Web.E2ETests/Features/School/SchoolHome.feature
- web/tests/Web.E2ETests/Pages/School/CurriculumFinancialPlanningPage.cs
- web/tests/Web.E2ETests/Pages/School/DetailsPage.cs
- web/tests/Web.E2ETests/Selectors.cs
- web/tests/Web.E2ETests/Steps/School/HomeSteps.cs
[AB#216366](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/216366)
updated selectors
> fixed failing of tests and added login part to one of the test

- web/README.md
- web/Web.sln
- web/src/Web.App/AssetSrc/scss/main.scss
[AB#216052](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/216052) [AB#188391](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/188391)
Also updated README.md to add private npm feed connection details that went missing from an earlier commit.
> Remove grey background box from priority forecast message

- web/src/Web.App/Constants/PageTitles.cs
- web/src/Web.App/Controllers/SchoolComparatorsController.cs
- web/src/Web.App/Controllers/SchoolController.cs
- web/src/Web.App/Controllers/SchoolCustomDataController.cs
- web/src/Web.App/Controllers/TrustController.cs
- web/src/Web.App/Views/SchoolCustomData/Index.cshtml
- web/src/Web.App/Views/SchoolCustomData/Revert.cshtml
- web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
- web/tests/Web.Integration.Tests/Pages/Schools/CustomData/WhenViewingCustomDataRevert.cs
- web/tests/Web.Integration.Tests/Pages/Trusts/Comparators/WhenViewingComparatorsRevert.cs
- web/tests/Web.Integration.Tests/Paths.cs
AB#216232 [AB#192482](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/192482)
Also added missing integration test coverage for all 'revert' actions, plus 'sign in' CTA at beginning of Custom Data journey.
No links through to the custom data 'revert' action yet, but going direct to the correct URL should allow the journey to be validated.
> Added 'revert' functonality to School custom data journey

- web/src/Web.App/Views/TrustSpending/Index.cshtml
[AB#216395](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/216395) [AB#192288](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/192288)
> Appended 'per pupil' to Trust spending priorities table value

- pipelines/web/build.yaml
disabling a11y tests to reduce noise for e2e for investigation 
NA
NA
- ~~[] Work items have been linked [(use AB#)](https://learn.microsoft.com/en-us/azure/devops/boards/github/link-to-from-github?view=azure-devops#use-ab-to-link-from-github-to-azure-boards-work-items)~~
~~- [ ] Your branch has been rebased onto main~~
> disable a11y tests to reduce noise

- pipelines/web/steps/run-e2e-tests.yaml
removed pipeline continue on error for e2e 
n/a
n/a
n/a
> removed continue on error to set the pipeline to fail if failing

- web/src/Web.App/Views/SchoolCustomDataChange/_CustomDataEntryTableRow.cshtml
- web/src/Web.App/Views/Shared/_Layout.cshtml
- web/tests/Web.Integration.Tests/Pages/Schools/CustomData/WhenViewingCustomDataFinancialData.cs
[AB#216385](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/216385) [AB#198080](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/198080)
> Set all 'original' currency values to zero decimal places

- web/tests/Web.E2ETests/appsettings.json
updated e2e appsettings to show page response
n/a
n/a
n/a
> updated e2e appsettings to output page response

- pipelines/web/build.yaml
> reenable a11y tests in pipeline

- web/src/Web.App/Views/TrustSpending/Index.cshtml
- web/tests/Web.Integration.Tests/Pages/Trusts/WhenViewingSpending.cs
- web/tests/Web.Integration.Tests/Paths.cs
- web/tests/Web.Integration.Tests/WebAppClientBase.cs
[AB#216463](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/216463) [AB#192288](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/192288)
Integration tests
> Trust Spending integration tests

- front-end-components/src/views/budget-forecast-returns/partials/bfr-chart.tsx
- front-end-components/src/views/budget-forecast-returns/partials/bfr-table.tsx
- front-end-components/src/views/budget-forecast-returns/partials/year-end.tsx
- web/src/Web.App/Views/TrustForecast/_Metrics.cshtml
- web/src/Web.App/Views/TrustForecast/_RiskSummary.cshtml
- web/tests/Web.Integration.Tests/Pages/Trusts/WhenViewingForecast.cs
[AB#216769](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/216769) [AB#188391](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/188391)
Copy updates
> Update copy on BFR page

- web/tests/Web.Integration.Tests/Pages/Schools/CustomData/WhenViewingCustomDataCensus.cs
- web/tests/Web.Integration.Tests/Pages/Schools/CustomData/WhenViewingCustomDataComparison.cs
- web/tests/Web.Integration.Tests/Pages/Schools/CustomData/WhenViewingCustomisedData.cs
[AB#192482](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/192482) - [AB#214242](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/214242) [AB#214244](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/214244) [AB#214245](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/214245)
Adds integration tests for the following pages
- custom data census
- custom data comparison
- customised data (custom data dashboard)
N/A. integration tests for spending priorities to follow on a future PR
> test: integration tests for view custom data pages

- web/tests/Web.Integration.Tests/Pages/Schools/CustomData/WhenViewingCustomDataCensus.cs
- web/tests/Web.Integration.Tests/Pages/Schools/CustomData/WhenViewingCustomDataComparison.cs
- web/tests/Web.Integration.Tests/Pages/Schools/CustomData/WhenViewingCustomisedData.cs
[AB#192482](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/192482)
Updates expected breadcrumbs nodes in integration tests following changes
N/A
> test: fix failing tests following changes to breadcrumbs

- platform/src/abstractions/Platform.Functions/PipelineMessage.cs
- platform/src/apis/Platform.Orchestrator/PipelineDb.cs
- platform/src/apis/Platform.Orchestrator/PipelineFunctions.cs
[AB#192482](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/192482) [AB#215863](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/215863)
Handles unsuccessful pipeline runs, and set the user data status to failed.
N/A
> feat: handles unsuccessful pipeline runs

- web/src/Web.App/Attributes/CompareDecimalValueAttribute.cs
- web/src/Web.App/Attributes/CompareIntValueAttribute.cs
- web/src/Web.App/Attributes/CompareValueAttribute.cs
- web/src/Web.App/Controllers/FindOrganisationController.cs
- web/src/Web.App/Controllers/SchoolComparatorsController.cs
- web/src/Web.App/Controllers/SchoolComparatorsCreateByController.cs
- web/src/Web.App/Controllers/SchoolController.cs
- web/src/Web.App/Controllers/TrustComparatorsCreateByController.cs
- web/src/Web.App/ViewModels/SchoolComparatorsByNameViewModel.cs
- web/src/Web.App/ViewModels/SchoolViewModel.cs
- web/src/Web.App/ViewModels/TrustComparatorsByNameViewModel.cs
- web/src/Web.App/ViewModels/UserDefinedSchoolCharacteristicViewModel.cs
- web/src/Web.App/Views/School/_Banners.cshtml
- web/tests/Web.Integration.Tests/Pages/Schools/Comparators/WhenViewingComparatorsRevert.cs
[Content logic and error states tracker](https://docs.google.com/spreadsheets/d/12sHnxmp5_-lwXhHMLl1M9ARMHeBBC9yViSuj_9POZRk/edit?gid=951009702#gid=951009702)
> First set of error messages updates

- core-infrastructure/terraform/README.md
- core-infrastructure/terraform/ai.tf
Sample query in new query pack for Log Analytics
> Log analytics query pack

- web/src/Web.App/ViewModels/TrustForecastViewModel.cs
- web/src/Web.App/Views/TrustForecast/_Metrics.cshtml
- web/tests/Web.Integration.Tests/Pages/Trusts/WhenViewingForecast.cs
> Do not display 'Green' BFR guidance. Include year for Metrics data

- front-end-components/src/views/compare-your-census/partials/total-teachers-qualified.tsx
- front-end-components/src/views/compare-your-costs/partials/total-expenditure.tsx
- front-end-components/src/views/compare-your-trust/partials/total-expenditure.tsx
- front-end-components/src/views/historic-data/partials/census-section.tsx
- front-end-components/src/views/historic-data/partials/spending-section.tsx
- web/src/Web.App/Constants/PageTitles.cs
- web/src/Web.App/Views/LocalAuthorityCensus/Index.cshtml
- web/src/Web.App/Views/LocalAuthorityComparison/Index.cshtml
- web/src/Web.App/Views/Shared/Components/CustomDataFinanceTools/Default.cshtml
- web/src/Web.App/Views/Shared/Components/LocalAuthorityFinanceTools/Default.cshtml
- web/src/Web.App/Views/Shared/Components/Resources/Default.cshtml
- web/src/Web.App/Views/Shared/Components/TrustFinanceTools/Default.cshtml
- web/src/Web.App/Views/Trust/Details.cshtml
- web/src/Web.App/Views/TrustCensus/Index.cshtml
- web/src/Web.App/Views/TrustComparators/Index.cshtml
- web/src/Web.App/Views/TrustComparison/Index.cshtml
- web/tests/Web.Integration.Tests/Pages/Schools/CustomData/WhenViewingCustomDataCensus.cs
- web/tests/Web.Integration.Tests/Pages/Schools/CustomData/WhenViewingCustomDataComparison.cs
- web/tests/Web.Integration.Tests/Pages/Schools/CustomData/WhenViewingCustomDataSpendingComparison.cs
- web/tests/Web.Integration.Tests/Pages/Schools/CustomData/WhenViewingCustomisedData.cs
- web/tests/Web.Integration.Tests/Pages/Schools/WhenViewingComparison.cs
- web/tests/Web.Integration.Tests/Pages/Trusts/WhenViewingCensus.cs
- web/tests/Web.Integration.Tests/Pages/Trusts/WhenViewingComparison.cs
- web/tests/Web.Integration.Tests/Pages/Trusts/WhenViewingDetails.cs
Content updates 
Content updates 
N/A
> chore: content updates

- core-infrastructure/terraform/README.md
- core-infrastructure/terraform/queries.tf
- core-infrastructure/terraform/variables.tf
- platform/terraform/README.md
- prototype/terraform/README.md
- web/src/Web.App/Constants/TrackedRequestType.cs
- web/src/Web.App/Controllers/LocalAuthorityCensusController.cs
- web/src/Web.App/Controllers/LocalAuthorityComparisonController.cs
- web/src/Web.App/Controllers/SchoolCensusController.cs
- web/src/Web.App/Controllers/SchoolComparatorsController.cs
- web/src/Web.App/Controllers/SchoolComparatorsCreateByController.cs
- web/src/Web.App/Controllers/SchoolComparatorsCreateController.cs
- web/src/Web.App/Controllers/SchoolComparisonController.cs
- web/src/Web.App/Controllers/SchoolSpendingComparisonController.cs
- web/src/Web.App/Controllers/SchoolSpendingController.cs
- web/src/Web.App/Controllers/TrustCensusController.cs
- web/src/Web.App/Controllers/TrustComparatorsController.cs
- web/src/Web.App/Controllers/TrustComparatorsCreateByController.cs
- web/src/Web.App/Controllers/TrustComparisonController.cs
- web/src/Web.App/Controllers/TrustSpendingController.cs
- web/terraform/README.md
Also updated tracked request feature names to make the chart splits more informative:
> Modified log analytics query for tracked links

- core-infrastructure/terraform/README.md
- core-infrastructure/terraform/queries.tf
- platform/terraform/README.md
- prototype/terraform/README.md
- web/terraform/README.md
> Analytics workspace function syntax fix

- web/src/Web.App/Controllers/StaticContentController.cs
- web/src/Web.App/Views/DataSource/Index.cshtml
- web/src/Web.App/Views/DataSource/_Catering.cshtml
- web/src/Web.App/Views/DataSource/_DataSources.cshtml
- web/src/Web.App/Views/DataSource/_EducationalSupplies.cshtml
- web/src/Web.App/Views/DataSource/_FinanceCosts.cshtml
- web/src/Web.App/Views/DataSource/_Ict.cshtml
- web/src/Web.App/Views/DataSource/_Interpretation.cshtml
- web/src/Web.App/Views/DataSource/_Other.cshtml
- web/src/Web.App/Views/DataSource/_Premises.cshtml
- web/src/Web.App/Views/DataSource/_SpecialFacilities.cshtml
- web/src/Web.App/Views/DataSource/_TeachingCosts.cshtml
- web/src/Web.App/Views/DataSource/_Utilities.cshtml
- web/src/Web.App/Views/Shared/Components/Banner/Default.cshtml
- web/src/Web.App/Views/Shared/_Layout.cshtml
- web/src/Web.App/Views/StaticContent/Contact.cshtml
- web/src/Web.App/Views/StaticContent/Cookies.cshtml
- web/src/Web.App/Views/StaticContent/Privacy.cshtml
- web/tests/Web.Integration.Tests/Pages/WhenViewingContact.cs
- web/tests/Web.Integration.Tests/Pages/WhenViewingPrivacy.cs
Updates to content for static pages
- Data source
- Cookies
- Contact
- feedback banner links to Contact page
- Privacy link in footer links to DfE personal charter
N/A
> chore: static content pages updates

- web/src/Web.App/Views/SchoolComparators/Index.cshtml
- web/src/Web.App/Views/SchoolComparators/UserDefined.cshtml
- web/src/Web.App/Views/SchoolComparatorsCreateBy/_ChosenSchools.cshtml
changes following content discussion
Pupil numbers displayed as whole numbers
N/A
> chore: rounding of display for pupil numbers

- core-infrastructure/terraform/queries.tf
- core-infrastructure/terraform/variables.tf
- web/src/Web.App/Attributes/RequestTelemetry/RequestTelemetryAttribute.cs
- web/src/Web.App/Program.cs
- web/src/Web.App/Telemetry/AuthenticatedUserTelemetryInitializer.cs
- web/src/Web.App/Views/Shared/Components/Analytics/Default.cshtml
- web/tests/Web.Integration.Tests/TestAuth.cs
Also reinstates previously failing TF resource with resolved syntax.
> Include authenticated user ID in request, pageviews and queries

- web/src/Web.App/Constants/PageTitles.cs
- web/src/Web.App/Views/LocalAuthorityComparison/Index.cshtml
- web/src/Web.App/Views/SchoolComparison/Index.cshtml
- web/src/Web.App/Views/SchoolPlanningCreate/Start.cshtml
- web/src/Web.App/Views/Shared/CommercialResource/AllResources.cshtml
- web/src/Web.App/Views/Shared/Components/Banner/Default.cshtml
- web/src/Web.App/Views/Shared/Components/CustomDataFinanceTools/Default.cshtml
- web/src/Web.App/Views/Shared/Components/LocalAuthorityFinanceTools/Default.cshtml
- web/src/Web.App/Views/Shared/Components/SchoolFinanceTools/Default.cshtml
- web/src/Web.App/Views/StaticContent/Contact.cshtml
- web/tests/Web.E2ETests/Pages/School/HomePage.cs
- web/tests/Web.Integration.Tests/Pages/Schools/CustomData/WhenViewingCustomDataCensus.cs
- web/tests/Web.Integration.Tests/Pages/Schools/CustomData/WhenViewingCustomDataComparison.cs
- web/tests/Web.Integration.Tests/Pages/Schools/CustomData/WhenViewingCustomDataSpendingComparison.cs
- web/tests/Web.Integration.Tests/Pages/Schools/CustomData/WhenViewingCustomisedData.cs
- web/tests/Web.Integration.Tests/Pages/Schools/FinancialPlanning/WhenViewingPlanning.cs
- web/tests/Web.Integration.Tests/Pages/Schools/WhenViewingCensus.cs
- web/tests/Web.Integration.Tests/Pages/Schools/WhenViewingComparison.cs
- web/tests/Web.Integration.Tests/Pages/Schools/WhenViewingHome.cs
Content updates following discussion with design
Updates to a number of pages for minor tweaks
adds content for contact page and link for survey
updates integration and e2e tests following these content changes
N/A
> Chore: further content updates

- data-pipeline/src/pipeline/comparator_sets.py
- data-pipeline/src/pipeline/main.py
if there are no data to be persisted, do not attempt to write to the database.
> fix: skip database for empty data

- core-infrastructure/terraform/variables.tf
- web/src/Web.App/Attributes/RequestTelemetry/RequestTelemetryAttribute.cs
- web/src/Web.App/Constants/TrackedLinks.cs
- web/src/Web.App/Views/StaticContent/Contact.cshtml
- web/tests/Web.Tests/Attributes/GivenALocalAuthorityRequestTelemetryAttribute.cs
- web/tests/Web.Tests/Attributes/GivenASchoolRequestTelemetryAttribute.cs
- web/tests/Web.Tests/Attributes/GivenATrustRequestTelemetryAttribute.cs
[AB#216369](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/216369) [AB#196367](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/196367)
Also added `survey` as distinct type of `TrackedLink`
> `RequestTelemetryAttribute` implementation unit tests

- core-infrastructure/terraform/README.md
- core-infrastructure/terraform/dashboards.tf
- core-infrastructure/terraform/dashboards/mi.tpl
- core-infrastructure/terraform/dashboards/oi.tpl
- core-infrastructure/terraform/main.tf
- core-infrastructure/terraform/queries.tf
- core-infrastructure/terraform/queries/feature-requests.kql
- core-infrastructure/terraform/queries/get-establishment-requests.kql
- core-infrastructure/terraform/queries/get-feature-requests.kql
- core-infrastructure/terraform/queries/get-tracked-links.kql
- core-infrastructure/terraform/queries/pipeline-runs.kql
- core-infrastructure/terraform/queries/popular-local-authority-requests-chart.kql
- core-infrastructure/terraform/queries/popular-school-requests-chart.kql
- core-infrastructure/terraform/queries/popular-trust-requests-chart.kql
- core-infrastructure/terraform/queries/session-count-per-day.kql
- core-infrastructure/terraform/queries/session-length-per-day.kql
- core-infrastructure/terraform/queries/tracked-links.kql
- core-infrastructure/terraform/queries/user-auth-count-per-day.kql
- core-infrastructure/terraform/queries/user-count-per-day.kql
- core-infrastructure/terraform/queries/user-new-count-per-day.kql
- pipelines/common/sync-terraform.yaml
- pipelines/core-infrastructure/sync.yaml
- pipelines/destroy/destroy.yaml
[AB#217481](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/217481) [AB#196367](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/196367)
Deploy shared MI and OI dashboards to Azure Portal containing output from Log Analytics queries and App Insights metrics.
Dashboards have been deployed to [d15 feature environment](https://portal.azure.com/#@platform.education.gov.uk/dashboard/arm/subscriptions/f155d7d4-a235-4563-b077-c19686c7c92a/resourcegroups/s198d15-ebis-core/providers/microsoft.portal/dashboards/s198d15-ebis-dashboard-mi) for validation (note: potential lack of underlying data).
> Starter MI dashboard

- documentation/features/1_Integration-with-DfE-Signin.md
> update dfe sign documentation with DSI configuration

- core-infrastructure/terraform/README.md
- core-infrastructure/terraform/databases.tf
- platform/terraform/README.md
- platform/terraform/data.tf
- platform/terraform/functions.tf
- platform/terraform/modules/functions/README.md
- platform/terraform/modules/functions/main.tf
- platform/terraform/modules/functions/provider.tf
- platform/terraform/modules/functions/variables.tf
- platform/terraform/provider.tf
[AB#217767](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/217767) [AB#216190](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/216190)
Register client ID associated with each function app as database user. Updated app service connection string to use managed identity instead of user id/password combination.
This should not affect connecting to the database from a local developer machine using user id/password in the connection string as per the existing implementation. As deployed to `d17`, connecting from within infrastructure initiates the managed identity flow as may be seen when tracing a request:
> Added managed identity user to database and updated function app SQL connection string

- web/src/Web.App/Attributes/SchoolAuthorizationAttribute.cs
- web/src/Web.App/Attributes/TrustAuthorizationAttribute.cs
- web/tests/Web.Integration.Tests/Pages/Trusts/WhenViewingForecast.cs
[AB#218281](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/218281) [AB#218285](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/218285)
Fixes response from authorization attribute to return 403 rather than 401
Ensure `DisableOrganisationClaimCheck` feature set is to false.
> Fixes response from authorization attribute

- front-end-components/src/composed/horizontal-bar-chart-wrapper/composed.tsx
- front-end-components/src/views/compare-your-costs/partials/accordion-sections/administrative-supplies.tsx
- front-end-components/src/views/compare-your-costs/partials/accordion-sections/catering-staff-services.tsx
- front-end-components/src/views/compare-your-costs/partials/accordion-sections/educational-ict.tsx
- front-end-components/src/views/compare-your-costs/partials/accordion-sections/educational-supplies.tsx
- front-end-components/src/views/compare-your-costs/partials/accordion-sections/non-educational-support-staff.tsx
- front-end-components/src/views/compare-your-costs/partials/accordion-sections/other-costs.tsx
- front-end-components/src/views/compare-your-costs/partials/accordion-sections/premises-staff-services.tsx
- front-end-components/src/views/compare-your-costs/partials/accordion-sections/teaching-support-staff.tsx
- front-end-components/src/views/compare-your-costs/partials/accordion-sections/utilities.tsx
- front-end-components/src/views/compare-your-costs/partials/total-expenditure.tsx
- web/src/Web.App/Controllers/Api/CensusProxyController.cs
- web/src/Web.App/Controllers/Api/ExpenditureProxyController.cs
- web/src/Web.App/Controllers/SchoolComparatorsCreateByController.cs
- web/src/Web.App/Controllers/SchoolSpendingController.cs
- web/src/Web.App/Domain/Benchmark/SchoolComparatorSet.cs
- web/src/Web.App/Services/SchoolComparatorSetService.cs
- web/src/Web.App/TagHelpers/NavigationTagHelper.cs
- web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
- web/tests/Web.Integration.Tests/Proxy/WhenRequestingCensus.cs
- web/tests/Web.Integration.Tests/Proxy/WhenRequestingExpenditure.cs
[AB#217961](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/217961) [AB#218156](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/218156)
Gracefully handle when there is no comparator set, to ensure 500 response isn't returned to the front-end components.
There is open questions/spike regarding how to handle when there is no financial return data for a school.
Front-end package version will require bumping
> fix: gracefully handle when there is no comparator set

- core-infrastructure/terraform/dashboards.tf
- core-infrastructure/terraform/dashboards/mi.tpl
- core-infrastructure/terraform/dashboards/oi.tpl
- core-infrastructure/terraform/queries.tf
- core-infrastructure/terraform/queries/custom-data-funnel.kql
- core-infrastructure/terraform/queries/failures-query-prefix.kql
- core-infrastructure/terraform/queries/feature-requests-chart.kql
- core-infrastructure/terraform/queries/functions/get-auth-users.kql
- core-infrastructure/terraform/queries/functions/get-commercial-resources.kql
- core-infrastructure/terraform/queries/functions/get-establishment-requests.kql
- core-infrastructure/terraform/queries/functions/get-feature-requests.kql
- core-infrastructure/terraform/queries/functions/get-new-users.kql
- core-infrastructure/terraform/queries/functions/get-session-length.kql
- core-infrastructure/terraform/queries/functions/get-sessions.kql
- core-infrastructure/terraform/queries/functions/get-tracked-links.kql
- core-infrastructure/terraform/queries/functions/get-users.kql
- core-infrastructure/terraform/queries/popular-commercial-resources.kql
- core-infrastructure/terraform/queries/popular-local-authority-requests-chart.kql
- core-infrastructure/terraform/queries/popular-school-requests-chart.kql
- core-infrastructure/terraform/queries/popular-trust-requests-chart.kql
- core-infrastructure/terraform/queries/session-count-per-day.kql
- core-infrastructure/terraform/queries/session-length-per-day.kql
- core-infrastructure/terraform/queries/user-auth-count-per-day.kql
- core-infrastructure/terraform/queries/user-count-per-day.kql
- core-infrastructure/terraform/queries/user-counts.kql
- core-infrastructure/terraform/queries/user-new-count-per-day.kql
- core-infrastructure/terraform/queries/user-sessions.kql
[AB#218122](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/218122) [AB#196367](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/196367)
- Mini refactor of dashboard queries
- User counts dashboard part
- Sessions dashboard part
- Custom Data funnel dashboard part
- Commercial Resources dashboard part
- Application features dashboard part
Dashboard has been deployed to `d15` feature environment, but lack of data here renders some of the parts as empty.
> Further additions to MI Dashboard

- core-infrastructure/terraform/queries/functions/get-new-users.kql
- core-infrastructure/terraform/queries/user-counts.kql
[AB#218122](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/218122) [AB#196367](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/196367)
See workaround at https://stackoverflow.com/a/74315368/504477.
Dashboard has been deployed to `d15` feature environment, but lack of data here renders some of the parts as empty.
> GetNewUsers function fix to consume input time range

- core-infrastructure/terraform/dashboards.tf
- core-infrastructure/terraform/dashboards/mi.tpl
- core-infrastructure/terraform/queries.tf
- core-infrastructure/terraform/queries/user-sessions.kql
- core-infrastructure/terraform/queries/weekly-active-users.kql
[AB#218122](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/218122) [AB#196367](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/196367)
- `user-sessions` query fix
- `weekly-active-users` query addition
- Dashboard layout tweaks to make it easier to export .json from Portal and import into VSC
Dashboard has been deployed to `d15` feature environment, but lack of data here renders some of the parts as empty.
> Additional MI dashboard improvements

- data-pipeline/tests/unit/pre_processing/test_custom_data.py
- avoid using fields which are now referenced/modified elsewhere in the pipeline;
- account for recent post-processing changes.
should fix the issues seen as part of the build in #1112.
> test: correct custom-data tests

- documentation/testing/test-plans/20240710_release-test-plan.md
- documentation/testing/test-plans/20240711_release-test-plan.md
release test plan. This is a living doc until the end of day. it will be shared after being updated with all the tickets that will be completed and tested today.
> release test plan

- core-infrastructure/terraform/queries.tf
- core-infrastructure/terraform/queries/functions/get-anon-requests.kql
- core-infrastructure/terraform/queries/functions/get-session-length.kql
- core-infrastructure/terraform/queries/user-counts.kql
- core-infrastructure/terraform/queries/user-sessions.kql
[AB#219333](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/219333) [AB#196367](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/196367)
Also allow custom build number to be defined when running Feature pipeline
Currently deployed to `d15` feature environment for validation.
> Include anonymous user requests in User Counts query

- core-infrastructure/terraform/queries/functions/get-anon-requests.kql
- core-infrastructure/terraform/queries/user-sessions.kql
[AB#219333](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/219333) [AB#196367](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/196367)
Currently deployed to `d15` feature environment for validation.
> Filter out API requests from all requests function

- platform/tests/Platform.ApiTests/Features/EstablishmentLocalAuthorities.feature
- platform/tests/Platform.ApiTests/Features/EstablishmentSchools.feature
- platform/tests/Platform.ApiTests/Features/EstablishmentTrusts.feature
- platform/tests/Platform.ApiTests/Steps/EstablishmentLocalAuthoritiesSteps.cs
- platform/tests/Platform.ApiTests/Steps/EstablishmentSchoolsSteps.cs
- platform/tests/Platform.ApiTests/Steps/EstablishmentTrustsSteps.cs
[AB#218555](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/218555) - [AB#218581](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/218581)
Adds specflow tests for Establishment API endpoints.
To run locally ```appsettings.local.json``` must contain host and key for ```d02```
> chore: establishment api tests

- platform/src/apis/Platform.Api.Benchmark/OpenApi/Examples/UserDataExamples.cs
- platform/src/apis/Platform.Api.Benchmark/UserData/UserDataFunctions.cs
- platform/src/apis/Platform.Api.Insight/Trusts/TrustsFunctions.cs
- platform/src/apis/Platform.Api.Insight/Trusts/TrustsParameters.cs
- platform/tests/Platform.ApiTests/Features/BenchmarkComparators.feature
[AB#220971](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/220971) [AB#217226](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/217226)
First attempt to force a re-deploy of functions by fixing broken API tests due to target test environment not yet being updated.
Related to #1137, which broke the build due to failing API test.
> Force a re-deploy of functions by fixing broken API test

- core-infrastructure/terraform/README.md
- core-infrastructure/terraform/dashboards.tf
- core-infrastructure/terraform/dashboards/mi.tpl
- core-infrastructure/terraform/dashboards/oi.tpl
- core-infrastructure/terraform/queries.tf
- core-infrastructure/terraform/queries/feature-requests-by-auth.kql
- core-infrastructure/terraform/queries/feature-requests.kql
- core-infrastructure/terraform/queries/functions/get-waf-blocked-requests.kql
- core-infrastructure/terraform/queries/functions/get-waf-logs.kql
- core-infrastructure/terraform/queries/popular-local-authority-requests.kql
- core-infrastructure/terraform/queries/popular-school-requests.kql
- core-infrastructure/terraform/queries/popular-trust-requests.kql
- core-infrastructure/terraform/queries/waf-blocked-requests-per-hour.kql
- core-infrastructure/terraform/queries/waf-requests.kql
[AB#220583](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/220583) [AB#219227](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/219227)
Updated dashboard has been deployed to `d15` feature environment for validation. A wider time range may need to be set to see any results and/or some dummy failed requests made to that environment to see the results.
> Added Firewall queries to OI dashboard

- core-infrastructure/terraform/provider.tf
- front-end-components/package-lock.json
- platform/Directory.Packages.props
- platform/src/abstractions/Platform.Functions/packages.lock.json
- platform/src/apis/Platform.Api.Benchmark/packages.lock.json
- platform/src/apis/Platform.Api.Establishment/packages.lock.json
- platform/src/apis/Platform.Api.Insight/packages.lock.json
- platform/src/apis/Platform.Orchestrator/packages.lock.json
- platform/src/apis/Platform.UserDataCleanUp/packages.lock.json
- platform/terraform/modules/functions/provider.tf
- platform/tests/Platform.ApiTests/packages.lock.json
- platform/tests/Platform.Tests/packages.lock.json
- prototype/src/package-lock.json
- web/Directory.Packages.props
- web/src/Web.App/package-lock.json
- web/src/Web.App/packages.lock.json
- web/tests/Web.A11yTests/packages.lock.json
- web/tests/Web.E2ETests/packages.lock.json
- web/tests/Web.Integration.Tests/packages.lock.json
- web/tests/Web.Tests/packages.lock.json
[AB#222227](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/222227) [AB#222226](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/222226)
Resolve all pending dependabot package updates across front end projects in monorepo.
Restore and build everything locally and run tests/regression.
> dependabot updates across all front end projects

- web/src/Web.App/Constants/PageTitles.cs
- web/src/Web.App/Controllers/SchoolComparatorsCreateByController.cs
- web/src/Web.App/ViewModels/SchoolComparatorsByNameViewModel.cs
- web/src/Web.App/ViewModels/SchoolComparatorsChosenSchoolsViewModel.cs
- web/src/Web.App/ViewModels/SchoolComparatorsSubmittedViewModel.cs
- web/src/Web.App/Views/SchoolComparatorsCreateBy/Name.cshtml
- web/src/Web.App/Views/SchoolComparatorsCreateBy/Submit.cshtml
- web/src/Web.App/Views/SchoolComparatorsCreateBy/_ChosenSchools.cshtml
- web/tests/Web.Integration.Tests/Pages/Schools/Comparators/WhenViewingComparatorsCreateSubmit.cs
[AB#218109](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/218109) - [AB#222934](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/222934)
Addresses issue 32 and 40 for this story
use `UserDefinedSchoolComparatorSet.RunId` to set whether this is an edit to a previous user defined comparator set or not. Conditionally set button text and the heading and title for the submit page based on this.
N/A
> fixes to edit school comparator set journey

- web/src/Web.App/Infrastructure/Apis/ApiRequests/PostSchoolComparatorsRequest.cs
- web/src/Web.App/ViewModels/SchoolComparatorsPreviewViewModel.cs
- web/src/Web.App/ViewModels/UserDefinedSchoolCharacteristicViewModel.cs
- web/src/Web.App/Views/SchoolComparatorsCreateBy/Preview.cshtml
- web/src/Web.App/Views/SchoolComparatorsCreateBy/_SchoolCategories.cshtml
- web/tests/Web.Tests/Infrastructure/Apis/Requests/GivenAPostSchoolComparatorsRequest.cs
[AB#221010](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/221010) - [AB#221648](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/221648)
Updates the phases displayed for selection on the user defined comparator set characteristics creation page to match those listed on this story
n/a
> feat: updates phases for user defined comparator sets characteristics

- web/src/Web.App/Domain/OverallPhaseTypes.cs
- web/src/Web.App/Views/TrustComparatorsCreateBy/Characteristic.cshtml
[AB#221010](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/221010) - [AB#223688](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/223688)
The characteristics selection has been updated to only include those phases valid for academies
n/a
> feat: updates phases displayed for trust-to-trust benchmarking

- data-pipeline/src/pipeline/main.py
- retrieve data from correct BFR SOFA file
- account for conditions where the BFR SOFA file is _not_ there
[AB#217947](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/217947)
> fix: correct BFR SOFA derivation

- web/src/Web.App/ViewModels/SchoolSpendingViewModel.cs
- web/src/Web.App/Views/SchoolSpending/CustomData.cshtml
- web/src/Web.App/Views/SchoolSpending/_Costs.cshtml
[AB#224429](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/224429) ([AB#224467](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/224467))
Fixes URI on priority spending pages, so that correctly links to the appropriate comparison pages
N/A
> bug: fixes uri for comparision pages

- data-pipeline/src/pipeline/main.py
- data-pipeline/src/pipeline/pre_processing.py
- data-pipeline/tests/unit/pre_processing/test_bfr.py
- leave IO-based tasks in `main.py`
- move actual data manipulation to `pre_processing.py`
> refactor: isolate BFR SOFA processing

- documentation/architecture/decisions/0005-api-performance-testing-with-azure-load-tests.md
AB#222981 [AB#219594](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/219594)
> Documentation for technical decision for Azure Load Testing

- core-infrastructure/terraform/README.md
- core-infrastructure/terraform/databases.tf
- core-infrastructure/terraform/provider.tf
[AB#222561](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/222561) ([AB#224630](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/224630))
Adds permission to service permission to enable database migration to be run using managed identity
N/A
> feat: add database permission to sp

- pipelines/core-infrastructure/deployment.yaml
[AB#222561](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/222561) ([AB#224632](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/224632))
Update pipeline to pass in MI connection string for db migration app
> feat: update db migration to use MI

- platform/src/apis/Platform.Api.Establishment/Schools/SchoolsService.cs
[AB#223871](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/223871) ([AB#225575](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/225575))
Updates response to include additional address field
N/A
> feat: adds additional fields to suggest response

- web/src/Web.App/Services/SuggestService.cs
[AB#223871](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/223871) ([AB#225793](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/225793))
Updates LA suggest responses to include LA Code
N/A
> feat: adds la code to suggest response

- web/tests/Web.Tests/Services/WhenSchoolSuggestionsIsCalled.cs
[AB#223871](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/223871) ([AB#225699](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/225699))
Adds unit test coverage for changes to school suggestions
Tests continue to passes. Tests cases added for the various outputs to the school suggestion text.
> feat: adds unit test coverage

- web/src/Web.App/Constants.cs
- web/src/Web.App/Views/Error/Forbidden.cshtml
- web/src/Web.App/Views/StaticContent/Contact.cshtml
[AB#225527](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/225527) ([AB#225729](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/225729))
Updates support email address on access denied and contact pages
> feat: updates support email address

- web/tests/Web.E2ETests/Extensions/LocatorExtensions.cs
- web/tests/Web.E2ETests/Features/FindOrganisation.feature
- web/tests/Web.E2ETests/Pages/FindOrganisationPage.cs
- web/tests/Web.E2ETests/Steps/FindOrganisationSteps.cs
[AB#223871](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/223871) ([AB#225696](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/225696))
added e2e test scenario
n/a
> e2e tests for school suggest response

- front-end-components/src/components/total-catering-costs-type/component.tsx
[AB#225534](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/225534) [AB#214976](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/214976)
Copy change.
> Modified radio toggle heading

- support-analytics/terraform/README.md
- support-analytics/terraform/alerts.tf
- support-analytics/terraform/data.tf
[AB#225090](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/225090) ([AB#225827](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/225827))
Adds CPU and memory utilisation alerts
N/A
> feat: adds CPU and memory utilisation alerts

- front-end-components/index.html
- front-end-components/src/components/charts/table-chart/component.tsx
- front-end-components/src/index.css
- web/src/Web.App/package-lock.json
[AB#225534](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/225534) [AB#214976](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/214976)
CSS fix.
> Prevented wrapping of 'value' cells in chart tables

- web/src/Web.App/package-lock.json
- web/tests/Web.E2ETests/Features/School/CompareYourCosts.feature
- web/tests/Web.E2ETests/Pages/School/CompareYourCostsPage.cs
- web/tests/Web.E2ETests/Selectors.cs
- web/tests/Web.E2ETests/Steps/School/CompareYourCostsSteps.cs
[AB#225694](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/225694) [AB#225478](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/225478)
End-to-end test coverage
> E2E tests for chart tooltip accessible via keyboard

- web/tests/Web.E2ETests/Steps/School/FinancialPlanningSteps.cs
[AB#226248](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/226248) ([AB#226247](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/226247)) 
n/a
n/a
> update dsi login to deal with separate email and password page

- web/tests/Web.E2ETests/Steps/School/HomeSteps.cs
[AB#226247](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/226247) ([AB#226248](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/226248))
fixed homepage tests
> fixed homepage tests

- documentation/testing/performance-test-plans/0001_API-average-load-test-plan.md
- performance-tests/src/platform/establishment/school/suggest/config.yaml
- performance-tests/src/platform/establishment/school/suggest/suggest.csv
- performance-tests/src/platform/establishment/school/suggest/url-test.json
[AB#225958](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/225958) [AB#222362](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/222362)
Copy of input files from Load Test deployed and executed on `t01`.
> Load test definition for `POST /schools/suggest`

- platform/Directory.Packages.props
- platform/src/abstractions/Platform.Functions/packages.lock.json
- platform/src/abstractions/Platform.Infrastructure/packages.lock.json
- platform/src/apis/Platform.Api.Benchmark/packages.lock.json
- platform/src/apis/Platform.Api.Establishment/packages.lock.json
- platform/src/apis/Platform.Api.Insight/packages.lock.json
- platform/src/apis/Platform.Orchestrator/packages.lock.json
- platform/src/apis/Platform.UserDataCleanUp/packages.lock.json
- platform/src/search/Platform.Search.App/packages.lock.json
- platform/src/search/Platform.Search.Processor/packages.lock.json
- platform/src/search/Platform.Search/packages.lock.json
- platform/tests/Platform.ApiTests/packages.lock.json
- platform/tests/Platform.Tests/packages.lock.json
[AB#226361](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/226361) ([AB#226362](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/226362))
Bumps package deps;
- Microsoft.Azure.Functions.Worker
- Microsoft.Azure.Functions.Worker.Core
- Microsoft.Azure.Functions.Worker.ApplicationInsights
- Microsoft.Azure.Functions.Worker.Extensions.DurableTask
- Microsoft.Data.SqlClient
- Microsoft.NET.Test.Sdk
N/A
> chore: bumps platform package deps

- web/Directory.Packages.props
- web/src/Web.App/package-lock.json
- web/src/Web.App/packages.lock.json
- web/tests/Web.A11yTests/packages.lock.json
- web/tests/Web.E2ETests/packages.lock.json
- web/tests/Web.Integration.Tests/packages.lock.json
- web/tests/Web.Tests/packages.lock.json
[AB#226361](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/226361) ([AB#226363](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/226363))
Updated dependencies for 'web' project following dependabot notifications.
> `web` package updates

- documentation/testing/performance-test-plans/0001_API-average-load-test-plan.md
- documentation/testing/performance-test-plans/0002_API-peak-load-test-plan.md
[AB#222943](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/222943) ([AB#219594](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/219594))
Peak load test plan
> peak load test plan

- data-pipeline/src/pipeline/rag.py
As per 224500, schools are not RAG rated when they include only part-year data.
- extend reduced column-list to include part-year indicator
- skip rows where this is both present and true
…
> feat: skip RAG for part-year data

- core-infrastructure/terraform/databases.tf
[AB#226836](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/226836) [AB#222562](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/222562)
For this to work, SAS on log storage account has also been re-enabled.
`checkov` ignore statement added, with link back to above story.
This has been released to the `d12` feature environment for validation.
> Added `storage_account_access_key` to various DB auditing resources

- core-infrastructure/terraform/dashboards.tf
- core-infrastructure/terraform/dashboards/oi.tpl
- core-infrastructure/terraform/queries.tf
- core-infrastructure/terraform/queries/function-app-role-instance-count.kql
- core-infrastructure/terraform/queries/functions/get-fa-traces.kql
[AB#227945](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/227945) [AB#226875](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/226875)
OI dashboard update
Deployed to `d13` feature environment. Validated in `t01` previously.
> Added Function App instance count to OI dashboard

- core-infrastructure/terraform/databases.tf
- core-infrastructure/terraform/queries.tf
- core-infrastructure/terraform/queries/pipeline-runs.kql
- core-infrastructure/terraform/storage.tf
- platform/terraform/storage.tf
- supporting-data/terraform/storage.tf
- web/terraform/storage.tf
[AB#228879](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/228879) [AB#228386](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/228386)
Also modified Pipeline Runs query to remove dependency on current environment name
This change has been deployed to [`d12`](https://s198d12-education-benchmarking-dsggcjhggxdnaye6.a02.azurefd.net/) feature environment and validated to have no detrimental impact on the product.
> Disabled Local User across all storage accounts

- web/src/Web.App/Views/SchoolPlanning/View.cshtml
- web/src/Web.App/Views/SchoolPlanningCreate/ManagementRoles.cshtml
- web/src/Web.App/Views/SchoolPlanningCreate/ManagersPerRole.cshtml
- web/src/Web.App/Views/SchoolPlanningCreate/OtherTeachingPeriods.cshtml
- web/src/Web.App/Views/SchoolPlanningCreate/OtherTeachingPeriodsConfirm.cshtml
- web/src/Web.App/Views/SchoolPlanningCreate/OtherTeachingPeriodsReview.cshtml
- web/src/Web.App/Views/SchoolPlanningCreate/PrePopulateData.cshtml
- web/src/Web.App/Views/SchoolPlanningCreate/PrimaryHasMixedAgeClasses.cshtml
- web/src/Web.App/Views/SchoolPlanningCreate/PrimaryMixedAgeClasses.cshtml
- web/src/Web.App/Views/SchoolPlanningCreate/PrimaryPupilFigures.cshtml
- web/src/Web.App/Views/SchoolPlanningCreate/PupilFigures.cshtml
- web/src/Web.App/Views/SchoolPlanningCreate/SelectYear.cshtml
- web/src/Web.App/Views/SchoolPlanningCreate/Start.cshtml
- web/src/Web.App/Views/SchoolPlanningCreate/TeacherPeriodAllocation.cshtml
- web/src/Web.App/Views/SchoolPlanningCreate/TeachingAssistantFigures.cshtml
- web/src/Web.App/Views/SchoolPlanningCreate/TeachingPeriodsManager.cshtml
- web/src/Web.App/Views/SchoolPlanningCreate/TimetableCycle.cshtml
- web/src/Web.App/Views/SchoolPlanningCreate/TotalEducationSupport.cshtml
- web/src/Web.App/Views/SchoolPlanningCreate/TotalExpenditure.cshtml
- web/src/Web.App/Views/SchoolPlanningCreate/TotalIncome.cshtml
- web/src/Web.App/Views/SchoolPlanningCreate/TotalNumberTeachers.cshtml
- web/src/Web.App/Views/SchoolPlanningCreate/TotalTeacherCosts.cshtml
- web/tests/Web.Integration.Tests/DocumentAssert.cs
[AB#228451](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/228451) [AB#221013](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/221013)
This replaces existing implementations of school name/page title combination.
> Added `EstablishmentHeading` component to CFP views

- pipelines/core-infrastructure/deployment.yaml
- pipelines/platform/deployment.yaml
- pipelines/platform/security-scan.yaml
- pipelines/web/security-scan.yaml
[AB#225528](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/225528) - [AB#229154](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/229154)
Updates `AzureKeyVault@1` to `AzureKeyVault@2` 
all inputs remain the same
> chore: update deprecated AzureKeyVault task

- web/src/Web.App/Controllers/StaticContentController.cs
- web/src/Web.App/Views/Shared/_Layout.cshtml
- web/src/Web.App/Views/StaticContent/Accessibility.cshtml
- web/tests/Web.Integration.Tests/Pages/WhenViewingAccessibility.cs
[AB#212855](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/212855) - [AB#228833](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/228833)
Adds an accessibility statement page to the service, basic integration test.  
Ensure no copy errors to the content
> feat: adds accessibility statement page

- web/src/Web.App/Domain/OverallPhaseTypes.cs
- web/tests/Web.Tests/Infrastructure/Apis/Requests/GivenAPostSchoolComparatorsRequest.cs
- web/tests/Web.Tests/ViewModels/GivenATrustViewModel.cs
[AB#229315](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/229315) [AB#229260](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/229260)
Added missing test coverage in addition to the above
View a trust containing UTC(s) as per the story (e.g. https://localhost:7095/trust/07166427) to ensure that the missing college is now present.
> Resolved case sensitivity of `University Technical College` overall phase type

- web/src/Web.App/Views/StaticContent/Accessibility.cshtml
[AB#212855](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/212855)
Minor content updates
N/A
> feat: content update

- web/tests/Web.E2ETests/Extensions/LocatorExtensions.cs
- web/tests/Web.E2ETests/Features/School/CompareYourCosts.feature
- web/tests/Web.E2ETests/Features/Trust/CompareYourCosts.feature
- web/tests/Web.E2ETests/Features/Trust/TrustHome.feature
- web/tests/Web.E2ETests/Pages/School/CompareYourCostsPage.cs
- web/tests/Web.E2ETests/Pages/School/HomePage.cs
- web/tests/Web.E2ETests/Pages/Trust/CompareYourCostsPage.cs
- web/tests/Web.E2ETests/Pages/Trust/HomePage.cs
- web/tests/Web.E2ETests/Selectors.cs
- web/tests/Web.E2ETests/Steps/School/CompareYourCostsSteps.cs
- web/tests/Web.E2ETests/Steps/Trust/CompareYourCostsSteps.cs
- web/tests/Web.E2ETests/Steps/Trust/HomeSteps.cs
- web/tests/Web.E2ETests/Web.E2ETests.csproj
[AB#229317](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/229317) [AB#228013](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/228013)
Run the end-to-end tests targeting the `d02` environment.
> E2E tests for part year data in School and Trust benchmark charts

- documentation/quality-assurance/release-test-plans/00006_reelase-test-plan.md
> release plan 23/09/24

- front-end-components/index.html
- front-end-components/src/views/historic-data/partials/spending-section-other.tsx
- web/Web.sln.DotSettings
- web/tests/Web.E2ETests/Pages/School/HistoricDataPage.cs
[AB#229801](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/229801) [AB#229448](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/229448)
>  Added missing chart to historical 'other costs'

- core-infrastructure/terraform/README.md
- core-infrastructure/terraform/provider.tf
- data-pipeline/terraform/README.md
- data-pipeline/terraform/provider.tf
- performance-tests/terraform/README.md
- performance-tests/terraform/provider.tf
- platform/terraform/README.md
- platform/terraform/modules/functions/README.md
- platform/terraform/provider.tf
- prototype/terraform/README.md
- prototype/terraform/provider.tf
- scripts/terraform.ps1
- support-analytics/terraform/README.md
- support-analytics/terraform/provider.tf
- supporting-data/terraform/provider.tf
- web/terraform/README.md
- web/terraform/provider.tf
[AB#229937](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/229937) [AB#227199](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/227199)
Update `hashicorp/azurerm` provider to latest version.
Trunk deployed to `d15` (original versions of the provider) before this branch was then deployed to the same environment. This should replicate what happens when rolled out to existing environments. No Terraform issues occurred during this second deployment using the latest version of the provider across all components in the monorepo.
> Bumped `hashicorp/azurerm` provider to `4.3.0`

- front-end-components/src/components/charts/establishment-tick/component.tsx
[AB#230150](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/230150) [AB#230149](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/230149)
Build and copy `front-end` to `web`. Browse to a school with part year data, such as https://localhost:7095/school/139735/comparison. The '⚠️' icon should be aligned with each school name rather than to the left of the tick on the y-axis.
> Aligned `<Exclamation>` component with sibling `<text>` element in chart tick

- front-end-components/index.html
- front-end-components/src/views/historic-data/partials/balance-section.tsx
- front-end-components/src/views/historic-data/partials/income-section-self-generated.tsx
[AB#230321](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/230321) [AB#230041](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/230041)
Also fixed badly formatted `<details>` block.
> Resolved typo on revenue reserve commentary

- documentation/quality-assurance/4_Performance-Testing.md
- documentation/quality-assurance/performance-test-plans/0004_Web-average-load-test-plan.md
- performance-tests/src/web/average/local-authority/home/config.yaml
- performance-tests/src/web/average/local-authority/home/local-authorities.csv
- performance-tests/src/web/average/local-authority/home/url-test.json
[AB#230398](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/230398) [AB#229325](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/229325)
To be used for before/after LA/School refactor.
> Load test for Local Authority home page

- platform/src/apis/Platform.Api.Establishment/LocalAuthorities/LocalAuthoritiesFunctions.cs
- platform/src/apis/Platform.Api.Establishment/LocalAuthorities/LocalAuthoritiesService.cs
- platform/src/apis/Platform.Api.Establishment/Trusts/TrustsFunctions.cs
- platform/src/apis/Platform.Api.Establishment/Trusts/TrustsService.cs
- platform/tests/Platform.Tests/Establishment/LocalAuthoritiesFunctionsTestBase.cs
- platform/tests/Platform.Tests/Establishment/TrustsFunctionsTestBase.cs
- platform/tests/Platform.Tests/Establishment/WhenFunctionReceivesGetLocalAuthorityRequest.cs
- platform/tests/Platform.Tests/Establishment/WhenFunctionReceivesGetTrustRequest.cs
[AB#230534](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/230534) [AB#229325](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/229325)
Functionally, both LAs and Trusts should behave the same after this change.
> Refactor `LocalAuthoritiesService` and `TrustsService` to remove dependency on `SchoolsService` from respective functions

- data-pipeline/src/pipeline/comparator_sets.py
known [issue](https://github.com/pandas-dev/pandas/issues/16864) in Pandas.
> fix: avoid single-element comparator-sets

- web/tests/Web.E2ETests/Steps/School/FinancialPlanningSteps.cs
- web/tests/Web.E2ETests/Steps/School/HomeSteps.cs
[AB#230856](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/230856) ([AB#230857](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/230857))
updated e2e tests
> updated e2e tests after dsi login changes

- prototype/src/package-lock.json
[AB#230660](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/230660) [AB#230656](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/230656)
Versions updated according to dependabot reported versions
Run `prototype` and then browse the site locally to validate no unexpected results.
> chore: Bumped `prototype` package versions

- front-end-components/package-lock.json
[AB#230659](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/230659) [AB#230656](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/230656)
Versions updated according to dependabot reported versions
Build and copy `front-end` to `Web` and browse the site locally to validate no unexpected results.
> Bumped `front-end` package versions

- data-pipeline/README.md
[AB#230921](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/230921) [AB#230919](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/230919)
> Added instructions for installing dependencies using poetry from current Windows DfE kit

- data-pipeline/src/pipeline/comparator_sets.py
- data-pipeline/src/pipeline/input_schemas.py
- data-pipeline/src/pipeline/main.py
- data-pipeline/src/pipeline/maintained_schools.py
- data-pipeline/src/pipeline/mappings.py
- data-pipeline/src/pipeline/part_year/__init__.py
- data-pipeline/src/pipeline/part_year/academies.py
- data-pipeline/src/pipeline/part_year/common.py
- data-pipeline/src/pipeline/part_year/maintained_schools.py
- data-pipeline/src/pipeline/pre_processing.py
- data-pipeline/tests/unit/comparator_sets/test_part_year.py
- data-pipeline/tests/unit/part_year/test_map_academies.py
- data-pipeline/tests/unit/pre_processing/conftest.py
- data-pipeline/tests/unit/pre_processing/test_mappings.py
Much as previously done with for Maintained Schools, perform various checks as per the referenced ticket and, where necessary, skip RAG calculations.
[AB#226428](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/226428)
- refactor existing Maintained-school functions for dual-use
- add functions to derive the various "check" values
- extend comparator-set checks to include Academy-specific checks
…
> feat: handle Academies part-year data

- data-pipeline/src/pipeline/pre_processing.py
- data-pipeline/tests/unit/pre_processing/test_aar.py
- data-pipeline/tests/unit/pre_processing/test_central_services.py
[AB#229446](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/229446) ([AB#232050](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/232050))
Fixes in-year balance calculation for academies. 
Pipeline ran successfully locally
> bugfix: fixes in-year balance calculation

- data-pipeline/src/pipeline/mappings.py
- data-pipeline/tests/unit/pre_processing/test_mappings.py
[AB#232000](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/232000) ([AB#232040](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/232040))
Based on when the academy transferred into a trust the period should be as follows;
- 1st Sept > 10th Sept == 12 months
- 10th Sept >  30th Sept == 11 months
- 1st Oct >  31st Oct == 11 months
- 1st Nov>  30th Nov == 10 months
- 1st Dec >  31st Dec == 9 months
- 1st Jan >  31st Jan  == 8 months
- 1st Feb >  28th Feb == 7 months
- 1st Mar >  31st Mar == 6 months
- 1st Apr >  30th Apr == 5 months
- 1st May >  31st May == 4 months
- 1st June >  30th June == 3 months
- 1st July >  31st July == 2 months
- 1st Aug >  31st Aug == 1 months
- 
Based on when the academy transferred out of …
> bugfix: fixes period covered by return logic

- pipelines/support-analytics/release.yaml
[AB#229444](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/229444) [AB#229443](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/229443) [AB#229868](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/229868) #1381
Reverts previous planned change. To be merged once dependent environments stable following removal of dashboard-related resources.
Reverts 191e6c204bcfb460748d5551189e96471ada14dd
> Revert temporary removal of `support-analytics` trigger

- data-pipeline/src/pipeline/config.py
- data-pipeline/src/pipeline/database.py
- data-pipeline/src/pipeline/pre_processing.py
- data-pipeline/tests/unit/pre_processing/test_aar.py
- data-pipeline/tests/unit/pre_processing/test_central_services.py
[AB#217196](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/217196) ([AB#232316](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/232316))
Ensures DirectRevenueFinancing is correctly populated.
NB: income_category_map wasn't updated as same field is used two, and renaming of field causes one or the either to disappear.
Ran pipeline locally to validate output
> bugfix: fixes null direct revenue values

- web/src/Web.App/Views/StaticContent/Accessibility.cshtml
[AB#230287](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/230287) - [AB#232988](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/232988)
replaces IE11 with Microsoft Edge in the content for the accessibility page
N/A
> fix: update accessibility content

- platform/src/apis/Platform.Api.Establishment/Schools/School.cs
- platform/src/apis/Platform.Api.Establishment/Schools/SchoolsService.cs
- web/src/Web.App/Domain/Establishment/FederationSchool.cs
- web/src/Web.App/Domain/Establishment/School.cs
- web/src/Web.App/ViewModels/SchoolViewModel.cs
- web/src/Web.App/Views/School/Index.cshtml
- web/src/Web.App/Views/School/_FederationSchools.cshtml
- web/tests/Web.Integration.Tests/Pages/Schools/WhenViewingHome.cs
[AB#232745](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/232745) - [AB#233273](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/233273)
Adds a section to the homepage to be displayed when said school is a lead federation school. This contains a brief message that the school is the lead school and a list of school within that federation.
Minor change to platform to return the federated schools in the response.
Minor change to update the existing integration tests for this page.
Integration tests to follow in a future PR
> Lead federation school homepage

- documentation/quality-assurance/6_Data-Seeding-in-Test-Environment.md
data seeding approach for automated tests.
> data seeding in testing environment.

- web/src/Web.App/package-lock.json
[AB#233513](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/233513)
bump front-end package following #1490 
N/A
> chore: bump front-end to 1.0.96

- web/src/Web.App/Views/SchoolComparators/Index.cshtml
[AB#233516](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/233516) ([AB#233998](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/233998))
Updates content for pupil comparator set
N/A
> feat: updates content for pupil comparator set

- web/src/Web.App/Extensions/ServiceCollectionExtensions.cs
[AB#234442](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/234442) ([AB#234443](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/234443))
Ensures company number is correctly padding to 8 digits
Locally reproduced and validated using Trust reported by client.
> bugfix: adds padding to company number claim received from DSI

- documentation/quality-assurance/release-test-plans/00009_reelase-test-plan.md
completed release plan 2024.10.5
> Doc/release test plan 2024.10.5

- web/src/Web.App/Domain/CostCategories.cs
- web/tests/Web.E2ETests/Features/CostCategoriesGuidance.feature
[AB#234656](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/234656) ([AB#234665](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/234665))
Adds missing sub-categories for other costs
N/A
> feat: Adds missing categories for other costs

- core-infrastructure/terraform/databases.tf
- core-infrastructure/terraform/storage.tf
- pipelines/common/run-terraform.yaml
- platform/terraform/storage.tf
- web/terraform/storage.tf
[AB#234398](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/234398) [AB#231301](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/231301)
Previously deployed to `d15` feature environment for validation
> Enabled versioning and container soft delete on all storage accounts

- web/src/Web.App/Views/Shared/CommercialResource/_AdministrativeSupplies.cshtml
- web/src/Web.App/Views/Shared/CommercialResource/_CateringStaffServices.cshtml
- web/src/Web.App/Views/Shared/CommercialResource/_EducationalIct.cshtml
- web/src/Web.App/Views/Shared/CommercialResource/_EducationalSupplies.cshtml
- web/src/Web.App/Views/Shared/CommercialResource/_NonEducationalSupportStaff.cshtml
- web/src/Web.App/Views/Shared/CommercialResource/_OtherCosts.cshtml
- web/src/Web.App/Views/Shared/CommercialResource/_PremisesStaffServices.cshtml
- web/src/Web.App/Views/Shared/CommercialResource/_TeachingStaff.cshtml
- web/src/Web.App/Views/Shared/CommercialResource/_Utilities.cshtml
- web/tests/Web.E2ETests/Features/School/CommercialResources.feature
- web/tests/Web.E2ETests/Features/School/SpendingCosts.feature
- web/tests/Web.E2ETests/Pages/School/CommercialResourcesPage.cs
- web/tests/Web.E2ETests/Steps/School/CommercialResourcesSteps.cs
[AB#234352](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/234352) [AB#233625](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/233625)
Ensure links updated according to the latest recommended resources attached to the story.
> Updated commercial resources and E2E tests

- web/src/Web.App/Views/SchoolPlanning/View.cshtml
ICFP journey wording incorrect.
[AB#235469](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/235469)
Updating "equipment" to "equivalent", as required.
N/A
> fix: correct ICFP journey wording

- platform/Directory.Packages.props
- platform/src/abstractions/Platform.Functions/packages.lock.json
- platform/src/apis/Platform.Api.Benchmark/packages.lock.json
- platform/src/apis/Platform.Api.Establishment/packages.lock.json
- platform/src/apis/Platform.Api.Insight/packages.lock.json
- platform/src/apis/Platform.Orchestrator/packages.lock.json
- platform/src/apis/Platform.UserDataCleanUp/packages.lock.json
- platform/src/search/Platform.Search.Processor/packages.lock.json
- platform/terraform/README.md
- platform/terraform/modules/functions/main.tf
- platform/terraform/modules/functions/provider.tf
- platform/terraform/provider.tf
- platform/tests/Platform.ApiTests/packages.lock.json
- platform/tests/Platform.Tests/packages.lock.json
[AB#235616](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/235616) [AB#235614](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/235614)
Bumped Terraform providers in Platform. `azure/azapi` v2.0 is a major update with some [breaking changes](https://registry.terraform.io/providers/Azure/azapi/latest/docs/guides/2.0-upgrade-guide#breaking-changes). Bumped `Microsoft.Extensions.Configuration.Json` and `System.Text.Json`.
This requires latest Terraform to be installed to prevent `This configuration does not support Terraform version XXX` error.
> Bumped Platform dependencies

- prototype/src/app/views/latest/index.html
- prototype/src/package-lock.json
- prototype/src/package.json
- prototype/terraform/provider.tf
[AB#235620](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/235620) [AB#235614](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/235614)
> Bumped `azurerm` Terraform provider and GDS packages in Prototype

- web/Directory.Packages.props
- web/src/Web.App/package-lock.json
- web/src/Web.App/package.json
- web/src/Web.App/packages.lock.json
- web/terraform/provider.tf
- web/tests/Web.Integration.Tests/packages.lock.json
- web/tests/Web.Tests/packages.lock.json
[AB#235619](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/235619) [AB#235614](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/235614)
Bumped `azurerm` Terraform provider, GDS package and `FeatureManagement` in Web. ~~This does not include the latest front-end-components from #1545 unless that PR is merged before this in which case that version may also be bumped.~~
Latest GDS version includes an [updated Royal Arms](https://github.com/alphagov/govuk-frontend/releases/tag/v5.7.0), whose presence should be validated.
> Bumped Web dependencies

- web/src/Web.App/AssetSrc/scss/_variables.scss
- web/src/Web.App/AssetSrc/scss/main.scss
- web/src/Web.App/ViewComponents/RagPosition.cs
- web/src/Web.App/ViewModels/Components/RagPositionViewModel.cs
- web/src/Web.App/Views/SchoolBenchmarkingReportCards/Index.cshtml
- web/src/Web.App/Views/Shared/Components/RagPosition/Default.cshtml
- web/terraform/app-service.tf
[AB#235837](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/235837) [AB#222988](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/222988)
Addition of new view component. This will be consumed correctly as part of future work.
After rebuilding client assets, browse to `https://localhost:7095/school/123456/benchmarking-report-cards` to view the component in action.
> Created `RagPosition` view component and rendered with some dummy data to validate output SVG

- web/src/Web.App/Controllers/SchoolBenchmarkingReportCardsController.cs
- web/src/Web.App/ViewModels/BenchmarkingReportCardsViewModel.cs
- web/src/Web.App/ViewModels/ISchoolKeyInformationViewModel.cs
- web/src/Web.App/ViewModels/SchoolViewModel.cs
- web/src/Web.App/Views/School/Index.cshtml
- web/src/Web.App/Views/SchoolBenchmarkingReportCards/Index.cshtml
- web/src/Web.App/Views/Shared/_SchoolKeyInformation.cshtml
[AB#235828](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/235828) [AB#222988](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/222988)
Refactored school 'key information' grid for re-use across school homepage and BRC. Added CFR/AAR dates as appropriate to introductory text and subtitle. Returned `404` for non-lead federated schools.
> Added Key Information and introductory sections to BRC

- web/terraform/variables.tf
[AB#236099](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/236099)([AB#234602](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/234602)) 
terraform variable update to enable dsi claim check
> terraform update to set variable in automated test

- web/src/Web.App/AssetSrc/scss/main.scss
- web/src/Web.App/ViewModels/SchoolBenchmarkingReportCardsViewModel.cs
- web/src/Web.App/Views/SchoolBenchmarkingReportCards/Index.cshtml
- web/src/Web.App/Views/SchoolBenchmarkingReportCards/_NextSteps.cshtml
- web/src/Web.App/Views/SchoolBenchmarkingReportCards/_PupilWorkforceMetrics.cshtml
- web/src/Web.App/Views/SchoolBenchmarkingReportCards/_WhoYouAreComparedWith.cshtml
- web/src/Web.App/Views/SchoolComparators/Index.cshtml
- web/src/Web.App/Views/SchoolComparators/Workforce.cshtml
- web/src/Web.App/Views/Shared/_BuildingCostCategoriesList.cshtml
- web/src/Web.App/Views/Shared/_RunningCostCategoriesList.cshtml
- web/tests/Web.Tests/ViewModels/GivenASchoolBenchmarkingReportCardsViewModel.cs
[AB#236145](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/236145) [AB#222988](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/222988)
Also removed 'other costs' category and 'green' RAGs from the 'other priorities' BRC
> Added commentary sections to BRCs

- web/src/Web.App/AssetSrc/scss/_headlines.scss
- web/src/Web.App/AssetSrc/scss/main.scss
- web/src/Web.App/Views/SchoolBenchmarkingReportCards/Index.cshtml
- web/src/Web.App/Views/SchoolBenchmarkingReportCards/_Costs.cshtml
- web/src/Web.App/Views/SchoolBenchmarkingReportCards/_Introduction.cshtml
- web/src/Web.App/Views/SchoolBenchmarkingReportCards/_KeyInformation.cshtml
- web/src/Web.App/Views/SchoolBenchmarkingReportCards/_NextSteps.cshtml
- web/src/Web.App/Views/SchoolBenchmarkingReportCards/_PriorityAreasAllSchools.cshtml
- web/src/Web.App/Views/SchoolBenchmarkingReportCards/_PriorityAreasOther.cshtml
- web/src/Web.App/Views/SchoolBenchmarkingReportCards/_PupilWorkforceMetrics.cshtml
- web/src/Web.App/Views/SchoolPlanning/View.cshtml
- web/src/Web.App/Views/Shared/Components/Banner/Default.cshtml
- web/src/Web.App/Views/Shared/Components/RagPosition/Default.cshtml
- web/src/Web.App/Views/Shared/_Layout.cshtml
- web/src/Web.App/Views/Shared/_PrintPageLink.cshtml
[AB#236015](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/236015) [AB#222988](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/222988)
'Print' buttons at top and bottom of page. Many elements hidden or reformatted when in `@media print`.
> Added 'Print this page' buttons to BRC and ensured printable version is formatted adequately

- web/src/Web.App/Views/Shared/Components/SchoolFinanceTools/Default.cshtml
- web/src/Web.App/Views/Shared/Components/TrustFinanceTools/Default.cshtml
- web/tests/Web.A11yTests/PageBase.cs
- web/tests/Web.A11yTests/Pages/Trust/WhenViewingForecast.cs
[AB#235250](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/235250) , [AB#236369](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/236369)
Ensures links have discernible text
N/A
> ﻿feat: ensures links have discernible text

- front-end-components/src/views/compare-your-census/partials/non-classroom-support.tsx
[AB#236607](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/236607) [AB#235684](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/235684)
E2E tests currently failing against `d02` due to a missing chart for `NonClassroomSupportStaff`, which should be the valid category `NonClassroomSupportStaffFte` instead.
Build `front-end-components` locally and copy to `Web`. Browse through a School's Census data and all should now be present. Post-merge, an additional push to `Web` will be needed to fix in `d01`/`d02` and then the E2E tests may be re-run.
> Resolved invalid Census category that was identified now validation is present in Census API

- pipelines/web/security-scan.yaml
[AB#237472](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/237472) [AB#236431](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/236431)
Updated referenced image in `.yml`. Moved target URL to be resolved from variable library.
Execute the `docker run` command in the `.yml` file locally to validate the scan works as expected:
> Updated Web security scan to use current supported Docker image for full default scan

- pipelines/platform/security-scan.yaml
[AB#237473](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/237473) [AB#236431](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/236431)
Updated referenced image in `.yml`.
Execute the `docker run` command in the `.yml` file locally to validate the scan works as expected:
> Updated Platform security scan to use current supported Docker image for full default API scan

- web/src/Web.App/Controllers/TrustCensusController.cs
- web/src/Web.App/Controllers/TrustComparisonController.cs
- web/src/Web.App/ViewModels/LocalAuthorityCensusViewModel.cs
- web/src/Web.App/ViewModels/LocalAuthorityComparisonViewModel.cs
- web/src/Web.App/ViewModels/TrustCensusViewModel.cs
- web/src/Web.App/ViewModels/TrustComparisonViewModel.cs
- web/src/Web.App/Views/LocalAuthorityCensus/Index.cshtml
- web/src/Web.App/Views/LocalAuthorityComparison/Index.cshtml
- web/src/Web.App/Views/TrustCensus/Index.cshtml
- web/src/Web.App/Views/TrustComparison/Index.cshtml
[AB#239062](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/239062) [AB#239063](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/239063)
Adds guards to prevent render of front-end component when there is no schools within an LA or Trust.
Front-end is currently erroring (silently, but can be seen in browser console). 
Back-end is logging errors due to URN collection being empty.
N/A
> feat: adds guards for when there is no schools within a trust or LA

- support-analytics/terraform/README.md
- support-analytics/terraform/dashboards.tf
- support-analytics/terraform/dashboards/mi.tpl
- support-analytics/terraform/data.tf
- support-analytics/terraform/queries.tf
- support-analytics/terraform/queries/functions/get-anon-requests.kql
- support-analytics/terraform/queries/functions/get-requests.kql
- support-analytics/terraform/queries/popular-local-authority-requests.kql
- support-analytics/terraform/queries/request-counts.kql
- support-analytics/terraform/queries/user-counts.kql
[AB#238971](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/238971) [AB#221294](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/221294)
Split User and Request counts into separate queries/dashboard parts. Added commentary to try and explain metrics with regards to user having accepted analytics cookies or not.
Changes pushed to `d18` and `d19` feature branches to validate against previous work on impact of cookie acceptance by users.
> MI Dashboard improvements to User/Request metrics

- web/Directory.Packages.props
- web/src/Web.App/Views/DataSource/_DataSources.cshtml
- web/src/Web.App/Views/Shared/_Layout.cshtml
- web/tests/Web.E2ETests/Assist/DynamicInstanceComparisonException.cs
- web/tests/Web.E2ETests/Assist/DynamicInstanceFromTableException.cs
- web/tests/Web.E2ETests/Assist/DynamicSetComparisonException.cs
- web/tests/Web.E2ETests/Assist/DynamicTableHelpers.cs
- web/tests/Web.E2ETests/Features/DataSources.feature
- web/tests/Web.E2ETests/Pages/DataSourcesPage.cs
- web/tests/Web.E2ETests/Pages/HomePage.cs
- web/tests/Web.E2ETests/Selectors.cs
- web/tests/Web.E2ETests/Steps/DataSourcesSteps.cs
- web/tests/Web.E2ETests/Web.E2ETests.csproj
- web/tests/Web.E2ETests/packages.lock.json
[AB#239550](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/239550) [AB#237852](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/237852) [AB#236150](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/236150)
Includes E2E tests, plus addition of dynamic set comparison helpers (as also used in Platform tests).
> Added Data Sources link to footer

- web/Web.sln.DotSettings
- web/src/Web.App/gulpfile.js
- web/src/Web.App/package-lock.json
- web/src/Web.App/package.json
[AB#240026](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/240026) [AB#239313](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/239313)
Gulp job updates
Run `npm i` and then `npm run build` from `web/src/Web.App` to see the missing files generated in `wwwroot`.
> Copied and renamed `govuk-icon-180.png` from GDS assets into `wwwroot` to reduce `404`s

- web/Web.sln.DotSettings
- web/src/Web.App/Constants.cs
- web/src/Web.App/Controllers/TrustController.cs
- web/src/Web.App/Extensions/HtmlExtensions.cs
- web/src/Web.App/ViewModels/TrustViewModel.cs
- web/src/Web.App/Views/Trust/Details.cshtml
- web/src/Web.App/Views/Trust/Index.cshtml
- web/tests/Web.Integration.Tests/Pages/Trusts/WhenViewingDetails.cs
- web/tests/Web.Integration.Tests/Pages/Trusts/WhenViewingHome.cs
- web/tests/Web.Tests/WhenConstants.cs
[AB#240405](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/240405) [AB#235688](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/235688)
Previously this would return a 404 to the user. School details page also updated to remove empty 'Schools' section and broken GIAS link in this Trust scenario.
> Show message and minimal Trust content when missing financials for current year

- core-infrastructure/terraform/README.md
- core-infrastructure/terraform/provider.tf
[AB#240703](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/240703) [AB#240701](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/240701)
December 2024 dependabot updates (#1622 - #1623)
> `core-infrastructure` dependency updates

- platform/Platform.sln
- platform/terraform/modules/functions/README.md
- platform/terraform/modules/functions/provider.tf
[AB#240704](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/240704) [AB#240701](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/240701)
December 2024 dependabot updates (#1624 & #1626)
> `platform` dependency updates

- platform/terraform/README.md
- platform/terraform/provider.tf
- web/src/Web.App/package-lock.json
- web/terraform/README.md
- web/terraform/provider.tf
[AB#240706](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/240706) [AB#240701](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/240701) 
December 2024 dependabot updates (#1624, #1626, #1637)
> `web` dependency updates

- front-end-components/src/components/auto-complete/component.tsx
[AB#241011](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/241011) [AB#240744](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/240744)
Build and copy `front-end` to `web` to validate locally.
> Ensured `minLength` within auto-complete is honoured post-trim

- documentation/developers/2_Branching-Policy.md
- pipelines/common/validate-branch.yaml
- web/terraform/variables.tf
[AB#241359](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/241359) [AB#222988](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/222988)
This feature is ready to be released to pre-production and production.
This PR includes the addition of `chore` as a permitted branch name.
> Enable `FinancialBenchmarkingInsightsSummary` feature in pre-/production

- documentation/data/4_Releases.md
[AB#241380](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/241380) [AB#232974](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/232974)
> Updated `default` message format in release documentation

- documentation/quality-assurance/release-test-plans/00013_release-test-plan.md
Release test plan for `2024.12.0`
> docs: release test plan for 2024.12.0

- documentation/quality-assurance/release-test-plans/00014_release-test-plan.md
Release test plan for `2024.12.1`
> Release test plan for 2024.12.1

- platform/src/apis/Platform.Api.Insight/Census/CensusService.cs
- platform/tests/Platform.Tests/Insight/Census/WhenCensusServiceQueriesAsync.cs
- platform/tests/Platform.Tests/Insight/Census/WhenFunctionReceivesGetComparatorSetAverageCensusRequest.cs
- platform/tests/Platform.Tests/Insight/Census/WhenFunctionReceivesGetNationalAverageCensusRequest.cs
[AB#241828](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/241828)
Updates response used in insight census api historic trends
Ensure the props match what is expected
> update response from api for insight census historic trends

- pipelines/web/steps/run-e2e-tests.yaml
- web/terraform/variables.tf
- web/tests/Web.E2ETests/Features/School/HistoricData.feature
[AB#241830](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/241830) [AB#237633](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/237633)
Enabled `HistoricalTrends` feature in test and automated test environments and removed E2E feature exclusion from pipeline.
> Fixed and enabled Historical Trends E2E tests

- documentation/quality-assurance/performance-test-plans/0001_API-average-load-test-plan.md
- documentation/quality-assurance/performance-test-plans/0002_API-peak-load-test-plan.md
- documentation/quality-assurance/performance-test-plans/0006_API-school-history-load-test-plan.md
- performance-tests/src/platform/average/insight/school/expenditure/history/comparator-set/config.yaml
- performance-tests/src/platform/average/insight/school/expenditure/history/comparator-set/dimensions.csv
- performance-tests/src/platform/average/insight/school/expenditure/history/comparator-set/schools.csv
- performance-tests/src/platform/average/insight/school/expenditure/history/comparator-set/url-test.json
- performance-tests/src/platform/average/insight/school/expenditure/history/get/config.yaml
- performance-tests/src/platform/average/insight/school/expenditure/history/get/dimensions.csv
- performance-tests/src/platform/average/insight/school/expenditure/history/get/schools.csv
- performance-tests/src/platform/average/insight/school/expenditure/history/get/url-test.json
- performance-tests/src/platform/average/insight/school/expenditure/history/national-average/config.yaml
- performance-tests/src/platform/average/insight/school/expenditure/history/national-average/dimensions.csv
- performance-tests/src/platform/average/insight/school/expenditure/history/national-average/financeTypes.csv
- performance-tests/src/platform/average/insight/school/expenditure/history/national-average/overallPhases.csv
- performance-tests/src/platform/average/insight/school/expenditure/history/national-average/url-test.json
- performance-tests/src/platform/peak/insight/school/expenditure/history/comparator-set/config.yaml
- performance-tests/src/platform/peak/insight/school/expenditure/history/comparator-set/dimensions.csv
- performance-tests/src/platform/peak/insight/school/expenditure/history/comparator-set/schools.csv
- performance-tests/src/platform/peak/insight/school/expenditure/history/comparator-set/url-test.json
- performance-tests/src/platform/peak/insight/school/expenditure/history/get/config.yaml
- performance-tests/src/platform/peak/insight/school/expenditure/history/get/dimensions.csv
- performance-tests/src/platform/peak/insight/school/expenditure/history/get/schools.csv
- performance-tests/src/platform/peak/insight/school/expenditure/history/get/url-test.json
- performance-tests/src/platform/peak/insight/school/expenditure/history/national-average/config.yaml
- performance-tests/src/platform/peak/insight/school/expenditure/history/national-average/dimensions.csv
- performance-tests/src/platform/peak/insight/school/expenditure/history/national-average/financeTypes.csv
- performance-tests/src/platform/peak/insight/school/expenditure/history/national-average/overallPhases.csv
- performance-tests/src/platform/peak/insight/school/expenditure/history/national-average/url-test.json
[AB#242432](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/242432) [AB#237633](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/237633)
Load test definitions for the one existing, plus two new Expenditure endpoints for the Benchmarking Historical Trends feature in the Insights API.
> Average and peak load test definitions for School Expenditure History endpoints

- web/src/Web.App/package-lock.json
Following #1677 bump front end
> chore: bump front-end to 1.1.22

- documentation/quality-assurance/performance-test-plans/0006_API-school-history-load-test-plan.md
- performance-tests/src/platform/average/insight/school/census/history/national-average/config.yaml
- performance-tests/src/platform/average/insight/school/census/history/national-average/overallPhases.csv
- performance-tests/src/platform/average/insight/school/expenditure/history/national-average/config.yaml
- performance-tests/src/platform/average/insight/school/expenditure/history/national-average/overallPhases.csv
- performance-tests/src/platform/peak/insight/school/census/history/national-average/config.yaml
- performance-tests/src/platform/peak/insight/school/census/history/national-average/overallPhases.csv
- performance-tests/src/platform/peak/insight/school/expenditure/history/national-average/config.yaml
- performance-tests/src/platform/peak/insight/school/expenditure/history/national-average/overallPhases.csv
[AB#242433](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/242433) [AB#242432](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/242432) [AB#237633](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/237633) [AB#242616](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/242616)
Fixed invalid Overall Phases in input file. Added results of test runs post database tuning.
> Updated load test configuration for 'national average' history endpoints

- front-end-components/package-lock.json
- web/tests/Web.E2ETests/Features/School/CompareYourCosts.feature
[AB#243087](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/243087) [AB#243085](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/243085) #1708 #1707 #1706 #1705 #1704 #1702 #1701 #1699 #1698 #1697
January 2025 Dependabot updates
> Bumped `front-end` dependencies

- core-infrastructure/terraform/README.md
- core-infrastructure/terraform/databases.tf
- core-infrastructure/terraform/provider.tf
[AB#243089](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/243089) [AB#243085](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/243085) #1732 #1733
January 2025 Dependabot updates
> Bumped `core-infrastructure` dependencies

- prototype/src/package-lock.json
- prototype/terraform/README.md
- prototype/terraform/provider.tf
[AB#243122](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/243122) [AB#243085](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/243085) #1728 #1710
January 2025 Dependabot updates.
> Bumped `prototype` dependencies

- web/tests/Web.E2ETests/Features/Trust/TrustBenchmarking.feature
- web/tests/Web.E2ETests/Pages/Trust/Benchmarking/CreateComparatorsByCharacteristicPage.cs
- web/tests/Web.E2ETests/Pages/Trust/Benchmarking/CreateComparatorsByNamePage.cs
- web/tests/Web.E2ETests/Pages/Trust/Benchmarking/CreateComparatorsByPage.cs
- web/tests/Web.E2ETests/Pages/Trust/Benchmarking/ICreateComparatorsByPage.cs
- web/tests/Web.E2ETests/Pages/Trust/Benchmarking/TrustBenchmarkSpendingPage.cs
- web/tests/Web.E2ETests/Pages/Trust/HomePage.cs
- web/tests/Web.E2ETests/Selectors.cs
- web/tests/Web.E2ETests/Steps/Trust/TrustBenchmarkingSteps.cs
[AB#234604](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/234604) (AB#242719)
e2e tests for trust benchmarking
> e2e tests for trusts benchmarking

- web/tests/Web.E2ETests/Features/LocalAuthority/AccessFinancialPlanningForSchool.feature
- web/tests/Web.E2ETests/Features/School/AccessTrustForecastAsAcademy.feature
- web/tests/Web.E2ETests/Features/School/CompareYourCosts.feature
[AB#239732](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/239732) (AB#24052) 
n/a
n/a
> Tests updates after DSI changes

- web/tests/Web.E2ETests/Features/Trust/CurriculumFinancialPlanning.feature
- web/tests/Web.E2ETests/Features/Trust/TrustHome.feature
- web/tests/Web.E2ETests/Pages/Trust/CurriculumFinancialPlanningPage.cs
- web/tests/Web.E2ETests/Pages/Trust/HomePage.cs
- web/tests/Web.E2ETests/Selectors.cs
- web/tests/Web.E2ETests/Steps/Trust/CurriculumFinancialPlanningSteps.cs
- web/tests/Web.E2ETests/Steps/Trust/HomeSteps.cs
[AB#234771](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/234771) ([AB#242721](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/242721))
n/a
n/a
> trust CFP tests completed

- web/tests/Web.E2ETests/Features/School/HistoricData.feature
- web/tests/Web.E2ETests/Features/Trust/TrustHome.feature
- web/tests/Web.E2ETests/Pages/Trust/TrustForecastPage.cs
- web/tests/Web.E2ETests/Selectors.cs
- web/tests/Web.E2ETests/Steps/Trust/HomeSteps.cs
[AB#234772](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/234772) ([AB#242723](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/242723)) 
e2e tests assertions updated 
n/a
> Trust BFR e2e tests

- core-infrastructure/terraform/ai.tf
[AB#243802](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/243802) [AB#243796](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/243796)
Single Terraform update.
> Set Log Anlaytics Workspace retention period to 1.5 years

- web/src/Web.App/package-lock.json
[AB#235748](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/235748)
Following #1753 requires package bump
note: still awaiting design input/crit
> chore: bump front-end to 1.1.26

- front-end-components/src/views/compare-your-costs/view.tsx
[AB#235748](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/235748) - [AB#244507](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/244507)
Updates to content for warning message for compare your costs when negative and zero values are suppressed.
WIll require bump to front-end after merge.
> chore: update content for warning message in compare-your-costs

- web/src/Web.App/package-lock.json
[AB#235748](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/235748)
Following #1763 updates front-end package
> chore: bump front-end to 1.1.27

- pipelines/platform/build.yaml
- pipelines/platform/steps/flush-cache.yaml
[AB#244049](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/244049) [AB#237633](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/237633)
Additional step in Platform deployment pipeline as a dependency of API test run
> Flush cache before API test run in pipeline

- documentation/quality-assurance/7_DSI-Test-Organisations.md
DSI Test organisations overview.
> DSI pre production overview

- web/tests/Web.E2ETests/Features/School/CompareYourCosts.feature
- web/tests/Web.E2ETests/Features/School/SpendingCosts.feature
- web/tests/Web.E2ETests/Pages/School/CompareYourCostsPage.cs
- web/tests/Web.E2ETests/Pages/School/SpendingCostsPage.cs
- web/tests/Web.E2ETests/Selectors.cs
- web/tests/Web.E2ETests/Steps/School/CompareYourCostsSteps.cs
- web/tests/Web.E2ETests/Steps/School/SpendingCostsSteps.cs
[AB#235748](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/235748) ([AB#242137](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/242137))
added e2e tests
> E2E tests for supressing negative and zero

- platform/tests/Platform.ApiTests/Steps/BenchmarkUserDataSteps.cs
[AB#245990](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/245990) [AB#242105](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/242105)
API test fix (broken build)
> Updated custom data related API test

- web/tests/Web.E2ETests/Features/School/CreateCustomData.feature
[AB#245990](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/245990) [AB#242105](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/242105) #1781
E2E test fix (broken build)
> Updated custom data related E2E test

- data-pipeline/Makefile
- data-pipeline/src/pipeline/bfr.py
- data-pipeline/src/pipeline/input_schemas/__init__.py
- data-pipeline/src/pipeline/mappings.py
- data-pipeline/src/pipeline/part_year/academies.py
- data-pipeline/src/pipeline/pre_processing/__init__.py
- data-pipeline/src/pipeline/pre_processing/academies/__init__.py
- data-pipeline/src/pipeline/pre_processing/academies/academies.py
- data-pipeline/src/pipeline/rag.py
- data-pipeline/tests/unit/comparator_sets/test_part_year.py
- data-pipeline/tests/unit/pre_processing/test_bfr.py
- data-pipeline/tests/unit/pre_processing/test_maintained_schools.py
- data-pipeline/tests/unit/pre_processing/test_mappings.py
- pipelines/data-pipeline/build.yaml
- pipelines/data-pipeline/steps/run-lint.yaml
[AB#231273](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/231273) - [AB#245691](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/245691)
Add new job to build pipeline for data-pipeline
black and isort to check formatting and display diff
fixes all lint errors
> chore: add lint job to build pipeline for data-pipeline

- web/src/Web.App/package-lock.json
[AB#246167](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/246167) [AB#245267](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/245267)
> Bumped `front-end` to `1.1.30`

- web/src/Web.App/package-lock.json
[AB#246167](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/246167) [AB#244563](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/244563) #1791
> Bumped `front-end` to `1.1.31`

- front-end-components/src/components/share-content-by-elements/component.tsx
- front-end-components/src/main.tsx
- web/src/Web.App/Views/Shared/_SaveChartsButton.cshtml
[AB#246738](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/246738) [AB#242099](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/242099)
App Insights custom event tracking for new 'save all' button. Also support for 'save by id' version which currently has no implementations.
> Added custom event tracking for 'Save all chart images' button press

- core-infrastructure/src/db/Core.Database/Scripts/107-CreateRecommendedIndexes.sql
[AB#245001](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/245001) [AB#239257](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/239257)
Added recommended index.
Query may be validated by running the core migrations against a local database and then validating the existence of the new index.
> Added recommended index for `[UserData]` table

- web/src/Web.App/package-lock.json
- web/tests/Web.E2ETests/Pages/School/CompareYourCostsPage.cs
- web/tests/Web.E2ETests/Pages/School/SpendingCostsPage.cs
- web/tests/Web.E2ETests/Selectors.cs
[AB#245900](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/245900) [AB#242099](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/242099)
Also bumped `front-end` version.
> E2E tests for 'Save all' button

- pipelines/documentation/build.yaml
[AB#246980](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/246980) [AB#245331](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/245331)
Pipeline update.
Validated in [this](https://dfe-ssp.visualstudio.com/s198-DfE-Benchmarking-service/_build/results?buildId=551405&view=results) (intentionally failing) build run.
> Ensured `documentation` pipeline triggered on PR

- documentation/data/2_Models.md
- documentation/tools/input_schemas.py
Recent changes in the 2024 data structure from some files need to be reflected in the documentation.
[AB#241700](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/241700)  
- update docs. to reflect models as of 2024
- add column mappings (i.e. instances where columns are renamed on ingest)
- add column derivations (i.e. instance where columns are calculated on ingest)
Added the `tools/input_schemas.py` to quickly render each of the tables directly from the `pipeline.input_schemas`.
> docs: update data-model documentation

- documentation/architecture/decisions/0006-chart-rendering.md
Architectural Decision Record (ADR) for Rendering of Charts
> docs : Architectural Decision Record (ADR) for Rendering of Charts

- documentation/architecture/decisions/0007-deployment-options-rendering-charts-service.md
Architectural Decision Record (ADR) for deployment options for SVG service for rendering charts
> ADR for deployment options for SVG service

- web/terraform/variables.tf
[AB#247596](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/247596) [AB#237633](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/237633)
Terraform variable map update.
> Enabled Benchmark Historical Trends feature in pre-/prod environments

- platform/src/apis/Platform.Api.Insight/Features/Expenditure/GetExpenditureTrustsFunction.cs
- web/src/Web.App/Domain/Insight/Expenditure.cs
- web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
- web/tests/Web.Integration.Tests/Paths.cs
- web/tests/Web.Integration.Tests/Proxy/WhenRequestingExpenditureUserDefined.cs
[AB#248789](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/248789) [AB#248795](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/248795)
Added integration test to validate properties. 
E2E test coverage will be managed as part of future work due to complexities around managing user defined data behind login via automated tests.
See work item for previously failing requests that may be replayed locally after this fix for additional assurance.
> Reinstated missing properties on `TrustExpenditure` class in order to pass values to front end

- web/src/Web.App/package-lock.json
[AB#247366](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/247366) [AB#242099](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/242099) #1825
Bumped dependency to get E2E tests in #1825 to pass.
> Bumped `front-end` to `1.1.44`

- platform/Platform.sln
- platform/src/apis/Platform.Api.Benchmark/host.json
- platform/src/apis/Platform.Api.Establishment/host.json
- platform/src/apis/Platform.Api.Insight/host.json
- platform/src/apis/Platform.UserDataCleanUp/host.json
- platform/terraform/README.md
- platform/terraform/data.tf
- platform/terraform/functions.tf
- platform/terraform/modules/functions/README.md
- platform/terraform/modules/functions/main.tf
- platform/terraform/modules/functions/variables.tf
- platform/terraform/storage.tf
[AB#248449](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/248449) [AB#248450](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/248450) [AB#248451](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/248451) [AB#248427](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/248427)
Also enabled all function app logging at `Information` level.
Deployed to `d19` feature environment for validation.
> Added Diagnostic Logging for Function Apps and backing storage account

- web/src/Web.App/package-lock.json
[AB#248694](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/248694) [AB#245786](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/245786) #1894
Bump dependency after #1894 merged.
> Bumped `front-end` to `1.1.45`

- web/src/Web.App/package-lock.json
[AB#248192](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/248192) [AB#245257](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/245257) #1885
Bumped `front-end` to `1.1.47` after #1885 merged.
> Bumped `front-end` to `1.1.47`

- .github/dependabot.yml
- front-end-components/package-lock.json
[AB#248373](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/248373) [AB#248372](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/248372)
February 2025 dependency updates.
> Front-end dependency updates

- prototype/src/package-lock.json
- prototype/terraform/README.md
- prototype/terraform/provider.tf
[AB#248381](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/248381) [AB#248372](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/248372)
February 2025 dependency updates.
> Prototype dependency updates

- documentation/architecture/decisions/0008-resolving-Intermittent-errors-function-app.md
Proposed ADR for resolving Intermittent 502, 503, and 429 errors on Azure Function App.
> Proposed ADR

- web/src/Web.App/package-lock.json
[AB#249738](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249738) [AB#249206](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249206) [AB#249736](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249736) [AB#249204](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249204) #1940 #1939
Bumped `front-end` dependency, post merge of #1940 and #1939.
> Bumped `front-end` to `1.1.52`

- web/src/Web.App/Views/SchoolSpending/Index.cshtml
fix for regression following changes to PageActions component
N/A
> fix: pass through `saveTitleAttr` for `PageActions` in SchoolSpending view

- core-infrastructure/src/db/Core.Database/Views/012-ExpenditureTrust.sql
[AB#249227](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249227) - [AB#249860](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249860)
Adds missing columns to the views
n/a
> fix: add `WaterSewerageCosts`, `WaterSewerageCostsCS` and `WaterSewerageCostsSchool` to additional dimension views

- platform/tests/Platform.ApiTests/Features/InsightExpenditure.feature
[AB#249227](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249227) - [AB#250104](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/250104)
Adds additional api tests to assert the response to cover any future regression in this area.
n/a
> chore: add api tests for trust expenditure Utilities

- front-end-components/src/components/modals/modal-save-images/modal-save-images-modal/component.tsx
[AB#249976](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249976) [AB#242099](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/242099)
Copy changes following design review.
> 'Save images' dialog copy

- web/src/Web.App/package-lock.json
[AB#249976](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249976) [AB#242099](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/242099)
Follow-up to #1956.
> Bumped `front-end` to `1.1.57`

- support-analytics/terraform/smart-alerts.tf
[AB#249751](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249751) [AB#249750](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249750)
Minor Terraform update.
Deployed to `d12` to verify no changes:
> Replaced frequency of `PT24H` with the equivalent `P1D`

- documentation/quality-assurance/release-test-plans/00016_release-test-plan.md
The finalised Live Release Plan for 2025.02.5, updated to reflect the completion of the release process.
> draft release plan document

- documentation/developers/10_Monthly-Reporting.md
[AB#250239](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/250239) [AB#250240](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/250240) [AB#250080](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/250080)
Documentation update for monthly platform analytics report.
> Monthly reporting instructions

- web/Web.sln.DotSettings
- web/src/Web.App/Controllers/Api/NationalRankProxyController.cs
- web/src/Web.App/Domain/Establishment/LocalAuthorityRanking.cs
- web/src/Web.App/Infrastructure/Apis/Establishment/Api.cs
- web/src/Web.App/Infrastructure/Apis/Establishment/EstablishmentApi.cs
- web/tests/Web.Tests/Infrastructure/GivenAnEstablishmentApi.cs
[AB#250896](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/250896) [AB#249546](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249546) #2018
Web proxy and associated test updates.
Dependency on #2018.
> Web proxy to resolve LA national rankings from API

- platform/src/apis/Platform.Api.NonFinancial/Configuration/Services.cs
- platform/src/apis/Platform.Api.NonFinancial/Constants.cs
- platform/src/apis/Platform.Api.NonFinancial/Features/EducationHealthCarePlans/EducationHealthCarePlansFeature.cs
- platform/src/apis/Platform.Api.NonFinancial/Features/EducationHealthCarePlans/GetEducationHealthCarePlansFunction.cs
- platform/src/apis/Platform.Api.NonFinancial/Features/EducationHealthCarePlans/Models/EducationHealthCarePlans.cs
- platform/src/apis/Platform.Api.NonFinancial/Features/EducationHealthCarePlans/Parameters/EducationHealthCarePlansParameters.cs
- platform/src/apis/Platform.Api.NonFinancial/Features/EducationHealthCarePlans/Routes.cs
- platform/src/apis/Platform.Api.NonFinancial/Features/EducationHealthCarePlans/Services/EducationHealthCarePlansService.cs
- platform/src/apis/Platform.Api.NonFinancial/Features/EducationHealthCarePlans/Services/EducationHealthCarePlansStubService.cs
- platform/src/apis/Platform.Api.NonFinancial/Features/Validators/EducationHealthCarePlansParametersValidator.cs
- platform/tests/Platform.ApiTests/Features/NonFinancialEducationHealthCarePlans.feature
- platform/tests/Platform.ApiTests/Steps/EducationHealthCarePlansLocalAuthoritySteps.cs
- platform/tests/Platform.NonFinancial.Tests/EducationHealthCarePlans/EducationHealthCarePlansParametersTests.cs
- platform/tests/Platform.NonFinancial.Tests/Validators/WhenGivenEducationHealthCarePlansParameters.cs
[AB#249550](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249550) - [AB#251205](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/251205)
Adds new endpoint for `EducationHealthCarePlans` in `Platform.Api.NonFinancial`
currently using stubbed data for development
n/a
> feat: adds new `EducationHealthCarePlans` endpoint and test coverage

- web/src/Web.App/Controllers/Api/EducationHealthCarePlansProxyController.cs
- web/src/Web.App/Controllers/Api/HighNeedsProxyController.cs
- web/src/Web.App/Controllers/Api/Mappers/EducationHealthCarePlansHistoryResponseMapper.cs
- web/src/Web.App/Controllers/Api/Mappers/LocalAuthorityHighNeedsHistoryResponseMapper.cs
- web/src/Web.App/Controllers/Api/Responses/EducationHealthCarePlansHistoryResponse.cs
- web/src/Web.App/Domain/LocalAuthorities/History.cs
- web/src/Web.App/Domain/NonFinancial/EducationHealthCarePlans.cs
- web/src/Web.App/Extensions/ServiceCollectionExtensions.cs
- web/src/Web.App/Infrastructure/Apis/NonFinancial/Api.cs
- web/src/Web.App/Infrastructure/Apis/NonFinancial/EducationHealthCarePlansApi.cs
- web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
- web/tests/Web.Integration.Tests/Paths.cs
- web/tests/Web.Integration.Tests/Proxy/WhenRequestingEducationHealthCarePlansHistory.cs
- web/tests/Web.Integration.Tests/Proxy/WhenRequestingHighNeedsHistory.cs
- web/tests/Web.Tests/Controllers/Api/Mappers/WhenEducationHealthCarePlansHistoryResponseMapperMapsWithCode.cs
- web/tests/Web.Tests/Controllers/Api/Mappers/WhenLocalAuthorityHighNeedsHistoryResponseMapperMapsWithCode.cs
[AB#249550](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249550) - [AB#251490](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/251490)
adds proxy endpoint to web for the new stubbed `EducationHealthCarePlans` api
add mapping for the response to conform with the structure expected to be required by `front-end-components`
adds test coverage for mapping and integration tests for the proxy endpoint
n/a
> feat: adds web proxy endpoint for `EducationHealthCarePlans` api

- platform/Directory.Packages.props
- platform/tests/Platform.ApiTests/packages.lock.json
- web/Directory.Packages.props
- web/src/Web.App/Views/LocalAuthorityHighNeedsHistoricData/Index.cshtml
- web/src/Web.App/package-lock.json
- web/tests/Web.A11yTests/packages.lock.json
- web/tests/Web.E2ETests/Features/LocalAuthority/HighNeedsHistoricData.feature
- web/tests/Web.E2ETests/Pages/LocalAuthority/HighNeedsHistoricDataPage.cs
- web/tests/Web.E2ETests/Selectors.cs
- web/tests/Web.E2ETests/Steps/LocalAuthority/HighNeedsHistoricDataSteps.cs
- web/tests/Web.E2ETests/packages.lock.json
[AB#251209](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/251209) [AB#249550](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249550)
- Bumped `front-end` dependency
- Added component via element ID convention
- E2E coverage
- Downgraded `FluentAssertions` back to `7.x`
Blank page now replaced with content from `front-end` component.
> Added High needs historical component to Web

- web/src/Web.App/ViewComponents/LocalAuthorityHighNeedsHelpViewComponent.cs
- web/src/Web.App/Views/LocalAuthorityHighNeeds/Index.cshtml
- web/src/Web.App/Views/Shared/Components/LocalAuthorityHighNeedsHelp/Default.cshtml
- web/tests/Web.Integration.Tests/packages.lock.json
- web/tests/Web.Tests/packages.lock.json
[AB#249541](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249541) ([AB#251928](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/251928))
Adds boilerplate view component for high needs help and support section. Input from design required to confirm layout and content.
Boilerplate is to provoke discussion
N/A
> feat: adds boilerplate view component

- web/tests/Web.E2ETests/Pages/LocalAuthority/HighNeedsBenchmarkingPage.cs
[AB#249539](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249539) ([AB#251219](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/251219)) 
updated assertions for HighNeeds dashboard page
n/a
> updated assertions on benchmarking dashboard page

- core-infrastructure/src/db/Core.Database/Scripts/108-InsertS25Param.sql
- core-infrastructure/src/db/Core.Database/Views/003-Years.sql
- platform/src/apis/Platform.Api.Insight/Features/Years/GetCurrentReturnYearsFunction.cs
- platform/tests/Platform.ApiTests/Steps/InsightCommonSteps.cs
Background task to support future work -  adds year props to support potential UI content, as well as DB queries
N/A
> feat: adds additional prop for s251 year to support High Needs

- web/src/Web.App/Views/Shared/Components/LocalAuthorityFinanceTools/Default.cshtml
[AB#252566](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/252566) [AB#249535](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249535)
Copy update
> Updated LA financial tools copy for High needs tool

- web/src/Web.App/AssetSrc/scss/_link-list.scss
- web/src/Web.App/Domain/FinanceYears.cs
- web/src/Web.App/ViewComponents/DataSourceViewComponent.cs
- web/src/Web.App/Views/LocalAuthorityHighNeeds/Index.cshtml
- web/src/Web.App/Views/Shared/Components/LocalAuthorityHighNeedsHelp/Default.cshtml
- web/src/Web.App/Views/Shared/Components/LocalAuthorityHighNeedsHistory/Default.cshtml
- web/src/Web.App/Views/Shared/Components/LocalAuthorityHighNeedsNationalRankings/Default.cshtml
- web/tests/Web.E2ETests/Pages/LocalAuthority/HighNeedsBenchmarkingPage.cs
- web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
- web/tests/Web.Integration.Tests/Pages/LocalAuthorities/WhenViewingHighNeeds.cs
- web/tests/Web.Tests/Services/WhenFinanceServiceIsCalled.cs
- web/tests/Web.Tests/ViewModels/GivenASchoolFinancialBenchmarkingInsightsSummaryViewModel.cs
[AB#252565](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/252565) [AB#249538](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249538)
- Copy updates, including new financial years for High needs
- Test updates
> Updated copy on High needs benchmarking page

- web/src/Web.App/package-lock.json
[AB#249550](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249550) #2089
bump `front-end` to `1.1.67`
n/a
> chore: bump `front-end` to `1.1.67`

- platform/src/apis/Platform.Api.LocalAuthorityFinances/Features/HighNeeds/GetHighNeedsFunction.cs
- platform/src/apis/Platform.Api.LocalAuthorityFinances/Features/HighNeeds/HighNeedsFeature.cs
- platform/src/apis/Platform.Api.LocalAuthorityFinances/Features/HighNeeds/Models/LocalAuthority.cs
- platform/src/apis/Platform.Api.LocalAuthorityFinances/Features/HighNeeds/Parameters/HighNeedsParameters.cs
- platform/src/apis/Platform.Api.LocalAuthorityFinances/Features/HighNeeds/Routes.cs
- platform/src/apis/Platform.Api.LocalAuthorityFinances/Features/HighNeeds/Services/HighNeedsService.cs
- platform/src/apis/Platform.Api.LocalAuthorityFinances/Features/HighNeeds/Services/HighNeedsStubService.cs
- platform/src/apis/Platform.Api.LocalAuthorityFinances/Features/HighNeeds/Validators/HighNeedsParametersValidator.cs
- platform/src/apis/Platform.Api.NonFinancial/Features/EducationHealthCarePlans/GetEducationHealthCarePlansLocalAuthoritiesFunction.cs
- platform/src/apis/Platform.Api.NonFinancial/Features/EducationHealthCarePlans/Routes.cs
- platform/src/apis/Platform.Api.NonFinancial/Features/EducationHealthCarePlans/Services/EducationHealthCarePlansService.cs
- platform/src/apis/Platform.Api.NonFinancial/Features/EducationHealthCarePlans/Services/EducationHealthCarePlansStubService.cs
- platform/tests/Platform.ApiTests/Features/LocalAuthoritiesHighNeeds.feature
- platform/tests/Platform.ApiTests/Features/NonFinancialEducationHealthCarePlansLocalAuthoritiesHistory.feature
- platform/tests/Platform.ApiTests/Steps/LocalAuthoritiesHighNeedsSteps.cs
- platform/tests/Platform.ApiTests/Steps/NonFinancialEducationHealthCarePlansLocalAuthoritiesHistory.cs
- platform/tests/Platform.LocalAuthorityFinances.Tests/HighNeeds/GetHighNeedsFunctionTests.cs
- platform/tests/Platform.LocalAuthorityFinances.Tests/HighNeeds/Parameters/HighNeedsParametersTests.cs
- platform/tests/Platform.LocalAuthorityFinances.Tests/HighNeeds/Validators/WhenHighNeedsParametersValidatorValidates.cs
- platform/tests/Platform.NonFinancial.Tests/EducationHealthCarePlans/GetEducationHealthCarePlansLocalAuthoritiesFunctionTests.cs
[AB#252628](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/252628) [AB#249557](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249557)
- Added new `/high-needs` function to `LocalAuthorityFinances.HighNeeds` feature
- Added new `/education-health-care-plans/local-authorities` function to `NonFinancial.EducationHealthCarePlans` feature
- Updated unit and API tests
Stubbed endpoints may be validated locally in Swagger UI, e.g.:
- `http://localhost:7074/api/swagger/ui#/High%20Needs/GetHighNeedsFunction`
- `http://localhost:7075/api/swagger/ui#/High%20Needs/GetEducationHealthCarePlansLocalAuthoritiesFunction`
> Added new API endpoints for benchmarking S251 and SEND2 data

- web/src/Web.App/Views/Shared/Components/LocalAuthorityHighNeedsHelp/Default.cshtml
[AB#249541](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249541) [AB#252689](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/252689)
Updates data sources links and adds additional framework link
N/A
> feat: updates links in help & support section

- web/src/Web.App/Constants/PageTitles.cs
- web/src/Web.App/Controllers/LocalAuthorityHighNeedsBenchmarkingController.cs
- web/src/Web.App/Views/LocalAuthorityHighNeeds/Index.cshtml
- web/src/Web.App/Views/LocalAuthorityHighNeedsBenchmarking/Comparators.cshtml
- web/src/Web.App/Views/LocalAuthorityHighNeedsBenchmarking/Index.cshtml
- web/src/Web.App/package-lock.json
- web/tests/Web.A11yTests/Pages/LocalAuthority/WhenViewingHighNeedsDashboard.cs
- web/tests/Web.A11yTests/Pages/LocalAuthority/WhenViewingHighNeedsStartBenchmarking.cs
- web/tests/Web.E2ETests/Features/LocalAuthority/HighNeedsDashboard.feature
- web/tests/Web.E2ETests/Features/LocalAuthority/LocalAuthorityHome.feature
- web/tests/Web.E2ETests/Pages/LocalAuthority/HighNeedsBenchmarkingPage.cs
- web/tests/Web.E2ETests/Steps/LocalAuthority/HighNeedsBenchmarkingSteps.cs
- web/tests/Web.E2ETests/Steps/LocalAuthority/HighNeedsStartBenchmarkingSteps.cs
- web/tests/Web.E2ETests/Steps/LocalAuthority/HomeSteps.cs
- web/tests/Web.Integration.Tests/Pages/LocalAuthorities/WhenViewingHighNeeds.cs
- web/tests/Web.Integration.Tests/Pages/LocalAuthorities/WhenViewingHighNeedsBenchmarking.cs
- web/tests/Web.Integration.Tests/Pages/LocalAuthorities/WhenViewingHighNeedsDashboard.cs
- web/tests/Web.Integration.Tests/Pages/LocalAuthorities/WhenViewingHighNeedsStartBenchmarking.cs
- web/tests/Web.Integration.Tests/Pages/LocalAuthorities/WhenViewingHome.cs
- web/tests/Web.Integration.Tests/Pages/WhenAFeatureIsDisabled.cs
- web/tests/Web.Integration.Tests/Paths.cs
[AB#252631](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/252631) [AB#249557](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249557)
- Bumped `front-end`
- New Razor page that imports view from `front-end`
- Altered some paths to better reflect benchmarking journey
- Updated affected tests
Remaining test coverage to be resolved in subsequent PRs. Layout still subject to design crit.
> Created new High needs benchmarking page and imported view from front end

- documentation/quality-assurance/release-test-plans/00017_release-test-plan.md
Release test plan for `2025.3.0`
> Release test plan for 2025.3.0

- core-infrastructure/src/db/Core.Database/Scripts/110-CreateTableLaStatNeighbour.sql
[AB#253362](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/253362) ([AB#253286](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/253286))
Adds table creation script for Local Authority Statistical Neighbours
N/A
> feat: adds creation script for LocalAuthorityStatisticalNeighbour table

- web/src/Web.App/AssetSrc/scss/main.scss
- web/src/Web.App/ViewComponents/LocalAuthorityHighNeedsHeadlinesViewComponent.cs
- web/src/Web.App/ViewComponents/LocalAuthorityHighNeedsHistoryViewComponent.cs
- web/src/Web.App/ViewModels/Components/LocalAuthorityHighNeedsHeadlinesViewModel.cs
- web/src/Web.App/Views/LocalAuthorityHighNeeds/Index.cshtml
- web/src/Web.App/Views/Shared/Components/LocalAuthorityHighNeedsHeadlines/Default.cshtml
- web/src/Web.App/Views/Shared/Components/LocalAuthorityHighNeedsHeadlines/MissingData.cshtml
- web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
- web/tests/Web.Integration.Tests/Pages/LocalAuthorities/WhenViewingHighNeedsDashboard.cs
- web/tests/Web.Integration.Tests/Proxy/WhenRequestingEducationHealthCarePlansComparison.cs
- web/tests/Web.Integration.Tests/Proxy/WhenRequestingEducationHealthCarePlansHistory.cs
- web/tests/Web.Integration.Tests/Proxy/WhenRequestingHighNeedsComparison.cs
- web/tests/Web.Integration.Tests/Proxy/WhenRequestingHighNeedsHistory.cs
[AB#252983](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/252983) [AB#249575](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249575)
- Populated card
Deployed to `d18` feature environment for validation.
> Populated High needs headline figures summary card

- core-infrastructure/src/db/Core.Database/Scripts/111-CreateTableLaNonFinancial.sql
[AB#253361](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/253361) ([AB#253282](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/253282))
Adds table create script for local authority non financial data
N/A
> feat: adds creation script for LocalAuthorityNonFinancial table

- core-infrastructure/src/db/Core.Database/Views/018-LocalAuthorityFinancial.sql
[AB#253451](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/253451) [AB#252392](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/252392)
- New database views
Run database migrations locally to create views for validation.
> Added local authority financial views over `LocalAuthorityFinancial` table

- documentation/architecture/decisions/0010-sfb-decomm.md
ADR for Decommissioning Schools financial benchmarking service
> docs: ADR 0010 Decommissioning Schools financial benchmarking service

- pipelines/platform/steps/run-api-tests.yaml
- platform/tests/Platform.ApiTests/Features/EstablishmentLocalAuthorities.feature
- platform/tests/Platform.ApiTests/Features/LocalAuthoritiesHighNeeds.feature
- platform/tests/Platform.ApiTests/Features/NonFinancialEducationHealthCarePlansLocalAuthorities.feature
AB#253753 [AB#252392](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/252392)
Fixes broken pipeline
> Exclude High needs API tests until automated test environment seeded

- core-infrastructure/src/db/Core.Database/Views/019-LocalAuthorityNonFinancial.sql
[AB#253452](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/253452) [AB#253282](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/253282)
New database views
To be wired up as part of other work items
> Added non-financial Local authority views for EHCP data

- core-infrastructure/src/db/Core.Database/Views/019-LocalAuthorityNonFinancial.sql
[AB#254002](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/254002) [AB#253282](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/253282)
Updated database view
> Resolve 'per population' EHCP view

- web/terraform/variables.tf
[AB#253829](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/253829) ([AB#253802](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/253802)) 
Enables feature in lower environment
May break automated tests, as they are still disabled
> feat: enable high needs feature in d01, d02 and t01

- front-end-components/src/components/charts/historic-data-section-251-tooltip/component.tsx
- front-end-components/src/components/charts/table-chart/component.tsx
- front-end-components/src/components/charts/table-chart/types.tsx
- front-end-components/src/composed/benchmark-chart-section-251/component.tsx
- front-end-components/src/composed/historic-chart-section-251-composed/component.tsx
- front-end-components/src/composed/horizontal-bar-chart-multi-series/composed.tsx
- web/src/Web.App/ViewModels/TrendIndicatorViewModel.cs
- web/src/Web.App/Views/LocalAuthorityHighNeeds/Index.cshtml
- web/src/Web.App/Views/Shared/Components/LocalAuthorityHighNeedsHeadlines/Default.cshtml
- web/src/Web.App/Views/Shared/Components/LocalAuthorityHighNeedsHistory/Default.cshtml
- web/src/Web.App/Views/Shared/_TrendIndicator.cshtml
- web/tests/Web.E2ETests/Pages/LocalAuthority/HighNeedsDashboardPage.cs
- web/tests/Web.Integration.Tests/Pages/LocalAuthorities/WhenViewingHighNeedsDashboard.cs
[AB#254435](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/254435) [AB#253802](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/253802)
Various updates as requested on the 'snagging' story.
`front-end` will need to be bumped in `Web` after the corresponding pipeline artefact is published.
> Content updates for High needs pages

- web/src/Web.App/package-lock.json
[AB#254435](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/254435) [AB#253802](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/253802) #2142
> Bumped `front-end` to `1.1.78`

- web/src/Web.App/Constants/PageTitles.cs
- web/src/Web.App/Controllers/Api/Mappers/LocalAuthorityHighNeedsResponseMapper.cs
- web/src/Web.App/Views/LocalAuthorityHighNeeds/Index.cshtml
- web/src/Web.App/Views/Shared/Components/LocalAuthorityHighNeedsHistory/Default.cshtml
- web/src/Web.App/Views/Shared/Components/LocalAuthorityHighNeedsHistory/MissingData.cshtml
- web/src/Web.App/Views/Shared/Components/LocalAuthorityHighNeedsNationalRankings/Default.cshtml
- web/src/Web.App/Views/Shared/Components/LocalAuthorityHighNeedsNationalRankings/MissingData.cshtml
- web/tests/Web.E2ETests/Pages/LocalAuthority/HighNeedsDashboardPage.cs
- web/tests/Web.Integration.Tests/Pages/LocalAuthorities/WhenViewingHighNeedsDashboard.cs
- web/tests/Web.Tests/Controllers/Api/Mappers/WhenLocalAuthorityHighNeedsHistoryResponseMapperMaps.cs
- web/tests/Web.Tests/Controllers/Api/Mappers/WhenLocalAuthorityHighNeedsHistoryResponseMapperMapsToDashboardWithCode.cs
[AB#254585](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/254585) [AB#253802](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/253802)
- Content updates to High needs dashboard
- Excluded historical data from dashboard start/end years if they are missing budget or outturn
See 'snagging' user story for full list of required changes.
> High needs content updates

- documentation/quality-assurance/4_Performance-Testing.md
- documentation/quality-assurance/performance-test-plans/0008_Web-high-needs-load-test-plan.md
- performance-tests/src/web/url/average/local-authority/high-needs/config.yaml
- performance-tests/src/web/url/average/local-authority/high-needs/local-authorities.csv
- performance-tests/src/web/url/average/local-authority/high-needs/url-test.json
- performance-tests/src/web/url/peak/local-authority/high-needs/config.yaml
- performance-tests/src/web/url/peak/local-authority/high-needs/local-authorities.csv
- performance-tests/src/web/url/peak/local-authority/high-needs/url-test.json
[AB#254439](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/254439) [AB#253802](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/253802)
- Definition and documentation updates for load testing this feature
> Load test definitions and results for High needs dashboard

- web/src/Web.App/package-lock.json
[AB#254571](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/254571) [AB#253802](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/253802) #2148
> Bumped `front-end` to `1.1.79`

- data-pipeline/src/pipeline/input_schemas/__init__.py
- data-pipeline/src/pipeline/input_schemas/cfo.py
- data-pipeline/src/pipeline/main.py
- data-pipeline/src/pipeline/pre_processing/ancillary/cfo.py
CFO details have updated as of February 2024—the service should be updated to reflect this.
[AB#254814](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/254814)
update the CFO data processing to be in line with recent changes, accommodating the new data format for 2024.
Note: "title" is no longer present in the input file and won't appear in FBIT.
- brought the CFO-parsing in line with recent changes.
- ran 2021-2024 locally and all looks good.
> feat: update CFO data ingest

- web/src/Web.App/AssetSrc/scss/main.scss
- web/src/Web.App/Controllers/SchoolSearchController.cs
- web/src/Web.App/Infrastructure/Apis/ApiRequests/SearchRequest.cs
- web/src/Web.App/Infrastructure/Apis/ApiResults/SearchResponse.cs
- web/src/Web.App/Infrastructure/Apis/Establishment/Api.cs
- web/src/Web.App/Infrastructure/Apis/Establishment/EstablishmentApi.cs
- web/src/Web.App/Program.cs
- web/src/Web.App/Services/SearchService.cs
- web/src/Web.App/ViewComponents/PaginationViewComponent.cs
- web/src/Web.App/ViewModels/Components/PaginationViewModel.cs
- web/src/Web.App/ViewModels/Search/SchoolSearchResultViewModel.cs
- web/src/Web.App/ViewModels/Search/SchoolSearchResultsPageViewModel.cs
- web/src/Web.App/ViewModels/Search/SchoolSearchResultsViewModel.cs
- web/src/Web.App/ViewModels/Search/SearchResultFacetViewModel.cs
- web/src/Web.App/Views/SchoolSearch/Search.cshtml
- web/src/Web.App/Views/Shared/Search/_SchoolSearchResults.cshtml
- web/src/Web.App/package-lock.json
- web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
- web/tests/Web.Integration.Tests/Pages/Schools/Search/WhenViewingSchoolSearch.cs
- web/tests/Web.Integration.Tests/Pages/Schools/Search/WhenViewingSchoolSearchResults.cs
- web/tests/Web.Tests/Infrastructure/GivenAnEstablishmentApi.cs
- web/tests/Web.Tests/Services/WhenSchoolSearchServiceIsCalled.cs
- web/tests/Web.Tests/ViewModels/Search/GivenASchoolSearchResultViewModel.cs
- web/tests/Web.Tests/ViewModels/Search/GivenASearchResultFacetViewModel.cs
[AB#255275](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/255275) [AB#250281](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/250281)
- Wired up faceted school search to API
- School faceted search tests, based on previously stubbed data
- Search empty/failure edge cases with tests
- Bumped `front-end` to `1.1.80`
> Wired up School faceted search to API

- front-end-components/src/composed/benchmark-chart-section-251/component.tsx
- front-end-components/src/composed/benchmark-chart-section-251/types.tsx
- front-end-components/src/views/benchmark-data-high-needs/partials/index.tsx
- front-end-components/src/views/benchmark-data-high-needs/partials/section-251-section.tsx
- front-end-components/src/views/benchmark-data-high-needs/types.tsx
- front-end-components/src/views/historic-data-high-needs/partials/index.tsx
- front-end-components/src/views/historic-data-high-needs/partials/section-251-section.tsx
- web/src/Web.App/ViewComponents/DataSourceViewComponent.cs
- web/src/Web.App/Views/Home/Index.cshtml
- web/src/Web.App/Views/LocalAuthorityHighNeeds/Index.cshtml
- web/src/Web.App/Views/LocalAuthorityHighNeedsBenchmarking/Index.cshtml
- web/src/Web.App/Views/LocalAuthorityHighNeedsHistoricData/Index.cshtml
- web/tests/Web.E2ETests/Pages/LocalAuthority/HighNeedsDashboardPage.cs
- web/tests/Web.Integration.Tests/Pages/LocalAuthorities/WhenViewingHighNeedsDashboard.cs
[AB#255683](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/255683) - [AB#256596](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/256596)
Copy updates for high needs following design crit
Also updates DataSourceViewComponent to support a different data source commentary for high needs historic data and benchmark data pages
changes should reflect the requirements as per the attachment in the task
will need a subsequent bump to front end
changes have been reviewed by Content
> chore: copy updates high needs

- web/src/Web.App/package-lock.json
[AB#255683](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/255683) - [AB#256596](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/256596) - #2233 
bump to `front-end` package
n/a
> chore: bump `front-end` to `1.1.82`

- platform/tests/Platform.ApiTests/Features/EstablishmentSchools.feature
- platform/tests/Platform.ApiTests/Steps/EstablishmentSchoolsSteps.cs
[AB#250281](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/250281) - [AB#256048](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/256048)
Adds api tests for the `schools/search` establishment endpoint
n/a
> chore: add platform api tests for `schools/search` establishment endpoint

- web/src/Web.App/Views/SchoolComparatorsCreateBy/Index.cshtml
[AB#256181](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/256181) [AB#254434](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/254434)
Content addition
> User defined comparator schools intro

- web/src/Web.App/Constants/PageTitles.cs
- web/src/Web.App/Views/LocalAuthorityHighNeedsBenchmarking/Index.cshtml
- web/tests/Web.Integration.Tests/Pages/LocalAuthorities/WhenViewingHighNeedsDashboard.cs
A#256320 - [AB#257424](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/257424)
- update `LocalAuthorityHighNeeds` page title
- also update back link from `LocalAuthorityHighNeedsBenchmarking`
n/a
> feat: update `LocalAuthorityHighNeeds` page title

- web/Directory.Packages.props
- web/src/Web.App/AssetSrc/scss/main.scss
- web/src/Web.App/package-lock.json
- web/src/Web.App/packages.lock.json
- web/terraform/README.md
- web/terraform/provider.tf
- web/tests/Web.A11yTests/packages.lock.json
- web/tests/Web.E2ETests/packages.lock.json
- web/tests/Web.Integration.Tests/packages.lock.json
- web/tests/Web.Tests/packages.lock.json
[AB#257401](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/257401) [AB#257399](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/257399)
Bumped dependencies and validated.
> Bumped `web` dependencies

- platform/tests/Platform.ApiTests/Features/EstablishmentSchools.feature
- platform/tests/Platform.ApiTests/Steps/EstablishmentSchoolsSteps.cs
[AB#257253](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/257253) [AB#250281](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/250281) #2253 
Fixed failing API tests introduced in #2253
> Removed Facet assertions from School Search API tests

- platform/tests/Platform.ApiTests/Features/EstablishmentSchools.feature
[AB#250281](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/250281) #2255 
Fixes now failing platform api tests following changes introduced in #2255
n/a
> chore: updates to api tests following changes to `orderBy` behaviour

- platform/src/apis/Platform.Api.Establishment/Features/Schools/PostSchoolsSearchFunction.cs
- platform/src/apis/Platform.Api.Establishment/Features/Schools/SchoolsFeature.cs
- platform/src/apis/Platform.Api.Establishment/Features/Trusts/PostTrustsSearchFunction.cs
- platform/src/apis/Platform.Api.Establishment/Features/Trusts/TrustsFeature.cs
- platform/tests/Platform.ApiTests/Features/EstablishmentTrusts.feature
- platform/tests/Platform.ApiTests/Steps/EstablishmentSchoolsSteps.cs
- platform/tests/Platform.ApiTests/Steps/EstablishmentTrustsSteps.cs
[AB#258122](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/258122) [AB#250287](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/250287)
- Fixed School Search API tests (failing in build)
- Added Trust Search API tests
> Updated API tests for Trust search

- documentation/developers/2_Branching-Policy.md
Updates and clarifies branch naming section
> docs: updates branch naming section

- core-infrastructure/src/db/Core.Database/Views/023-LocalAuthoritySummary.sql
- platform/src/apis/Platform.Api.Establishment/Features/LocalAuthorities/Models/LocalAuthoritySummary.cs
- platform/src/apis/Platform.Api.Establishment/Features/LocalAuthorities/PostLocalAuthoritiesSuggestFunction.cs
- platform/src/apis/Platform.Api.Establishment/Features/LocalAuthorities/Services/LocalAuthoritiesService.cs
- platform/src/search/Platform.Search.Resources/LocalAuthority/LocalAuthorityDataSourceConnectionBuilder.cs
- platform/src/search/Platform.Search.Resources/LocalAuthority/LocalAuthorityIndex.cs
- platform/src/search/Platform.Search.Resources/LocalAuthority/LocalAuthorityIndexerBuilder.cs
- platform/tests/Platform.ApiTests/Steps/EstablishmentLocalAuthoritiesSteps.cs
- platform/tests/Platform.Establishment.Tests/LocalAuthorities/PostLocalAuthoritiesSuggestFunctionTests.cs
[AB#250286](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/250286) [AB#257775](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/257775)
- New database view
- Updated search index data source to use new view
- New return type from LA search index responses
- API and unit tests
Deployed to `d15` for validation.
> Created new `VW_LocalAuthoritySummary` view and wired up to LA 'suggest' endpoint

- web/src/Web.App/Constants/PageTitles.cs
- web/src/Web.App/Controllers/FindOrganisationController.cs
- web/src/Web.App/Controllers/LocalAuthoritySearchController.cs
- web/src/Web.App/Domain/Establishment/LocalAuthoritySummary.cs
- web/src/Web.App/Domain/Establishment/TrustSummary.cs
- web/src/Web.App/Infrastructure/Apis/Establishment/EstablishmentApi.cs
- web/src/Web.App/ViewModels/Search/FindLocalAuthorityViewModel.cs
- web/src/Web.App/Views/LocalAuthoritySearch/Index.cshtml
- web/tests/Web.A11yTests/Pages/LocalAuthority/WhenViewingSearch.cs
- web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
- web/tests/Web.Integration.Tests/Pages/LocalAuthorities/Search/WhenViewingLocalAuthoritySearch.cs
- web/tests/Web.Integration.Tests/Pages/WhenViewingFindOrganisation.cs
- web/tests/Web.Integration.Tests/Paths.cs
[AB#250286](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/250286) [AB#257777](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/257777) [AB#257780](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/257780)
- New 'standalone' page for LA search
- A11y coverage
Deployed to `d15` for validation
> Local Authority search page

- web/src/Web.App/Views/Shared/_ChangeLink.cshtml
- web/tests/Web.E2ETests/Pages/School/HomePage.cs
- web/tests/Web.E2ETests/Selectors.cs
- web/tests/Web.Integration.Tests/Pages/LocalAuthorities/WhenViewingHome.cs
- web/tests/Web.Integration.Tests/Pages/Trusts/WhenViewingHome.cs
[AB#250286](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/250286) [AB#258740](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/258740)
- Updated 'change link' `href`s based on feature flag
- Integration test updates
> Updated 'change link' URLs and integration tests

- web/src/Web.App/Controllers/LocalAuthoritySearchController.cs
- web/src/Web.App/ViewModels/Search/LocalAuthoritySearchResultViewModel.cs
- web/src/Web.App/ViewModels/Search/LocalAuthoritySearchResultsViewModel.cs
- web/src/Web.App/ViewModels/Search/LocalAuthoritySearchViewModel.cs
- web/src/Web.App/ViewModels/Search/TrustSearchResultViewModel.cs
- web/src/Web.App/Views/LocalAuthoritySearch/Search.cshtml
- web/src/Web.App/Views/Shared/Search/_LocalAuthoritySearchResults.cshtml
- web/tests/Web.A11yTests/Pages/LocalAuthority/WhenViewingSearchResults.cs
- web/tests/Web.Integration.Tests/Pages/LocalAuthorities/Search/WhenViewingLocalAuthoritySearch.cs
- web/tests/Web.Integration.Tests/Pages/LocalAuthorities/Search/WhenViewingLocalAuthoritySearchResults.cs
- web/tests/Web.Tests/ViewModels/Search/GivenALocalAuthoritySearchResultViewModel.cs
- web/tests/Web.Tests/ViewModels/Search/GivenATrustSearchResultViewModel.cs
[AB#250286](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/250286) [AB#257778](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/257778) [AB#257780](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/257780) #2280 
- LA search results page
- Integration, unit and A11y test coverage
Deployed to `d15` for validation. Dependency on #2280
> Added Local Authority search results page

- web/terraform/front-door.tf
[AB#258781](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/258781) [AB#258787](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/258787) #2284
Fixed invalid Terraform when targeting `production` environment.
This should resolve the following error when releasing Web to production:
> Resolve usage of `value` from iterator in `dynamic` block

- documentation/quality-assurance/release-test-plans/00018_release-test-plan.md
Release test plan for 2025.04.1
> Release test plan 2025.04.1

- documentation/developers/10_Monthly-Reporting.md
[AB#253596](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/253596) [AB#259617](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/259617)
Documentation updates
> Updated MI generation documentation

- platform/src/apis/Platform.Api.Establishment/Features/Trusts/PostTrustsSuggestFunction.cs
- platform/src/apis/Platform.Api.Establishment/Features/Trusts/Services/TrustsService.cs
- platform/tests/Platform.Establishment.Tests/Trusts/PostTrustsSuggestFunctionTests.cs
- web/src/Web.App/AssetSrc/ts/suggester.ts
- web/src/Web.App/Controllers/Api/SuggestProxyController.cs
- web/src/Web.App/Controllers/TrustSearchController.cs
- web/src/Web.App/Infrastructure/Apis/Establishment/EstablishmentApi.cs
- web/src/Web.App/Services/SuggestService.cs
- web/src/Web.App/ViewModels/Enhancements/SuggestScriptsViewModel.cs
- web/src/Web.App/Views/SchoolSearch/Index.cshtml
- web/src/Web.App/Views/SchoolSearch/Search.cshtml
- web/src/Web.App/Views/Shared/Enhancements/_SuggestScripts.cshtml
- web/src/Web.App/Views/TrustSearch/Index.cshtml
- web/src/Web.App/Views/TrustSearch/Search.cshtml
- web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
[AB#258757](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/258757) [AB#258864](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/258864) #2288
- Added autocomplete to Trust search
- Cancelable Trust suggest requests
Dependency on #2288
> Added autocomplete/suggester to Trust search form

- platform/src/apis/Platform.Api.Establishment/Features/LocalAuthorities/PostLocalAuthoritiesSuggestFunction.cs
- platform/src/apis/Platform.Api.Establishment/Features/LocalAuthorities/Services/LocalAuthoritiesService.cs
- platform/tests/Platform.Establishment.Tests/LocalAuthorities/PostLocalAuthoritiesSuggestFunctionTests.cs
- web/src/Web.App/Controllers/Api/SuggestProxyController.cs
- web/src/Web.App/Controllers/LocalAuthoritySearchController.cs
- web/src/Web.App/Infrastructure/Apis/Establishment/EstablishmentApi.cs
- web/src/Web.App/Services/SuggestService.cs
- web/src/Web.App/Views/LocalAuthoritySearch/Index.cshtml
- web/src/Web.App/Views/LocalAuthoritySearch/Search.cshtml
- web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
[AB#258757](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/258757) [AB#258865](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/258865) #2289
- Added autocomplete to LA search
- Cancelable LA suggest requests
Dependency on #2289
> Added autocomplete/suggester to LA search form

- web/tests/Web.E2ETests/Features/LocalAuthority/LocalAuthoritySearch.feature
- web/tests/Web.E2ETests/Features/School/SchoolSearch.feature
- web/tests/Web.E2ETests/Features/Trust/TrustSearch.feature
- web/tests/Web.E2ETests/Pages/LocalAuthority/SearchPage.cs
- web/tests/Web.E2ETests/Pages/LocalAuthority/SearchResultsPage.cs
- web/tests/Web.E2ETests/Pages/School/SearchResultsPage.cs
- web/tests/Web.E2ETests/Pages/Trust/SearchPage.cs
- web/tests/Web.E2ETests/Pages/Trust/SearchResultsPage.cs
- web/tests/Web.E2ETests/Selectors.cs
- web/tests/Web.E2ETests/Steps/LocalAuthority/SearchPageSteps.cs
- web/tests/Web.E2ETests/Steps/School/SearchPageSteps.cs
- web/tests/Web.E2ETests/Steps/Trust/SearchPageSteps.cs
[AB#258757](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/258757) [AB#259401](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/259401) #2290
- E2E test coverage over autocompletes
Dependency on #2290
> E2E tests for progressively enhanced search boxes

- platform/src/apis/Platform.Api.Benchmark/Features/ComparatorSets/PostSchoolUserDefinedComparatorSetFunction.cs
- platform/src/apis/Platform.Api.Benchmark/Features/CustomData/PostSchoolCustomDataFunction.cs
- platform/src/apis/Platform.Api.Benchmark/Shared/MultiResponse.cs
- platform/tests/Platform.Benchmark.Tests/CustomData/WhenDeleteSchoolCustomDataFunctionRuns.cs
- platform/tests/Platform.Benchmark.Tests/CustomData/WhenGetSchoolCustomDataFunctionRuns.cs
- platform/tests/Platform.LocalAuthorityFinances.Tests/HighNeeds/Services/WhenHighNeedsServiceQueriesAsync.cs
- platform/tests/Platform.NonFinancial.Tests/EducationHealthCarePlans/Services/WhenEducationHealthCarePlansServiceQueriesAsync.cs
[AB#259620](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/259620) [AB#259767](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/259767)
Improve platform API test coverage
> Added additional API test coverage

- core-infrastructure/terraform/README.md
- core-infrastructure/terraform/provider.tf
[AB#259646](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/259646) [AB#259652](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/259652)
bump provider prompted by dependabot PR
`terraform validate` shows success
> chore: bumped `core-infrastructure` dependencies

- platform/src/search/Platform.Search.Resources/SearchMaintenanceService.cs
[AB#256576](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/256576) [AB#260021](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/260021)
Count and show number of errors via exception thrown upon `Platform.Search` deployment error(s).
Should now fail during the pipeline run, rather than continue after logging the error.
> Throw exception from Search app if any failures occurred during execution

- web/src/Web.App/package-lock.json
[AB#258443](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/258443) [AB#259847](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/259847) #2332
> Bumped `front-end` to `1.1.89`

- web/tests/Web.E2ETests/Features/School/CompareYourCosts.feature
- web/tests/Web.E2ETests/Features/Trust/CompareYourCosts.feature
- web/tests/Web.E2ETests/Pages/Trust/CompareYourCostsPage.cs
[AB#258443](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/258443) [AB#259847](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/259847)
Fix tests failing since #2338 merged.
> Fixed failing E2E tests

- documentation/.markdownlint-cli2.jsonc
- documentation/quality-assurance/release-test-plans/00019_release-test-plan.md
WIP release plan for the upcoming release.
> release plan

- web/src/Web.App/Program.cs
[AB#260832](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/260832) [AB#260997](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/260997) #2283
Feature no longer required due to a requirement change to how traffic from legacy platform is redirected.
> Removed SFB from allowed forwarded hosts

- web/src/Web.App/ViewComponents/SchoolSpendingCostsViewComponent.cs
- web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
- web/tests/Web.Integration.Tests/Pages/Schools/CustomData/WhenViewingCustomDataSpending.cs
- web/tests/Web.Integration.Tests/Pages/Schools/WhenViewingSpending.cs
[AB#258039](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/258039) [AB#260351](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/260351)
Remaining integration tests for SSR charts on School Spending Priorities page, dependent on feature flag.
The following scenarios should be covered:
- Feature enabled
- Feature enabled, but problem with API
- Feature disabled
> Integration tests for SSR charts on School Spending Page

- web/Directory.Packages.props
- web/src/Web.App/package-lock.json
- web/src/Web.App/packages.lock.json
- web/terraform/README.md
- web/terraform/provider.tf
- web/tests/Web.A11yTests/packages.lock.json
- web/tests/Web.E2ETests/packages.lock.json
- web/tests/Web.Integration.Tests/packages.lock.json
- web/tests/Web.Tests/packages.lock.json
[AB#261141](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/261141) [AB#261143](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/261143)
Dependency updates across NuGet, npm and Terraform
> Updated `web` dependencies

- documentation/quality-assurance/release-test-plans/00020_release-test-plan.md
> release test plan for 2025.05.2

- documentation/features/8_Progressive_Enhancements.md
- web/README.md
[AB#258039](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/258039) [AB#262150](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/262150)
Documentation updates
> Progressive enhancements feature documentation

- pipelines/common/destroy-terraform.yaml
- pipelines/common/sync-terraform.yaml
- pipelines/core-infrastructure/destroy.yaml
- pipelines/destroy/destroy.yaml
[AB#262219](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/262219) [AB#262220](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/262220)
Fixed 'Destroy' pipeline by ensuring missing variable is correctly parsed and forwarded from template `.yml` parameters. 
Validated by running Destroy pipeline with this branch as the source.
> Added missing `supportAlertEmail` to Destroy pipeline templates

- support-analytics/terraform/README.md
- support-analytics/terraform/provider.tf
- support-analytics/terraform/queries.tf
- support-analytics/terraform/queries/functions/get-sfb-referrer-requests.kql
[AB#260833](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/260833) [AB#263376](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/263376) #2438
- KQL query as query pack function for re-use
- Bumped `azurerm`
Run KQL in Log Analytics in `p01` to validate results. Dependency on #2438.
> KQL function for requests to Redirect app service

- documentation/developers/10_Monthly-Reporting.md
[AB#263340](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/263340) [AB#263463](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/263463)
Documentation update
>  Added documentation for generating SFB decommissioning stats for the MI report

- platform/src/abstractions/Platform.Functions/Extensions/HttpRequestDataExtensions.cs
- platform/src/abstractions/Platform.Functions/VersionedFunctionBase.cs
- platform/src/abstractions/tests/Platform.Functions.Tests/VersionedFunctionBaseTests.cs
- platform/src/apis/Platform.Api.Establishment/Features/Trusts/Functions/GetTrustFunction.cs
Refactors common code in function method to base method for versioned function end points
> Refactors common code in function method

- web/src/Web.App/package-lock.json
[AB#258231](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/258231) [AB#264306](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/264306) #2458
Bumped `front-end` after pipeline run for #2458.
> Bumped `front-end` to `1.1.99`

- web/src/Web.App/Constants/PageTitles.cs
- web/src/Web.App/ViewComponents/DataSourceViewComponent.cs
- web/tests/Web.Integration.Tests/Pages/LocalAuthorities/WhenViewingHighNeedsHistoricData.cs
[AB#265206](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/265206) [AB#265464](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/265464) 
- H1 updated
- “Budget” changed to “planned expenditure” in the paragraph after H1
N/A
> Feature/265206/265464 web app UI updates

- web/tests/Web.A11yTests/Pages/LocalAuthority/WhenViewingHighNeedsNationalRankings.cs
[AB#265025](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/265025) [AB#265459](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/265459)
tests to cover each toggle for chart mode for each tab
n/a
> add additional a11y tests for la national ranking page

- web/tests/Web.E2ETests/Features/LocalAuthority/HighNeedsNationalRankings.feature
- web/tests/Web.E2ETests/Pages/LocalAuthority/HighNeedsNationalRankingsPage.cs
- web/tests/Web.E2ETests/Steps/LocalAuthority/HighNeedsNationalRankingsSteps.cs
[AB#265025](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/265025) [AB#265458](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/265458)
updates e2e tests following updates to this page
n/a
> chore: update e2e tests for la national ranking page

- web/src/Web.App/Views/DataSource/_DataSources.cshtml
[AB#260084](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/260084) [AB#266024](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/266024)
Content update
> Added ILR entry to Data Sources page

- documentation/architecture/decisions/0011_azure-front-door-upgrade.md
[AB#264358](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/264358) [AB#266307](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/266307)
Documentation update
> Marked ADR 0011 as `Accepted`

- documentation/architecture/12_DfE-Databricks.md
Considerations for what we'll do about DfE's Databricks instance.
> doc: Databricks ADR

- documentation/architecture/decisions/0008-resolving-Intermittent-errors-function-app.md
- documentation/architecture/decisions/0009-js-library.md
- documentation/architecture/decisions/0012_uage-managed-identity.md
Initial draft of AD0012 - Use of Connection Strings/Keys vs Managed Identity in Azure Authentication
> docs: ADR0012

- web/README.md
- web/src/Web.App/Cache/CacheOptions.cs
- web/src/Web.App/Services/BannerService.cs
- web/src/Web.App/Services/CommercialResourcesService.cs
- web/src/Web.App/Services/FinanceService.cs
- web/src/Web.App/ViewModels/Components/BannerViewModel.cs
- web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
- web/tests/Web.Integration.Tests/DocumentAssert.cs
- web/tests/Web.Integration.Tests/Pages/LocalAuthorities/WhenViewingHome.cs
- web/tests/Web.Integration.Tests/Pages/Schools/WhenViewingHome.cs
- web/tests/Web.Integration.Tests/Pages/Trusts/WhenViewingHome.cs
- web/tests/Web.Integration.Tests/Pages/WhenViewingLandingPage.cs
- web/tests/Web.Tests/Services/WhenBannerServiceIsCalled.cs
- web/tests/Web.Tests/Services/WhenCommercialResourcesServiceIsCalled.cs
[AB#264114](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/264114) [AB#266411](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/266411)
Integration test coverage for the above feature.
Dependency on #2561 
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
To prevent flaky tests, bypass cache by allowing '0' to be defined in cache options.
Run integration test suite to validate changes
> Integration test coverage for service banners

- test-data/Banner.csv
- web/src/Web.App/ViewComponents/BannerViewComponent.cs
- web/src/Web.App/ViewModels/Components/BannerViewModel.cs
- web/src/Web.App/Views/Home/Index.cshtml
- web/src/Web.App/Views/Shared/Components/Banner/Default.cshtml
- web/tests/Web.E2ETests/Features/HomePage.feature
- web/tests/Web.E2ETests/Features/LocalAuthority/LocalAuthorityHome.feature
- web/tests/Web.E2ETests/Features/School/SchoolHome.feature
- web/tests/Web.E2ETests/Features/Trust/TrustHome.feature
- web/tests/Web.E2ETests/Pages/HomePage.cs
- web/tests/Web.E2ETests/Pages/LocalAuthority/HomePage.cs
- web/tests/Web.E2ETests/Pages/School/HomePage.cs
- web/tests/Web.E2ETests/Pages/Trust/HomePage.cs
- web/tests/Web.E2ETests/Selectors.cs
- web/tests/Web.E2ETests/Steps/HomePageSteps.cs
- web/tests/Web.E2ETests/Steps/LocalAuthority/HomeSteps.cs
- web/tests/Web.E2ETests/Steps/School/HomeSteps.cs
- web/tests/Web.E2ETests/Steps/Trust/HomeSteps.cs
[AB#264114](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/264114) [AB#266412](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/266412)
- E2E test coverage over the above feature
- Set banner to two-thirds width on service landing page, to match content
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
`d02` has already been seeded with the values to support the proposed changes
> E2E test coverage for banner on relevant home pages

- platform/tests/Platform.ApiTests/Data/CommercialResources.json
[AB#266678](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/266678) [AB#268109](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/268109)
updates test data following updates to d02 CommercialResources table. 
this should fix the currently failing pipeline for automated test for platform
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
n/a
tested locally with content api pointing to d02 db. The two currently failing tests now pass.
> chore: update `CommercialResources.json` following updates to d02 CommercialResources table

- platform/Directory.Packages.props
- platform/src/abstractions/Platform.Cache/packages.lock.json
- platform/src/abstractions/Platform.Functions/packages.lock.json
- platform/src/abstractions/Platform.Search/packages.lock.json
- platform/src/abstractions/Platform.Sql/packages.lock.json
- platform/src/abstractions/Platform.Test/packages.lock.json
- platform/src/abstractions/tests/Platform.Cache.Tests/packages.lock.json
- platform/src/abstractions/tests/Platform.Domain.Tests/packages.lock.json
- platform/src/abstractions/tests/Platform.Functions.Tests/packages.lock.json
- platform/src/abstractions/tests/Platform.Search.Tests/packages.lock.json
- platform/src/abstractions/tests/Platform.Sql.Tests/packages.lock.json
- platform/src/apis/Platform.Api.Benchmark/packages.lock.json
- platform/src/apis/Platform.Api.Content/packages.lock.json
- platform/src/apis/Platform.Api.Establishment/packages.lock.json
- platform/src/apis/Platform.Api.Insight/packages.lock.json
- platform/src/apis/Platform.Api.LocalAuthorityFinances/packages.lock.json
- platform/src/apis/Platform.Api.NonFinancial/packages.lock.json
- platform/src/apis/Platform.Orchestrator/packages.lock.json
- platform/src/apis/Platform.UserDataCleanUp/packages.lock.json
- platform/src/search/Platform.Search.App/packages.lock.json
- platform/src/search/Platform.Search.Resources/packages.lock.json
- platform/tests/Platform.ApiTests/packages.lock.json
- platform/tests/Platform.Benchmark.Tests/packages.lock.json
- platform/tests/Platform.Content.Tests/packages.lock.json
- platform/tests/Platform.Establishment.Tests/packages.lock.json
- platform/tests/Platform.Insight.Tests/packages.lock.json
- platform/tests/Platform.LocalAuthorityFinances.Tests/packages.lock.json
- platform/tests/Platform.NonFinancial.Tests/packages.lock.json
- platform/tests/Platform.Orchestrator.Tests/packages.lock.json
[AB#264999](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/264999) [AB#268189](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/268189)
Prompted by this month's dependabot PRs this should update all required nuget packages for platform and close those dependabot PRs 
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
n/a
full platform test suite passes
> chore: update platform nuget packages

- prototype/src/package-lock.json
- prototype/src/package.json
[AB#264999](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/264999) [AB#268191](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/268191)
Latest security/dependency pass over packages in the `prototype` project.
Covers validation of the following PRs in a single sweep 🧹:
- #2559
- #2551 
- #2548 
- #2530 
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
Dependency update only.
Build and run local dev server to validate.
> Bumped `prototype` node dependencies

- front-end-components/src/components/charts/table-chart/component.tsx
[AB#269291](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/269291) [AB#265181](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/265181) 
Ensures table and chart have same value.
<details>
</details>
<details>
</details>
<details>
</details>
Will need to build front-end locally
> feat: fixes table view

- documentation/architecture/decisions/0014-DfE-Databricks-data-out.md
ADR for how we want to take data extracts from Databricks
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> doc: add ADR for databricks data out options

- documentation/quality-assurance/performance-test-plans/0009_Web-shutter-load-test-plan.md
- performance-tests/src/web/url/average/shutter/config.yaml
- performance-tests/src/web/url/average/shutter/url-test.json
- performance-tests/src/web/url/peak/shutter/config.yaml
- performance-tests/src/web/url/peak/shutter/url-test.json
- pipelines/common/run-terraform.yaml
- pipelines/feature/release.yaml
- pipelines/production/deployment.yaml
- pipelines/production/release.yaml
- pipelines/web/deployment.yaml
- web/terraform/shutter.tf
[AB#227179](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/227179) [AB#268759](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/268759)
- Load test scripts for Shutter site
- Load test run documentation
- SKU change for Shutter service plan
- `enabled` flag driven from variable for Shutter service
- During deployment, mark service as `enabled` and then back to `disabled` again, as required
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
Load tests already executed against feature environment.
> Bumped shutter service ASP SKU to `P0V3` with load test evidence

- documentation/quality-assurance/release-test-plans/00021_release-test-plan.md
Release plan for `2025.07.0`
See also:
- [AB#263444](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/263444)
> Release plan for `2025.07.0`

- web/Directory.Packages.props
- web/Web.sln
- web/src/Web.App/package-lock.json
- web/src/Web.App/package.json
- web/src/Web.App/packages.lock.json
- web/tests/Web.A11yTests/packages.lock.json
- web/tests/Web.E2ETests/packages.lock.json
- web/tests/Web.Integration.Tests/packages.lock.json
- web/tests/Web.Tests/packages.lock.json
[AB#270026](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/270026) [AB#270028](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/270028)
Bumps dependencies as per #2623, #2629, #2631, #2633, #2641, #2647. 
Shutter dependencies managed as part of separate PR #2653.
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
Web app should run as expected after the updates, and unit/integration tests pass.
> Bumped `Web.App` dependencies

- front-end-components/src/views/compare-your-trust/partials/accordion-sections/non-educational-support-staff.tsx
Minor content update on high exec pay chart
[AB#270637](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/270637) [AB#270704](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/270704)
<details>
- [c] Code follows project coding standards.
- [c] Code builds clean without any errors or warnings.
- [c] Branch has been rebased onto main.
- [c] Unit and integration tests updated _(if applicable)_.
- [c] All unit/integration tests are executed and passed.
- [c] Tested by running locally.
</details>
<details>
</details>
<details>
</details>
Will require bump of front-end version
> feat: minor content update on high exec pay chart

- documentation/quality-assurance/release-test-plans/00022_release-test-plan.md
release test plan 
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
>Add any additional context or questions for reviewers. Include any dependencies that are required for this change. 
>Briefly describe how this was tested and any special setup or edge cases to verify.
> release test plan 2025.07.1

- platform/src/apis/Platform.Api.ChartRendering/src/functions/horizontalBarChart/builder.ts
- web/src/Web.App/AssetSrc/scss/_filter.scss
- web/src/Web.App/AssetSrc/scss/main.scss
[AB#270080](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/270080) [AB#272563](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/272563)
Ensures label is clipped at appropriate length
<details>
</details>
<details>
</details>
<details>
</details>
Clipped had been previously implemented.
> feat: ensures label clipping at appropriate length

- web/src/Web.App/AssetSrc/scss/_filter.scss
- web/src/Web.App/Views/SchoolComparisonItSpend/Index.cshtml
[AB#270080](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/270080) [AB#272622](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/272622)
Adds styles to filter box
<details>
</details>
<details>
</details>
<details>
</details>
> feat: adds styles to filter box

- web/src/Web.App/Views/SchoolComparisonItSpend/Index.cshtml
[AB#270080](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/270080)
[AB#274546](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/274546)
Highlights the selected school in the table view for the benchmark IT spending page to properly replicate the current table behaviour across other pages.
<details>
</details>
<details>
</details>
<details>
</details>
> feat: highlight selected school in table view

- web/tests/Web.Integration.Tests/Pages/Schools/Comparison/WhenViewingComparisonItSpend.cs
[AB#270080](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/270080)
[AB#273659](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/273659)
Adds further integration tests to validate more behaviour on this page.
- suppression of zero and negative warning is present only when required
- clear correctly removes filters
<details>
</details>
<details>
</details>
<details>
</details>
> chore: add further integration tests for benchmark IT spend page

- documentation/data/1_Domain.md
I was talking with Willem and I think this is useful at a high level
> Add grid for data sources

- documentation/tools/make-pdf.sh
- pipelines/documentation/build.yaml
* set more config so tables render nicely in PDF
* add libraries so the config works
> Test CICD environment works for pdf generation enhancements

- web/README.md
- web/src/Web.App/AssetSrc/ts/components/chart-actions/ChartActions.vue
- web/src/Web.App/AssetSrc/ts/components/page-actions/PageActions.vue
- web/src/Web.App/AssetSrc/ts/components/page-actions/index.d.ts
- web/src/Web.App/AssetSrc/ts/components/school-chart-tooltip/SchoolChartTooltips.vue
- web/src/Web.App/AssetSrc/ts/index.html
[AB#270093](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/270093) [AB#276022](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/276022)
- Added optional prop to `PageActions` component to start the 'save all' process immediately
- Updated playground to set this value, and documented how to label components correctly in the Vue dev tools
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
Intentionally not consumed anywhere as yet. This will be done as part of future related work.
> Enabled auto-start of save images dialog

- web/src/Web.App/Domain/CostCodes.cs
- web/tests/Web.E2ETests/Features/School/CompareYourCosts.feature
- web/tests/Web.E2ETests/Features/Trust/CompareYourCosts.feature
- web/tests/Web.Tests/Domain/GivenASubCategoryCostCodes.cs
[AB#269577](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/269577) [AB#276411](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/276411)
Updated code for above category along with affected tests.
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Updated AAR code code for Grounds Maintenance Costs to `BAE170`

- documentation/architecture/decisions/0013_DfE-Databricks.md
- documentation/architecture/decisions/0014-DfE-Databricks-data-out.md
- documentation/architecture/decisions/0015-chart-svg-generation.md
ADR for Chart Rendering API Performance and Scalability Improvements (0015)
<details>
</details>
<details>
</details>
> docs: adds ADR 0015

- web/src/Web.App/AssetSrc/ts/components/school-chart-tooltip/SchoolChartTooltip.vue
[AB#270083](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/270083) [AB#276417](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/276417)
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Removed `numeric` cell class from Pupils in tooltip table

- documentation/developers/14_Authentication-Authorisation.md
Add authentication & authorisation documentation
<details>
</details>
<details>
</details>
<details>
</details>
> docs: add authentication & authorisation documentation

- platform/src/abstractions/Platform.Sql/QueryBuilders/PlatformQuery.cs
- platform/src/abstractions/Platform.Sql/QueryBuilders/PublishedNewsQueries.cs
- platform/src/abstractions/tests/Platform.Sql.Tests/Builders/PlatformQueryTests.cs
- platform/src/abstractions/tests/Platform.Sql.Tests/Builders/PublishedNewsQueryTests.cs
- platform/src/apis/Platform.Api.Content/Configuration/Services.cs
- platform/src/apis/Platform.Api.Content/Constants.cs
- platform/src/apis/Platform.Api.Content/Features/News/GetNewsArticleFunction.cs
- platform/src/apis/Platform.Api.Content/Features/News/Handlers/GetNewsArticleV1Handler.cs
- platform/src/apis/Platform.Api.Content/Features/News/Models/News.cs
- platform/src/apis/Platform.Api.Content/Features/News/NewsFeature.cs
- platform/src/apis/Platform.Api.Content/Features/News/Routes.cs
- platform/src/apis/Platform.Api.Content/Features/News/Services/NewsService.cs
- platform/tests/Platform.ApiTests/Data/ContentNewsArticleNotYetArchived.json
- platform/tests/Platform.ApiTests/Data/ContentNewsArticlePublished.json
- platform/tests/Platform.ApiTests/Features/ContentNews.feature
- platform/tests/Platform.ApiTests/Steps/ContentNewsSteps.cs
- platform/tests/Platform.Content.Tests/News/Functions/GetNewsArticleFunctionTests.cs
- platform/tests/Platform.Content.Tests/News/Handlers/GetNewsArticleV1HandlerTests.cs
- platform/tests/Platform.Content.Tests/News/Services/WhenNewsServiceQueriesNewsArticleAsync.cs
[AB#264127](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/264127) [AB#277307](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/277307) #2777
- New function/handler and routing
- New service with database call via query builder
- API test coverage
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
Dependency on deployment of #2777 along with its test data seeded into `d02`.
> Added `news/{slug}` endpoint to Content API

- core-infrastructure/terraform/README.md
- core-infrastructure/terraform/provider.tf
- platform/terraform/README.md
- platform/terraform/provider.tf
- prototype/terraform/README.md
- prototype/terraform/provider.tf
- web/terraform/README.md
- web/terraform/provider.tf
[AB#265001](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/265001) [AB#278024](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/278024) #2796 #2810 #2832 #2841
Bumped Terraform provider to resolve above dependabot PRs in one pass.
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Bumped `azurerm` Terraform provider

- platform/src/abstractions/Platform.Sql/QueryBuilders/PublishedNewsQueries.cs
- platform/src/abstractions/tests/Platform.Sql.Tests/Builders/PublishedNewsQueryTests.cs
- platform/src/apis/Platform.Api.Content/Features/News/GetNewsFunction.cs
- platform/src/apis/Platform.Api.Content/Features/News/Handlers/GetNewsV1Handler.cs
- platform/src/apis/Platform.Api.Content/Features/News/Models/News.cs
- platform/src/apis/Platform.Api.Content/Features/News/NewsFeature.cs
- platform/src/apis/Platform.Api.Content/Features/News/Routes.cs
- platform/src/apis/Platform.Api.Content/Features/News/Services/NewsService.cs
- platform/tests/Platform.ApiTests/Data/ContentNewsArticleNotYetArchived.json
- platform/tests/Platform.ApiTests/Data/ContentNewsArticlePublished.json
- platform/tests/Platform.ApiTests/Data/ContentNewsArticles.json
- platform/tests/Platform.ApiTests/Features/ContentNews.feature
- platform/tests/Platform.ApiTests/Steps/ContentNewsSteps.cs
- platform/tests/Platform.Content.Tests/News/Functions/GetNewsFunctionTests.cs
- platform/tests/Platform.Content.Tests/News/Handlers/GetNewsV1HandlerTests.cs
- platform/tests/Platform.Content.Tests/News/Services/WhenNewsServiceQueriesNewsAsync.cs
[AB#264127](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/264127) [AB#277515](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/277515) #2782
- New function/handler and routing
- Extended service with database call via query builder for custom fields
- API test coverage
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
Dependency on #2782 along with test data that should have already been seeded into `d02`.
> Added `news` endpoint to Content API

- web/src/Web.App/package-lock.json
- web/src/Web.App/package.json
[AB#270556](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/270556) [AB#278113](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/278113)
Bumped `front-end` to pull in changes after feature flag deprecation
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Bumped `front-end` to `1.2.15`

- front-end-components/src/views/historic-data/partials/balance-section.tsx
[AB#268157](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/268157) [AB#278244](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/278244)
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
This will require a follow-up bump to `front-end` in `web`.
> Updated revenue reserve commentary

- pipelines/platform/steps/run-unit-tests.yaml
- pipelines/web/steps/run-unit-tests.yaml
[AB#276259](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/276259) [AB#278781](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/278781)
Version bumped ADO task due to Node version warnings as well as flaky code coverage gathering task execution.
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Bumped `BuildQualityChecks` ADO task to `10` for `web` and `platform`

- documentation/sources/dsg-funding.md
>Create a markdown document which describes the Dedicated Schools Grant, how it is made up and the milestones relating to the DGS and how they relate to other High Needs data sources.
<details>
</details>
<details>
</details>
>Does this give a good understanding of what the DSG is and its relationship to High Needs?
> Create dsg-funding.md to provide an overview of the DSG and related milestones

- documentation/developers/16_Azure-DevOps-Workflow.md
Initial draft document for the ADO workflow
> docs: initial draft document for the ado workflow

- documentation/data/1_Domain.md
* Trying to add coverage in our docs
> doc: Add detail for use cases and ancillary data per data release. Include the join key for each ancillary source.

- platform/src/apis/Platform.Api.ChartRendering/.vscode/settings.json
- platform/src/apis/Platform.Api.ChartRendering/jest.config.js
- platform/src/apis/Platform.Api.ChartRendering/src/assets/openapi.json
- platform/src/apis/Platform.Api.ChartRendering/src/functions/horizontalBarChart/template.ts
- platform/src/apis/Platform.Api.ChartRendering/src/functions/index.d.ts
- platform/src/apis/Platform.Api.ChartRendering/src/functions/utils.ts
- platform/src/apis/Platform.Api.ChartRendering/src/functions/verticalBarChart/template.ts
- platform/src/apis/Platform.Api.ChartRendering/tests/functions/utils.test.ts
- platform/tests/Platform.ApiTests/Data/HorizontalBarChartValidSingleCurrencyMissingDataLabel.svg
- platform/tests/Platform.ApiTests/Data/HorizontalBarChartValidSingleCurrencyMissingDataLabelRequest.json
- platform/tests/Platform.ApiTests/Features/ChartRenderingHorizontalBarChart.feature
- platform/tests/Platform.ApiTests/Models/PostHorizontalBarChartRequest.cs
- platform/tests/Platform.ApiTests/Steps/ChartRenderingHorizontalBarChartSteps.cs
- web/src/Web.App/AssetSrc/scss/main.scss
[AB#266041](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/266041) [AB#281173](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/281173)
- New config and implementation to support above requirement
- Refactored `sort()` logic into `utils` with unit tests
- SASS updates to match [`red` GDS tag](https://design-system.service.gov.uk/components/tag#using-colour-with-tags)
- No changes to SVG output when new optional config not set (verified via API tests)
- API test coverage for new options
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> New optional SSR horizontal bar configuration to support 'missing data' label

- platform/src/apis/Platform.Api.ChartRendering/src/assets/openapi.json
- platform/src/apis/Platform.Api.ChartRendering/src/functions/horizontalBarChart/template.ts
- platform/src/apis/Platform.Api.ChartRendering/src/functions/index.d.ts
- platform/src/apis/Platform.Api.ChartRendering/src/functions/utils.ts
- platform/src/apis/Platform.Api.ChartRendering/src/functions/verticalBarChart/template.ts
- platform/src/apis/Platform.Api.ChartRendering/tests/functions/utils.test.ts
- platform/tests/Platform.ApiTests/Data/HorizontalBarChartValidSingleCurrencyCustomDomain.svg
- platform/tests/Platform.ApiTests/Data/HorizontalBarChartValidSingleCurrencyCustomDomainRequest.json
- platform/tests/Platform.ApiTests/Features/ChartRenderingHorizontalBarChart.feature
- platform/tests/Platform.ApiTests/Models/ChartRequest.cs
[AB#266041](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/266041) [AB#281174](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/281174)
- New optional `domainMin` and `domainMax` added to chart config
- Values used for domain if valid, else suitable min/max calculated based on min/max values across the data set
- `nice()`-ing the domain may alter the custom values slightly in order for ticks to be resolved based on `suggestedXAxisTickCount` but this would be consistent across charts with the same customised domain values
- Domain calculation (before `nice()`-ing) refactored, with added unit test coverage
- API test coverage
<details>
</details>
<details>
<summary>Documentation …
> Add optional domain range to chart configuration

- documentation/developers/17_Azure-Front-Door-Review.md
Documents process for reviewing WAF logs
<details>
</details>
> docs: first draft for waf review process

- data-pipeline/src/pipeline/pre_processing/bfr/config.py
* Fixing misconfigured imports from #2971 
* My local environment could deal with the imports, but in the container it couldn't, so it slipped through the net
> fix imports

- web/src/Web.App/Controllers/SchoolComparisonItSpendController.cs
- web/src/Web.App/Domain/Charts/Dimensions.cs
- web/src/Web.App/Domain/Charts/Views.cs
- web/src/Web.App/ViewModels/BenchmarkingViewModelCostSubCategory.cs
- web/src/Web.App/ViewModels/SchoolComparisonItSpendViewModel.cs
- web/src/Web.App/ViewModels/SchoolComparisonSubCategoriesViewModel.cs
- web/src/Web.App/Views/SchoolComparisonItSpend/Index.cshtml
- web/src/Web.App/Views/SchoolComparisonItSpend/_ItSpendFilter.cshtml
- web/tests/Web.Integration.Tests/Pages/Schools/Comparison/WhenViewingComparisonItSpend.cs
- web/tests/Web.Tests/ViewModels/GivenASchoolComparisonItSpendViewModel.cs
- web/tests/Web.Tests/ViewModels/GivenASchoolComparisonSubCategoriesViewModel.cs
[AB#266041](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/266041) [AB#281179](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/281179)
Separate PR from actual Trust IT Spend filtering so as to not make that PR too large with this refactor as well as new changes. Regression of School IT spend may be required as part of the larger story (work item logged as such).
This should also unblock the [flaky unit test runs](https://dfe-ssp.visualstudio.com/s198-DfE-Benchmarking-service/_build/results?buildId=610930&view=logs&j=d0ad3af2-1ec5-5489-aaf1-1421492374d2&s=6884a131-87da-5381-61f3-d7acc3b91d76&t=490f45b8-0c34-524e-2d57-dc8e9fd8a294&l=1178) when AutoFixture is unable to `Create()` a …
> Mini view model refactor to support reuse for Trust IT Spend

- platform/src/apis/Platform.Api.ChartRendering/src/functions/utils.ts
- platform/src/apis/Platform.Api.ChartRendering/tests/functions/utils.test.ts
- platform/tests/Platform.ApiTests/Data/HorizontalBarChartValidSingleCurrencyGroupedKeys.svg
- platform/tests/Platform.ApiTests/Data/HorizontalBarChartValidSingleCurrencyGroupedKeysRequest.json
- platform/tests/Platform.ApiTests/Features/ChartRenderingHorizontalBarChart.feature
- platform/tests/Platform.ApiTests/Models/PostHorizontalBarChartRequest.cs
- platform/tests/Platform.ApiTests/TestDataHelpers/TestDataProvider.cs
- web/src/Web.App/AssetSrc/scss/_variables.scss
- web/src/Web.App/AssetSrc/scss/main.scss
[AB#266041](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/266041) [AB#281175](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/281175)
- Removed default `sort` for intentionally unsorted chart data
- Added sample API tests for `groupedKeys` usage
- Added sample styles for custom bar colours based on above grouping
> 💡 **NOTE**: #2972 contains the fix to the flaky Web pipeline build and so should be merged first
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Sample horizontal bar chart request using `groupedKeys` to apply custom bar styles

- web/tests/Web.A11yTests/Pages/Schools/WhenViewingBenchmarkItSpending.cs
- web/tests/Web.A11yTests/Pages/Trust/WhenViewingBenchmarkItSpending.cs
- web/tests/Web.Integration.Tests/Pages/Trusts/Comparison/WhenViewingComparisonItSpend.cs
[AB#266041](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/266041) [AB#280876](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/280876)
- Also updated School IT spend a11y to include Table view
- Fixed broken build after most recent PR was merged
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> A11y tests for chart/table views on Trust IT spending

- platform/src/apis/Platform.Api.ChartRendering/src/functions/horizontalBarChart/template.ts
- platform/src/apis/Platform.Api.ChartRendering/src/functions/utils.ts
- platform/src/apis/Platform.Api.ChartRendering/tests/functions/utils.test.ts
[AB#266041](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/266041) [AB#283824](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/283824)
- Previously this was cropping the beginning of the trust name
- Values are in all caps due to the original data source (at the highest level, Companies House)
- If/when Trust names are nicely title-cased the original truncation will be reverted without any additional work
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Applied more aggressive label truncation on SSR horizontal bar chart if value is in all caps

- web/src/Web.App/AssetSrc/scss/main.scss
[AB#266041](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/266041) [AB#284240](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/284240)
- Bring implementation back in line with design
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Modify bar colour for 'no tooltip/hover' SSR charts to match usual hover colour

- web/src/Web.App/AssetSrc/scss/main.scss
- web/src/Web.App/Views/TrustComparisonItSpend/_ItSpendTable.cshtml
[AB#266041](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/266041) [AB#284241](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/284241)
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Improved layout of 'forecast' Trust IT spend table

- web/src/Web.App/ViewModels/Components/ResourcesViewModel.cs
- web/src/Web.App/Views/Shared/Components/Resources/Default.cshtml
- web/src/Web.App/Views/Trust/Index.cshtml
- web/tests/Web.Integration.Tests/Pages/Trusts/WhenViewingHome.cs
[AB#270713](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/270713) [AB#284109](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/284109)
- Conditionally show FBIS CTA based on feature flag
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Added FBIS for Trusts link to Trust landing page
