front-end-components/src/components/school-expenditure/educational-supplies.tsx
front-end-components/src/components/school-expenditure/non-educational-support-staff.tsx
front-end-components/src/components/school-expenditure/other-costs.tsx
front-end-components/src/components/school-expenditure/premises-staff-services.tsx
front-end-components/src/services/school-api.tsx
platform/src/apis/EducationBenchmarking.Platform.Api.Insight/Models/PagedSchoolExpenditure.cs
platform/src/apis/EducationBenchmarking.Platform.Api.Insight/Models/SchoolExpenditure.cs
web/src/EducationBenchmarking.Web/Domain/SchoolExpenditure.cs

Adds missing chart and fixes typo on heading.
1. Total educational supplies costs
2. Total non-educational support staff costs
3. Total premises staff and service costs table/chart

Adds missing charts and typo fix

---

core-infrastructure/terraform/provider.tf
platform/terraform/provider.tf
web/terraform/provider.tf

Fixed AzureRm provider to version 3.87 as a bug has been introduced in v3.88 that causes validation fails due to camel casing. There is an open bug report with terraform so this should be a temporary fix

Fixed AzureRm provider to version 3.87

---

front-end-components/.eslintrc.cjs
front-end-components/.prettierrc
front-end-components/README.md
front-end-components/package-lock.json
front-end-components/package.json

- Default `.prettierrc` configuration used, for discussion
- Intentionally not run `eslint --fix` on the ~2400 problems until configuration confirmed
- Updated `README.md` for those using VS Code IDE
- Updated `vite` to resolve `npm audit` high severity warning
> **TODO:** Resolve problems highlighted by `prettier` (next PR)
> **TODO:** Update pipelines to perform `npm run lint`, once all existing problems have been resolved (final PR)
[AB#192808](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/192808)

Added `prettier` to front-end to help enforce consistent code styles along with existing linting

---

core-infrastructure/pipelines/build.yaml

Switch core pipeline to use ubuntu-latest

chore: switch core pipeline to use ubuntu-latest

---

front-end-components/src/components/chart-dimensions/index.tsx
front-end-components/src/components/chart-dimensions/types.tsx
front-end-components/src/views/compare-your-workforce/partials/headcount.tsx
front-end-components/src/views/compare-your-workforce/partials/types.tsx

- corrected calculation for HeadcountPerFTE in CalculateWorkforceValue. now this is workforce headcount / specific FTE (value)
- removed dropdown value on chart/table for School workforce (Headcount). This is now the only trivial result for the data.

fix: workforce headcount per FTE

---

web/src/EducationBenchmarking.Web/Controllers/SchoolPlanningYearController.cs
web/src/EducationBenchmarking.Web/Infrastructure/Apis/Requests/PutFinancialPlanRequest.cs
web/src/EducationBenchmarking.Web/ViewModels/SchoolPlanViewModel.cs
web/src/EducationBenchmarking.Web/Views/SchoolPlanningYear/Index.cshtml

part of the icfp journey - this is for the prepopulated data page 
Task - [AB#191733](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/191733)
Story - [AB#191578](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/191578)
this PR adds:
- required logic to post a financial plan from prepopulated data to the api
- fixes error with how year is displayed on page
outstanding to complete the ticket
- logic for backend to post relevant data to Cosmos
- validation
- get the financial plan when it exists for the page 
N/A

icfp prepopulated data - adds post financial plan to api from web app

---

front-end-components/index.html
front-end-components/package-lock.json
front-end-components/package.json
front-end-components/src/components/charts/horizontal-bar-chart-wrapper.tsx
front-end-components/src/components/charts/types.tsx
front-end-components/src/components/charts/utils.test.ts
front-end-components/src/components/charts/utils.ts
front-end-components/vite.config-dev.ts

Adds support for sorting data passed to `HorizontalBarChartWrapper`.
Adds support for sorting data passed to `HorizontalBarChartWrapper`.
All charts and tables should render by default as `value` descending. The sort may be overridden on a chart-by-chart basis. 
[AB#194908](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/194908) ([AB#185925](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/185925))

Added default sorting of `data` provided to `HorizontalBarChartWrapper`

---

web/Directory.Packages.props
web/README.md
web/src/EducationBenchmarking.Web/EducationBenchmarking.Web.csproj
web/src/EducationBenchmarking.Web/Infrastructure/Session/CosmosCacheSettings.cs
web/src/EducationBenchmarking.Web/Infrastructure/Session/CosmosClientFactory.cs
web/src/EducationBenchmarking.Web/Program.cs
web/src/EducationBenchmarking.Web/appsettings.Development.json
web/src/EducationBenchmarking.Web/packages.lock.json
web/terraform/README.md
web/terraform/cache.tf
web/terraform/main.tf
web/tests/EducationBenchmarking.Web.Integration.Tests/BenchmarkingWebAppClient.cs
web/tests/EducationBenchmarking.Web.Integration.Tests/packages.lock.json
web/tests/EducationBenchmarking.Web.Tests/packages.lock.json

4096 bytes cookie limits imposed by RFC therefore we need a better way to handle saving state for custom comparator sets.
Use ASP.NET Core session state backed by Cosmos.
**Requires configuration updates**
**_no backlog reference_**

Adds session cache

---

platform/src/abstractions/EducationBenchmarking.Platform.Domain/DataObjects/FinancialPlanDataObject.cs
platform/src/abstractions/EducationBenchmarking.Platform.Domain/Requests/FinancialPlanRequest.cs
platform/src/abstractions/EducationBenchmarking.Platform.Domain/Responses/FinancialPlan.cs
platform/src/apis/EducationBenchmarking.Platform.Api.Benchmark/Db/FinancialPlanDb.cs

part of the icfp journey - this is for the prepopulated data page
Story - [AB#191578](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/191578)
Task - [AB#191733](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/191733)
this PR adds:
- changes records for req/res/db to allow post and get of the financial plan
outstanding to complete ticket:
- display financial plan when it exists for the page
- validation on web app
N/A

api changes to allow post and get icfp prepopulated data plan

---

web/src/EducationBenchmarking.Web/Controllers/SchoolPlanningYearController.cs
web/src/EducationBenchmarking.Web/Views/SchoolPlanningYear/TotalExpenditure.cshtml
web/tests/EducationBenchmarking.Web.Integration.Tests/Paths.cs
web/tests/EducationBenchmarking.Web.Integration.Tests/WhenViewingSchoolPlanningTotalExpenditure.cs

[AB#195268](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/195268)
- Wired up back link in TotalExpenditure.cshtml
- Created integrated test: WhenViewingSchoolPlanningTotalExpenditure.cs
NA

Total Expenditure back link wired up and tests added

---

web/src/EducationBenchmarking.Web/Controllers/SchoolPlanningYearController.cs
web/src/EducationBenchmarking.Web/Domain/FinancialPlan.cs
web/src/EducationBenchmarking.Web/Infrastructure/Apis/Requests/PutFinancialPlanRequest.cs
web/src/EducationBenchmarking.Web/ViewModels/SchoolPlanViewModel.cs
web/src/EducationBenchmarking.Web/Views/SchoolPlanningYear/Index.cshtml

part of the icfp journey - this is for the prepopulated data page
Story - [AB#191578](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/191578)
Task - [AB#191733](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/191733)
This PR adds functionality to the pre populated data page to use a plan if it exists for display of radio button on page and post when required to not overwrite existing figures.
This PR in addition to others for this task 
- #157 
- #147
- #144 
should fulfil the AC for this task
N/A

post and get to display figures for icfp pre populate data page

---

web/tests/EducationBenchmarking.Web.A11yTests/PageBase.cs
web/tests/EducationBenchmarking.Web.A11yTests/Pages/School/FinancialPlanning/WhenViewingSchoolFinancialPlanning.cs
web/tests/EducationBenchmarking.Web.A11yTests/Pages/School/FinancialPlanning/WhenViewingSchoolFinancialPlanningHelp.cs
web/tests/EducationBenchmarking.Web.A11yTests/Pages/School/FinancialPlanning/WhenViewingSchoolFinancialPlanningPrePopulatedData.cs
web/tests/EducationBenchmarking.Web.A11yTests/Pages/School/FinancialPlanning/WhenViewingSchoolFinancialPlanningSelectYear.cs
web/tests/EducationBenchmarking.Web.A11yTests/Pages/School/FinancialPlanning/WhenViewingSchoolFinancialPlanningStart.cs
web/tests/EducationBenchmarking.Web.A11yTests/Pages/School/FinancialPlanning/WhenViewingSchoolFinancialPlanningTotalExpenditure.cs
web/tests/EducationBenchmarking.Web.A11yTests/Pages/School/FinancialPlanning/WhenViewingSchoolFinancialPlanningTotalIncome.cs
web/tests/EducationBenchmarking.Web.A11yTests/Pages/School/FinancialPlanning/WhenViewingSchoolFinancialPlanningTotalNumberTeachers.cs
web/tests/EducationBenchmarking.Web.A11yTests/Pages/School/FinancialPlanning/WhenViewingSchoolFinancialPlanningTotalTeacherCosts.cs
web/tests/EducationBenchmarking.Web.A11yTests/Pages/School/WhenViewingSchoolBenchmarkWorkforceData.cs
web/tests/EducationBenchmarking.Web.A11yTests/Pages/School/WhenViewingSchoolCompareYourCosts.cs
web/tests/EducationBenchmarking.Web.A11yTests/Pages/School/WhenViewingSchoolHome.cs
web/tests/EducationBenchmarking.Web.A11yTests/Pages/WhenViewingFindOrganisation.cs
web/tests/EducationBenchmarking.Web.A11yTests/Pages/WhenViewingServiceLanding.cs
web/tests/EducationBenchmarking.Web.A11yTests/WebDriver.cs

HTTP errors due to misconfigured A11y tests were being consumed by the application making debugging difficult.
Output HTTP responses to the `ITestOutputHelper` to give better visibility over what the A11y tests are doing.
Running the A11y tests locally should output all HTTP responses. 
- ~~[ ] Work items have been linked [(use AB#)](https://learn.microsoft.com/en-us/azure/devops/boards/github/link-to-from-github?view=azure-devops#use-ab-to-link-from-github-to-azure-boards-work-items)~~

Added `ITestOutputHelper` to A11y tests

---

web/tests/EducationBenchmarking.Web.A11yTests/Pages/Schools/FinancialPlanning/WhenViewingFinancialPlanningTotalEducationSupportStaffCosts.cs

[AB#192517](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/192517) ([AB#195882](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/195882))
added a11y tests for total education support staff costs page
none

added a11y tests for total educational support staff page

---

web/src/EducationBenchmarking.Web/package-lock.json
web/src/EducationBenchmarking.Web/package.json

V5.1 caused a11y and e2e test failures
Bump govuk frontend version
https://github.com/alphagov/govuk-frontend/issues/4762
N/A

bugfix: bump govuk-frontend version

---

web/tests/EducationBenchmarking.Web.A11yTests/Pages/Schools/FinancialPlanning/WhenViewingFinancialPlanningTimetableCycle.cs

Story - [AB#191586](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/191586)
Task - [AB#195880](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/195880)
Adds a11y tests for this CFP Timecycle page
N/A

adds a11y tests for timetable cycle page

---

front-end-components/package-lock.json
front-end-components/package.json
front-end-components/src/components/charts/line-chart/component.tsx
front-end-components/src/components/charts/stat/component.tsx
front-end-components/src/components/charts/types.tsx
front-end-components/src/components/charts/vertical-bar-chart/component.tsx
front-end-components/src/components/charts/vertical-bar-chart/types.tsx
front-end-components/src/hooks/useDownloadImage.ts
front-end-components/src/main.tsx

[AB#197110](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/197110)
Added ability to download chart (or any element, in fact) as an image. 
Sample usage in the `front-end-components` local dev server.

Download rechart as an image

---

web/src/EducationBenchmarking.Web/Constants/PageTitles.cs
web/src/EducationBenchmarking.Web/Controllers/SchoolPlanningCreatePlanController.cs
web/src/EducationBenchmarking.Web/Domain/FinancialPlanStages/OtherTeachingPeriodsConfirmStage.cs
web/src/EducationBenchmarking.Web/Validators/FinancialPlanStageValidator.cs
web/src/EducationBenchmarking.Web/Validators/FinancialPlanStages/OtherTeachingPeriodsConfirmStageValidator.cs
web/src/EducationBenchmarking.Web/Views/SchoolPlanningCreate/OtherTeachingPeriodsConfirm.cshtml

Story - [AB#191593](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/191593)
Tasks - [AB#198910](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/198910) & [AB#198911](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/198911)
Adds the confirmation page to proceed without adding other teaching periods to the plan for the cfp journey
adds validation if the users does not select yes or no
Hint text used rather than a warning text to match the style used in previous steps of the journey.
Title also changed from the ticket for the same reasons

adds other teaching periods confirmation page to cfp journey

---

web/src/Web.App/ViewModels/SchoolDeploymentPlanViewModel.cs

[AB#191678](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/191678) ([AB#200308](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/200308))
Fixes error in deployment plan when zero teaching assistant
Enter zero for all teaching assistances.

fix: error in deployment plan when zero teaching assistants

---

.gitignore
web/README.md
web/global.json
web/src/Web.App/appsettings.Development.json

This is a minor PR that adds the following 
* .gitgnore for local dev SQL scenarios
* An extra note about `dotnet user-secrets init` in README
* global.json added to ensure that the .NET version is contolled by the solution
* removed DfE settings.

Setting and Docs tidy up for Web frontend.

---

documentation/developers/session-data.md
web/README.md
web/src/Web.App/Extensions/WebApplicationBuilderExtensions.cs
web/src/Web.App/Infrastructure/Session/CosmosCacheSettings.cs
web/src/Web.App/Program.cs
web/terraform/main.tf

Remove local dev dependency on Azure resource - for local development memory cache can be used, instead of cosmos.
Always gives flexibility to use other provides per environment (i.e. in memory for non-production to reduce costs).

Remove dependency on cosmos for session data for local dev.

---

web/pipelines/steps-web-run-a11y-tests.yaml
web/pipelines/steps-web-run-e2e-tests.yaml

[AB#201673](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/201673)
fixed the directory path for e2e and a11y tests in pipeline
N/A

tech-debt/fixed directory issue 

---

.gitignore
front-end-components/src/components/charts/horizontal-bar-chart/component.tsx
front-end-components/src/components/charts/line-chart/component.tsx
front-end-components/src/components/charts/types.tsx
front-end-components/src/components/charts/vertical-bar-chart/component.tsx
front-end-components/src/composed/horizontal-bar-chart-wrapper/composed.tsx
front-end-components/src/hooks/useDownloadImage.ts

[AB#201449](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/201449) [AB#201366](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/201366)
Disabled 'Save as image' button when clicked, up until the file is downloaded.
https://github.com/DFE-Digital/education-benchmarking-and-insights/assets/3224486/45d619af-efd2-477f-a11c-25c242433f20
'Save as image' functionality is no quicker than previous implementation, but the user feedback is much improved.

Disabled 'Save as image' button on `<HorizontalBarChartWrapper>` during the image download process

---

web/src/Web.App/Domain/Deciles.cs
web/tests/Web.Tests/Domain/GivenValuesDecileHandler.cs
web/tests/Web.Tests/Domain/WhenCalculatingDecilesFindFromHighest.cs
web/tests/Web.Tests/Domain/WhenCalculatingDecilesFindFromLowest.cs
web/tests/Web.Tests/Web.Tests.csproj

Story - [AB#199507](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/199507)
Task - [AB#200093](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/200093)
Adds DecileFinder to calculate the deciles of a comparator set and return the decile of a given value that this value falls into the upper and lower bounds of. See story comments for the rules around this. 
Currently we have two implementations of the Find method, "from lowest" and "from highest" which is relevant if duplicate values are split across different deciles. If required we can build on this with other implementations in the future.
Check logic and whether this meets the requirements in this story.
This PR only adds the decile calculation to support the …

adds DecileFinder to calculate deciles for rag statuses

---

web/tests/Web.A11yTests/Pages/Schools/WhenViewingCommercialResources.cs

[AB#185942](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/185942)([AB#201985](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/201985))
a11y tests for the page
N/A

added a11y tests for when viewing commercial resources

---

front-end-components/src/views/find-organisation/partials/school-input.tsx
front-end-components/src/views/find-organisation/partials/trust-input.tsx
web/tests/Web.Integration.Tests/packages.lock.json

[AB#197543](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/197543)
Debounce `fetch` calls by 500ms when using auto complete inputs.
Fewer API calls should be made when using the auto complete input fields for School or Trust search. The results displayed should be from the final API call made, rather than a random historical request.

 Debounced autocomplete API calls for performance reasons

---

front-end-components/src/components/charts/school-tick/component.tsx
front-end-components/src/components/charts/school-tick/types.tsx
front-end-components/src/components/charts/table-chart/component.tsx
front-end-components/src/components/charts/table-chart/types.tsx
front-end-components/src/composed/horizontal-bar-chart-wrapper/composed.tsx
front-end-components/src/index.css

[AB#202503](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/202503) / [AB#203726](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/203726)
[AB#202520](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/202520) / [AB#203727](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/203727)
Disable tabbing into 'visually hidden' table.
Allow tabbing through school elements within charts.
When table visible, schools should be tabbed between.
When table not visible, tab focus should not enter hidden table.
When chart visible, schools should be tabbed between.

Accessibility improvements to Chart/Table view toggle

---

front-end-components/src/composed/historic-chart-composed/component.tsx
front-end-components/src/composed/historic-chart-composed/index.tsx
front-end-components/src/composed/historic-chart-composed/types.tsx
front-end-components/src/views/historic-data/partials/balance-section.tsx
front-end-components/src/views/historic-data/partials/income-section-direct-revenue.tsx
front-end-components/src/views/historic-data/partials/income-section-grant-funding.tsx
front-end-components/src/views/historic-data/partials/income-section-self-generated.tsx
front-end-components/src/views/historic-data/partials/income-section.tsx
front-end-components/src/views/historic-data/partials/spending-section-administrative-supplies.tsx
front-end-components/src/views/historic-data/partials/spending-section-catering-services.tsx
front-end-components/src/views/historic-data/partials/spending-section-educational-ict.tsx
front-end-components/src/views/historic-data/partials/spending-section-educational-supplies.tsx
front-end-components/src/views/historic-data/partials/spending-section-non-educational-staff-costs.tsx
front-end-components/src/views/historic-data/partials/spending-section-other.tsx
front-end-components/src/views/historic-data/partials/spending-section-premises-services.tsx
front-end-components/src/views/historic-data/partials/spending-section-teaching-costs.tsx
front-end-components/src/views/historic-data/partials/spending-section-utilities.tsx
front-end-components/src/views/historic-data/partials/spending-section.tsx
front-end-components/src/views/historic-data/partials/workforce-section.tsx

[AB#185907](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/185907) - [AB#202606](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/202606)
[AB#185882](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/185882) - [AB#202609](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/202609)
[AB#185900](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/185900) - [AB#202607](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/202607)
[AB#185893](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/185893) - …

composed component for Historic data to display either line chart or table

---

pipelines/common/destroy-terraform.yaml
pipelines/core-infrastructure/destroy.yaml
pipelines/destroy/release.yaml
pipelines/platform/destroy.yaml
pipelines/web/destroy.yaml

It was not possible to test the `Destroy` pipeline until it was merged to `main`. Herein are the related bug fixes.
Fixed dependency tree between pipeline jobs. Made job names unique. Fixed Terraform working directory. Destroyed Terraform state as the very last task.
Deploy a new feature branch, then run the Destroy pipeline to remove it again.

`Destroy` release pipeline fixes

---

documentation/developers/features/incomplete-data.md
front-end-components/src/components/charts/types.tsx
front-end-components/src/components/warning-banner/component.tsx
front-end-components/src/components/warning-banner/index.tsx
front-end-components/src/components/warning-banner/types.tsx
front-end-components/src/composed/comparison-chart-summary/composed.tsx
front-end-components/src/composed/comparison-chart-summary/types.tsx
front-end-components/src/composed/horizontal-bar-chart-wrapper/composed.tsx
front-end-components/src/contexts/contexts.tsx
front-end-components/src/main.tsx
front-end-components/src/services/types.tsx
front-end-components/src/views/compare-your-costs/view.tsx
front-end-components/src/views/compare-your-workforce/partials/auxiliary-staff.tsx
front-end-components/src/views/compare-your-workforce/partials/headcount.tsx
front-end-components/src/views/compare-your-workforce/partials/non-classroom-support.tsx
front-end-components/src/views/compare-your-workforce/partials/school-workforce.tsx
front-end-components/src/views/compare-your-workforce/partials/senior-leadership.tsx
front-end-components/src/views/compare-your-workforce/partials/teaching-assistants.tsx
front-end-components/src/views/compare-your-workforce/partials/total-teachers-qualified.tsx
front-end-components/src/views/compare-your-workforce/partials/total-teachers.tsx
web/src/Web.App/Domain/SchoolExpenditure.cs
web/src/Web.App/Domain/Workforce.cs
web/src/Web.App/ViewModels/SchoolSpendingViewModel.cs
web/src/Web.App/Views/SchoolSpending/Index.cshtml

[AB#201938](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/201938) - [AB#203886](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/203886)
[AB#205583](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/205583)
Adds a warning banner conditionally rendered on the presence of incomplete financial data in any of the schools being used as part of a comparison. For pages Spending and costs, Compare your costs and Workforce benchmark data.
Creates a React component to be used for a warning banner which is used in the composed components to render this warning for each chart/table.
Also updates the documentation for this feature.
This now fulfills the AC of …

incomplete data warning UI

---

core-infrastructure/terraform/acr.tf

This is a pre-requiste change to core infrastructure, to create an Azure Container Registry, to store the pipeline images that will be build
Proposes adding an azure contianer registry to the `core-infrastructure`.
Worth noting that I have enabled admin access on this, however I will be looking to turn that off once I can get the Managed Identity working with Azure Container Apps

feat: adding acr to core infrastructure

---

front-end-components/src/composed/historic-chart-composed/component.tsx
front-end-components/src/services/types.tsx
platform/src/abstractions/Platform.Domain/Responses/BalanceResponseModel.cs
platform/src/abstractions/Platform.Domain/Responses/ExpenditureResponseModel.cs
platform/src/abstractions/Platform.Domain/Responses/IncomeResponseModel.cs
platform/src/abstractions/Platform.Domain/Responses/WorkforceResponseModel.cs
web/src/Web.App/Domain/Balance.cs
web/src/Web.App/Domain/Expenditure.cs
web/src/Web.App/Domain/Income.cs
web/src/Web.App/Domain/Workforce.cs

[AB#185882](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/185882) ([AB#204740](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/204740))
[AB#185907](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/185907)
[AB#185900](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/185900)
[AB#185893](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/185893)
Ensures full years are shown both on axis and stat box
N/A

feat: adds full year display on history charts

---

pipelines/core-infrastructure/build.yaml
pipelines/front-end-components/build.yaml
pipelines/platform/build.yaml
pipelines/web/build.yaml

Updates main build pipelines to only set version numbering on main builds and skips on PR builds or non-main branches

chore: updates main build pipeline version numbering

---

web/src/Web.App/Views/FindOrganisation/Index.cshtml

[AB#207282](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/207282) [AB#206189](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/206189)
Warning message displayed to user on the above page if JavaScript is disabled, rather than showing a blank page.
Validate with/without JavaScript enabled.

Added `<noscript>` block to Find Organisation page

---

documentation/developers/features/find-organisation.md
front-end-components/package-lock.json
front-end-components/package.json
front-end-components/src/components/auto-complete/component.tsx
front-end-components/src/components/auto-complete/index.tsx
front-end-components/src/components/auto-complete/types.tsx
front-end-components/src/index.css
front-end-components/src/types/accessible-autocomplete.d.ts
front-end-components/src/views/find-organisation/partials/school-input.tsx
front-end-components/src/views/find-organisation/partials/trust-input.tsx
web/src/Web.App/Views/Shared/_Layout.cshtml
web/tests/Web.A11yTests/Pages/WhenViewingFindOrganisation.cs
web/tests/Web.E2ETests/Features/FindOrganisation.feature
web/tests/Web.E2ETests/Pages/FindOrganisationPage.cs
web/tests/Web.E2ETests/Selectors.cs
web/tests/Web.E2ETests/Steps/FindOrganisationSteps.cs

[AB#207281](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/207281) [AB#206189](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/206189)
Replace School and Trust search suggesters with `<AccessibleAutocomplete>` component from `alphagov`.
Functionally, this component should work exactly the same as the previous iteration. This includes the accessibility support.

School and Trust search/suggester refactor

---

front-end-components/src/components/charts/utils.test.ts
front-end-components/src/components/charts/utils.ts
front-end-components/src/composed/historic-chart-composed/component.tsx
front-end-components/src/composed/historic-chart-composed/types.tsx
front-end-components/src/views/historic-data/partials/census-section.tsx

[AB#207445](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/207445) [AB#207564](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/207564)
`Teachers with qualified teacher status` chart to include `%` on the y-axis where previously this was missing. Update `statValueFormatter()` to support percentage value units.
To validate locally, browse to `/school/123456/history#census` and find the `Teachers with qualified teacher status (%)` chart. The y-axis and 'stat' should include `%`.

Explicitly set `Teachers with qualified teacher status` to be a percentage value unit dimension

---

front-end-components/src/main.tsx
front-end-components/src/views/find-organisation/partials/la-input.tsx
front-end-components/src/views/find-organisation/partials/trust-input.tsx
front-end-components/src/views/find-organisation/types.tsx
front-end-components/src/views/find-organisation/view.tsx
web/src/Web.App/Controllers/FindOrganisationController.cs
web/src/Web.App/ViewModels/FindOrganisationViewModel.cs
web/src/Web.App/Views/FindOrganisation/Index.cshtml
web/tests/Web.A11yTests/Pages/WhenViewingFindOrganisation.cs

[AB#207649](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/207649) [AB#206189](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/206189)
Added the ability to search by Local Authority on the Find Organisation page.
LA search should function in a similar way to the School and Trust search. The suggestions on matching name or code should appear for the user to select from. Validation errors should be displayed in the same way. Once the form is successfully submitted, it is currently intentional that the home page is redirected to in lieu of the Local Authority landing page (see the `todo`).

Added Local Authority search to Find Organisation page

---

front-end-components/src/composed/historic-chart-composed/component.tsx

[AB#207445](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/207445) [AB#207564](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/207564)
Bug fix for Stat formatting after earlier formatting fix to historical charts. Ensures options correctly passed to formatter.

Fixed ResolvedStat formatting in historical chart composed

---

web/src/Web.App/Controllers/LocalAuthorityResourcesController.cs
web/src/Web.App/ViewModels/LocalAuthorityResourcesViewModel.cs
web/src/Web.App/Views/LocalAuthorityResources/index.cshtml

[AB#199506](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/199506) - [AB#203890](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/203890)
Adds model, view and controller for this page.
View model is currently unused. Controller currently just returns the view without any local authority data. Due to this EstablishmentHeading also is missing from the view. Backlink is also missing. I propose if there are no objections that these are all picked up as tech debt when the rest of the local authority journey is built next sprint. I will add a ticket for this after review.

adds local authority commercial resources page

---

front-end-components/src/composed/historic-chart-composed/component.tsx
front-end-components/src/composed/historic-chart-composed/types.tsx
front-end-components/src/views/historic-data/partials/census-section.tsx

Fixes incorrect column headers show on historic data - explicitly sets column header for qualified status and pupils on roll

bugfix: explicitly set column header

---

front-end-components/src/components/charts/utils.test.ts
front-end-components/src/components/charts/utils.ts
front-end-components/src/composed/horizontal-bar-chart-wrapper/composed.tsx
front-end-components/src/views/compare-your-costs/partials/accordion-sections/administrative-supplies.tsx
front-end-components/src/views/compare-your-costs/partials/accordion-sections/catering-staff-services.tsx
front-end-components/src/views/compare-your-costs/partials/accordion-sections/educational-ict.tsx
front-end-components/src/views/compare-your-costs/partials/accordion-sections/educational-supplies.tsx
front-end-components/src/views/compare-your-costs/partials/accordion-sections/non-educational-support-staff.tsx
front-end-components/src/views/compare-your-costs/partials/accordion-sections/other-costs.tsx
front-end-components/src/views/compare-your-costs/partials/accordion-sections/premises-staff-services.tsx
front-end-components/src/views/compare-your-costs/partials/accordion-sections/teaching-support-staff.tsx
front-end-components/src/views/compare-your-costs/partials/total-expenditure.tsx

[AB#207861](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/207861) [AB#207893](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/207893)
Added support for `%` `valueUnit` to the `shortValueFormatter()` and ensured `valueUnit` from `dimension` used instead of an overridden value at chart definition level.
Use the drop down on the Compare your costs page to change the dimension, and therefore the associated units for each chart to ensure the correct labels are shown.

Resolved percentage formatting in composed horizontal bar chart

---

core-infrastructure/terraform/storage.tf
pipelines/feature/release.yaml
platform/terraform/README.md
platform/terraform/databases.tf
platform/terraform/storage.tf

[AB#209017](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/209017) ([AB#209018](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/209018))
Disables shared access on threat, audit and vulnerability storage accounts. Also applies network ACL to threat and audit - public access still required for vulnerability to allow ADO pipeline to create the storage container.
N/A

chore: disables access key on threat, audit and vulnerability storage

---

pipelines/common/sync-terraform.yaml
pipelines/core-infrastructure/sync.yaml
pipelines/destroy/destroy.yaml
pipelines/platform/sync.yaml
pipelines/web/sync.yaml

[AB#208908](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/208908) [AB#208907](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/208907)
Add steps to the Destroy pipeline to 'sync' Terraform (i.e. re-`apply` in the correct order) before attempting the `destroy`, if the target resource group has yet to be destroyed. This will ensure that the target environment is in the expected state before destruction, particularly when it comes to `data` imports between modules, which was the original source of this problem.
This has been validated by successfully destroying the `d12` infrastructure using this branch as the source when running the pipeline. Previously this was failing due to missing `data` dependencies which were …

Apply latest Terraform changes to infrastructure before destroying them, to ensure state remains consistent

---

front-end-components/src/contexts/contexts.tsx
front-end-components/src/index.css
front-end-components/src/main.tsx
front-end-components/src/services/census-api.tsx
front-end-components/src/services/establishment-api.tsx
front-end-components/src/views/compare-your-census/partials/auxiliary-staff.tsx
front-end-components/src/views/compare-your-census/partials/headcount.tsx
front-end-components/src/views/compare-your-census/partials/non-classroom-support.tsx
front-end-components/src/views/compare-your-census/partials/school-workforce.tsx
front-end-components/src/views/compare-your-census/partials/senior-leadership.tsx
front-end-components/src/views/compare-your-census/partials/teaching-assistants.tsx
front-end-components/src/views/compare-your-census/partials/total-teachers-qualified.tsx
front-end-components/src/views/compare-your-census/partials/total-teachers.tsx
front-end-components/src/views/compare-your-census/types.tsx
front-end-components/src/views/compare-your-census/view.tsx
front-end-components/src/views/compare-your-costs/types.tsx
front-end-components/src/views/compare-your-costs/view.tsx
platform/src/apis/Platform.Api.Establishment/Db/SchoolDb.cs
platform/src/apis/Platform.Api.Establishment/SchoolsFunctions.cs
platform/tests/Platform.Tests/Establishment/WhenFunctionReceivesQuerySchoolsRequest.cs
web/src/Web.App/Controllers/Api/CensusProxyController.cs
web/src/Web.App/Controllers/Api/ProxyController.cs
web/src/Web.App/Controllers/LocalAuthorityCensusController.cs
web/src/Web.App/Controllers/LocalAuthorityComparisonController.cs
web/src/Web.App/ViewModels/LocalAuthorityCensusViewModel.cs
web/src/Web.App/ViewModels/LocalAuthorityComparisonViewModel.cs
web/src/Web.App/Views/LocalAuthorityCensus/Index.cshtml
web/src/Web.App/Views/LocalAuthorityComparison/Index.cshtml

[AB#200888](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/200888) ([AB#209181](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/209181))
Adds phase filters to cost comparison and census benchmarking pages for local authority
Front-end version will require bumping post PR merge

feat: add filters to local authority benchmarking pages

---

web/src/Web.App/Constants/BreadcrumbNodes.cs
web/src/Web.App/Constants/PageTitles.cs
web/src/Web.App/Controllers/SchoolCustomDataChangeController.cs
web/src/Web.App/Domain/CustomData.cs
web/src/Web.App/Services/CustomDataService.cs
web/src/Web.App/ViewModels/FinancialDataCustomDataViewModel.cs
web/src/Web.App/ViewModels/ICustomDataViewModel.cs
web/src/Web.App/ViewModels/NonFinancialDataCustomDataViewModel.cs
web/src/Web.App/ViewModels/SchoolCustomDataChangeViewModel.cs
web/src/Web.App/ViewModels/SchoolCustomDataViewModel.cs
web/src/Web.App/ViewModels/WorkforceDataCustomDataViewModel.cs
web/src/Web.App/Views/SchoolCustomDataChange/WorkforceData.cshtml
web/src/Web.App/Views/Shared/Components/ComparatorSetDetails/Default.cshtml
web/src/Web.App/Views/_ViewImports.cshtml

[AB#208016](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/208016) [AB#198080](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/198080)
Population of Custom Workforce Data form, including validation and managing of underlying values via state. Added feature-toggled link from Spending and Costs page.
Data capture should be possible from the Spending and Costs page through to the Workforce Custom Data page. This is the scope of this work item - the actual posting of the Custom Data persisted to session storage to the Orchestrator, and the UI around polling for job completion is covered as part of another story. Final value-dependent validations are also covered under a sibling ticket.

Workforce data Custom Data form

---

web/src/Web.App/Controllers/Api/CensusProxyController.cs
web/src/Web.App/Controllers/Api/ProxyController.cs
web/src/Web.App/Controllers/TrustCensusController.cs
web/src/Web.App/Controllers/TrustComparisonController.cs
web/src/Web.App/ViewModels/TrustCensusViewModel.cs
web/src/Web.App/ViewModels/TrustComparisonViewModel.cs
web/src/Web.App/Views/TrustCensus/Index.cshtml
web/src/Web.App/Views/TrustComparison/Index.cshtml

[AB#207740](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/207740) - [AB#209254](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/209254) & [AB#207739](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/207739) - [AB#209255](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/209255)
Adds filter by phase to comparison and census benchmarking pages for trusts.
N/A

adds phase filter for trust benchmarking

---

web/src/Web.App/Attributes/CompareDecimalValueAttribute.cs
web/src/Web.App/ViewModels/SchoolCustomDataChangeViewModel.cs
web/src/Web.App/ViewModels/WorkforceDataCustomDataViewModel.cs
web/src/Web.App/Views/SchoolCustomDataChange/FinancialData.cshtml
web/src/Web.App/Views/SchoolCustomDataChange/NonFinancialData.cshtml
web/src/Web.App/Views/SchoolCustomDataChange/WorkforceData.cshtml
web/src/Web.App/Views/SchoolCustomDataChange/_CustomDataEntryTableRow.cshtml
web/tests/Web.Tests/Attributes/GivenACompareDecimalValueAttribute.cs

[AB#209239](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/209239) [AB#198080](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/198080)
Additional validation rules on Workforce page. Client side calculation of Income/Expenditure totals on Financial Data page.
Vanilla JS is used for the client side calculations here within the Web project, so there is no need to copy over `front-end-components` to test locally. There is a case for refactoring this script into something that could get `gulp`ed from TypeScript in `AssetSrc` into `wwwroot` and then importing by filename in the view rather than polluting the latter with lots of JS. Happy to do so if the reviewer insists!

Custom Data 'Totals' calculations and additional validation rules

---

.gitignore
pipelines/web/steps/run-a11y-tests.yaml
platform/terraform/databases.tf
web/README.md
web/src/Web.App/Views/SchoolCustomDataChange/FinancialData.cshtml
web/src/Web.App/Views/SchoolCustomDataChange/_AccordionSection.cshtml
web/tests/Web.A11yTests/AuthPageBase.cs
web/tests/Web.A11yTests/Drivers/WebDriver.cs
web/tests/Web.A11yTests/PageBase.cs
web/tests/Web.A11yTests/Pages/Schools/CustomData/WhenViewingCustomData.cs
web/tests/Web.A11yTests/Pages/Schools/CustomData/WhenViewingCustomDataFinancialData.cs
web/tests/Web.A11yTests/Pages/Schools/CustomData/WhenViewingCustomDataNonFinancialData.cs
web/tests/Web.A11yTests/Pages/Schools/CustomData/WhenViewingCustomDataWorkforceData.cs
web/tests/Web.A11yTests/Pages/Schools/FinancialPlanning/WhenViewingFinancialPlanning.cs
web/tests/Web.A11yTests/TestConfiguration.cs
web/tests/Web.A11yTests/appsettings.json
web/tests/Web.Integration.Tests/TestExtensions.cs

[AB#208021](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/208021) [AB#198080](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/198080)
Accessibility tests for Custom Data pages, as well as a fix for ARIA tags on a GDS Accordion. New `AuthPageBase` that should be inherited from for a11y tests that require the user to be authenticated.
Added Traits to filter out authentication-dependent a11y tests during CI until suitable credentials are available. When running locally tests marked with the `Category` `CustomData` or `FinancialPlanning` will fail unless valid username/password set in configuration that corresponds to a pre-prod DSI account with correct organisational access. This is documented in the README and …

Accessibility tests for Custom Data

---

web/src/Web.App/AssetSrc/scss/_headlines.scss
web/src/Web.App/AssetSrc/scss/_variables.scss
web/src/Web.App/AssetSrc/scss/main.scss
web/src/Web.App/Domain/RagRating.cs
web/src/Web.App/Extensions/StringExtensions.cs
web/src/Web.App/ViewComponents/RagStack.cs
web/src/Web.App/ViewModels/Components/RagStackViewModel.cs
web/src/Web.App/ViewModels/TrustViewModel.cs
web/src/Web.App/Views/SchoolCustomDataChange/_AccordionSection.cshtml
web/src/Web.App/Views/SchoolCustomDataChange/_CustomDataEntryTable.cshtml
web/src/Web.App/Views/SchoolCustomDataChange/_CustomDataEntryTableRow.cshtml
web/src/Web.App/Views/Shared/Components/RagStack/Default.cshtml
web/src/Web.App/Views/Trust/Index.cshtml
web/src/Web.App/gulpfile.js
web/src/Web.App/package-lock.json
web/src/Web.App/package.json
web/tests/Web.Tests/Extensions/GivenAString.cs

[AB#210318](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/210318) [AB#188333](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/188333)
Replacement of cost categories on Trust home page with stacked RAGs for each, with link through to underlying cost item (once target page available). Updates to RAG and 'headline' colour palette.
Browse to any Trust home page to view the changes. The links for each cost category and the RAGs therein may be updated at a later stage.

Ordered cost categories on Trust home page and enhanced with stacked RAG 'chart's

---

web/src/Web.App/AssetSrc/scss/_headlines.scss
web/src/Web.App/AssetSrc/scss/main.scss
web/src/Web.App/ViewComponents/DataSourceViewComponent.cs
web/src/Web.App/ViewComponents/RagStack.cs
web/src/Web.App/ViewModels/Components/RagStackViewModel.cs
web/src/Web.App/ViewModels/RagViewModel.cs
web/src/Web.App/ViewModels/TrustViewModel.cs
web/src/Web.App/Views/Shared/Components/RagStack/Default.cshtml
web/src/Web.App/Views/Trust/Index.cshtml
web/src/Web.App/Views/Trust/_SchoolsSection.cshtml

[AB#210606](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/210606) [AB#188333](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/188333)
Added a list of schools - along with their RAG status  - grouped by `OverallPhase`, within the Trust.
Viewing a larger MAT such as `Oasis Community Learning` helps to give a better representation on what each RAG status corresponds to for each listed school, and how the `Weighting` was tweaked.

Listed schools by phase within Trust, ordered by RAG status

---

web/src/Web.App/Views/LocalAuthority/Index.cshtml
web/src/Web.App/Views/School/Index.cshtml
web/src/Web.App/Views/Trust/Index.cshtml
web/tests/Web.Integration.Tests/Pages/LocalAuthorities/WhenViewingHome.cs
web/tests/Web.Integration.Tests/Pages/Schools/WhenViewingHome.cs
web/tests/Web.Integration.Tests/Pages/Trusts/WhenViewingHome.cs

[AB#209775](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/209775) - [AB#210430](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/210430)
Add financial year information to school, trust and la homepages
Adds integration tests to confirm this behaviour.
Removed existing datasource component from trust homepage and replaced with one below the main heading on the page to align with the other pages. Happy to amend as required based on feedback on this PR.

adds year information to homepages

---

front-end-components/src/components/error-banner/component.tsx
front-end-components/src/components/error-banner/index.tsx
front-end-components/src/components/error-banner/types.tsx
front-end-components/src/composed/horizontal-bar-chart-wrapper/composed.tsx
front-end-components/src/contexts/contexts.tsx
front-end-components/src/views/compare-your-census/partials/auxiliary-staff.tsx
front-end-components/src/views/compare-your-census/partials/headcount.tsx
front-end-components/src/views/compare-your-census/partials/non-classroom-support.tsx
front-end-components/src/views/compare-your-census/partials/school-workforce.tsx
front-end-components/src/views/compare-your-census/partials/senior-leadership.tsx
front-end-components/src/views/compare-your-census/partials/teaching-assistants.tsx
front-end-components/src/views/compare-your-census/partials/total-teachers-qualified.tsx
front-end-components/src/views/compare-your-census/partials/total-teachers.tsx
front-end-components/src/views/compare-your-costs/view.tsx
web/src/Web.App/Extensions/DecimalExtensions.cs
web/src/Web.App/Services/FinanceService.cs
web/src/Web.App/ViewModels/SchoolViewModel.cs
web/src/Web.App/Views/School/Index.cshtml
web/src/Web.App/gulpfile.js

[AB#210710](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/210710) [AB#198080](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/198080)
Some schools listed under a Trust do not have a RAG status due to missing financial data. Drilling down to said schools were returning the `404` page, but it is a better user experience to instead return a partially populated page with a warning message. This is also the case for census data.
Load a trust such as [Oasis](https://localhost:7095/trust/5398529) and observe a number of schools with 'Status unavailable'. Drill down to those schools to view the newly added warning banner instead of an error page. Other schools should work as before.

When school financial or census data cannot be loaded, display appropriate warning rather than 404 page

---

web/src/Web.App/Views/Trust/_SchoolsSection.cshtml

[AB#188333](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/188333) [AB#211087](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/211087)
Updates school link to navigate to spending & costs rather than home page
N/A

fix: update school link to navigate to spending & costs

---

platform/src/apis/Platform.Api.Insight/Db/RatingsDb.cs
platform/src/apis/Platform.Api.Insight/RatingsFunctions.cs
web/src/Web.App/Constants/BreadcrumbNodes.cs
web/src/Web.App/Constants/PageTitles.cs
web/src/Web.App/Controllers/TrustSpendingController.cs
web/src/Web.App/ViewModels/RagViewModel.cs
web/src/Web.App/ViewModels/TrustSpendingViewModel.cs
web/src/Web.App/ViewModels/TrustViewModel.cs
web/src/Web.App/Views/Trust/Index.cshtml
web/src/Web.App/Views/TrustSpending/Index.cshtml

[AB#211007](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/211007) [AB#211012](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/211012) [AB#192288](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/192288)
New page to list all schools in a cost category / RAG status (as a first pass).
This intentionally omits some elements from the designs but will be iterated upon as part of the main story. Navigating from the Trust home page by Cost Category, or a RAG bar within that Cost Category will now display the details of which schools are in that Cost Category and, if applicable, RAG status. This required some API changes to be able to select only the RAGs of interest based on the …

List schools per cost category and RAG status in new Trust Spending Priorities page

---

web/src/Web.App/Services/SuggestService.cs
web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
web/tests/Web.Integration.Tests/Proxy/WhenRequestingSuggest.cs

AB#21005 - AB210708
Adds company number to the return of TrustSuggestions similar to how we append the address details for schools in SchoolSuggestions
Adds integration test for the suggest proxy end point
N/A

adds company number to trust suggester

---

front-end-components/src/components/charts/table-chart/component.tsx
front-end-components/src/components/charts/table-chart/types.tsx
front-end-components/src/components/charts/utils.test.ts
front-end-components/src/components/charts/utils.ts
front-end-components/src/composed/historic-chart-composed/component.tsx
front-end-components/src/composed/horizontal-bar-chart-wrapper/composed.tsx

[AB#210058](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/210058) - [AB#211769](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/211769)
Updates charts and tables to use the following number formatting
currency - to zero decimal places
percentage - to one decimal place
ratio - to two decimal places
adds fullValueFormatter for use in the tables to show the complete value but formatted as specified above
alters shortValueFormatter to show maximumFractionDigits as 2 as default and 1 only for percentage but preserves all other existing behaviour
N/A

changes to number formatting for charts and tables

---

core-infrastructure/terraform/databases.tf
web/src/Web.App/Controllers/TrustSpendingController.cs
web/src/Web.App/Domain/CostCategories.cs
web/src/Web.App/ViewModels/TrustSpendingViewModel.cs
web/src/Web.App/Views/Shared/Components/RagStack/Default.cshtml
web/src/Web.App/Views/Trust/Index.cshtml
web/src/Web.App/Views/TrustSpending/Index.cshtml

[AB#211011](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/211011) [AB#192288](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/192288)
Two new `<select>`s and `<form>` now present on Trust Spending page to allow the user to switch between categories and priorities without having to go back to the Trust home page.
Changing the filters should update the results displayed. Links through from the Trust homepage RAGs should continue to work as previously, with the filters pre-populated based on the query string.

Added filtering to Trust Spending view

---

front-end-components/index.html
front-end-components/src/constants.tsx
front-end-components/src/main.tsx
front-end-components/vite.config-dev.ts
web/src/Web.App/Constants/PageTitles.cs
web/src/Web.App/Constants/SessionKeys.cs
web/src/Web.App/Controllers/SchoolComparatorsCreateByController.cs
web/src/Web.App/Domain/ComparatorSet.cs
web/src/Web.App/Services/ComparatorSetService.cs
web/src/Web.App/ViewModels/SchoolComparatorsByNameViewModel.cs
web/src/Web.App/ViewModels/SchoolComparatorsChosenSchoolsViewModel.cs
web/src/Web.App/Views/SchoolComparatorsCreateBy/Name.cshtml
web/src/Web.App/Views/SchoolComparatorsCreateBy/_ChosenSchools.cshtml

[AB#212119](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/212119) [AB#210705](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/210705)
On the 'by name' journey for creating a user defined comparator set the user may use the school suggester to add and remove schools to ultimately be used for a custom comparator set.
To run locally, the `front-end-components` will first need to be built and copied over to `Web` in order for the independent `<SchoolInput>` component to be rendered as expected. A subsequent PR will bump the version of that dependency once this one has been merged.

 Added school suggester and add/remove to user defined comparator school list

---

platform/src/apis/Platform.Api.Benchmark/UserData/UserDataFunctions.cs
platform/src/apis/Platform.Api.Benchmark/UserData/UserDataService.cs
web/src/Web.App/AssetSrc/scss/main.scss
web/src/Web.App/Constants/PageTitles.cs
web/src/Web.App/Controllers/Api/UserDataProxyController.cs
web/src/Web.App/Controllers/SchoolComparatorsCreateByController.cs
web/src/Web.App/Controllers/SchoolController.cs
web/src/Web.App/Extensions/ClaimsPrincipalExtensions.cs
web/src/Web.App/Infrastructure/Apis/ComparatorSetApi.cs
web/src/Web.App/Infrastructure/Apis/Requests/PutComparatorSetUserDefinedRequest.cs
web/src/Web.App/ViewModels/SchoolComparatorsChosenSchoolsViewModel.cs
web/src/Web.App/ViewModels/SchoolComparatorsSubmittedViewModel.cs
web/src/Web.App/ViewModels/SchoolViewModel.cs
web/src/Web.App/Views/School/Index.cshtml
web/src/Web.App/Views/SchoolComparatorsCreateBy/Index.cshtml
web/src/Web.App/Views/SchoolComparatorsCreateBy/Submit.cshtml
web/src/Web.App/Views/SchoolComparatorsCreateBy/_ChosenSchools.cshtml

[AB#212120](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/212120) [AB#210705](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/210705)
Submit pending user defined comparator set to data pipeline and poll until corresponding user data entry completes or fails.
Running locally the user data entry never moves out of the `pending` state, so this will need to be done manually to complete testing of the journey end-to-end. e.g.:
```sql
update [UserData] set [Status] = 'complete' where id = '<guid>'
```

Submit pending user defined comparator set and poll on result

---

data-pipeline/src/pipeline/comparator_sets.py
data-pipeline/tests/unit/comparator_sets/conftest.py
data-pipeline/tests/unit/comparator_sets/test_top_set_urns.py

Include PFI/Boarding status in comparator-set calculation:
[AB#209994](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/209994)
- update to the `comparator_sets.select_top_set…` function to accept and include PFI and Boarding values as part of the "top" matches criteria.
- some related refactoring.
- once-over with `make lint`.
As discussed: the initial "60" selection should contain on those orgs. with matching PFI/Boarding statuses, prior to region restrictions.
If this selection falls short of the "30" required, this is supplemented from the _original_ list (i.e. pre-PFI-Boarding restrictions).

#209994/boarding pfi group comparator sets

---

front-end-components/index.html
front-end-components/src/main.tsx
front-end-components/src/views/find-organisation/partials/la-input.tsx
front-end-components/src/views/find-organisation/types.tsx
platform/src/apis/Platform.Api.Establishment/LocalAuthorities/LocalAuthoritiesFunctions.cs
platform/src/apis/Platform.Api.Establishment/LocalAuthorities/LocalAuthoritiesService.cs
platform/tests/Platform.Tests/Establishment/WhenFunctionReceivesSuggestLocalAuthoritiesRequest.cs
web/src/Web.App/Controllers/Api/SuggestProxyController.cs
web/src/Web.App/Controllers/SchoolComparatorsCreateByController.cs
web/src/Web.App/Infrastructure/Apis/EstablishmentApi.cs
web/src/Web.App/Infrastructure/Apis/Requests/PostSchoolComparatorsRequest.cs
web/src/Web.App/Services/SuggestService.cs
web/src/Web.App/ViewModels/UserDefinedCharacteristicViewModel.cs
web/src/Web.App/Views/SchoolComparatorsCreateBy/Characteristic.cshtml
web/src/Web.App/Views/SchoolComparatorsCreateBy/_LocalAuthorities.cshtml
web/src/Web.App/package-lock.json
web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs

[AB#212642](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/212642)
When 'Choose' option is selected for LAs, it is now possible to add/remove LAs rather than select a single entry. Previous validation rules should still be upheld, and all LAs should be posted to the comparator set builder API. Previously selected LAs should be excluded from the suggester.
This has a dependency on `front-end-components` and so to test locally, the latest build will need to be copied to `Web`. A subsequent commit will pull the new version, once published. There are some known usability issues here due to the avoidance of use of any client script to get this working - most noticeably the need to scroll back down to the LA element after one has been added/removed.

Allow multiple LAs to be selected on Characteristic builder

---

web/src/Web.App/Constants/SessionKeys.cs
web/src/Web.App/Controllers/SchoolComparatorsController.cs
web/src/Web.App/Controllers/SchoolComparatorsCreateByController.cs
web/src/Web.App/Services/ComparatorSetService.cs
web/src/Web.App/ViewModels/SchoolComparatorsPreviewViewModel.cs
web/src/Web.App/Views/SchoolComparatorsCreateBy/Preview.cshtml
web/src/Web.App/package-lock.json

[AB#212851](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/212851) [AB#210705](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/210705)
New session storage key for the above to prevent the need to use query string or temp data to manage characteristics for a particular URN. Cleared down once user defined comparator set is submitted.

Replaced `TempData` with session storage for `UserDefinedCharacteristicViewModel` persistence

---

pipelines/web/steps/run-a11y-tests.yaml
web/README.md
web/src/Web.App/Views/SchoolComparatorsCreateBy/Characteristic.cshtml
web/src/Web.App/Views/SchoolComparatorsCreateBy/Preview.cshtml
web/src/Web.App/Views/SchoolComparatorsCreateBy/_ChosenSchools.cshtml
web/tests/Web.A11yTests/AuthPageBase.cs
web/tests/Web.A11yTests/Drivers/WebDriver.cs
web/tests/Web.A11yTests/Pages/Schools/Comparators/WhenViewingComparators.cs
web/tests/Web.A11yTests/Pages/Schools/Comparators/WhenViewingComparatorsBy.cs
web/tests/Web.A11yTests/Pages/Schools/Comparators/WhenViewingComparatorsByCharacteristic.cs
web/tests/Web.A11yTests/Pages/Schools/Comparators/WhenViewingComparatorsByName.cs
web/tests/Web.A11yTests/Pages/Schools/Comparators/WhenViewingComparatorsPreview.cs
web/tests/Web.A11yTests/Pages/Schools/Comparators/WhenViewingComparatorsSubmit.cs

[AB#212326](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/212326) [AB#210705](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/210705)
Added missing accessibility tests. Fixed test authentication to select first of multiple DSI organisations. Removed category filter from pipeline.

A11y tests for User Defined comparator sets

---

pipelines/platform/deployment.yaml
platform/Platform.sln
platform/src/apis/Platform.Orchestrator/Constants.cs
platform/src/apis/Platform.UserDataCleanUp/CleanUpFunctions.cs
platform/src/apis/Platform.UserDataCleanUp/Constants.cs
platform/src/apis/Platform.UserDataCleanUp/PipelineDb.cs
platform/src/apis/Platform.UserDataCleanUp/Platform.UserDataCleanUp.csproj
platform/src/apis/Platform.UserDataCleanUp/Properties/launchSettings.json
platform/src/apis/Platform.UserDataCleanUp/Startup.cs
platform/src/apis/Platform.UserDataCleanUp/host.json
platform/src/apis/Platform.UserDataCleanUp/packages.lock.json
platform/terraform/README.md
platform/terraform/functions.tf

[AB#210705](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/210705)
Adds function app to clean up any remove or expired user defined comparator sets / custom data.

feat: adds user data clean up func app

---

web/src/Web.App/Constants/BreadcrumbNodes.cs
web/src/Web.App/Constants/PageTitles.cs
web/src/Web.App/Controllers/TrustComparatorsController.cs
web/src/Web.App/Controllers/TrustComparatorsCreateByController.cs
web/src/Web.App/ViewModels/TrustComparatorsViewModel.cs
web/src/Web.App/Views/TrustComparatorsCreateBy/Index.cshtml
web/tests/Web.Integration.Tests/Pages/Trusts/Comparators/WhenViewingComparatorsCreateBy.cs
web/tests/Web.Integration.Tests/Paths.cs

[AB#213056](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/213056)
Allow the user a choice between 'by name' or 'by characteristic' for trust-to-trust comparison.
Requires DSI login to be able to test. Currently no other page links to this new one, either.

Trust comparator set choice page

---

data-pipeline/src/pipeline/main.py
data-pipeline/src/pipeline/rag.py

relates #212505
[AB#212505](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/212505)
Changes required to accommodate user-defined comparator sets.
- initial check in `main.py` as to whether the incoming message holds a user-defined comparator set;
- if so, skip pre-processing;
- run `run_user_defined_rag()` (a variant of the existing `run_compute_rag()` and `compute_rag_for()` functions);
- run `compute_user_defined_rag()` (similar to existing `compute_rag()`, less the comparator-set derivation);
- write to blob-storage;
- write to database.
- have I correctly understood the pipeline flow?
- are there any specific requirements around the blob-storage/database keys?

feat: user-defined comparator sets

---

data-pipeline/src/pipeline/main.py
data-pipeline/src/pipeline/rag.py
data-pipeline/tests/unit/rag/test_user_defined_comparator_sets.py

- use a `list` for restricting the data to just the comparator set.
- `DataFrame` [should work](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.isin.html) but would require more coercing to the right structure.
- add a test to validate the above **_but_** `skip()` this for now due to the requirement for a representative data-set.
relates #212505

fix: correct comparator-set URN restriction

---

web/src/Web.App/Constants/PageTitles.cs
web/src/Web.App/Constants/SessionKeys.cs
web/src/Web.App/Controllers/Api/UserDataProxyController.cs
web/src/Web.App/Controllers/SchoolComparatorsCreateByController.cs
web/src/Web.App/Controllers/TrustComparatorsCreateByController.cs
web/src/Web.App/Controllers/TrustController.cs
web/src/Web.App/Domain/TrustComparatorSet.cs
web/src/Web.App/Infrastructure/Apis/ComparatorSetApi.cs
web/src/Web.App/Infrastructure/Apis/Requests/PutComparatorSetUserDefinedRequest.cs
web/src/Web.App/Services/SchoolComparatorSetService.cs
web/src/Web.App/Services/TrustComparatorSetService.cs
web/src/Web.App/ViewModels/TrustComparatorsSubmittedViewModel.cs
web/src/Web.App/ViewModels/TrustViewModel.cs
web/src/Web.App/Views/Trust/Index.cshtml
web/src/Web.App/Views/TrustComparatorsCreateBy/Submit.cshtml

[AB#213058](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/213058) [AB#213062](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/213062) [AB#206777](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/206777)
Submit the selected Trusts by company number for use as a new user defined comparator set. Display spinner and poll until job complete. Display banner with result of request on Trust home page.
Process should now work end-to-end, although there is no entry point yet defined. Resultant comparator trusts will be added and managed as part of future work.

Trust user-defined comparator set submission, polling and result display

---

web/src/Web.App/Constants/PageTitles.cs
web/src/Web.App/Controllers/TrustComparatorsController.cs
web/src/Web.App/Services/UserDataService.cs
web/src/Web.App/ViewModels/TrustComparatorsViewModel.cs
web/src/Web.App/Views/Shared/_Layout.cshtml
web/src/Web.App/Views/Trust/Index.cshtml
web/src/Web.App/Views/TrustComparators/UserDefined.cshtml
web/src/Web.App/Views/TrustComparatorsCreateBy/_ChosenTrusts.cshtml

[AB#213444](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/213444) [AB#206777](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/206777)
Added page to view current user-defined set of Trusts (excluding current one). Includes link to edit existing set and then re-submit if any changes required.
Link to view custom set is currently only visible from the Trust homepage after a custom set has been submitted.

View set of user-defined Trusts

---

web/src/Web.App/Constants/PageTitles.cs
web/src/Web.App/Controllers/TrustComparatorsController.cs
web/src/Web.App/Views/Trust/Index.cshtml
web/src/Web.App/Views/TrustComparators/Revert.cshtml
web/src/Web.App/Views/TrustComparatorsCreateBy/Name.cshtml

[AB#213059](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/213059) [AB#206777](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/206777)
Allow user defined Trust comparators to be reverted.
~~Currently this reverts back to the 'previous' custom set rather than the defaults in some scenarios, unless this is the only custom set still active for the user/trust. To be investigated in [AB#213453](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/213453) at a later date.~~

Revert user defined Trust comparator set

---

web/src/Web.App/Constants/PageTitles.cs
web/src/Web.App/Controllers/TrustComparatorsController.cs
web/src/Web.App/Controllers/TrustController.cs
web/src/Web.App/ViewModels/TrustToTrustViewModel.cs
web/src/Web.App/ViewModels/TrustViewModel.cs
web/src/Web.App/Views/Shared/Components/TrustFinanceTools/Default.cshtml
web/src/Web.App/Views/Trust/Index.cshtml
web/src/Web.App/Views/TrustComparators/Index.cshtml
web/src/Web.App/Views/TrustComparatorsCreateBy/Submit.cshtml
web/tests/Web.A11yTests/Pages/Trust/Comparators/WhenViewingComparators.cs
web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
web/tests/Web.Integration.Tests/Pages/Trusts/Comparators/WhenViewingComparators.cs

[AB#213657](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/213657) [AB#207092](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/207092)
Wired up Trust home page link to holding trust-to-trust comparison page. If no user defined comparison set, redirect user to the beginning of that journey.
Content for trust-to-trust landing page will come next, but this PR should enable the create user defined set end-to-end.

Skeleton Trust-to-trust landing page

---

platform/src/apis/Platform.Api.Insight/MetricRagRatings/MetricRagRatingParameters.cs
platform/src/apis/Platform.Api.Insight/MetricRagRatings/MetricRagRatingsFunctions.cs
web/src/Web.App/Infrastructure/Apis/Insight/MetricRagRatingApi.cs

[AB#192482](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/192482) ([AB#214351](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/214351))
Adds end-point for custom RAG data
N/A

feat: adds custom data end point for metric rag

---

web/src/Web.App/Controllers/SchoolCensusController.cs
web/src/Web.App/Controllers/SchoolComparisonController.cs
web/src/Web.App/ViewComponents/CustomDataBannerViewComponent.cs
web/src/Web.App/ViewModels/Components/CustomDataBannerViewModel.cs
web/src/Web.App/Views/SchoolCensus/CustomData.cshtml
web/src/Web.App/Views/SchoolComparison/CustomData.cshtml
web/src/Web.App/Views/Shared/Components/CustomDataBanner/Default.cshtml

[AB#192482](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/192482) - [AB#214243](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/214243)
This PR updates the custom data comparison and benchmark workforce pages to use the front end component to display the respective charts and pass the custom data id in the dataset. In a future PR front end components will be updated to use this to pass to the proxy api end points so the actual custom data can be used for these charts.

adds custom data banner, updates census and comparison pages

---

front-end-components/src/contexts/contexts.tsx
front-end-components/src/main.tsx
front-end-components/src/services/census-api.tsx
front-end-components/src/services/expenditure-api.tsx
front-end-components/src/views/compare-your-census/partials/auxiliary-staff.tsx
front-end-components/src/views/compare-your-census/partials/headcount.tsx
front-end-components/src/views/compare-your-census/partials/non-classroom-support.tsx
front-end-components/src/views/compare-your-census/partials/school-workforce.tsx
front-end-components/src/views/compare-your-census/partials/senior-leadership.tsx
front-end-components/src/views/compare-your-census/partials/teaching-assistants.tsx
front-end-components/src/views/compare-your-census/partials/total-teachers-qualified.tsx
front-end-components/src/views/compare-your-census/partials/total-teachers.tsx
front-end-components/src/views/compare-your-census/types.tsx
front-end-components/src/views/compare-your-census/view.tsx
front-end-components/src/views/compare-your-costs/partials/accordion-sections/administrative-supplies.tsx
front-end-components/src/views/compare-your-costs/partials/accordion-sections/catering-staff-services.tsx
front-end-components/src/views/compare-your-costs/partials/accordion-sections/educational-ict.tsx
front-end-components/src/views/compare-your-costs/partials/accordion-sections/educational-supplies.tsx
front-end-components/src/views/compare-your-costs/partials/accordion-sections/non-educational-support-staff.tsx
front-end-components/src/views/compare-your-costs/partials/accordion-sections/other-costs.tsx
front-end-components/src/views/compare-your-costs/partials/accordion-sections/premises-staff-services.tsx
front-end-components/src/views/compare-your-costs/partials/accordion-sections/teaching-support-staff.tsx
front-end-components/src/views/compare-your-costs/partials/accordion-sections/utilities.tsx
front-end-components/src/views/compare-your-costs/types.tsx
front-end-components/src/views/compare-your-costs/view.tsx

[AB#192482](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/192482) - [AB#214246](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/214246)
Updates to front-end components so that the customDataId prop is passed to the proxy api end points, expenditure and census. A future update will use this to generate the custom data for the charts for these components
N/A

pass customDataId as param to proxy end points

---

web/Web.sln.DotSettings
web/src/Web.App/AssetSrc/scss/main.scss
web/src/Web.App/Controllers/TrustForecastController.cs
web/src/Web.App/ViewModels/TrustForecastViewModel.cs
web/src/Web.App/Views/TrustForecast/Index.cshtml
web/tests/Web.Integration.Tests/Pages/Trusts/WhenViewingForecast.cs

[AB#214517](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/214517) [AB#188391](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/188391)
Top-most priority banner on Trust forecast page depending on state of incoming data (pending).
To test the different states, `TrustForecastViewModel` may be manually modified to set each of the r/a/g props to `true`.

Added priority guidance panel to Trust forecast and risks page, pending data to set various states

---

web/Web.sln.DotSettings
web/src/Web.App/Controllers/Api/ForecastProxyController.cs
web/src/Web.App/Controllers/TrustForecastController.cs
web/src/Web.App/Domain/Establishment/Trust.cs
web/src/Web.App/Domain/Insight/Balance.cs
web/src/Web.App/Extensions/WebApplicationBuilderExtensions.cs
web/src/Web.App/Infrastructure/Apis/Insight/BalanceApi.cs
web/src/Web.App/ViewModels/TrustForecastViewModel.cs
web/tests/Web.A11yTests/Pages/Trust/WhenViewingForecast.cs
web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
web/tests/Web.Integration.Tests/Paths.cs

[AB#214181](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/214181) AB#188397
Stubbed API calls to BFR and BFR metrics based on the latest database schema. To be wired up properly as part of future tickets. BFR endpoint called via client for rendering chart/table. BFR metric endpoint called from Forecast controller.
This will be tweaked when the BFR schema is stable, but for now these models will suffice to continue with the front end build.

Added API stubs for BFR and BFR metrics endpoints

---

web/src/Web.App/ViewModels/TrustForecastMetricsViewModel.cs
web/src/Web.App/ViewModels/TrustForecastViewModel.cs
web/src/Web.App/Views/TrustForecast/Index.cshtml
web/src/Web.App/Views/TrustForecast/_Metrics.cshtml
web/src/Web.App/Views/TrustForecast/_RiskSummary.cshtml
web/tests/Web.Integration.Tests/Pages/Trusts/WhenViewingForecast.cs

[AB#214182](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/214182) [AB#188391](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/188391)
Added partial to support rendering of BFR metrics.
Once schema and realistic data is available it is likely the `Metric` values will need to be managed within the application in order to allow the mixed-value row for 'Self-generated income vs grant funding' to be added instead of the two distinct rows that are currently stubbed out.

Wired up BFR metrics table

---

front-end-components/index.html
front-end-components/src/components/charts/chart-link/component.tsx
front-end-components/src/components/charts/chart-link/index.tsx
front-end-components/src/components/charts/chart-link/types.tsx
front-end-components/src/components/charts/establishment-tick/component.tsx
web/src/Web.App/Views/Shared/Components/RagStack/Default.cshtml
web/src/Web.App/package-lock.json
web/tests/Web.A11yTests/Pages/Trust/Comparators/WhenViewingComparators.cs
web/tests/Web.A11yTests/Pages/Trust/WhenViewingHome.cs

[AB#215031](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/215031) [AB#214915](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/214915)
Fixes to some `<a>` elements when children of `<svg>` for accessibility tests.

Use `xlink:href` instead of `href` in `<a>` within `<svg>` elements

---

web/src/Web.App/Controllers/SchoolController.cs
web/src/Web.App/Controllers/SchoolSpendingComparisonController.cs
web/src/Web.App/Controllers/SchoolSpendingController.cs
web/src/Web.App/ViewModels/SchoolSpendingComparisonViewModel.cs
web/src/Web.App/Views/SchoolSpendingComparison/Index.cshtml
web/src/Web.App/Views/SchoolSpendingComparison/_CategoryList.cshtml
web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
web/tests/Web.Integration.Tests/Pages/Schools/CustomData/WhenViewingCustomDataSpendingComparison.cs
web/tests/Web.Integration.Tests/Paths.cs

[AB#192482](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/192482) - [AB#214247](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/214247) [AB#214250](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/214250)
adds spending comparison page for the custom page (side by side comparison original and custom rag rating)
adds integration tests for this page
also adds SchoolAuthorization to the pages in this story where missing.
N/A

adds custom data spending comparison page

---

core-infrastructure/src/db/Core.Database/Scripts/045-CreateBudgetForecastTable.sql
platform/src/apis/Platform.Api.Insight/BudgetForecast/BudgetForecastFunctions.cs
platform/src/apis/Platform.Api.Insight/BudgetForecast/BudgetForecastModel.cs
platform/src/apis/Platform.Api.Insight/BudgetForecast/BudgetForecastResponse.cs
platform/src/apis/Platform.Api.Insight/BudgetForecast/BudgetForecastService.cs
platform/tests/Platform.Tests/Insight/BudgetForecast/WhenBudgetForecastReturnsResponseFactoryCreatesResponse.cs

[AB#215136](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/215136) [AB#188391](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/188391)
Calculated actual and forecast RR and pupil count based on agreed logic (see below). Re-defined table schema for source data based on what will be outputted from data pipeline.
Unit tests should all pass to cover the new functionality. Downstream consumers will need to be updated at a future date but nothing will break due to stubs still being in use.

Redefined `dbo.BudgetForecastReturn` table and managed mapping to expected API response in code

---

data-pipeline/src/pipeline/comparator_sets.py

This was causing all but the first of each phase type to be skipped when generating comparator-sets.
The resulting `'float' object has no attribute 'tolist'` error was the result of trying to apply `.tolist()` to a column for which a comparator-set hadn't been generated (i.e. once processed, it's an `array`; unprocessed, it's a `float`).

fix: remove extraneous break

---

web/src/Web.App/Controllers/SchoolSpendingController.cs
web/src/Web.App/Views/SchoolSpending/CustomData.cshtml
web/tests/Web.Integration.Tests/Pages/Schools/CustomData/WhenViewingCustomDataSpendingComparison.cs

[AB#192482](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/192482) - [AB#214248](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/214248)
Adds spending priorities (spending and costs) page to the custom data journey
Note currently endpoints are not returning the custom data for this page to be functional.
Integration tests to follow on a future PR

feat: adds custom data spending page

---

platform/src/abstractions/Platform.Functions/PipelineMessage.cs
platform/src/apis/Platform.Api.Benchmark/CustomData/CustomDataRequest.cs
platform/src/apis/Platform.Api.Benchmark/CustomData/CustomDataService.cs
web/Web.sln.DotSettings
web/src/Web.App/Controllers/SchoolCustomDataChangeController.cs
web/src/Web.App/Domain/Benchmark/CustomDataSchool.cs
web/src/Web.App/Services/CustomDataService.cs
web/src/Web.App/ViewModels/SchoolCustomDataChangeViewModel.cs
web/src/Web.App/Views/SchoolCustomDataChange/_CustomDataEntryTable.cshtml
web/src/Web.App/Views/SchoolCustomDataChange/_CustomDataEntryTableRow.cshtml
web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
web/tests/Web.Integration.Tests/Pages/Schools/CustomData/WhenViewingCustomDataFinancialData.cs
web/tests/Web.Integration.Tests/Pages/Schools/CustomData/WhenViewingCustomDataNonFinancialData.cs

[AB#215864](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/215864) [AB#192482](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/192482)
Allow user to 'edit' previously submitted custom data for a school.
Submit custom data for a school, then go back and attempt to submit again to see the previous values pre-populated until the new journey is started.

Pre-populated previous Custom Data values when defining new set of data for school

---

web/tests/Web.A11yTests/AuthPageBase.cs

removing saving of auth state
a11y tests were saving auth state which was not helpful. removing it for now. 
Include any useful information needed to review this change. Include any dependencies that are required for this change. 
~~- [ ] Your branch has been rebased onto main~~

removed saving of auth state

---

web/src/Web.App/Constants/PageTitles.cs
web/src/Web.App/Controllers/Api/UserDataProxyController.cs
web/src/Web.App/Controllers/SchoolCustomDataChangeController.cs
web/src/Web.App/ViewModels/SchoolCustomDataSubmittedViewModel.cs
web/src/Web.App/Views/SchoolCustomDataChange/Submit.cshtml
web/tests/Web.Integration.Tests/Pages/Schools/CustomData/WhenViewingCustomDataWorkforceData.cs
web/tests/Web.Integration.Tests/Paths.cs

[AB#192482](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/192482)- [AB#215344](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/215344)
Adds a submit page to the end of the create custom data journey. 
Adds new proxy end point to return UserData which this page will poll until a status other than pending is received.
Updates integration tests for submit form for the previous page to mock UserData CustomDataSchool
Guard clauses on customised data page will be updated to also check this status rather than just the existence of a custom data id in a following PR and the orchestrator will also be updated in a future PR to return a status of failed rather than complete on any errors while the pipeline creates this …

feat: adds loading submit page to create custom data journey

---

web/src/Web.App/Controllers/SchoolCensusController.cs
web/src/Web.App/Controllers/SchoolComparisonController.cs
web/src/Web.App/Controllers/SchoolController.cs
web/src/Web.App/Controllers/SchoolSpendingComparisonController.cs
web/src/Web.App/Controllers/SchoolSpendingController.cs
web/tests/Web.Integration.Tests/Pages/Schools/CustomData/WhenViewingCustomDataSpendingComparison.cs

[AB#192482](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/192482) - [AB#215862](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/215862)
Adds guard clauses for all customised data pages to also also check the status of UserData not just the custom data id
Updates setup in integration tests for `WhenViewingCustomDataSpendingComparison` to include the status.
N/A

chore: updates guard clauses for customised data pages

---

web/src/Web.App/Controllers/SchoolCustomDataChangeController.cs
web/src/Web.App/Controllers/SchoolCustomDataController.cs
web/src/Web.App/Services/CustomDataService.cs

AB#216321 [AB#192482](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/192482)
Call API to delete previous custom data when saving new so that there is only ever one active instance per user per school.

Remove previous custom data for a school when creating new set

---

core-infrastructure/terraform/README.md
core-infrastructure/terraform/databases.tf
core-infrastructure/terraform/provider.tf
pipelines/feature/release.yaml

[AB#216465](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/216465) [AB#186287](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/186287)
There isn't `azurerm` support for this feature, so `azapi` needs to be [used](https://github.com/hashicorp/terraform-provider-azurerm/issues/7665#issuecomment-1854459160) instead. Incentive to configure automatic tuning is to try and resolve performance issues with the E2E tests.
Validated by pushing out to the `d14` feature environment.

Define database automatic tuning using `azapi` provider

---

web/src/Web.App/ViewModels/TrustSpendingViewModel.cs
web/src/Web.App/Views/TrustSpending/Index.cshtml
web/src/Web.App/Views/TrustSpending/_PriorityStatus.cshtml
web/src/Web.App/Views/TrustSpending/_PriorityTable.cshtml

[AB#216436](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/216436) [AB#192288](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/192288)
Otherwise stick to original behaviour and order by selected Category/ies first, then by Status.
Switch between all categories or specific one(s) using the drop down on the left of the Trust spending-and-costs page to observe the different result grouping. New ticket added for the missing integration tests here.

When no categories chosen on Trust spending priorities order by Status first, then by category

---

pipelines/web/build.yaml

need to fix a11y tests to not leave any data and more observation for stable e2e tests run
Reverts DFE-Digital/education-benchmarking-and-insights#1033

Revert "reenable a11y tests in pipeline"

---

front-end-components/index.html
front-end-components/src/index.css
platform/src/apis/Platform.Api.Insight/BudgetForecast/BudgetForecastResponse.cs
platform/tests/Platform.Tests/Insight/BudgetForecast/WhenBudgetForecastReturnsResponseFactoryCreatesResponse.cs
web/src/Web.App/Infrastructure/Apis/Insight/BudgetForecastApi.cs

[AB#215312](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/215312) [AB#188391](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/188391)
Wire up to API to get data feeding through from the now-populated source tables. Sample populated content is below:
Additional wiring up of the metric categories will also be required once these have been properly defined.
View a Trust Forecast page.

Wired up Web to Budget Forecast API

---

web/src/Web.App/Controllers/SchoolController.cs
web/src/Web.App/ViewModels/SchoolViewModel.cs
web/src/Web.App/Views/School/CustomData.cshtml
web/src/Web.App/Views/School/_Banners.cshtml
web/src/Web.App/Views/School/_CustomDataBanner.cshtml
web/src/Web.App/Views/SchoolCensus/CustomData.cshtml
web/src/Web.App/Views/SchoolComparison/CustomData.cshtml
web/src/Web.App/Views/SchoolCustomDataChange/Submit.cshtml
web/src/Web.App/Views/Shared/Components/ComparatorSetDetails/Default.cshtml

[AB#192482](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/192482)
fixes and updates to the pages in this story to match ACs (and correct errors I missed last week!)
- closes div correctly for census and comparison pages of the custom data journey so that the custom data finance tools section shows correctly.
- success banner on customised data page (dashboard) only shows when directed from creating/editing custom data
- correct breadcrumbs on customised data page 
- "view your custom data set" from elsewhere in the service updated to direct to the customised data page 
- "view or change your custom data set" link from the customised data page now directs to the start of the create custom data journey
- updates wording to match with the latest …

fix: custom data fixes

---

front-end-components/src/services/types.tsx
front-end-components/src/views/budget-forecast-returns/partials/bfr-table.tsx
platform/src/apis/Platform.Api.Insight/BudgetForecast/BudgetForecastResponse.cs
platform/tests/Platform.Tests/Insight/BudgetForecast/WhenBudgetForecastReturnsResponseFactoryCreatesResponse.cs
web/src/Web.App/Controllers/TrustForecastController.cs
web/src/Web.App/Domain/Insight/Balance.cs
web/src/Web.App/ViewModels/TrustForecastMetricsViewModel.cs
web/src/Web.App/ViewModels/TrustForecastViewModel.cs
web/src/Web.App/Views/TrustForecast/_Metrics.cshtml
web/tests/Web.Integration.Tests/Pages/Trusts/WhenViewingForecast.cs
web/tests/Web.Tests/ViewModels/GivenATrustForecastViewModel.cs

[AB#214547](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/214547) [AB#188391](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/188391)
Rules from Word document from user story attachments used to implement logic for remaining statuses. Test coverage to validate each use case. May need to be tweaked based on feedback from client.
`SELECT` from the `BudgetForecastReturn` table to find trusts at varying status levels to validate the expected logic.

Display remaining priority status/guidance on BFR

---

web/src/Web.App/Views/TrustSpending/Index.cshtml
web/src/Web.App/Views/TrustSpending/_PriorityTable.cshtml
web/tests/Web.Integration.Tests/Pages/Trusts/WhenViewingSpending.cs

[AB#216588](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/216588) [AB#192288](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/192288)
For these two cost categories only, display spending as 'per square metre' instead of 'per pupil'.

Set units to 'square metre' for utilities and premises costs

---

web/src/Web.App/ViewModels/SchoolCustomDataChangeViewModel.cs
web/src/Web.App/Views/SchoolCustomDataChange/FinancialData.cshtml
web/src/Web.App/Views/SchoolCustomDataChange/_CustomDataEntryTableRow.cshtml

[AB#216378](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/216378) [AB#198080](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/198080)
This behaviour [existed previously](https://github.com/DFE-Digital/education-benchmarking-and-insights/commit/c515f6077e972a4abb2b05cea1726198d2359d0a#diff-81473a4a2985639913c2161343efe07ad5b6853d08f07a7b49304fd890e7ab1e), before Income/RR was editable.

Reinstated 'live' expenditure calculation on Custom Data Financials page

---

core-infrastructure/terraform/ai.tf

Converted original query to function and added new query specifically for 'Popular' Schools, Trusts and LAs.

Updated log analytics query and function

---

data-pipeline/src/pipeline/comparator_sets.py
data-pipeline/src/pipeline/main.py
data-pipeline/src/pipeline/pre_processing.py
data-pipeline/src/pipeline/rag.py
data-pipeline/tests/unit/pre_processing/test_custom_data.py

For custom-data processing:
1. when overlaying the custom data, skip processing of datasets where the target URN isn't present (previously this was effectively _adding_ this as a new row).
2. don't produce comparator-sets for datasets where the target URN isn't present (but produce an empty DataFrame with the right columns for downstream processing).
3. skip RAG calculations for all but the target URN (the comparators will be reduced as per the above but the input data is still there in its entirety; all rows need to be there for the RAG calculation but the final dataset reduced to just the relevant row).
- skip RAG calculations entirely for datasets where the target URN isn't present (again, producing an empty, consistent DataFrame for downstream processing).

Avoid unecessary processing for custom-data

---

web/src/Web.App/Controllers/SchoolComparatorsCreateByController.cs
web/src/Web.App/Controllers/TrustComparatorsCreateByController.cs
web/src/Web.App/ViewModels/SchoolComparatorsByNameViewModel.cs
web/src/Web.App/ViewModels/TrustComparatorsByNameViewModel.cs

[AB#217431](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/217431) [AB#217429](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/217429)
Bug fix on school and trust manual add/remove comparators pages introduced after validation rules changed during content review.

Use distinct models for add/remove school/trust comparators to separate validation rules

---

data-pipeline/src/pipeline/comparator_sets.py

make certain that `Pupil` and `Building` are _always_ added as columns, even if no comparator sets are generated.

fix: always inclue comparator-set columns

---

web/src/Web.App/Controllers/SchoolComparatorsController.cs
web/src/Web.App/ViewComponents/ComparatorSetDetailsViewComponent.cs
web/src/Web.App/ViewModels/Components/ComparatorSetDetailsViewModel.cs
web/src/Web.App/Views/SchoolCensus/Index.cshtml
web/src/Web.App/Views/SchoolComparators/Workforce.cshtml
web/src/Web.App/Views/Shared/Components/ComparatorSetDetails/Default.cshtml
web/tests/Web.E2ETests/Pages/School/BenchmarkCensusPage.cs

following discussion with design and product agreed a page is required for displaying comparator set for only pupil which is relevant when viewing workforce benchmarking
Adds this page
updates e2e tests following changes
Include any useful information needed to review this change. Include any dependencies that are required for this change. 

feat: adds comparator page for workforce only

---

data-pipeline/terraform/container_apps.tf

[AB#217528](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/217528) [AB#217527](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/217527)
Also set app container environment workload minimum count to `3` for production only
Deployed to `d12` feature environment to validate Terraform, but impact will not be seen until pushed to production.

Set minimum app contanier replicas to `1` for production only

---

web/src/Web.App/Views/School/CustomData.cshtml
web/tests/Web.Integration.Tests/Pages/Schools/CustomData/WhenViewingCustomisedData.cs

[AB#192482](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/192482)
fix following QA feedback
View or change your custom data now directs to financial data input page in this journey not the start page of the journey
tests also updated to reflect this change
N/A

Fix: view or change custom data link

---

data-pipeline/src/pipeline/comparator_sets.py

`to_sql()` will include the named index in addition to columns.

fix: include URN in empty comparator-set data

---

data-pipeline/src/pipeline/input_schemas.py
data-pipeline/src/pipeline/main.py
data-pipeline/src/pipeline/pre_processing.py
data-pipeline/tests/unit/pre_processing/test_aar.py

Some further processing is needed on custom-data:
- _all_ central-services columns must be set to zero for the row in question, not just those present in the custom-data;
- per-unit and total columns must be set to zero for the row in question but _only_ for those present in the custom-data;
- the processing done in `mappings.py#map_cost_series()` must be repeated to recalculate per-unit and total costs.

fix: zero-out and recalculate custom-data

---

front-end-components/copy-js.ps1
front-end-components/copy-js.sh
front-end-components/package.json
front-end-components/vite.config.ts
web/src/Web.App/gulpfile.js

[AB#217989](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/217989) [AB#217950](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/217950)
JS source maps were being generated for all Vite builds. Config updated to not produce these by default rather use [CLI argument](https://vitejs.dev/guide/cli#build) instead. Also include `govuk-frontend.min.js.map` in Web `wwwroot` as per [GDS instructions](https://frontend.design-system.service.gov.uk/install-using-precompiled-files/#copy-and-install-the-precompiled-files) (at least for the time being).
CI build should not produce the source maps, so once deployed to `d01` there should no longer be `404`s reported trying to resolve this missing asset. For local dev purposes, the …

Only output sourcemaps for dev Vite.js builds

---

front-end-components/index.html
front-end-components/src/components/charts/utils.ts
front-end-components/src/views/historic-data/partials/income-section-self-generated.tsx

[AB#218017](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/218017) [AB#217960](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/217960)
Fixed typo - the wrong value was attempting to be rendered in the historical chart. Use empty string instead of `undefined` in tables where values are missing.
Run Vite dev server in `front-end-components` to load Trust that was previously experiencing this issue, but now renders correctly.

Typo in `HistoricChart` for Investment Income

---

web/src/Web.App/Views/Trust/Details.cshtml

[AB#218036](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/218036) [AB#218015](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/218015)
The Trust History feature is not yet production ready and so has been removed from the UI.
View any Trust Details page to ensure that there is no mention of Trust History.

Remove Trust History tab

---

data-pipeline/src/pipeline/pre_processing.py

- `Catering staff and supplies_Net Costs` are normally calculated _after_ other fields;
- for custom-data, this field must be excluded from `_Total` calculations;
- for now, temporarily set this to zero to allow the existing logic to be re-used, before setting the value back to its original.

fix: exclude catering net costs for custom-data

---

web/Directory.Packages.props
web/src/Web.App/Infrastructure/Cosmos/ClientFactory.cs
web/src/Web.App/Web.App.csproj
web/src/Web.App/packages.lock.json
web/terraform/README.md
web/terraform/app-service.tf
web/terraform/cache.tf
web/tests/Web.Integration.Tests/packages.lock.json
web/tests/Web.Tests/packages.lock.json

[AB#217518](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/217518) [AB#216189](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/216189)
Also updated app service Cosmos connection string to remove `AccountKey` in order for `DefaultAzureCredential` to be used instead of `AzureKeyCredential` as per the modified `ClientFactory`. Local development may continue to use the key from .NET secrets but deployments should honour the SQL RBAC.
Deployed to `d16` feature environment for validation, but due to lack of data the underlying Cosmos connection is yet to be validated.

Assigned app service system defined identity to Cosmos account with read/write role

---

data-pipeline/src/pipeline/database.py
data-pipeline/src/pipeline/pre_processing.py

there is an inconsistency between the  Trust information in    `academy_master_list` and `gias_all_links`: rely on the latter for    Trust-related data.
[AB#218046](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/218046)
[AB#218339](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/218339)
change the data used for the `TrustName` column from `Trust Name` (from the `academy_master_list` file) to `Group Name` (from the `gias_all_links` file) for consistency with `Group UID`.
…

fix: use gias_all_links for Trust info.

---

data-pipeline/src/pipeline/pre_processing.py

[AB#218640](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/218640)
Adds apportionment calculation for revenue reserve, in-year balance, total income and total expenditure.
Currently just sorting the whole CS value for all schools
N/A

chore: add apportionment for missing values

---

web/terraform/front-door.tf

[AB#219080](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/219080)
updates web test to only use valid regions allowed in WAF policy
Availability web tests failed as expected in 3 of the 5 regions (only UK South & West passed)

feat: updates web test to only use valid regions allowed in WAF policy

---

web/src/Web.App/ViewModels/SchoolViewModel.cs

[AB#218546](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/218546) - [AB#220130](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/220130)
Excludes category "Other costs" from Ratings property so this is not displayed in the Top spending priorities on the school homepage.
To confirm run locally with the example provided in the story where this occurs to confirm the change.

feat: filter other costs from ratings

---

web/src/Web.App/ViewModels/SchoolViewModel.cs

[AB#218546](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/218546) - [AB#220226](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/220226)
Correct filtering of Ratings on SchoolViewModel to now only filter for school homepage. Not find ways to spend less page as introduced by #1130 
Using the example in the story can confirm locally school homepage no longer displays Other costs as a priority but on the find ways to spend less page other costs is still included in the recommended section.

filter other costs for school homepage only

---

data-pipeline/src/pipeline/rag.py
data-pipeline/tests/unit/rag/test_percentile.py

As per [AB#216667](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/216667), percentile calculations are off by one.
1. Adding tests to validate the expected values.
2. Removing the decrement of the calculated percentile.
I've used [`scipy.stats.percentilofscore()`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.percentileofscore.html) to calculate the expected values, which tally with the expectations as per the ticket.
Note: `scipy` recognises various "percentile" calculations, as per the `kind` parameter:
* `rank` is the variant used for the above and matches the client expectations, as per the ticket.
* `strict` is one variant which includes values _strictly less_ than the score—this may have been the intention but the final …

fix: correct percentile calculation

---

core-infrastructure/src/db/Core.Database/Scripts/048-AlterSchoolPhasesCoveredByTrust.sql
platform/src/apis/Platform.Api.Insight/Trusts/TrustCharacteristic.cs
platform/src/apis/Platform.Api.Insight/Trusts/TrustsFunctions.cs
platform/tests/Platform.ApiTests/Features/InsightTrusts.feature
platform/tests/Platform.ApiTests/Steps/InsightTrustsSteps.cs
web/src/Web.App/Domain/Insight/TrustCharacteristic.cs
web/src/Web.App/Views/TrustComparatorsCreateBy/Characteristic.cshtml
web/src/Web.App/Views/TrustComparatorsCreateBy/Preview.cshtml
web/src/Web.App/Views/TrustComparatorsCreateBy/_ChosenTrusts.cshtml
web/tests/Web.A11yTests/Pages/Trust/Comparators/WhenViewingComparatorsByName.cs

[AB#220506](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/220506) [AB#217226](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/217226)
Modified view and bound type to parse trust school phase count as well as name.
The figures will only show up on environment(s) where the database migration script has been executed to include the phase counts.

Include school phase breakdown in Trust Comparators table

---

platform/tests/Platform.Tests/Benchmark/WhenFunctionReceivesCreateComparatorSetRequest.cs
platform/tests/Platform.Tests/Benchmark/WhenFunctionReceivesGetComparatorSetRequest.cs
platform/tests/Platform.Tests/Benchmark/WhenFunctionReceivesRemoveComparatorSetRequest.cs

[AB#219825](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/219825) - [AB#219826](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/219826)
Adds unit tests for platform benchmark comparator set functions

chore: adds benchmark comparator set unit tests

---

front-end-components/src/index.css
web/src/Web.App/ViewModels/SchoolSpendingViewModel.cs
web/src/Web.App/Views/SchoolSpending/CustomData.cshtml
web/src/Web.App/Views/SchoolSpending/Index.cshtml
web/src/Web.App/Views/SchoolSpending/_Costs.cshtml
web/src/Web.App/Views/Trust/_SchoolsSection.cshtml

[AB#217308](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/217308) - [AB#220879](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/220879)
- Adds functionality to navigate from the school lists bar charts directly to the school spending page at the first cost category of that priority type (ie high, medium, low)
- Refactors both the school spending page and the custom data version to use a partial for each category.
- Also adds CSS to add a min height to the container as without this the page will update after the user has navigated causing the desired element to be out of view.
N/A

adds clickable bar chart for trust home school list

---

data-pipeline/src/pipeline/pre_processing.py

Fix double counting of BNCH11123-BTI011-A (MAT Central services - Income) and BNCH11123-BAI011-A (Academies - Income)
Removed the double counting of BNCH11123-BTI011-A (MAT Central services - Income) and BNCH11123-BAI011-A (Academies - Income)
Check that double counting of BNCH11123-BTI011-A (MAT Central services - Income) and BNCH11123-BAI011-A (Academies - Income) no longer occurs

fixed double counting of Academies funding

---

platform/src/apis/Platform.Api.Establishment/Trusts/TrustsFunctions.cs

[AB#221688](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/221688) - [AB#221689](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/221689)
Updates OpenApiOperation tag so that this will be displayed correctly in the swagger ui under Trusts
run locally and check swagger

fix: OpenApiOperation tag for swagger updated

---

.github/dependabot.yml

[AB#222233](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/222233) [AB#222226](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/222226)
Update `dependabot` configuration now that Platform projects have been upgraded to .NET 8. A further pass to pick up additional packages that should be updated will need to take place after this has been merged.

Removed .NET 7/8 `dependabot` ignored package versions

---

core-infrastructure/terraform/dashboards/oi.tpl

[AB#220583](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/220583) [AB#219227](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/219227)
Switch chart type displayed in OI dashboard for this query.
When pointing to the prod WAF, the results should now be more readable, e.g.:

Replace `Donut` chart with `UnstackedColumn` when displaying WAF hits by rule name in OI dashboard

---

data-pipeline/src/pipeline/pre_processing.py

In year balance for academies had a typo
[(AB#221270)](https://dev.azure.com/dfe-ssp/s198-DfE-Benchmarking-service/_workitems/edit/221270)
replaced typo and removed "Trust Balance" calculation as part of last fix
Check typo replacement is correct

removed typo

---

web/src/Web.App/Views/SchoolComparators/Index.cshtml
web/src/Web.App/Views/SchoolComparators/UserDefined.cshtml
web/src/Web.App/Views/SchoolComparators/Workforce.cshtml

[AB#216448](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/216448) - [AB#222015](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/222015)
see update 3 on the story and comments.
For default, workforce and user defined comparator page this displays the chosen school to the table at row 1 as per the design.
Also amends the count for the default comparator page to now show the whole set including the chosen school
N/A

display chosen school for comparators table

---

web/src/Web.App/Constants/PageTitles.cs
web/src/Web.App/Controllers/TrustComparatorsCreateByController.cs
web/src/Web.App/ViewModels/TrustComparatorsByNameViewModel.cs
web/src/Web.App/ViewModels/TrustComparatorsChosenTrustsViewModel.cs
web/src/Web.App/ViewModels/TrustComparatorsSubmittedViewModel.cs
web/src/Web.App/Views/TrustComparatorsCreateBy/Name.cshtml
web/src/Web.App/Views/TrustComparatorsCreateBy/Submit.cshtml
web/src/Web.App/Views/TrustComparatorsCreateBy/_ChosenTrusts.cshtml
web/tests/Web.Integration.Tests/Pages/Trusts/Comparators/WhenViewingComparatorsCreateSubmit.cs

[AB#218109](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/218109) - [AB#222934](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/222934)
Issue 31 and 40
Use `UserDefinedTrustComparatorSet.RunId` to set whether this is an edit or not and conditionally display the button text for the create by name page, title and heading for the submit page as per the AC
N/A

fix: updates to edit user defined trust comparator set journey

---

web/src/Web.App/Domain/OverallPhaseTypes.cs
web/src/Web.App/ViewModels/TrustViewModel.cs
web/src/Web.App/Views/Trust/Index.cshtml
web/tests/Web.Integration.Tests/Pages/Trusts/WhenViewingHome.cs

[AB#221010](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/221010) - [AB#221882](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/221882)
updates phases displayed as rag stack tables on the trust home page to match the phases detailed in the ticket for academies
N/A

feat: updates to trust home displayed school phases

---

web/src/Web.App/ViewModels/LocalAuthorityViewModel.cs
web/src/Web.App/Views/LocalAuthority/Index.cshtml
web/src/Web.App/Views/LocalAuthority/_SchoolsSection.cshtml
web/tests/Web.Integration.Tests/Pages/LocalAuthorities/WhenViewingHome.cs

[AB#221010](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/221010) - [AB#221649](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/221649)
Updates to displayed phases for the la home page. phases are no longer grouped as other or special and pru. Also refactored so only the phases within the la are displayed as accordion sections
n/a

feat: updates to displayed phases for la home

---

data-pipeline/src/pipeline/main.py

From the main ticket:
> _"…the BFR value for Revenue reserve for Current and previous years takes from the SOFA and efaline 430."_
> _"…where it is a balance, then Y2P2…"_
[AB#217947](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/217947)
Still reading the various `academies` files but replacing values therein with the corresponding `EFALineNo` from the BFR SOFA data for that year.
Note: looked at this and the plan was to replace both `Trust Revenue reserve` and `Total pupils in trust`. However, while the former (line 430) looks roughly right, the latter (which, according to [this doc.](https://assets.publishing.service.gov.uk/media/6605777ff9ab410011eea508/BFR_lines_quick_reference_guide.pdf), should be 999) is `0.0` across the board.
I've therefore …

fix: get BFR data from SOFA

---

data-pipeline/src/pipeline/main.py

- typo. in column renaming.
- better handle absence of SOFA files (derived columns _must_ be present even if the file is absent; if the file is present, avoid `merge()` issues).

fix: correct BFR SOFA column name

---

web/src/Web.App/Views/School/History.cshtml

[AB#219193](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/219193) - [AB#223775](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/223775)
Updates content for the historic page to correctly call out the data source for the pupil and workforce tab as workforce census and school census as per the ticket.
n/a

fix: data source for pupil and school census

---

web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
web/tests/Web.Integration.Tests/Pages/Schools/CustomData/WhenViewingCustomDataSpending.cs
web/tests/Web.Integration.Tests/Pages/Schools/WhenViewingSpending.cs
web/tests/Web.Integration.Tests/Paths.cs

[AB#224502](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/224502) - [AB#224934](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/224934)
Adds integration tests to cover the expected behaviour for the school spending (spending and costs) pages. Both default and custom
N/A

chore: adds integration tests for spending and costs default and custom

---

core-infrastructure/terraform/README.md
core-infrastructure/terraform/queries.tf
core-infrastructure/terraform/queries/functions/get-tracked-save-charts.kql
front-end-components/src/composed/horizontal-bar-chart-wrapper/composed.tsx
front-end-components/src/views/budget-forecast-returns/partials/year-end.tsx

[AB#225439](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/225439) [AB#223210](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/223210)
Custom event tracking for above feature.
Authored Kusto query to return custom events of this type, for future reporting.
Build and copy `front-end-components` locally into `Web`. Set an app insights instrumentation key. Click on 'Save as image' on various charts. Observe App Insights event tracking, e.g.:
TimeGenerated | Name | ChartName | OperationId | UserId | Establishment | Feature | Identifier
-- | -- | -- | -- | -- | -- | -- | --
2024-08-23T07:34:50.291Z | save-chart-as-image | total expenditure | 41082ffdfb434ccfb544ba06e7eda659 | rxCbaKpPR0Ex0IgCQM2qNe | school | …

Added App Insights event tracking to 'Save chart as image' buttons

---

web/src/Web.App/Constants/DataSourceTypes.cs
web/src/Web.App/ViewComponents/DataSourceViewComponent.cs
web/src/Web.App/ViewModels/Components/DataSourceViewModel.cs
web/src/Web.App/Views/LocalAuthority/Index.cshtml
web/src/Web.App/Views/LocalAuthorityCensus/Index.cshtml
web/src/Web.App/Views/LocalAuthorityComparison/Index.cshtml
web/src/Web.App/Views/School/Index.cshtml
web/src/Web.App/Views/SchoolCensus/Index.cshtml
web/src/Web.App/Views/SchoolComparison/Index.cshtml
web/src/Web.App/Views/SchoolSpending/Index.cshtml
web/src/Web.App/Views/Shared/Components/DataSource/Default.cshtml
web/src/Web.App/Views/Trust/Index.cshtml
web/src/Web.App/Views/TrustCensus/Index.cshtml
web/src/Web.App/Views/TrustComparators/Index.cshtml
web/src/Web.App/Views/TrustComparison/Index.cshtml
web/src/Web.App/Views/TrustSpending/Index.cshtml

[AB#219193](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/219193) - [AB#225244](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/225244)
Updates content for the benchmark pupil and workforce data page for school, la and trust to correctly call out the data source as workforce census and school census as per the ticket.
Refactors DataSource component to use additional parameter sourceType
N/A

fix: data source for benchmark census

---

front-end-components/index.html
front-end-components/src/components/charts/horizontal-bar-chart/component.tsx
front-end-components/src/components/total-catering-costs-type/component.tsx
front-end-components/src/components/total-catering-costs-type/index.tsx
front-end-components/src/components/total-catering-costs-type/types.tsx
front-end-components/src/services/types.tsx
front-end-components/src/views/compare-your-costs/partials/accordion-sections/catering-staff-services.tsx
front-end-components/src/views/compare-your-costs/partials/accordion-sections/types.tsx
front-end-components/src/views/compare-your-trust/partials/accordion-sections/catering-staff-services.tsx
front-end-components/src/views/compare-your-trust/partials/accordion-sections/types.tsx
front-end-components/src/views/historic-data/partials/spending-section-catering-services.tsx
web/src/Web.App/Domain/Insight/Expenditure.cs
web/tests/Web.E2ETests/Features/School/CompareYourCosts.feature
web/tests/Web.E2ETests/Pages/School/CompareYourCostsPage.cs
web/tests/Web.E2ETests/Pages/School/HistoricDataPage.cs
web/tests/Web.E2ETests/Selectors.cs
web/tests/Web.E2ETests/Steps/School/CompareYourCostsSteps.cs

[AB#225534](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/225534) [AB#214976](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/214976)
Added radio buttons to Total Catering Costs charts to toggle between Gross and Net values.
All expenditure charts are affected, including custom comparators and history for both Schools and Trusts.

Allow toggle between Gross and Net total catering income in UI

---

support-analytics/terraform/README.md
support-analytics/terraform/alerts.tf
support-analytics/terraform/data.tf
support-analytics/terraform/variables.tf

[AB#225090](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/225090) ([AB#225824](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/225824))
Adds alert for web app availability 
N/A

feat: adds availability alert

---

front-end-components/index.html
front-end-components/src/components/charts/establishment-tick/component.tsx
front-end-components/src/components/charts/establishment-tick/types.tsx
front-end-components/src/components/charts/horizontal-bar-chart/component.tsx
front-end-components/src/components/charts/line-chart/component.tsx
front-end-components/src/components/charts/vertical-bar-chart/component.tsx
front-end-components/src/composed/horizontal-bar-chart-wrapper/composed.tsx
front-end-components/src/index.css

[AB#225682](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/225682) [AB#225478](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/225478)
Required to resolve A02 from accessibility audit, whereby tooltip should be visible in charts by users who are unable to hover over a column bar using a pointing device.
Keyboard tabbing between schools or trusts on benchmarking charts should display the tooltip without the need to use a mouse.

Displayed tooltip in Horizontal line charts when row focused via keypress

---

core-infrastructure/terraform/dashboards.tf
core-infrastructure/terraform/queries.tf
core-infrastructure/terraform/queries/dlq-message-count.kql
core-infrastructure/terraform/queries/functions/get-messages-by-queue-name.kql

Adds foundational queries for the DLQ graph in the dashboard.
[AB#223831](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/223831)
- add `GetMessagesByQueueName` as a reusable function to derive messages counts by queue name.
- use the above as the basis for the DLQ count, adding that as a query-pack query.
This is just to get the initial queries in place:
1. they might not be entirely correct but should have the right "shape" (i.e. will yield the right columns for populating the dashboard).
2. once added, I intend to add the new graph to the dashboard and export said dashboard to correctly derive the right JSON for the `oi.tpl` file.

feat: add queue/DLQ queries

---

data-pipeline/src/pipeline/main.py
data-pipeline/src/pipeline/pre_processing.py

Update pupil figures as per recent comments on the ticket ("should be from…line 999 and the Y1P2 column").
[AB#217947](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/217947)
As per `Trust Revenue reserve`, derive the `Total pupils in trust` from the BFR SOFA file(s).
N/A

fix: use BFR SOFA for pupil figures

---

data-pipeline/Makefile
data-pipeline/tests/unit/pre_processing/test_bfr.py

This test _should_ have failed on the previous run.
Need to look into why but this should update the test to reflect the recent change.

Correct historical BFR test

---

core-infrastructure/terraform/acr.tf
core-infrastructure/terraform/provider.tf
web/terraform/cache.tf
web/terraform/provider.tf

[AB#226388](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/226388) - [AB#226504](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/226504)/[AB#226689](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/226689)
Following Dependabot alerts #1287 and #1277 updates required for the latest version of azurerm.
`retention_policy` has been replaced by `retention_policy_in_days`.
[docs](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/container_registry#retention_policy_in_days)
[4.0 upgrade guide](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/4.0-upgrade-guide#azurerm_container_registry)
`trust_policy` block has been replaced …

chore: terraform provider updates

---

data-pipeline/src/pipeline/pre_processing.py

Previously, only schools with an empty `CloseDate` were retained, effectively removing any maintained-schools which had made part-year submissions.
Drop the `CloseDate` filter on the `schools`/GIAS dataset.
See `pipeline.maintained_schools#create_master_list()`, line 30: this is where the `schools` data are joined to `managed_schools`. As there's no `how` parameter passed, it'll default to `inner` which is where the above problem creeps in.

fix: omit removal of closed schools data

---

data-pipeline/src/pipeline/comparator_sets.py
data-pipeline/src/pipeline/config.py
data-pipeline/src/pipeline/maintained_schools.py
data-pipeline/src/pipeline/pre_processing.py

Partial-year submission for maintained schools need to be omitted from comparator-set/RAG calculations under certain circumstances.
1. extend the maintained school data to include indicators which determine whether comparator-sets are calculated
2. in the comparator-set workflow, use these to skip comparator-set calculations.
3. moving some existing pre-processing code to `config.py` for re-use when identifying columns for the above.
See the checks/outcomes in the linked ticket.

Data-pipeline: handle part-year submissions for maintained schools

---

data-pipeline/src/pipeline/comparator_sets.py

Failed pipeline run with `AttributeError: 'float' object has no attribute 'tolist'`.
As we were skipping comparator-set generation for part-year records, this would have been a `numpy.nan`, hence the error.
Include an empty array for skipped comparator-sets to they can be correctly serialised as per existing behaviour.
…

fix: include empty comparator-sets for part-year data

---

data-pipeline/Makefile

[AB#226820](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/226820) [AB#225091](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/225091)
Explicitly target `linux/amd64` rather than the default from the source device that initiated the build. 
For example when building on MacOS the following is returned when attempting to provision an incorrectly targeted image:
```
Status: "Failed"
│ Code: "ContainerAppOperationError"
│ Message: "Failed to provision revision for container app 's198d50-ebis-data-pipeline'. Error details: The following field(s) are either invalid or missing. Field
│ 'template.containers.edis-data-pipeline.image' is invalid with details: 'Invalid value: …
```

Ensure Docker build for `data-pipeline` targets correct architecture

---

core-infrastructure/terraform/README.md
core-infrastructure/terraform/dashboards.tf
core-infrastructure/terraform/dashboards/oi.tpl
core-infrastructure/terraform/queries.tf
core-infrastructure/terraform/queries/dlq-message-count.kql
core-infrastructure/terraform/queries/dlq-new-messages-per-hour.kql
core-infrastructure/terraform/queries/functions/get-messages-by-queue-name.kql
core-infrastructure/terraform/queries/functions/get-queue-put-messages.kql
core-infrastructure/terraform/storage.tf

[AB#227012](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/227012) [AB#223831](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/223831)
Switched query to use count of `PutMessage` rather than `GetMessages`. 
Added missing Diagnostic Settings infrastructure configuration.
Appended chart displaying query results to OI dashboard.
Modified OI dashboard deployed to `d11` feature environment. Add a message to the `dlq` queue and wait ~5 minutes for the updated metric to be displayed in the chart.

Add DLQ query to OI dashboard

---

data-pipeline/src/pipeline/database.py

Only a single entry per comparator-set run is being included for part-year data where pupil/building comparator-set generation would be skipped. This is due to the `drop_duplicates()` call in the `upsert()` function.
This will not consider the index (i.e. `URN`) as part of the duplicate check and, as columns are reduced to just `Pupil` and `Building`, any instances where the comparator set is empty (i.e. `[]`) will be considered duplicates.
Extend the `upsert()` function to take an optional argument indicating whether deduplication should take place. This will default to `True` to maintain existing behaviour where this is used elsewhere but `insert_comparator_set()` will explicitly …

fix: correct comparator-set upsert

---

core-infrastructure/terraform/storage.tf

[AB#227131](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/227131) [AB#223831](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/223831)
Include additional automatically provisioned `azurerm_monitor_diagnostic_setting`s and ignore unused `retention_policy`.
See:
- https://github.com/hashicorp/terraform-provider-azurerm/issues/17172 
- https://stackoverflow.com/a/78299394/504477
- https://github.com/hashicorp/terraform/issues/26359
New log output shows that there is now no drift between configuration and state but does include the warning that is safe to ignore:
```
No changes. Your infrastructure matches the configuration.
Terraform has compared your real infrastructure against your configuration
and found no …
```

Include additional automatically provisioned `azurerm_monitor_diagnostic_setting`s

---

web/terraform/cache.tf

[AB#226388](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/226388) - [AB#226793](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/226793)
Due to a bug in Terraform we are unable to update the provider version to >4.0 and replace the deprecated property in the same release for azurerm.
This PR updates the deprecated property.
A following PR will update the version [AB#227199](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/227199).
This has been tested in a feature environment `d17` and returns no errors or unexpected changes on `terraform plan`
Updates deprecated property on `azurerm_cosmosdb_sql_container`
N/A

chore: updates deprecated property on azurerm_cosmosdb_sql_container

---

platform/README.md
platform/src/apis/Platform.Api.Benchmark/Configuration/Logging.cs
platform/src/apis/Platform.Api.Benchmark/host.json
platform/src/apis/Platform.Api.Establishment/Configuration/Logging.cs
platform/src/apis/Platform.Api.Establishment/host.json
platform/src/apis/Platform.Api.Insight/Configuration/Logging.cs
platform/src/apis/Platform.Api.Insight/host.json
platform/src/apis/Platform.Orchestrator/Configuration/Logging.cs
platform/src/apis/Platform.Orchestrator/host.json
platform/src/apis/Platform.UserDataCleanUp/Configuration/Logging.cs
platform/src/apis/Platform.UserDataCleanUp/host.json

[AB#227839](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/227839) [AB#227696](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/227696)
Set appropriate `logLevel`s across all Function App `host.json` files.
Removed exclusion of `ApplicationInsightsLoggerProvider` rule from logger configuration across all Function Apps.
Updated Platform `README.md` to include `logLevel` overrides for local development.
Set appropriate `local.settings.json` for each Function App (including AI instrumentation key) and run locally.
Hit an endpoint and observe the results in Application Insights.
Modify or remove `logLevel` override configuration to observe different results in Application Insights.

Modified logging configuration across Function Apps to reduce noise

---

web/src/Web.App/AssetSrc/scss/main.scss
web/src/Web.App/Middleware/CustomResponseHeadersMiddleware.cs
web/src/Web.App/ViewComponents/RagStack.cs
web/src/Web.App/ViewModels/Components/RagStackViewModel.cs
web/src/Web.App/Views/Shared/Components/RagStack/Default.cshtml
web/src/Web.App/Views/Trust/_SchoolsSection.cshtml

[AB#216194](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/216194) [AB#215819](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/215819)
Fixed only occurrence of `style=` from Web. JavaScript-rendered inline styles seem to be permitted.
Run `Web` locally, after performing an `npm run build` to get `gulp` to rebuild the CSS. Browse the site, especially those containing charts, plus the Trust landing page.

Removed `unsafe-inline` `style-src` from CSP

---

web/src/Web.App/web.config

[AB#216193](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/216193) [AB#215819](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/215819)
Minor configuration change
Change not picked up when debugging Web locally by most web browsers. `hosts` file might need to be modified to do see the header, or else validate in `d13` [feature deployment](https://s198d13-education-benchmarking-c8c4bhdsb0axbma2.a02.azurefd.net/).

Set HSTS header `max-age` to `2592000` (30 days) instead of `31536000` (1 year)

---

data-pipeline/src/pipeline/database.py

Reports of missing data from the service. Specifically, this has manifested in missing RAG metrics though as this appears to be caused by the `upsert()` function, this could be more widespread.
[AB#227113](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/227113)
- retain in-place `drop_duplicates()` behaviour
- update this to take the index (typically the URN but potentially not always) into account
Note: this also reverts 7d71c4c540fe86644f86071ed6419005b14972b1 as it's no longer necessary.
Currently difficult to validate as this resides in the DB layer but:
```python
import pandas as pd
df = pd.read_parquet("output/metric-rag/2023/maintained_schools.parquet")
print("Original:", len(df.index))
print("Previous drop-duplicates:", …
```

fix: amend deduplication during DB merge

---

data-pipeline/src/pipeline/maintained_schools.py
data-pipeline/src/pipeline/pre_processing.py
data-pipeline/tests/unit/pre_processing/test_maintained_schools.py

[AB#228227](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/228227) ([AB#228605](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/228605))
Corrects Net catering cost calculation. Previous calculation was Net income, rather than cost.
Not tested locally,

bugfix: correct net catering income cost calc

---

web/src/Web.App/Controllers/TrustComparatorsController.cs
web/src/Web.App/Controllers/TrustController.cs
web/src/Web.App/ViewModels/TrustViewModel.cs
web/src/Web.App/Views/Trust/Index.cshtml
web/tests/Web.Integration.Tests/Pages/Trusts/Comparators/WhenViewingComparatorsRevert.cs

[AB#228435](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/228435) [AB#218588](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/218588)
See bug 'Repro Steps'

Display 'comparator reverted' banner on Trust homepage when custom comparators cleared

---

front-end-components/src/views/compare-your-trust/partials/accordion-sections/other-costs.tsx
front-end-components/src/views/historic-data/partials/income-section.tsx
front-end-components/src/views/historic-data/partials/spending-section-other.tsx
front-end-components/src/views/historic-data/partials/spending-section.tsx

[AB#228512](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/228512) [AB#226428](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/226428)
Documented fields will no longer be populated after changes to the underlying Trust views. The associated charts may therefore be safely removed.
View Trust income/expenditure current/history to ensure charts are no longer displayed. View corresponding School charts to ensure charts are still present. To validate locally, build and copy `front-end-components` to `Web` first.

Remove redundant Trust financial fields from charts in front end

---

front-end-components/index.html
front-end-components/src/components/charts/establishment-tick/component.tsx
front-end-components/src/components/charts/establishment-tick/types.tsx
front-end-components/src/components/charts/horizontal-bar-chart/component.tsx
front-end-components/src/components/charts/types.tsx
front-end-components/src/composed/horizontal-bar-chart-wrapper/composed.tsx
front-end-components/src/index.css
front-end-components/src/main.tsx
front-end-components/src/services/types.tsx
front-end-components/src/views/compare-your-costs/partials/accordion-sections/administrative-supplies.tsx
front-end-components/src/views/compare-your-costs/partials/accordion-sections/catering-staff-services.tsx
front-end-components/src/views/compare-your-costs/partials/accordion-sections/educational-ict.tsx
front-end-components/src/views/compare-your-costs/partials/accordion-sections/educational-supplies.tsx
front-end-components/src/views/compare-your-costs/partials/accordion-sections/non-educational-support-staff.tsx
front-end-components/src/views/compare-your-costs/partials/accordion-sections/other-costs.tsx
front-end-components/src/views/compare-your-costs/partials/accordion-sections/premises-staff-services.tsx
front-end-components/src/views/compare-your-costs/partials/accordion-sections/teaching-support-staff.tsx
front-end-components/src/views/compare-your-costs/partials/accordion-sections/types.tsx
front-end-components/src/views/compare-your-costs/partials/accordion-sections/utilities.tsx
front-end-components/src/views/compare-your-costs/partials/expenditure-accordion.tsx
front-end-components/src/views/compare-your-costs/partials/total-expenditure.tsx
front-end-components/src/views/compare-your-costs/types.tsx

[AB#228229](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/228229) [AB#228013](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/228013)
Also display exclamation mark next to school name
Find a school with part-year data (e.g. URN `103837`) and view Spending Priorities charts.

Show horizontal chart bar in 'warning' colour if part-year data present for school

---

front-end-components/index.html
front-end-components/package-lock.json
front-end-components/package.json
front-end-components/src/views/find-organisation/partials/la-input.tsx
front-end-components/src/views/find-organisation/partials/school-input.tsx
front-end-components/src/views/find-organisation/partials/trust-input.tsx
front-end-components/src/views/find-organisation/utils.test.ts
front-end-components/src/views/find-organisation/utils.ts

[AB#229209](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/229209) [AB#228611](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/228611)
Included test coverage with the above
To validate locally, build and copy from `front-end` to `web`. Then perform an organisation that may return multiple highlighted elements (see Bug for examples).

Modified regex for highlighting search suggestions

---

front-end-components/index.html
front-end-components/src/components/charts/utils.test.ts
front-end-components/src/components/charts/utils.ts

[AB#229805](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/229805) [AB#229079](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/229079)
For numbers in charts formatted as a currency, if less than 1000 and more than -1000, use two decimal places if the number is a decimal.
Viewing 'Utilities' charts as '£ per square metre' often generates numbers in the format that previously was not acceptable.

Modified decimal currency formatting in charts

---

platform/README.md
platform/src/apis/Platform.Api.Benchmark/Comparators/ComparatorsFunctions.cs
platform/src/apis/Platform.Api.Benchmark/Configuration/Services.cs
platform/src/apis/Platform.Api.Benchmark/Platform.Api.Benchmark.csproj
platform/src/apis/Platform.Api.Benchmark/packages.lock.json
platform/src/apis/Platform.Api.Establishment/Comparators/Characteristics.cs
platform/src/apis/Platform.Api.Establishment/Comparators/ComparatorSchool.cs
platform/src/apis/Platform.Api.Establishment/Comparators/ComparatorSchools.cs
platform/src/apis/Platform.Api.Establishment/Comparators/ComparatorSchoolsRequest.cs
platform/src/apis/Platform.Api.Establishment/Comparators/ComparatorSchoolsService.cs
platform/src/apis/Platform.Api.Establishment/Comparators/ComparatorTrust.cs
platform/src/apis/Platform.Api.Establishment/Comparators/ComparatorTrusts.cs
platform/src/apis/Platform.Api.Establishment/Comparators/ComparatorTrustsRequest.cs
platform/src/apis/Platform.Api.Establishment/Comparators/ComparatorTrustsService.cs
platform/src/apis/Platform.Api.Establishment/Comparators/ComparatorsFunctions.cs
platform/src/apis/Platform.Api.Establishment/Configuration/Services.cs
platform/tests/Platform.ApiTests/Features/BenchmarkComparators.feature
platform/tests/Platform.ApiTests/Features/EstablishmentComparators.feature
platform/tests/Platform.ApiTests/Platform.ApiTests.csproj
platform/tests/Platform.ApiTests/Steps/BenchmarkComparatorsSteps.cs
platform/tests/Platform.ApiTests/Steps/EstablishmentComparatorsSteps.cs
platform/tests/Platform.ApiTests/packages.lock.json
platform/tests/Platform.Tests/Establishment/WhenExpressionBuilderAddsFilterToList.cs
platform/tests/Platform.Tests/packages.lock.json
web/src/Web.App/Extensions/ServiceCollectionExtensions.cs

[AB#230334](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/230334) [AB#229318](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/229318)
Old endpoints marked as deprecated and set to return `410 Gone`.
There is further work required to fulfil the user story.
`Platform` changes may be validated locally by running the APIs, after having first configured them to connect to the `d02` database/search. The API tests may then be executed. `Web` may also then be run - pointing to the local APIs - and a custom comparator set request made based on characteristics for both a Trust and a School.

Moved Comparator functions from Benchmark to Establishment API

---

platform/src/apis/Platform.Api.Establishment/Comparators/ComparatorSchoolsRequest.cs
platform/src/apis/Platform.Api.Establishment/Comparators/ComparatorSchoolsService.cs
platform/src/apis/Platform.Api.Establishment/Comparators/ComparatorTrustsRequest.cs
platform/src/apis/Platform.Api.Establishment/Comparators/ComparatorTrustsService.cs
platform/src/apis/Platform.Api.Establishment/Comparators/ComparatorsFunctions.cs
platform/tests/Platform.ApiTests/Steps/EstablishmentComparatorsSteps.cs
web/src/Web.App/Controllers/SchoolComparatorsCreateByController.cs
web/src/Web.App/Controllers/TrustComparatorsCreateByController.cs
web/src/Web.App/Infrastructure/Apis/ApiRequests/PostSchoolComparatorsRequest.cs
web/src/Web.App/Infrastructure/Apis/ApiRequests/PostTrustComparatorsRequest.cs
web/src/Web.App/Infrastructure/Apis/Benchmark/Api.cs
web/src/Web.App/Infrastructure/Apis/Benchmark/ComparatorApi.cs
web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
web/tests/Web.Tests/Infrastructure/Apis/Requests/GivenAPostSchoolComparatorsRequest.cs
web/tests/Web.Tests/Infrastructure/Apis/Requests/GivenAPostTrustComparatorsRequest.cs
web/tests/Web.Tests/Infrastructure/GivenAComparatorApi.cs

[AB#230335](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/230334) [AB#229318](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/229318) 
Dependent on #1391
There is further work required to fulfil the user story.
`Platform` changes may be validated locally by running the APIs, after having first configured them to connect to the `d02` database/search. The API tests may then be executed. `Web` may also then be run - pointing to the local APIs - and a custom comparator set request made based on characteristics for both a Trust and a School.

Modified signature of Comparator functions to accept identifier in route instead of body

---

platform/Directory.Packages.props
platform/Platform.sln.DotSettings
platform/src/abstractions/Platform.Infrastructure/ResourceNames.cs
platform/src/apis/Platform.Api.Establishment/Configuration/Services.cs
platform/src/apis/Platform.Api.Establishment/Platform.Api.Establishment.csproj
platform/src/apis/Platform.Api.Establishment/packages.lock.json
platform/tests/Platform.ApiTests/packages.lock.json
platform/tests/Platform.Tests/packages.lock.json

[AB#230339](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/230339) [AB#229318](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/229318) 
Dependent on #1391
There is further work required to fulfil the user story.
Run `Establishment` API locally and either use Swagger UI, or else browse to `/api/health` directly. If Azure Search and Azure SQL is available then `Healthy` will be returned. Modify the Search Key in config and restart the service. Hitting the health check endpoint should return `Unhealthy` and detail logged in an exception.

Added Azure Search to Establishment API health checks

---

platform/src/apis/Platform.Api.Establishment/Trusts/TrustResponse.cs
platform/src/apis/Platform.Api.Establishment/Trusts/TrustsFunctions.cs
platform/tests/Platform.ApiTests/Features/EstablishmentTrusts.feature
platform/tests/Platform.ApiTests/Steps/EstablishmentTrustsSteps.cs
platform/tests/Platform.Tests/Establishment/TrustsFunctionsTestBase.cs
platform/tests/Platform.Tests/Establishment/WhenFunctionReceivesGetTrustRequest.cs
platform/tests/Platform.Tests/Establishment/WhenFunctionReceivesSuggestTrustsRequest.cs
web/src/Web.App/Controllers/TrustCensusController.cs
web/src/Web.App/Controllers/TrustComparisonController.cs
web/src/Web.App/Controllers/TrustController.cs
web/src/Web.App/Controllers/TrustPlanningController.cs
web/src/Web.App/Controllers/TrustSpendingController.cs
web/src/Web.App/Domain/Establishment/Trust.cs
web/src/Web.App/Domain/Establishment/TrustSchool.cs
web/src/Web.App/ViewModels/TrustPlanningViewModel.cs
web/src/Web.App/ViewModels/TrustSpendingViewModel.cs
web/src/Web.App/ViewModels/TrustViewModel.cs
web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
web/tests/Web.Integration.Tests/Pages/Trusts/WhenViewingCensus.cs
web/tests/Web.Integration.Tests/Pages/Trusts/WhenViewingComparison.cs
web/tests/Web.Integration.Tests/Pages/Trusts/WhenViewingDetails.cs
web/tests/Web.Integration.Tests/Pages/Trusts/WhenViewingHome.cs
web/tests/Web.Integration.Tests/Pages/Trusts/WhenViewingSpending.cs
web/tests/Web.Tests/ViewModels/GivenATrustPlanningViewModel.cs
web/tests/Web.Tests/ViewModels/GivenATrustSpendingViewModel.cs
web/tests/Web.Tests/ViewModels/GivenATrustViewModel.cs

[AB#230397](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/230397) [AB#229325](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/229325)
Perform single API call to obtain Trust and related part-School collection rather than require multiple API calls to achieve the same result.
Build and run Platform and Web locally and then browse to Trust home/census/comparison. Visually, results should be identical before and after this change.

Modified `Trust` API response model to include `Schools` collection

---

data-pipeline/src/pipeline/rag.py

- if the comparator-set is empty, no RAG calculations can be made
- this is already skipped for part-year data but this may occur in other circumstances.

fix: skip RAG processing for empty comparator-sets

---

web/src/Web.App/Domain/CostCategories.cs
web/src/Web.App/ViewModels/SchoolSpendingViewModel.cs
web/src/Web.App/Views/School/Index.cshtml
web/src/Web.App/Views/SchoolSpending/_Costs.cshtml
web/src/Web.App/Views/Shared/_RagRatingCommentary.cshtml
web/tests/Web.E2ETests/Features/School/SchoolHome.feature
web/tests/Web.E2ETests/Features/School/SpendingCosts.feature
web/tests/Web.E2ETests/Pages/School/HomePage.cs
web/tests/Web.E2ETests/Pages/School/SpendingCostsPage.cs
web/tests/Web.E2ETests/Steps/School/HomeSteps.cs
web/tests/Web.E2ETests/Steps/School/SpendingCostsSteps.cs

[AB#230746](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/230746) [AB#230538](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/230538)
For the following Cost Categories and if High priority RAG displayed, invert the commentary:
- Teaching and Teaching support staff
- Educational supplies
- Educational ICT
Change may be validated on School home and School spending priorities pages. Sample URNs for schools that should display the updated content: 
- 131251
- 140575
Categories not listed above, or are otherwise not marked as High priority should be unaffected.

Inverted commentary on red RAGs for defined set of cost categories

---

core-infrastructure/src/db/Core.Database/Scripts/014-RebuildFinancialTable.sql
core-infrastructure/src/db/Core.Database/Scripts/024-RebuildFinancialTableCentralServices.sql

Trailing semicolons causing failures during local migrations:
```sh
../core-infrastructure/src/db/Core.Database/Scripts/014-RebuildFinancialTable.sql
Msg 102, Level 15, State 1, Server f4594901140e, Line 8
Incorrect syntax near 'GO'.
```

fix: remove semicolons in migrations

---

front-end-components/index.html
front-end-components/src/index.css

[AB#230801](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/230801) [AB#230800](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/230800)
Locate a benchmark page for a school with comparators that are part-year to validate the change. e.g. URN `143996`

Set chart bar colour for 'other' part-year schools in a comparator set

---

data-pipeline/src/pipeline/part_year/common.py
data-pipeline/src/pipeline/pre_processing.py

`Number of pupils` and `Total Internal Floor Area` should _not_ have default values where missing, to avoid misrepresenting data.
[AB#231997](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/231997)
- remove the code which sets missing values for `Number of pupils` and `Total Internal Floor Area` to the collective median.
- remove the part-year checks which previously ignored those columns (as they would always contain a value).
Pipeline has been run locally and successfully created comparator sets for all Schools/Academies.

fix: remove default-median values for columns

---

data-pipeline/src/pipeline/comparator_sets.py
data-pipeline/src/pipeline/part_year/academies.py
data-pipeline/src/pipeline/pre_processing.py
data-pipeline/tests/unit/comparator_sets/test_part_year.py
data-pipeline/tests/unit/part_year/test_map_academies.py
data-pipeline/tests/unit/pre_processing/conftest.py
data-pipeline/tests/unit/pre_processing/test_aar.py

- previously, they were specifically treated as non-part-year Academies.
- should be instead removed as their net effect is null.
[AB#231999](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/231999)
- removal of previous processing/testing of "1 day" academies
- specifically removing rows from the AAR data where `ACADEMYTRUSTSTATUS` is `1 day`
- for Academies moving between Trusts, there will always be a second AAR row for the full academic year
- for closing Academies, the `1 day` row has no effect (i.e. no financial data, no apportionment)

fix: remove processing of 1-day Academies

---

pipelines/destroy/release.yaml
pipelines/feature/release.yaml
web/terraform/README.md
web/terraform/app-service.tf
web/terraform/cache.tf
web/terraform/storage.tf

[AB#231984](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/231984) [AB#230754](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/230754)
Also fixed Feature pipeline versioning to not generate conflicts when publishing front-end-components.
This has been pushed out to the `d12` feature environment. The Kudu tool may be used to validate the resolved configuration settings. At Web app service level the Key Vault references for any secrets should be used instead. To validate the underlying values, self-assign permission to Key Vault via Access Policies.

Replaced hard-coded app settings in Web app service with Key Vault references

---

data-pipeline/src/pipeline/comparator_sets.py
data-pipeline/tests/unit/comparator_sets/conftest.py
data-pipeline/tests/unit/comparator_sets/test_top_set_urns.py

Any org. for which there is only part-year data cannot appear in the comparator-set of another org.
[AB#231998](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/231998)
- remove previous logic which only restricted the omission of part-year orgs. based on whether they would themselves create a pupil/building comparator-set.
- replace this with a restriction based purely on part-year data being present.
- restore the tests for this particular function.
I've validated this locally by running the pipeline and verifying that all URNs for which there are part-year data _do not_ appear in the pupil/building comparator sets for non-part-year orgs. (note: part-year orgs. _can_ create their own comparator-sets and will appear therein: this is an important …

fix: exclude part-year orgs. from comparator-sets

---

data-pipeline/src/pipeline/pre_processing.py

[AB#231997](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/231997) ([AB#232193](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/232193))
Ensures financial values are written when CS is NaN (due to missing pupil and/or building data)
Validated locally against AAR data

bugfix: ensures finance values are written when CS is nan

---

web/src/Web.App/Domain/OverallPhaseTypes.cs
web/tests/Web.Tests/Infrastructure/Apis/Requests/GivenAPostSchoolComparatorsRequest.cs

Updates OverallPhaseTypes.PupilReferralUnit to correctly match the casing in the db 
Ran locally to confirm LA homepage displaying correctly.

fix: casing for PupilReferralUnit

---

data-pipeline/src/pipeline/pre_processing.py
data-pipeline/tests/unit/pre_processing/test_academies.py

Update "Revenue reserve" calculations as per ticket.
[AB#225541](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/225541)
- refactor to an isolated function
- derive Trust-level values from _final_ Academy values
- apportion the above based on pro-rata pupil basis
`Revenue reserve_CS` is effectively defunct but as it's still in the DB as `RevenueReserveCS` I've zeroed it out to remove in the future.

fix: correct Revenue Reserve calculations

---

data-pipeline/src/pipeline/pre_processing.py

This was removed due to the recent `Revenue reserve` changes. However, BFR requires this.
[AB#225541](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/225541)
Retain the `Trust Revenue reserve` column.
As a result of the recent changes, `Trust Revenue reserve` is the "sum of `Revenue reserve` for all Academies which ended the year in the Trust" _plus_ the "Central Services `Revenue reserve` for that Trust".
i.e. this is the value which is later apportioned to each Academy in the Trust.
Is this correct for BFR?

fix: retain Trust Revenue reserve column

---

platform/src/apis/Platform.Api.Establishment/LocalAuthorities/LocalAuthoritiesService.cs
platform/src/apis/Platform.Api.Establishment/Trusts/TrustsService.cs
web/src/Web.App/Controllers/Api/CensusProxyController.cs
web/src/Web.App/Controllers/Api/ExpenditureProxyController.cs

[AB#228225](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/228225) ([AB#232583](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/232583))
Only show schools in the current submission when viewing LA and/or Trust

bugfix: only show schools that are in current submission

---

.github/workflows/updated-documentation-pr.yml
pipelines/common/push-repo-artifacts.yaml

[AB#231171](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/231171) [AB#229428](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/229428) 
As a follow-up to #1452, fixed GitHub Action that is triggered by a specific tag push in order to automatically submit a pull request.
Validated within branch, but once merged to `main` triggering a new security scan against Web or Platform should conclude with the PR being created based on intermediate pipelines.

Amended GitHub Action trigger that creates a PR from security scan documentation results

---

front-end-components/index.html
front-end-components/src/components/charts/table-chart/component.tsx
front-end-components/src/components/charts/trust-data-tooltip/component.tsx
front-end-components/src/composed/horizontal-bar-chart-wrapper/types.tsx
front-end-components/src/services/types.tsx
front-end-components/src/views/compare-your-trust/partials/balance.tsx
platform/src/apis/Platform.Api.Insight/BudgetForecast/BudgetForecastResponse.cs
platform/tests/Platform.Tests/Insight/BudgetForecast/WhenBudgetForecastReturnsResponseFactoryCreatesResponse.cs
web/tests/Web.A11yTests/AuthPageBase.cs
web/tests/Web.A11yTests/Pages/Schools/Comparators/WhenViewingComparatorsByName.cs
web/tests/Web.A11yTests/Pages/Schools/Comparators/WhenViewingComparatorsRevert.cs
web/tests/Web.A11yTests/Pages/Schools/Comparators/WhenViewingComparatorsSubmit.cs
web/tests/Web.A11yTests/Pages/Trust/Comparators/WhenViewingComparators.cs
web/tests/Web.A11yTests/Pages/Trust/Comparators/WhenViewingComparatorsRevert.cs
web/tests/Web.A11yTests/Pages/Trust/Comparators/WhenViewingComparatorsSubmit.cs

[AB#232577](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/232577) [AB#225541](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/225541)
Also fixed Trust A11y tests, including `DivideByZeroException` in `BudgetForecastReturnResponse`.
View/create a new trust-to-trust comparator set and open the 'Balance' tab. The Revenue Reserve should only show 'totals' rather than central/school split.

Removed dependency on `schoolRevenueReserve` and `centralRevenueReserve` from front-end

---

.github/workflows/updated-documentation-pr.yml
pipelines/platform/security-scan.yaml
pipelines/web/security-scan.yaml

[AB#231848](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/231848) [AB#229428](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/229428) 
Also move downloaded build artifacts into parent folder before committing.
Accidentally pushed condition on 'web' security scan pipeline also reverted.
Validated within branch to correctly remove unexpected characters from 'web' security scan as well as move files to the 'flattened' location. Full run of documentation pipeline not yet executed, but the modified `.md` file looks like it should be accepted now.

Strip unexpected characters from 'web' security scan results

---

platform/src/apis/Platform.Api.Insight/Balance/BalanceModel.cs
platform/src/apis/Platform.Api.Insight/Balance/BalanceResponse.cs
platform/tests/Platform.ApiTests/Features/InsightBalance.feature
platform/tests/Platform.Tests/Insight/Balance/BalanceResponseFactoryCreate/Assertions.cs
platform/tests/Platform.Tests/Insight/Balance/BalanceResponseFactoryCreate/BalanceTestData.json
platform/tests/Platform.Tests/Insight/Balance/BalanceResponseFactoryCreate/TotalBalanceTestData.json

[AB#232578](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/232578) [AB#225541](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/225541)
As a follow-up to #1459, also remove unused fields from response models.
Expected output should be covered by unit/API tests, but Swagger UI could also be used to validate output models and values at http://localhost:7071/api/swagger/ui

Removed dependency on `RevenueReserveCS` from Insight API

---

core-infrastructure/src/db/Core.Database/Scripts/055-RemoveRevenueReserveCs.sql
core-infrastructure/src/db/Core.Database/Scripts/056-RecreateTrustBalanceViews.sql
core-infrastructure/src/db/Core.Database/Scripts/057-RecreateSchoolBalanceViews.sql
data-pipeline/src/pipeline/config.py
data-pipeline/src/pipeline/database.py
data-pipeline/src/pipeline/pre_processing.py

`RevenueReserveCS` no longer required; removed from dependant layers in #1459 and #1463.
[AB#225541](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/225541)
- no longer persist `RevenueReserveCs` to the DB in the data-pipeline
- remove column from financial tables
…

fix: remove RevenueReserveCS

---

web/src/Web.App/AssetSrc/scss/main.scss
web/src/Web.App/Views/School/Index.cshtml
web/tests/Web.E2ETests/Features/School/SchoolHome.feature
web/tests/Web.E2ETests/Pages/School/HomePage.cs
web/tests/Web.E2ETests/Steps/School/HomeSteps.cs

[AB#232097](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/232097) [AB#230874](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/230874)
Added guidance copy as per designs. 
Formatting adjustments to priority panels on school home page only.
View a school homepage to see the guidance and reformatted priority panels. Priority panels and RAG tags on other pages should not be affected by this change.

Added RAG guidance to Spending Priorities on School Homepage

---

core-infrastructure/terraform/databases.tf

[AB#231299](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/231299) - [AB#233110](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/233110)
adds `short_term_retention_policy` and `long_term_retention_policy` to the `azurerm_mssql_database` resource.
Appears Differential backup frequency and PITR retention already default to our desired values but set explicitly in the terraform anyway. Validated in `d16` and Weekly LTR shows 52 weeks as required.

chore: adds retention policies to db

---

web/src/Web.App/Constants/PageTitles.cs
web/src/Web.App/Controllers/StaticContentController.cs
web/src/Web.App/Domain/CostCategories.cs
web/src/Web.App/Extensions/StringExtensions.cs
web/src/Web.App/ViewModels/FinancialDataCustomDataViewModel.cs
web/src/Web.App/ViewModels/SchoolCustomDataChangeViewModel.cs
web/src/Web.App/ViewModels/SchoolCustomDataViewModel.cs
web/src/Web.App/Views/SchoolSpending/Index.cshtml
web/src/Web.App/Views/SchoolSpending/_Costs.cshtml
web/src/Web.App/Views/StaticContent/CostCategories.cshtml
web/src/Web.App/Views/StaticContent/_CategoryAndSubCategoryRow.cshtml
web/tests/Web.E2ETests/Features/CostCategoriesGuidance.feature
web/tests/Web.E2ETests/Features/School/SpendingCosts.feature
web/tests/Web.E2ETests/Pages/CostCategoriesGuidancePage.cs
web/tests/Web.E2ETests/Pages/School/SpendingCostsPage.cs
web/tests/Web.E2ETests/Steps/CostCategoriesGuidanceSteps.cs
web/tests/Web.E2ETests/Steps/School/SpendingCostsSteps.cs
web/tests/Web.Tests/Extensions/GivenAString.cs

[AB#232099](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/232099) [AB#230876](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/230876)
Added cost category commentary to School Spending Priorities page
Refactored definitions of sub-cost categories in a few places
Added `ToLower()` `string` extension method
Added cost categories guidance page and link from School Spending Priorities page
View the Spending Priorities page for any school. Additional commentary should be available below each summary chart on the  priority categories. Under the first page `<h2>` there is also an additional link that opens in a new tab that displays additional guidance.

Added Cost Category commentary and guidance

---

data-pipeline/src/pipeline/input_schemas.py
data-pipeline/src/pipeline/main.py
data-pipeline/src/pipeline/maintained_schools.py
data-pipeline/src/pipeline/pre_processing.py
data-pipeline/tests/unit/pre_processing/conftest.py
data-pipeline/tests/unit/pre_processing/test_maintained_schools.py

Handling of Federations has changed: the previous hard-/soft-Federation distinction has been dropped and data can be derived entirely on `LAEstab`/`Lead school in federation` values.
[AB#232745](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/232745)
- previous hard-/soft-Federation logic has been deprecated
- each Maintained School instead references the lead-School in its Federation (where present)
- Federation data can be derived based on this value
Successfully ran locally and populated `FederationLeadURN` and `FederationLeadName` as expected.

feat: update Federation handling for Maintained Schools

---

core-infrastructure/src/db/Core.Database/Scripts/059-RemoveSetType.sql
data-pipeline/src/pipeline/database.py
data-pipeline/src/pipeline/main.py
documentation/data/2_Models.md
documentation/data/3_Processing.md

"Mixed" datasets are no longer required and comparator-set/RAG processing thereof can be removed.
Note: the "all-schools" data, however, is being retained as this is useful in later processing.
[AB#232973](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/232973)
- remove generation of comparator-sets and RAG for mixed datasets
- remove references to mixed/unmixed data throughout
- remove `SetType` from all DB tables and associated constraints
- remove references to `SetType` from docs.
Note: this can't be merged until the API/UI is updated to accommodate these changes (#233103).

feat: remove processing of mixed datasets

---

web/src/Web.App/Controllers/SchoolController.cs
web/src/Web.App/ViewModels/SchoolViewModel.cs
web/src/Web.App/Views/School/NonLeadFederation.cshtml
web/tests/Web.Integration.Tests/Pages/Schools/WhenViewingHome.cs

[AB#232741](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/232741) - [AB#233270](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/233270)
school controller updated to to return NonLeadFederation view when the school is a non lead federation, view model updated.
minor update to integration tests to fix now failing tests
Waiting on pipeline run to fully test.
Further integration tests will be added in a future PR following more work on this feature.

Non lead federation school homepage

---

data-pipeline/src/pipeline/main.py

For no other reason that it bothers me seeing `Computing RAG done in 989.3214044570923 seconds` in the logs.
make sure all time-related logs are comma-formatted and restricted to 2 decimal places.
In no way a priority, just a formatting change for the logs.

fix: consistent log format for timestamps

---

web/Web.sln.DotSettings
web/src/Web.App/AssetSrc/scss/main.scss

[AB#233362](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/233362) [AB#230874](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/230874)
Responsive-friendly CSS fix
View school homepage in different responsive views to ensure margin renders correctly.

Removed margin at top of RAG guidance when positioned to the right of the spending priorities only

---

web/src/Web.App/Views/SchoolComparison/Index.cshtml
web/tests/Web.E2ETests/Pages/School/CompareYourCostsPage.cs

[AB#233614](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/233614) [AB#230616](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/230616)
Part-reverts a change from #1482.

Reinstated 'part year' banner on School Comparison page

---

web/tests/Web.Integration.Tests/Pages/Schools/WhenViewingHomeAsFederation.cs

[AB#232741](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/232741)/[AB#232745](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/232745) - [AB#233407](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/233407)
Adds integration tests for viewing the school homepage as a federation school, both as lead and non-lead.
`Schools/WhenViewingHome` is quite busy so rather than add further to the theories for each test and overcomplicate `AssertPageLayout` and `SetupNavigateInitPage` the tests for this behaviour have been created separately which does mean some repetition but hopefully still easier to maintain. Happy to take guidance on that if the reviewer disagrees.

chore: adds integration tests for school homepage as federation school

---

web/src/Web.App/Controllers/SchoolComparisonController.cs
web/src/Web.App/ViewModels/SchoolComparisonViewModel.cs
web/src/Web.App/Views/SchoolComparison/Index.cshtml
web/tests/Web.E2ETests/Features/School/CompareYourCosts.feature
web/tests/Web.E2ETests/Pages/School/CompareYourCostsPage.cs
web/tests/Web.E2ETests/Steps/School/CompareYourCostsSteps.cs
web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
web/tests/Web.Integration.Tests/Pages/Schools/WhenViewingComparison.cs
web/tests/Web.Tests/ViewModels/GivenASchoolComparisonViewModel.cs

[AB#233725](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/233725) [AB#230616](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/230616)
Also partially reverts E2E changes originally made in #1482 by removing user defined comparator set creation outside the `School create comparator set` feature. This will prevent a race condition on the current 'active' comparators for the same test school which was causing recent pipeline runs to fail.

Replaced comparator set existence check on part-year status with explicit comparator set lookup

---

web/src/Web.App/ViewModels/SchoolComparisonViewModel.cs
web/tests/Web.Integration.Tests/Pages/Schools/WhenViewingComparison.cs
web/tests/Web.Tests/ViewModels/GivenASchoolComparisonViewModel.cs

[AB#233725](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/233725) [AB#230616](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/230616)
Follow-up to #1489 following additional QA
Validate the following scenarios in `d01`:
1. Part year submission + no comparator set => banner + mock up: `100885`, `146059`
1. Full submission + no comparator set => mock up: `133545`
1. Part year submission + with comparator set => banner + normal: `147069`, `105296`, `105296`
1. Full submission + with comparator set => normal: `100000`, `145956`

Updated comparator set existence check to include empty as well as missing comparator sets

---

pipelines/common/app-service-settings-refresh.yaml
pipelines/platform/deployment.yaml
pipelines/web/deployment.yaml

[AB#234535](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/234535) [AB#229479](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/229479)
Instead of waiting up to 24 hours for unversioned Key Vault references to be updated on App Services, use [Azure Rest API to refresh](https://stackoverflow.com/a/79014000/504477) during Platform and Web deployments. 
Deployed to and tested in `d11` feature environment. Responses received successfully from `POST`s to the `.../config/configreferences/appsettings/refresh` endpoints, e.g.:
```json
{
"value": [
{
"id": ".../config/configreferences/appsettings/Apis__Benchmark__Key",
"name": "Apis__Benchmark__Key",
"type": "Microsoft.Web/sites/config/configreferences",
"location": "West …
```

Sync Key Vault references after deploying App Services

---

data-pipeline/src/pipeline/maintained_schools.py
data-pipeline/src/pipeline/pre_processing.py
data-pipeline/tests/unit/pre_processing/conftest.py
data-pipeline/tests/unit/pre_processing/test_maintained_schools.py
pipelines/common/validate-branch.yaml
pipelines/common/vars.yaml

Financial data for lead-schools are submitted as the aggregate of all schools in the Federation. Metrics (e.g. pupil numbers) are not, however. Lead-school metrics should therefore reflect the aggregated values across all Federation members.
[AB#234742](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/234742)
- extend the recently-added Federation logic to aggregate require metrics based on the `Lead school in federation` value.
- update the existing Maintained School data with these aggregate values.
WIP at the moment; needs testing.

feat: aggregate lead-school data for Federations

---

data-pipeline/src/pipeline/maintained_schools.py
data-pipeline/tests/unit/pre_processing/test_maintained_schools.py

incorrectly joining on `Federation LAEstab`, leading to aggregation for Federation members as well as leads.
[AB#234742](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/234742)
- join the aggregated data on `LAEstab`, not `Federation LEAstab`
- add a test to validate that non-lead-schools are unaffected
Needs validating in a local run of the pipeline (and I'm having issues with Storage Explorer).

fix: correct Federation-aggregation logic

---

data-pipeline/src/pipeline/main.py
data-pipeline/src/pipeline/pre_processing.py
data-pipeline/tests/unit/pre_processing/test_aar.py

See ticket for details: `Direct revenue financing (Revenue contributions to capital)` shouldn't be part of the `Total Expenditure` calculation for Academies (inc. Central Services).
[AB#235396](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/235396)
deduction of `Direct revenue financing (Revenue contributions to capital)` removed from `Total Expenditure` from both AAR and Central Services data.
N/A

fix: remove "Direct revenue financing"

---

core-infrastructure/terraform/README.md
core-infrastructure/terraform/databases.tf
core-infrastructure/terraform/provider.tf
pipelines/common/destroy-terraform.yaml
pipelines/common/fmt-validate-terraform.yaml
pipelines/common/run-terraform.yaml
pipelines/common/sync-terraform.yaml

[AB#235615](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/235615) [AB#235614](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/235614)
Bumped Terraform providers in Core. `azure/azapi` v2.0 is a major update with some [breaking changes](https://registry.terraform.io/providers/Azure/azapi/latest/docs/guides/2.0-upgrade-guide#breaking-changes).
This requires latest Terraform to be installed to prevent `This configuration does not support Terraform version XXX` error.

Bumped `azapi` and `azurerm` Terraform providers in Core

---

core-infrastructure/terraform/storage.tf
data-pipeline/terraform/container_app/data.tf
data-pipeline/terraform/container_app/main.tf
data-pipeline/terraform/container_app/variables.tf
data-pipeline/terraform/container_apps.tf
data-pipeline/terraform/data.tf
platform/terraform/functions.tf

The current `data-pipeline-job-start` queue will instead be split into `data-pipeline-job-custom-start` and `data-pipeline-job-default-start` queues, each serviced by a distinct Container App.
- add the new queues
- refactor the existing `container_apps.tf` into a Terraform module
- call this module twice, once for `default` and once for `custom` apps.
WIP

Split default/custom Container Apps.

---

data-pipeline/terraform/README.md
data-pipeline/terraform/container_app/README.md
data-pipeline/terraform/container_app/variables.tf
data-pipeline/terraform/container_apps.tf

Incorrect Resource Group passed to Storage Account/Registry.
Also updated the existing README and added one for the new module.
Pass a distinct Resource Group name for the Container Apps (as multiple resource types use the `*-ebis-core` name).
Definitely needs sanity-checking; I've reviewed the changes and values from the existing infra. but definitely needs another pair of eyes (or a `terraform plan`, if folks have the means).

fix: correct resource groups

---

data-pipeline/terraform/container_app/README.md
data-pipeline/terraform/container_app/main.tf
data-pipeline/terraform/container_app/variables.tf
data-pipeline/terraform/container_apps.tf

Container App name must be unique.
Pass a suffix to be appended to the Container App name.
`terraform plan` actually passes; this failed at the `apply`.

fix: Container App name must be unique

---

data-pipeline/terraform/container_app/main.tf

Image lacks the registry prefix:
```sh
'Invalid value: \"fbit-data-pipeline:1.1.7\": ET https:: UNAUTHORIZED:
```
Include prefix as per previous config.
…

fix: include registry prefix for image

---

data-pipeline/terraform/container_app/README.md
data-pipeline/terraform/container_app/data.tf
data-pipeline/terraform/container_app/main.tf
data-pipeline/terraform/container_app/variables.tf
data-pipeline/terraform/container_apps.tf

`container-app-resource-group-name` was added/passed but unused.
- correctly reference `container-app-resource-group-name` for the Container App resources.
- make the "core" Resource Group variable name clearer.
…

fix: add Container App to correct Resource Group

---

web/src/Web.App/ViewModels/SchoolBenchmarkingReportCardsViewModel.cs
web/src/Web.App/Views/SchoolBenchmarkingReportCards/Index.cshtml
web/src/Web.App/Views/SchoolBenchmarkingReportCards/_Costs.cshtml
web/src/Web.App/Views/SchoolBenchmarkingReportCards/_PriorityAreasOther.cshtml
web/tests/Web.Tests/ViewModels/GivenASchoolBenchmarkingReportCardsViewModel.cs

[AB#235831](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/235831) [AB#222988](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/222988) #1556
Additional spending priorities in the same vein as the dependent #1556. Space issue meant that the only sensible way to prevent text wrapping for building area-specific cost categories was to shorten `per square metre` to `per sq. metre`. If this is not sufficient it could be revisited by playing with the CSS again (with care over responsiveness).

Added 'other' spending priority categories to BRCs

---

web/src/Web.App/AssetSrc/scss/main.scss
web/src/Web.App/Controllers/SchoolBenchmarkingReportCardsController.cs
web/src/Web.App/ViewModels/SchoolBenchmarkingReportCardCensusViewModel.cs
web/src/Web.App/ViewModels/SchoolBenchmarkingReportCardsViewModel.cs
web/src/Web.App/Views/SchoolBenchmarkingReportCards/Index.cshtml
web/src/Web.App/Views/SchoolBenchmarkingReportCards/_Metric.cshtml
web/src/Web.App/Views/SchoolBenchmarkingReportCards/_PupilWorkforceMetrics.cshtml
web/tests/Web.Tests/ViewModels/GivenASchoolBenchmarkingReportCardsViewModel.cs

[AB#235833](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/235833) [AB#222988](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/222988) #1557
Metrics added to BRCs page. GDS 'half column' layout not used due to design requirements for gap and vertical line, so flexbox used instead on `$tablet` breakpoint and greater.

Added pupil workforce metrics to BRCs

---

web/src/Web.App/ViewModels/LocalAuthorityViewModel.cs

[AB#235679](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/235679), closes [AB#236366](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/236366)
Adds post-16 to phase order mapping and adds default order for any phase not explicitly set.
N/A

bugfix: ensures all phases returns an order for an LA

---

pipelines/web/build.yaml
pipelines/web/steps/run-a11y-tests.yaml

[AB#235250](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/235250), [AB#236368](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/236368)
Re-enables a11y tests in pipeline.
N/A

chore: re-enable a11y tests in pipeline

---

support-analytics/README.md
support-analytics/terraform/README.md
support-analytics/terraform/provider.tf
support-analytics/terraform/queries.tf
support-analytics/terraform/queries/functions/get-school-benchmarking-report-cards-requests.kql
web/src/Web.App/Attributes/RequestTelemetry/RequestTelemetryAttribute.cs
web/src/Web.App/Attributes/RequestTelemetry/SchoolBenchmarkingReportCardsTelemetry.cs
web/src/Web.App/Constants/TrackedRequestType.cs
web/src/Web.App/Controllers/SchoolBenchmarkingReportCardsController.cs
web/src/Web.App/Views/Shared/Components/SchoolFinanceTools/Default.cshtml
web/tests/Web.Integration.Tests/Pages/Schools/WhenViewingHome.cs
web/tests/Web.Integration.Tests/Pages/Schools/WhenViewingHomeAsFederation.cs
web/tests/Web.Integration.Tests/Paths.cs
web/tests/Web.Tests/Attributes/GivenASchoolBenchmarkingReportCardsRequestTelemetryAttribute.cs
web/tests/Web.Tests/Attributes/GivenASchoolRequestTelemetryAttribute.cs
web/tests/Web.Tests/Attributes/GivenATrustRequestTelemetryAttribute.cs

[AB#236266](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/236266) [AB#222988](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/222988)
Updated telemetry tracking to include `referrer` from query string for BRCs page only. Added `GetSchoolBenchmarkingReportCardsRequests` function to Log Analytics workspace. Documented custom properties logged with majority of requests to Web service.
Browsing to the BRC page from the School homepage should append `?referrer=school-home` to the URL and log the new telemetry property to App Insights. Browsing directly to that page without the `?referrer=` should not have any adverse impact. The `.kql` file in this PR may be executed directly against Log Analytics to show the …

Added explicit App Insights telemetry tracking for referrals to BRCs page

---

support-analytics/terraform/README.md
support-analytics/terraform/action-group.tf
support-analytics/terraform/logic-app.tf
support-analytics/terraform/main.tf
support-analytics/terraform/terraform.tfvars
support-analytics/terraform/variables.tf

[AB#234736](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/234736) [AB#225322](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/225322)
Logic App authored to post an alert schema-ed message to a Teams Channel from an Action Group. Other properties on the source message are also available, so the target message templates may be tweaked as required.
Deployed to and tested in `d12` feature environment. Target Team and Channel may be set in `support` Variable Group. Authorisation between the provisioned API Connection in Azure and Teams in Office 365 does, unfortunately, require interaction via Azure Portal. This is a one-off task per deployment, at least until the respective authorising user expires in Office 365.

Post alerts to Teams channel

---

web/tests/Web.A11yTests/Pages/Schools/WhenViewingSpendingPriorities.cs

[AB#233972](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/233972), [AB#236856](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/236856)
Adds a11y tests for spending priorities page. This should fail pending bug fix,
As expected the page fails the Axe assertions

bugfix: adds a11y tests for spending priorities page

---

front-end-components/src/index.css

[AB#233972](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/233972), [AB#236858](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/236858)
Removes grey colour from suffix due to a11y contrast issues
a11y tests pass locally

bugfix: remove grey colour from suffix due a11y contrast issue

---

core-infrastructure/src/db/Core.Database/Scripts/062-CreateSchoolMetricRAGView.sql
platform/src/apis/Platform.Api.Insight/Configuration/Services.cs
platform/src/apis/Platform.Api.Insight/Domain/CostCategory.cs
platform/src/apis/Platform.Api.Insight/Domain/RagRating.cs
platform/src/apis/Platform.Api.Insight/Income/Income.cs
platform/src/apis/Platform.Api.Insight/MetricRagRatings/MetricRagRatingService.cs
platform/src/apis/Platform.Api.Insight/MetricRagRatings/MetricRagRatingsFunctions.cs
platform/src/apis/Platform.Api.Insight/MetricRagRatings/MetricRagRatingsParameters.cs
platform/src/apis/Platform.Api.Insight/OpenApi/Examples/ExpenditureExamples.cs
platform/src/apis/Platform.Api.Insight/Validators/IncomeParametersValidator.cs
platform/src/apis/Platform.Api.Insight/Validators/MetricRagRatingsParametersValidator.cs
platform/tests/Platform.ApiTests/Features/InsightMetricRagRatings.feature
platform/tests/Platform.ApiTests/Steps/InsightMetricRagRatingSteps.cs
platform/tests/Platform.Tests/Insight/MetricRagRatings/WhenBudgetForecastServiceQueriesAsync.cs
platform/tests/Platform.Tests/Insight/MetricRagRatings/WhenMetricRagRatingsParametersSetsValues.cs
platform/tests/Platform.Tests/Insight/Validators/WhenMetricRagRatingsParametersValidatorValidates.cs
web/src/Web.App/Controllers/TrustController.cs
web/src/Web.App/Controllers/TrustSpendingController.cs
web/src/Web.App/Views/TrustSpending/Index.cshtml
web/tests/Web.E2ETests/Features/Trust/SpendingCosts.feature
web/tests/Web.E2ETests/Features/Trust/TrustHome.feature
web/tests/Web.E2ETests/Pages/Trust/HomePage.cs
web/tests/Web.E2ETests/Pages/Trust/SpendingCostsPage.cs
web/tests/Web.E2ETests/Selectors.cs
web/tests/Web.E2ETests/Steps/Trust/HomeSteps.cs
web/tests/Web.E2ETests/Steps/Trust/SpendingCostsSteps.cs
web/tests/Web.E2ETests/Web.E2ETests.csproj
web/tests/Web.Integration.Tests/Pages/Trusts/WhenViewingHome.cs

[AB#236605](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/236605) [AB#235684](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/235684)
- `[dbo].[SchoolMetricRAG]` view created to include `OverallPhase` and `LaCode` as well as contents of `[dbo].[MetricRAG]`
- Insight API updates to support additional query parameters `companyNumber`, `laCode` and `phase`
- Validation added to RAG-related parameters
- Consume modified endpoint from Web
- Additional and modified tests to complete coverage of the above
View addition already pushed to `d02` to aid validation. Modify config as appropriate and start the Platform APIs. All API tests should pass. Start Web, pointing to the local API. All E2E tests should pass. View a …

Support Company Number or LA Code with Phase as well as collection of URNs for Metric RAG Ratings Query endpoint

---

web/tests/Web.E2ETests/Pages/LocalAuthority/BenchmarkCensusPage.cs
web/tests/Web.E2ETests/Pages/Trust/BenchmarkCensusPage.cs

[AB#236607](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/236607) [AB#235684](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/235684)
E2E tests currently failing against `d02` due to the merge of #1585 fixing a missing Census chart.

E2E fix post merge of 536984ada6cea7aa6d5c8d095dad85d7845832d3

---

web/src/Web.App/Controllers/SchoolBenchmarkingReportCardsController.cs
web/src/Web.App/ViewModels/SchoolBenchmarkingReportCardsUnavailableViewModel.cs
web/src/Web.App/Views/SchoolBenchmarkingReportCards/Unavailable.cshtml
web/src/Web.App/Views/SchoolBenchmarkingReportCards/_Introduction.cshtml
web/tests/Web.E2ETests/Extensions/PageExtensions.cs
web/tests/Web.E2ETests/Features/School/SchoolBenchmarkingReportCards.feature
web/tests/Web.E2ETests/Features/School/SchoolHome.feature
web/tests/Web.E2ETests/Pages/School/SchoolBenchmarkingReportCardsPage.cs
web/tests/Web.E2ETests/Steps/School/HomeSteps.cs
web/tests/Web.E2ETests/Steps/School/SchoolBenchmarkingReportCardsSteps.cs
web/tests/Web.Integration.Tests/Pages/Schools/WhenViewingBenchmarkingReportCards.cs

[AB#236251](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/236251) [AB#222988](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/222988)
Non-lead Federated schools, part year schools, or those with missing financials should not be able to view their BRCs. Instead they are presented with a `404` with a warning message and a button to take them back to the School homepage.
Schools with sufficient data should not be affected. Schools in one of the exception states should see the warning banner, e.g. (in `d02`):

Display custom `404` page when BRCs not available to school due to its financial position

---

pipelines/platform/security-scan.yaml
pipelines/web/security-scan.yaml

[AB#237472](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/237472) [AB#237473](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/237473) [AB#236431](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/236431)
Updated cache image names, after updating the `docker run` command.

Updated cached docker images for security scans

---

web/src/Web.App/Controllers/SchoolSpendingController.cs
web/tests/Web.Integration.Tests/Pages/Schools/WhenViewingSpending.cs

[AB#237809](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/237809) [AB#237597](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/237597)
Fix may be validated with any of the URNs currently failing in prod and then viewing the Spending Priorities page:
- `146949`
- `148595`
- `148060`
- `147574`
- `149075`
- `146822`
- `147183`
- `148561`
Viewing the 'two sets of comparator schools' for the above should also show `0` for the building comparators.

Resolved invalid pattern match when resolving expenditure for building comparator set

---

core-infrastructure/terraform/storage.tf

[AB#236226](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/236226) [AB#238602](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/238602)
Removes redundant `data-pipeline-job-start` queue
N/A

feat: removes redundant queue from storage account

---

web/src/Web.App/Controllers/SchoolController.cs
web/src/Web.App/Domain/CostCategories.cs
web/src/Web.App/Domain/Insight/RagRating.cs
web/src/Web.App/ViewModels/SchoolResourcesViewModel.cs
web/src/Web.App/ViewModels/SchoolViewModel.cs
web/src/Web.App/Views/School/Resources.cshtml
web/src/Web.App/Views/School/_RecommendedResources.cshtml
web/src/Web.App/Views/SchoolSpending/_Costs.cshtml
web/tests/Web.E2ETests/Features/School/CommercialResources.feature
web/tests/Web.E2ETests/Features/School/SpendingCosts.feature
web/tests/Web.Integration.Tests/Pages/Schools/WhenViewingResources.cs
web/tests/Web.Tests/Domain/GivenACostCategory.cs
web/tests/Web.Tests/ViewModels/GivenASchoolResourcesViewModel.cs

[AB#238511](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/238511) [AB#236925](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/236925)
For the cost categories `EducationalIct`, `EducationalSupplies`, `TeachingStaff`:
- Remove commercial resources from Spending Priorities if red/amber RAG is less than average
- Remove commercial resources from Find Ways to Spend Less if red/amber RAG is less than average
- E2E, integration and unit test coverage
Identify schools with RAGs in the state(s) above to validate that the commercial resources are/not present as per the requirement. 
> **NOTE:** This PR intentionally does not make any changes to `RagRating.Mean` to reflect the actual calculation average, which is median. …

Remove commercial resources for certain categories if red/amber RAG is less than average

---

core-infrastructure/terraform/README.md
platform/terraform/modules/functions/main.tf
support-analytics/terraform/README.md

[AB#238781](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/238781) [AB#238783](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/238783)
`AzureWebJobsDashboard` setting is deprecated and is only supported when running on version 1.x of the Azure Functions runtime.
Setting builtin_logging_enabled to false disables this setting
N/A

chore: explicitly disable AzureWebJobsDashboard setting

---

front-end-components/src/components/auto-complete/component.tsx
front-end-components/src/components/auto-complete/types.tsx
front-end-components/src/views/find-organisation/partials/la-input.tsx
front-end-components/src/views/find-organisation/partials/school-input.tsx
front-end-components/src/views/find-organisation/partials/trust-input.tsx
platform/src/abstractions/Platform.Search/Validators/PostSuggestRequestValidator.cs
platform/src/apis/Platform.Api.Establishment/Configuration/Services.cs
platform/src/apis/Platform.Api.Establishment/LocalAuthorities/LocalAuthoritiesFunctions.cs
platform/src/apis/Platform.Api.Establishment/Schools/SchoolsFunctions.cs
platform/src/apis/Platform.Api.Establishment/Trusts/TrustsFunctions.cs
platform/tests/Platform.ApiTests/Features/EstablishmentLocalAuthorities.feature
platform/tests/Platform.ApiTests/Features/EstablishmentSchools.feature
platform/tests/Platform.ApiTests/Features/EstablishmentTrusts.feature
platform/tests/Platform.ApiTests/Steps/EstablishmentLocalAuthoritiesSteps.cs
platform/tests/Platform.ApiTests/Steps/EstablishmentSchoolsSteps.cs
platform/tests/Platform.ApiTests/Steps/EstablishmentTrustsSteps.cs
platform/tests/Platform.Tests/Search/Validators/PostSuggestRequestValidatorValidates.cs

[AB#238713](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/238713) [AB#235691](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/235691)
- Trim input on front end
- Additional validation on search text in API
`front-end-component` will need building and pushing to `Web` to validate the component change locally. If this is not done, and >100 characters are entered into the suggester then the API will reject with a `400` instead of Azure Search.

Trim search suggester input to `100` characters before submitting

---

web/src/Web.App/Constants/OrganisationCategories.cs
web/src/Web.App/Extensions/ServiceCollectionExtensions.cs
web/src/Web.App/Program.cs
web/src/Web.App/Services/ClaimsIdentifierService.cs
web/tests/Web.Tests/Services/WhenClaimsIdentifierServiceIsCalled.cs

[AB#236854](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/236854) 
[AB#236921](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/236921)
Closes [AB#237759](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/237759)
Closes [AB#238501](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/238501)
- Similar to the approach for Trusts look up for all maintained schools in the local authority performed and claims for those schools added for the user when they log in with an `organisation.category.id` of `002`
- When `TrustCompanyNumber` is present in FBIT for a user logging in with a school adds the claim for the parent Trust
- Refactor into a service …

feat: adds additional dsi claims to la users for their schools and academies for their parent trust

---

web/src/Web.App/Controllers/SchoolPlanningCreatePlanController.cs
web/src/Web.App/Views/SchoolPlanningCreate/Start.cshtml
web/tests/Web.Integration.Tests/Pages/Schools/FinancialPlanning/WhenViewingPlanningSelectYear.cs

[AB#238828](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/238828) [AB#235762](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/235762)
Integration tests added to cover in/valid pre-populate states.

Skip 'pre-populate' stage of CFP if school has insufficient data to use

---

data-pipeline/README.md
data-pipeline/src/pipeline/comparator_sets.py
data-pipeline/src/pipeline/database.py
data-pipeline/src/pipeline/main.py
data-pipeline/src/pipeline/message.py
data-pipeline/src/pipeline/rag.py
documentation/features/6_Orchestrator.md
platform/src/abstractions/Platform.Functions/Messages/PipelineFinishMessage.cs
platform/src/abstractions/Platform.Functions/Messages/PipelineMessagePayload.cs
platform/src/abstractions/Platform.Functions/Messages/PipelinePendingMessage.cs
platform/src/abstractions/Platform.Functions/Messages/PipelineStartCustomMessage.cs
platform/src/abstractions/Platform.Functions/Messages/PipelineStartDefaultMessage.cs
platform/src/abstractions/Platform.Functions/Messages/PipelineStartMessage.cs
platform/src/apis/Platform.Api.Benchmark/ComparatorSets/ComparatorSetsFunctions.cs
platform/src/apis/Platform.Api.Benchmark/ComparatorSets/ComparatorSetsService.cs
platform/src/apis/Platform.Api.Benchmark/CustomData/CustomDataFunctions.cs
platform/src/apis/Platform.Api.Benchmark/CustomData/CustomDataRequest.cs
platform/src/apis/Platform.Api.Insight/BudgetForecast/BudgetForecastFunctions.cs
platform/src/apis/Platform.Api.Insight/BudgetForecast/BudgetForecastReturnParameters.cs
platform/src/apis/Platform.Api.Insight/MetricRagRatings/MetricRagRatingParameters.cs
platform/src/apis/Platform.Api.Insight/MetricRagRatings/MetricRagRatingService.cs
platform/src/apis/Platform.Orchestrator/PipelineFunctions.cs
platform/tests/Platform.Tests/Insight/MetricRagRatings/WhenMetricRagRatingParametersSetsValues.cs
platform/tests/Platform.Tests/Orchestrator/Search/WhenPipelineStartCustomMessageCreatesFromPending.cs
platform/tests/Platform.Tests/Orchestrator/Search/WhenPipelineStartDefaultMessageCreatesFromPending.cs

Allow for processing of Academy, Maintained and BFR data from different years/sources.
[AB#232974](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/232974)
[AB#239415](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/239415)
- update docs. for expected message format
- process ancillary files separately for Academies, Maintained and BFR
- avoid separate processing if actually referencing the same source
Successfully ran locally with a `default` message:
```json
{
"type": "default",
"runId": 2023,
"year": {
"aar": 2023,
"cfr": 2023,
"bfr": 2023
}
}
```

feat: separate AAR, CFR, BFR processing

---

web/src/Web.App/ViewModels/SchoolFinancialBenchmarkingInsightsSummaryViewModel.cs
web/src/Web.App/Views/SchoolFinancialBenchmarkingInsightsSummary/_PriorityAreasAllSchools.cshtml
web/src/Web.App/Views/SchoolFinancialBenchmarkingInsightsSummary/_PriorityAreasOther.cshtml
web/src/Web.App/Views/SchoolFinancialBenchmarkingInsightsSummary/_PupilWorkforceMetrics.cshtml
web/tests/Web.E2ETests/Features/School/SchoolFinancialBenchmarkingInsightsSummary.feature
web/tests/Web.E2ETests/Pages/School/SchoolFinancialBenchmarkingInsightsSummaryPage.cs
web/tests/Web.E2ETests/Steps/School/SchoolFinancialBenchmarkingInsightsSummarySteps.cs
web/tests/Web.Integration.Tests/Pages/Schools/WhenViewingFinancialBenchmarkingInsightsSummary.cs
web/tests/Web.Tests/ViewModels/GivenASchoolFinancialBenchmarkingInsightsSummaryViewModel.cs

[AB#240076](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/240076) [AB#222988](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/222988)
Updated model to perform RAG and Census presence check and render message instead of summary content if not available.
May be validated in `d02` using URN `990754`, or URN `100060` in `d01`.

Display feedback in FBIS when RAG or Census data missing to prevent empty section render

---

front-end-components/index.html
front-end-components/src/components/charts/establishment-tick/component.tsx
front-end-components/src/components/charts/establishment-tick/types.tsx
front-end-components/src/composed/horizontal-bar-chart-wrapper/composed.tsx

[AB#240111](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/240111) [AB#226832](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/226832)
`<HorizontalBarChartWrapper>` and `<EstablishmentTick>` front end component updates.
Build `front-end-components` and copy to `web`, or run vite server to validate.

Maintain state of 'focused' tick tooltip(s) and prevent rechart tooltip from rendering at the same time

---

support-analytics/README.md
support-analytics/terraform/README.md
support-analytics/terraform/adaptive-cards/alert-assigned.json
support-analytics/terraform/adaptive-cards/alert-fired.json
support-analytics/terraform/adaptive-cards/alert-resolved.json
support-analytics/terraform/logic-app.tf

[AB#240303](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/240303) [AB#236780](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/236780)
Logic app code changes for more joined up alert reporting.
Deployed to `d17` feature environment which has been manually configured to point to the `FBIT Alerts - Development` channel in Teams for testing purposes. Upon a new alert firing, the 'fired' adaptive card is posted, which can then be self-assigned and updated to the 'assigned' card. Later, once resolved, the 'resolved' card is updated into the original message (based on the matching `alertId` from the last ~10 messages in the channel). See story or use VS Code plugin to view adaptive card designs.

Replaced Teams Alert basic message with adaptive cards

---

support-analytics/terraform/README.md
support-analytics/terraform/adaptive-cards/alert-assigned-minimal.json
support-analytics/terraform/adaptive-cards/alert-fired-minimal.json
support-analytics/terraform/adaptive-cards/alert-fired.json
support-analytics/terraform/adaptive-cards/alert-resolved-minimal.json
support-analytics/terraform/adaptive-cards/alert-resolved.json
support-analytics/terraform/logic-app.tf

[AB#240650](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/240650) [AB#236780](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/236780)
1. Ensured message correlation done by original fired date time rather than alert ID when updating based on a new HTTP trigger (the mixed en-US date format is intentional and is caused by some inconsistent date formatting within Logic Apps)
2. Support 'minimal' data alert types from Azure Monitor that previously caused Logic App to fail
May be tested in `d17` by firing and then resolving a test to the action group. To resolve the test message, obtain the `body` from the original test trigger, change the monitor condition to `Resolved` and add a `resolvedDateTime`. Then choose Run …

Modify Teams Alert logic app to ensure correct message ID is updated for `resolved` monitor state message

---

web/src/Web.App/Infrastructure/Apis/ApiRequests/PostSchoolComparatorsRequest.cs
web/src/Web.App/ViewModels/ISchoolKeyInformationViewModel.cs
web/src/Web.App/ViewModels/SchoolComparatorsPreviewViewModel.cs
web/src/Web.App/ViewModels/SchoolFinancialBenchmarkingInsightsSummaryViewModel.cs
web/src/Web.App/ViewModels/SchoolViewModel.cs
web/src/Web.App/ViewModels/UserDefinedSchoolCharacteristicViewModel.cs
web/src/Web.App/Views/School/NonLeadFederation.cshtml
web/src/Web.App/Views/SchoolComparatorsCreateBy/Characteristic.cshtml
web/src/Web.App/Views/SchoolComparatorsCreateBy/Preview.cshtml
web/src/Web.App/Views/Shared/_SchoolKeyInformation.cshtml
web/tests/Web.E2ETests/Features/School/SchoolFinancialBenchmarkingInsightsSummary.feature
web/tests/Web.E2ETests/Pages/School/SchoolFinancialBenchmarkingInsightsSummaryPage.cs
web/tests/Web.E2ETests/Selectors.cs
web/tests/Web.Integration.Tests/Pages/Schools/WhenViewingDetails.cs
web/tests/Web.Integration.Tests/Pages/Schools/WhenViewingFinancialBenchmarkingInsightsSummary.cs
web/tests/Web.Integration.Tests/Pages/Schools/WhenViewingHome.cs
web/tests/Web.Integration.Tests/Pages/Schools/WhenViewingHomeAsFederation.cs
web/tests/Web.Tests/Infrastructure/Apis/Requests/GivenAPostSchoolComparatorsRequest.cs

[AB#240745](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/240745) [AB#239852](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/239852)
This does not remove the fields from underlying domain models, as the response is still returned by the dependent APIs. Only the view models and views themselves, as well as tests, are affected.

Remove all 'Ofsted' references from Razor views

---

pipelines/common/publish-sharepoint-artifacts.yaml
pipelines/common/scripts/UploadToSharePoint.ps1
pipelines/documentation/build.yaml

[AB#238665](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/238665) [AB#209098](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/209098)
Documentation pipeline addition to push `.pdf` artifacts to SharePoint using the Enterprise Application credentials maintained in the `sharepoint` variable library.

Publish documentation to SharePoint using PowerShell PnP

---

front-end-components/src/components/charts/utils.test.ts
front-end-components/src/components/charts/utils.ts
web/src/Web.App/Extensions/DecimalExtensions.cs
web/tests/Web.E2ETests/Features/School/SchoolFinancialBenchmarkingInsightsSummary.feature
web/tests/Web.E2ETests/Features/School/SchoolHome.feature
web/tests/Web.E2ETests/Features/School/SpendingCosts.feature

[AB#217223](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/217223) - [AB#240769](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/240769)
web
- updates `ToPercent` extension method to return a maximum of one decimal place.
- updates E2E tests following the above change
front-end-components
- updates  `statValueFormatter` to return maximum of one decimal place when `options.valueUnit` is `"%"`
- updates unit tests following the above change
Following these changes the key information section for the school home page and the priority headline for each chart on the spending and costs page should correctly show percentages to a maximum of one decimal place. 
Also for the historic page the `chart-stat-value` div of the …

fix: maximum decimal places for percentages

---

front-end-components/index.html
front-end-components/src/components/charts/historic-data-tooltip/component.tsx
front-end-components/src/components/charts/historic-data-tooltip/index.tsx
front-end-components/src/components/charts/historic-data-tooltip/types.tsx
front-end-components/src/components/charts/line-chart/component.tsx
front-end-components/src/components/charts/types.tsx
front-end-components/src/composed/historic-chart-2-composed/component.tsx
front-end-components/src/composed/historic-chart-2-composed/index.tsx
front-end-components/src/composed/historic-chart-2-composed/types.tsx
front-end-components/src/composed/historic-chart-composed/component.tsx
front-end-components/src/constants.tsx
front-end-components/src/index.css
front-end-components/src/main.tsx
front-end-components/src/services/expenditure-api.tsx
front-end-components/src/services/types.tsx
front-end-components/src/views/historic-data-2/index.tsx
front-end-components/src/views/historic-data-2/partials/index.tsx
front-end-components/src/views/historic-data-2/partials/spending-section-premises-services.tsx
front-end-components/src/views/historic-data-2/partials/spending-section.tsx
front-end-components/src/views/historic-data-2/types.tsx
front-end-components/src/views/historic-data-2/view.tsx
front-end-components/src/views/historic-data/partials/income-section.tsx
front-end-components/src/views/historic-data/partials/spending-section.tsx
front-end-components/src/views/index.tsx

[AB#240729](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/240729) [AB#237633](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/237633) [AB#240730](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/240730)
Display 'Total Expenditure' historic chart and table with three series: school, comparator set average and national average (within phase and finance type). Dummy data intentionally used at this stage for demo purposes while backend implementation ongoing.
Run the `vite` dev server to preview the changes. Nothing consumes the new components as yet, but existing charts/tables should be unaffected.

New version of historic view/composed chart/tooltip components that supports three series

---

platform/src/apis/Platform.Api.Insight/Configuration/Services.cs
platform/src/apis/Platform.Api.Insight/Domain/FinanceType.cs
platform/src/apis/Platform.Api.Insight/Expenditure/ExpenditureFunctions.cs
platform/src/apis/Platform.Api.Insight/Expenditure/ExpenditureNationalAvgParameters.cs
platform/src/apis/Platform.Api.Insight/Expenditure/ExpenditureService.cs
platform/src/apis/Platform.Api.Insight/OpenApi/Examples/ExpenditureExamples.cs
platform/src/apis/Platform.Api.Insight/Validators/ExpenditureNationalAvgParametersValidator.cs
platform/tests/Platform.Tests/Insight/Expenditure/ExpenditureFunctionsTestBase.cs

[AB#240724](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/240724)
- Adds two new end points
-  `expenditure/school/history/national-average`
- based on `queryParams.Dimension` different views are queried 
- actuals - `SchoolExpenditureAvgHistoric`
- perUnit - `SchoolExpenditureAvgPerUnitHistoric`
- percentIncome - `SchoolExpenditureAvgPercentageOfIncomeComparatorSet`
- percentExpenditure - `SchoolExpenditureAvgPercentageOfExpenditureComparatorSet`
- `queryParams.OverallPhase` and `queryParams.FinanceType` are used to build the sql query strings
- new validator added for these parameters.
- …

feat: adds new platform api endpoints for school expenditure historic trends

---

web/src/Web.App/Controllers/Api/BudgetForecastProxyController.cs
web/src/Web.App/Views/TrustForecast/Index.cshtml
web/tests/Web.Integration.Tests/Pages/Trusts/WhenViewingForecast.cs
web/tests/Web.Tests/Controllers/Api/BudgetForecast/WhenBudgetForecastApiReceivesRequest.cs

[AB#241480](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/241480) [AB#236233](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/236233)
If the Trust does not have a BFR for the most recent year, instead show for the most recent year identified from the underlying BFR metrics. If this is also not available then show a (reworded) warning message.
Also moved API controller tests from `Wen.Integration.Tests` to `Web.Tests` and increased BFR test coverage.
Trusts with BFR data for current year, a previous year, or not at all should may all be validated when spinning up `web` locally.

Resolve 'current' BFR year based on metrics rather than `LatestBFRYear` value from `Parameters` table

---

front-end-components/src/components/charts/line-chart-dot/component.tsx
front-end-components/src/components/charts/line-chart-dot/index.tsx
front-end-components/src/components/charts/line-chart-dot/types.tsx
front-end-components/src/components/charts/line-chart-tooltip/component.tsx
front-end-components/src/components/charts/line-chart/component.tsx

[AB#241600](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/241600) [AB#225945](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/225945)
Accessible tooltips on line charts so that 'dots' can be tabbed through. Compatible with both versions of the historical data composed charts, as well as BFR (that has no tooltips). Implementation tips from [this issue](https://github.com/recharts/recharts/issues/1231).
Build and run the local Vite dev server to validate behaviour.

Allowed tabbing between 'dots' on line chart using keyboard

---

pipelines/web/steps/run-e2e-tests.yaml
web/tests/Web.E2ETests/Features/School/HistoricData.feature
web/tests/Web.E2ETests/Pages/School/HistoricDataPage.cs
web/tests/Web.E2ETests/Selectors.cs
web/tests/Web.E2ETests/Steps/School/HistoricDataSteps.cs

[AB#240731](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/240731) [AB#237633](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/237633)
For the time being, intentionally excluded from pipeline E2E run via trait filter. Once feature stable, and enabled in automated test environment, this filter may be removed.
Enable the `HistoricalTrends` feature flag locally and configure Web against `d02` before running E2E.

E2E tests for historic data tabs when feature flag is enabled

---

platform/src/apis/Platform.Api.Insight/Expenditure/ExpenditureFunctions.cs
platform/src/apis/Platform.Api.Insight/Expenditure/ExpenditureNationalAvgParameters.cs
platform/tests/Platform.Tests/Insight/Expenditure/ExpenditureFunctionsTestBase.cs
platform/tests/Platform.Tests/Insight/Expenditure/WhenExpenditureNationalAvgParametersSetsValues.cs
platform/tests/Platform.Tests/Insight/Expenditure/WhenExpenditureServiceQueriesAsync.cs
platform/tests/Platform.Tests/Insight/Expenditure/WhenFunctionReceivesGetComparatorSetAverageExpenditureHistoryRequest.cs
platform/tests/Platform.Tests/Insight/Expenditure/WhenFunctionReceivesGetExpenditureHistoryRequest.cs
platform/tests/Platform.Tests/Insight/Expenditure/WhenFunctionReceivesGetNationalAverageExpenditureHistoryRequest.cs

[AB#241662](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/241662)
Adds tests to cover behaviour of #1658
Corrections to an unused parameter in one of the endpoint methods and changes the scope of the props for the expected parameters.
To allow mocking of validation `ExpenditureFunctionsTestBase` has been amended to mock the relevant `IValidator` rather than the existing `InlineValidator`. This results in a slight change to existing tests in `WhenFunctionReceivesGetExpenditureHistoryRequest`.
Happy to create a new test base for the new tests if the reviewer thinks that would be a better approach.

Tests for insight expenditure historic trends methods

---

core-infrastructure/src/db/Core.Database/Scripts/073-CreateSchoolExpenditureAvgPercentageOfExpenditureHistoricView.sql
core-infrastructure/src/db/Core.Database/Scripts/077-RecreateSchoolExpenditureHistoricWithNullsView.sql
core-infrastructure/src/db/Core.Database/Scripts/078-RecreateSchoolExpenditureAvgHistoricView.sql
core-infrastructure/src/db/Core.Database/Scripts/079-RecreateSchoolExpenditureAvgPerUnitHistoricView.sql
core-infrastructure/src/db/Core.Database/Scripts/080-RecreateSchoolExpenditureAvgComparatorSetView.sql
core-infrastructure/src/db/Core.Database/Scripts/081-RecreateSchoolExpenditureAvgPerUnitComparatorSetView.sql
core-infrastructure/src/db/Core.Database/Scripts/082-RecreateSchoolExpenditurePercentageOfExpenditureHistoricView.sql
core-infrastructure/src/db/Core.Database/Scripts/083-RecreateSchoolExpenditurePercentageOfIncomeHistoricView.sql
core-infrastructure/src/db/Core.Database/Scripts/084-RecreateSchoolExpenditureAvgPercentageOfExpenditureHistoricView.sql
core-infrastructure/src/db/Core.Database/Scripts/085-RecreateSchoolExpenditureAvgPercentageOfIncomeHistoricView.sql
core-infrastructure/src/db/Core.Database/Scripts/086-RecreateSchoolExpenditureAvgPercentageOfExpenditureComparatorSetView.sql
core-infrastructure/src/db/Core.Database/Scripts/087-RecreateSchoolExpenditureAvgPercentageOfIncomeComparatorSetView.sql

Following #1655 and appropriate sign-off, the VIEWs created therein have been extended to include _all_ required columns.
recreate the following VIEWs with all required columns:
- `SchoolExpenditureHistoricWithNullsView`
- `SchoolExpenditureAvgHistoricView`
- `SchoolExpenditureAvgPerUnitHistoricView`
- `SchoolExpenditureAvgComparatorSetView`
- `SchoolExpenditureAvgPerUnitComparatorSetView`
- `SchoolExpenditurePercentageOfExpenditureHistoricView`
- `SchoolExpenditurePercentageOfIncomeHistoricView`
- `SchoolExpenditureAvgPercentageOfExpenditureHistoricView`
- `SchoolExpenditureAvgPercentageOfIncomeHistoricView`
- `SchoolExpenditureAvgPercentageOfExpenditureComparatorSetView`
- …

feat: extend Historical Trends VIEWs

---

web/src/Web.App/Controllers/Api/CensusProxyController.cs
web/src/Web.App/Domain/Insight/Expenditure.cs
web/src/Web.App/Domain/Insight/HistoryComparison.cs
web/src/Web.App/Infrastructure/Apis/Insight/Api.cs
web/src/Web.App/Infrastructure/Apis/Insight/CensusApi.cs
web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
web/tests/Web.Integration.Tests/Paths.cs
web/tests/Web.Integration.Tests/Proxy/WhenRequestingCensusHistoryComparison.cs
web/tests/Web.Integration.Tests/Proxy/WhenRequestingExpenditureHistoryComparison.cs
web/tests/Web.Tests/Controllers/Api/Census/WhenCensusApiReceivesHistoryComparisonRequest.cs
web/tests/Web.Tests/Controllers/Api/Census/WhenCensusApiReceivesHistoryRequest.cs
web/tests/Web.Tests/Controllers/Api/Census/WhenCensusApiReceivesQueryRequest.cs
web/tests/Web.Tests/Infrastructure/GivenACensusApi.cs

[AB#241827](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/241827) [AB#237633](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/237633)
New endpoint in Web API, proxying to proposed new endpoints in Insight API to support census historic trends.
Not yet wired up to anything, but may be validated by browsing locally directly to a URL such as `https://localhost:7095/api/census/history/comparison?id=123456&dimension=HeadcountPerFte`. This will gracefully fail until the new dependent Platform endpoints are ready.

Added `census/history/comparison` endpoint to Web proxy API

---

platform/src/apis/Platform.Api.Insight/Census/CensusFunctions.cs
platform/src/apis/Platform.Api.Insight/Census/CensusNationalAvgParameters.cs
platform/src/apis/Platform.Api.Insight/Census/CensusService.cs
platform/src/apis/Platform.Api.Insight/Configuration/Services.cs
platform/src/apis/Platform.Api.Insight/Expenditure/ExpenditureFunctions.cs
platform/src/apis/Platform.Api.Insight/Expenditure/ExpenditureService.cs
platform/src/apis/Platform.Api.Insight/Validators/CensusNationalAvgParametersValidator.cs
platform/src/apis/Platform.Api.Insight/Validators/ExpenditureNationalAvgParametersValidator.cs
platform/tests/Platform.Tests/Insight/Census/CensusFunctionsTestBase.cs
platform/tests/Platform.Tests/Insight/Census/WhenCensusNationalAvgParametersSetsValues.cs
platform/tests/Platform.Tests/Insight/Census/WhenCensusServiceQueriesAsync.cs
platform/tests/Platform.Tests/Insight/Census/WhenFunctionReceivesGetCensusRequest.cs
platform/tests/Platform.Tests/Insight/Census/WhenFunctionReceivesGetComparatorSetAverageCensusRequest.cs
platform/tests/Platform.Tests/Insight/Census/WhenFunctionReceivesGetNationalAverageCensusRequest.cs
platform/tests/Platform.Tests/Insight/Census/WhenFunctionReceivesGetWorkforceHistoryRequest.cs
platform/tests/Platform.Tests/Insight/Expenditure/WhenExpenditureServiceQueriesAsync.cs
platform/tests/Platform.Tests/Insight/Expenditure/WhenFunctionReceivesGetComparatorSetAverageExpenditureHistoryRequest.cs
platform/tests/Platform.Tests/Insight/Expenditure/WhenFunctionReceivesGetExpenditureHistoryRequest.cs
platform/tests/Platform.Tests/Insight/Expenditure/WhenFunctionReceivesGetNationalAverageExpenditureHistoryRequest.cs

[AB#241828](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/241828)
Adds two new endpoints for census historic trends
- `census/{urn}/history/comparator-set-average`
- `census/history/national-average`
- updates existing tests following changes to validation setup in the tests
- adds new tests
Currently contains proposed views which are not yet provisioned. Until there are in place these endpoints will not return data.

feat: add new api endpoints for census historic trends. 

---

core-infrastructure/src/db/Core.Database/Scripts/088-RecreateSchoolCensusHistoricView.sql
core-infrastructure/src/db/Core.Database/Scripts/089-CreateSchoolCensusHistoricWithNullsView.sql
core-infrastructure/src/db/Core.Database/Scripts/090-CreateSchoolCensusAvgHistoricView.sql
core-infrastructure/src/db/Core.Database/Scripts/091-CreateSchoolCensusAvgComparatorSetView.sql
core-infrastructure/src/db/Core.Database/Scripts/092-CreateSchoolCensusPerFteHistoricView.sql
core-infrastructure/src/db/Core.Database/Scripts/093-CreateSchoolCensusAvgPerFteHistoricView.sql
core-infrastructure/src/db/Core.Database/Scripts/094-CreateSchoolCensusAvgPerFteComparatorSetView.sql
core-infrastructure/src/db/Core.Database/Scripts/095-CreateSchoolCensusPercentageOfWorkforceFteHistoricView.sql
core-infrastructure/src/db/Core.Database/Scripts/096-CreateSchoolCensusAvgPercentageOfWorkforceFteHistoricView.sql
core-infrastructure/src/db/Core.Database/Scripts/097-CreateSchoolCensusAvgPercentageOfWorkforceFteComparatorSetView.sql
core-infrastructure/src/db/Core.Database/Scripts/098-CreateSchoolCensusPupilsPerStaffHistoricView.sql
core-infrastructure/src/db/Core.Database/Scripts/099-CreateSchoolCensusAvgPupilsPerStaffHistoricView.sql
core-infrastructure/src/db/Core.Database/Scripts/100-CreateSchoolCensusAvgPupilsPerStaffComparatorSetView.sql

Add actual/national-average/comparator-set averages for census data.
New VIEWs:
- `SchoolCensusHistoric`
- `SchoolCensusAvgHistoric`
- `SchoolCensusAvgComparatorSet`
- `SchoolCensusPerFteHistoric`
- `SchoolCensusAvgPerFteHistoric`
- `SchoolCensusAvgPerFteComparatorSet`
- `SchoolCensusPercentageOfWorkforceFteHistoric`
- `SchoolCensusAvgPercentageOfWorkforceFteHistoric`
- `SchoolCensusAvgPercentageOfWorkforceFteComparatorSet`
- `SchoolCensusPupilsPerStaffHistoric`
- `SchoolCensusAvgPupilsPerStaffHistoric`
- `SchoolCensusAvgPupilsPerStaffComparatorSet`
Validated in d15.

feat: add historical census views

---

front-end-components/index.html
front-end-components/src/components/charts/data-warning/component.tsx
front-end-components/src/components/charts/data-warning/index.tsx
front-end-components/src/components/charts/data-warning/types.tsx
front-end-components/src/components/charts/part-year-data-warning/component.tsx
front-end-components/src/composed/historic-chart-2-composed/component.tsx
front-end-components/src/main.tsx
front-end-components/src/services/census-api.tsx
front-end-components/src/services/expenditure-api.tsx
front-end-components/src/services/types.tsx
front-end-components/src/views/historic-data-2/partials/census-section.tsx
front-end-components/src/views/historic-data-2/partials/index.tsx
front-end-components/src/views/historic-data-2/partials/spending-section.tsx
front-end-components/src/views/historic-data-2/types.tsx
front-end-components/src/views/historic-data-2/view.tsx
front-end-components/src/views/historic-data/partials/balance-section.tsx
front-end-components/src/views/historic-data/partials/census-section.tsx
front-end-components/src/views/historic-data/partials/income-section.tsx
front-end-components/src/views/historic-data/partials/spending-section.tsx
front-end-components/src/views/historic-data/view.tsx
web/src/Web.App/Controllers/SchoolController.cs
web/src/Web.App/Domain/Insight/HistoryComparison.cs
web/src/Web.App/ViewModels/SchoolHistoryViewModel.cs
web/src/Web.App/Views/School/History.cshtml
web/terraform/variables.tf
web/tests/Web.E2ETests/Features/School/HistoricData.feature
web/tests/Web.E2ETests/Pages/School/HistoricDataPage.cs
web/tests/Web.E2ETests/Steps/School/HistoricDataSteps.cs

[AB#241826](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/241826) [AB#237633](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/237633)
- Created new `<CensusSection>` component to support multiple series in the line charts, and wired up to v2 Historic view.
- Perform historical data `fetch` when each tab is loaded, rather than all tabs when view is rendered due to additional overheads from new API endpoints.
- Added abort config to `fetch` and display warning message on load timeout.
- Updated E2E tests for Historic Census tab when flag enabled, taking special care over 'total pupils' chart/table that should not be affected by Dimension changes.
Use Vite dev server locally, or build and copy to Web in order to …

Created `<CensusSection>` for use when historical trends feature flag enabled

---

platform/tests/Platform.ApiTests/Features/InsightCensus.feature
platform/tests/Platform.ApiTests/Steps/InsightCensusSteps.cs

[AB#242608](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/242608)
adds api tests to `InsightsCensusEndpointsFeature` to cover behaviour of the the new census historic trends endpoints
N/A

test: add api tests for insight census historic trends

---

data-pipeline/src/pipeline/pre_processing.py

[AB#241716](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/241716) 
[AB#242851](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/242851)
aggregate contextual data for federations before rag costs are generated
`join_federations` before `calc_rag_cost_series`
Run data pipeline locally for 2024 (aar 2023, cfr 2024, bfr 2023) and verify the MetricRAG table now contains the correct values for the example URN provided in the ticket
New
|Category|SubCategory|Value|
|---|---|---|
|Educational ICT|Total|129.83|
|Non-educational support staff and services|Total|663.22|
|Teaching and Teaching support staff|Total|4686.15|
Original
|Category|SubCategory|Value|
|---|---|---|
|Educational ICT|Total|178.30|
|Non-educational …

fix: aggregate contextual data for federations before rag costs are generated

---

data-pipeline/src/pipeline/pre_processing.py
data-pipeline/tests/unit/pre_processing/test_census.py

Previously, the "census" dataset was missing orgs. present in the pupil data when those orgs. were missing from the workforce data.
[AB#241759](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/241759)  
[AB#243030](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/243030)
- update the `inner` merge to an `outer`
- add tests to validate that missing rows from either or both data sets retain the rows in the merged output
Because workforce is joined onto pupils, depending on which is missing data, the resulting index might be `URN` or not, hence the `reset_index().set_index()` addition.

fix: use outer join for census data

---

data-pipeline/src/pipeline/pre_processing.py
data-pipeline/tests/unit/pre_processing/test_custom_data.py

A "custom-data" job allows users to submit a new set of financial data.
Currently, rows where `Partial Years Present` is `True` are skipped, even if the job is processing custom-data.
[AB#241954](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/241954)  
As we're considering a custom-data job to represent a full-year's financial data, update the custom-data being processed accordingly and continue as normal.
WIP: adding tests.

fix: permit RAG for custom-data

---

support-analytics/terraform/README.md
support-analytics/terraform/dashboards.tf
support-analytics/terraform/dashboards/mi.tpl
support-analytics/terraform/queries.tf
support-analytics/terraform/queries/most-popular-recent-schools.kql

[AB#243310](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/243310) [AB#242081](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/242081)
New chart on MI dashboard to show 'popular' schools based on requests within the past 90 days to the Spending Priorities page. e.g. (in `p01`):
Deployed to `d11` feature environment for validation.

Added chart to MI dashboard to visualise 'popular' schools

---

platform/Platform.sln.DotSettings
platform/README.md
platform/src/abstractions/Platform.Cache/Configuration/RedisCacheOptions.cs
platform/src/abstractions/Platform.Cache/Configuration/Services.cs
platform/src/abstractions/Platform.Cache/IDistributedCache.cs
platform/src/abstractions/Platform.Cache/RedisConnectionMultiplexerFactory.cs
platform/src/abstractions/Platform.Cache/RedisDistributedCache.cs
platform/src/abstractions/tests/Platform.Cache.Tests/Cache/RedisDistributedCacheTestBase.cs
platform/src/abstractions/tests/Platform.Cache.Tests/Cache/WhenRedisDistributedCacheDeletes.cs
platform/src/abstractions/tests/Platform.Cache.Tests/Cache/WhenRedisDistributedCacheFlushes.cs
platform/src/apis/Platform.Orchestrator/Configuration/Services.cs
platform/src/apis/Platform.Orchestrator/PipelineFunctions.cs
platform/src/apis/Platform.Orchestrator/Platform.Orchestrator.csproj
platform/src/apis/Platform.Orchestrator/packages.lock.json
platform/terraform/functions.tf
platform/terraform/modules/functions/README.md
platform/terraform/modules/functions/main.tf
platform/terraform/modules/functions/variables.tf
platform/tests/Platform.Tests/packages.lock.json

[AB#244049](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/244049) [AB#237633](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/237633)
Added both `FLUSHALL` and `KEYS`/`DEL` operations to allow the removal of all, or pattern-matched keys from Redis respectively. Added Orchestrator managed identity to Redis with Contributor access (Owner would be required for `FLUSHALL`). Cleared keys matching successfully completed `RunId` for a default run using pattern `YYYY:*`, where `YYYY` is the year to clear from cache.
This may be validated locally without waiting for a pipeline run to complete by:
1. Add a value to the cache, e.g. `SET 2000:test hello` and validate presence, e.g. `KEYS 2000:*`
2. Update Orchestrator …

Orchestrator clear keys matching successful `RunId` from distributed cache

---

platform/src/abstractions/Platform.Cache/IDistributedCache.cs
platform/src/abstractions/Platform.Cache/RedisDistributedCache.cs
platform/src/abstractions/tests/Platform.Cache.Tests/Cache/WhenRedisDistributedCacheGetSetsObject.cs
platform/src/abstractions/tests/Platform.Cache.Tests/Cache/WhenRedisDistributedCacheGetsObject.cs
platform/src/abstractions/tests/Platform.Cache.Tests/Cache/WhenRedisDistributedCacheSetsObject.cs
platform/src/abstractions/tests/Platform.Cache.Tests/Cache/WhenRedisDistributedCacheSetsObjects.cs

[AB#244049](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/244049) [AB#237633](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/237633)
This is mostly to get around [deserialization issue with decimal precision](https://github.com/JamesNK/Newtonsoft.Json/issues/2551), but also for reported [performance boost](https://github.com/JamesNK/Newtonsoft.Json.Bson/issues/30).
Repeatedly running API tests after flushing cache initially should always return consistent results. This was failing with BSON encoding. 
> **NOTE:** Future work will flush the cache automatically before running the API tests from a pipeline build

Replaced default Bson encoding for objects persisted to cache with Json

---

data-pipeline/src/pipeline/rag.py
data-pipeline/tests/unit/rag/test_rag.py
web/src/Web.App/AssetSrc/scss/main.scss
web/src/Web.App/Views/SchoolSpending/_Costs.cshtml

[AB#235748](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/235748) - [AB#243322](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/243322) & [AB#244430](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/244430)
filter non selected schools in the comparator set when they have negative or zero values for each cost category for the spending priorites page (default and custom data) so they are not included in the charts.
display a warning for each chart when values are suppressed.
when calculating the values for the rag rating for each category in the data pipeline exclude other schools in the comparator set when they have negative or zero values so the calculations match the schools …

feat: suppress negative and zero values for spending priorities page

---

front-end-components/src/views/compare-your-costs/view.tsx
web/src/Web.App/Views/SchoolSpending/_Costs.cshtml

[AB#235748](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/235748) - [AB#245037](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/245037)
Content finalised for this warning text over charts where suppression of negative and zero is applied.
Updated in the service
Will require a following bump to `front-end` package

chore: update content of warning message suppression of negative and zero

---

web/src/Web.App/package-lock.json

[AB#235748](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/235748)
following #1776 bump front end package required
bump `front-end` to `1.1.28`
n/a

chore: bump `front-end` to `1.1.28`

---

core-infrastructure/src/db/Core.Database/Scripts/106-CreateFileTable.sql
core-infrastructure/src/db/Core.Database/Views/015-Files.sql
platform/src/apis/Platform.Api.Insight/Configuration/Services.cs
platform/src/apis/Platform.Api.Insight/Constants.cs
platform/src/apis/Platform.Api.Insight/Features/Files/GetAarTransparencyFilesFunction.cs
platform/src/apis/Platform.Api.Insight/Features/Files/GetCfrTransparencyFilesFunction.cs
platform/src/apis/Platform.Api.Insight/Features/Files/Mapper.cs
platform/src/apis/Platform.Api.Insight/Features/Files/Models/FileModel.cs
platform/src/apis/Platform.Api.Insight/Features/Files/Responses/FileResponse.cs
platform/src/apis/Platform.Api.Insight/Features/Files/Routes.cs
platform/src/apis/Platform.Api.Insight/Features/Files/Services/FilesService.cs
platform/tests/Platform.ApiTests/Features/InsightFiles.feature
platform/tests/Platform.ApiTests/Steps/InsightFilesSteps.cs
platform/tests/Platform.Insight.Tests/Files/GetAarTransparencyFilesFunctionTests.cs
platform/tests/Platform.Insight.Tests/Files/GetCfrTransparencyFilesFunctionTests.cs

[AB#244999](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/244999) [AB#244563](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/244563)
- New table and view for system files, with initial seeding
- API for getting CFR and AAR files from the database
- Unit and API tests
Run the migrations against a local database and then run the Insight API pointing to that database. The URLs `http://localhost:7071/api/files/transparency/aar` and `http://localhost:7071/api/files/transparency/cfr` may then be used to get each set of transparency files.

Expose endpoints for getting AAR and CFR files from database

---

web/src/Web.App/Controllers/DataSourceController.cs
web/src/Web.App/Domain/Insight/Files.cs
web/src/Web.App/Extensions/ServiceCollectionExtensions.cs
web/src/Web.App/Infrastructure/Apis/Insight/Api.cs
web/src/Web.App/Infrastructure/Apis/Insight/FilesApi.cs
web/src/Web.App/ViewModels/DataSourceViewModel.cs
web/src/Web.App/Views/DataSource/_DataSources.cshtml
web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
web/tests/Web.Integration.Tests/Pages/WhenViewingDataSources.cs

[AB#246012](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/246012) [AB#244563](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/244563)
Display list of downloadable transparency files from blob storage based on response from API call instead of hard-coded in application.

Consume API and write transparency files to Data Sources page

---

front-end-components/index.html
front-end-components/package-lock.json
front-end-components/package.json
front-end-components/src/components/charts/horizontal-bar-chart/component.tsx
front-end-components/src/components/charts/line-chart/component.tsx
front-end-components/src/components/charts/types.tsx
front-end-components/src/components/charts/vertical-bar-chart/component.tsx
front-end-components/src/composed/horizontal-bar-chart-wrapper/composed.tsx
front-end-components/src/hooks/useDownloadImage.ts
front-end-components/src/views/budget-forecast-returns/partials/year-end.tsx

[AB#245969](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/245969) [AB#245362](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/245362) [AB#216495](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/216495)
Switched above named npm packages
Build and copy build from `front-end-components` to `Web` after `npm i`. View a page with charts and click <kbd>Save as image</kbd> for functionally the same behaviour as per previous implementation.

Replaced `recharts-to-png` with `html-to-image`

---

front-end-components/src/views/compare-your-trust/partials/accordion-sections/administrative-supplies.tsx
front-end-components/src/views/compare-your-trust/partials/accordion-sections/catering-staff-services.tsx
front-end-components/src/views/compare-your-trust/partials/accordion-sections/educational-ict.tsx
front-end-components/src/views/compare-your-trust/partials/accordion-sections/educational-supplies.tsx
front-end-components/src/views/compare-your-trust/partials/accordion-sections/non-educational-support-staff.tsx
front-end-components/src/views/compare-your-trust/partials/accordion-sections/other-costs.tsx
front-end-components/src/views/compare-your-trust/partials/accordion-sections/premises-staff-services.tsx
front-end-components/src/views/compare-your-trust/partials/accordion-sections/utilities.tsx

[AB#246167](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/246167) [AB#244563](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/244563) #1786
Added missing prop from the earlier refactor. Identified via failing a11y test. `front-end` will need to be bumped after this is merged.

Added mising prop to `trust` cost comparison charts, post refactor

---

platform/src/abstractions/Platform.Domain/Messages/PipelinePayload.cs
platform/src/apis/Platform.Api.Benchmark/ComparatorSets/ComparatorSetsFunctions.cs
platform/src/apis/Platform.Api.Benchmark/CustomData/CustomDataRequest.cs
platform/tests/Platform.Benchmark.Tests/WhenFunctionReceivesCreateComparatorSetRequest.cs
platform/tests/Platform.Benchmark.Tests/WhenFunctionReceivesCreateCustomDataRequest.cs

[AB#246377](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/246377) [AB#242105](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/242105)
Partially reverts change from 1303232a16a1b790512be150d7c3795e51ea0ce0 that sent unexpected `kind` value to Orchestrator and ultimately data pipeline.

Revert pipeline message payload `kind` from earlier commit 

---

platform/src/abstractions/Platform.Domain/Messages/PipelinePayload.cs
platform/src/abstractions/Platform.Domain/Pipeline.cs
platform/src/apis/Platform.Api.Benchmark/ComparatorSets/ComparatorSetsFunctions.cs
platform/src/apis/Platform.Api.Benchmark/CustomData/CustomDataRequest.cs
platform/tests/Platform.Benchmark.Tests/WhenFunctionReceivesCreateComparatorSetRequest.cs
platform/tests/Platform.Benchmark.Tests/WhenFunctionReceivesCreateCustomDataRequest.cs

[AB#246377](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/246377) [AB#242105](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/242105) #1793
Follow-up change from linked PR to rename classes back as they were, whilst keeping the `kind` values expected by the data pipeline. This is done by using an alternative field for subtype discrimination during deserialization. Validated via unit tests.

Renamed `PipelinePayload` types back to previous class names whilst persisting `kind` values

---

front-end-components/index.html
front-end-components/package-lock.json
front-end-components/package.json
front-end-components/src/components/chart-mode/component.tsx
front-end-components/src/components/charts/horizontal-bar-chart/component.tsx
front-end-components/src/components/charts/line-chart/component.tsx
front-end-components/src/components/charts/vertical-bar-chart/component.tsx
front-end-components/src/components/progress/component.tsx
front-end-components/src/components/progress/index.tsx
front-end-components/src/components/progress/styles.css
front-end-components/src/components/progress/types.tsx
front-end-components/src/components/share-content-by-elements/component.tsx
front-end-components/src/components/share-content-by-elements/index.tsx
front-end-components/src/components/share-content-by-elements/types.tsx
front-end-components/src/components/share-content/component.tsx
front-end-components/src/constants.tsx
front-end-components/src/hooks/useDownloadImage.ts
front-end-components/src/index.css
front-end-components/src/main.tsx
web/src/Web.App/AssetSrc/scss/main.scss
web/src/Web.App/Views/SchoolComparison/Index.cshtml
web/src/Web.App/Views/Shared/_SaveChartsButton.cshtml
web/src/Web.App/Views/TrustComparison/Index.cshtml
web/tests/Web.Integration.Tests/Pages/Schools/WhenViewingComparison.cs
web/tests/Web.Integration.Tests/Pages/Trusts/WhenViewingComparison.cs

[AB#246636](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/246636) [AB#242099](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/242099)
- Added `<ShareContentByElements />` component for use with any HTMLElement that generates `.png`s for each matching element and bundles them into a `.zip` which is then sent to the client
- Added default implementation to be to select by matching element class name(s), which may be outside the React context
- Added optional progress indicator to `<ShareContentByElements />` component
- Added 'save all' button to School and Trust comparison pages
- Ensured if 'table' mode selected in chart radios then first select 'chart' before saving chart images
Multiple image save feature may …

Added 'Save all chart images' button to School and Trust cost comparison pages 

---

front-end-components/src/components/share-content-by-elements/component.tsx
front-end-components/src/components/share-content-by-elements/types.tsx
front-end-components/src/hooks/useDownloadImage.ts
front-end-components/src/main.tsx
web/src/Web.App/Views/SchoolComparison/Index.cshtml
web/src/Web.App/Views/SchoolSpending/Index.cshtml
web/src/Web.App/Views/SchoolSpending/_Costs.cshtml
web/src/Web.App/Views/Shared/_SaveChartsButton.cshtml
web/src/Web.App/Views/TrustComparison/Index.cshtml

[AB#246709](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/246709) [AB#242099](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/242099) #1798
- Added 'save all' button to School spending priority page
- Changed filename of 'save all' .zip file to match page and URN/company number
To validate locally, build `front-end-components` and copy to `Web` before visiting the affected pages.

Added 'Save all chart images' button to School spending priorities page

---

front-end-components/src/composed/historic-chart-2-composed/component.tsx
front-end-components/src/composed/historic-chart-2-composed/types.tsx
front-end-components/src/composed/historic-chart-composed/component.tsx
front-end-components/src/composed/historic-chart-composed/types.tsx
front-end-components/src/views/budget-forecast-returns/partials/year-end.tsx
front-end-components/src/views/historic-data-2/partials/catering-costs-history-chart.tsx
front-end-components/src/views/historic-data-2/partials/census-section.tsx
front-end-components/src/views/historic-data-2/partials/spending-section.tsx
front-end-components/src/views/historic-data/partials/balance-section.tsx
front-end-components/src/views/historic-data/partials/census-section.tsx
front-end-components/src/views/historic-data/partials/income-section-direct-revenue.tsx
front-end-components/src/views/historic-data/partials/income-section-grant-funding.tsx
front-end-components/src/views/historic-data/partials/income-section-self-generated.tsx
front-end-components/src/views/historic-data/partials/income-section.tsx
front-end-components/src/views/historic-data/partials/spending-section-administrative-supplies.tsx
front-end-components/src/views/historic-data/partials/spending-section-catering-services.tsx
front-end-components/src/views/historic-data/partials/spending-section-educational-ict.tsx
front-end-components/src/views/historic-data/partials/spending-section-educational-supplies.tsx
front-end-components/src/views/historic-data/partials/spending-section-non-educational-staff-costs.tsx
front-end-components/src/views/historic-data/partials/spending-section-other.tsx
front-end-components/src/views/historic-data/partials/spending-section-premises-services.tsx
front-end-components/src/views/historic-data/partials/spending-section-teaching-costs.tsx
front-end-components/src/views/historic-data/partials/spending-section-utilities.tsx
front-end-components/src/views/historic-data/partials/spending-section.tsx
web/tests/Web.E2ETests/Pages/School/HistoricDataPage.cs
web/tests/Web.E2ETests/Selectors.cs

[AB#244349](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/244349) - [AB#246622](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/246622)
- Adds save as image functionality to both versions of the historic data charts in `HistoricChart` and `HistoricChart2` using `ShareContent`
- updates now failing E2E tests
- updates selectors for save as image
- updates table in `HistoricChart2` to use a test id and updates the steps for those tests.
Subsequent bump to `front-end` package will be required.
New E2E tests to follow on a later PR

feat: adds save as image functionality to historic data charts

---

web/src/Web.App/package-lock.json

[AB#244349](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/244349)
Bump `front-end` package
n/a

chore: bump `front-end` to `1.1.35`

---

front-end-components/index.html
front-end-components/src/components/charts/line-chart/component.tsx
front-end-components/src/components/charts/types.tsx
front-end-components/src/composed/historic-chart-2-composed/component.tsx
front-end-components/src/composed/historic-chart-2-composed/types.tsx
front-end-components/src/index.css
web/tests/Web.E2ETests/Assist/DynamicTableHelpers.cs
web/tests/Web.E2ETests/Extensions/StringExtensions.cs
web/tests/Web.E2ETests/Pages/DataSourcesPage.cs
web/tests/Web.E2ETests/Pages/LocalAuthority/BenchmarkCensusPage.cs
web/tests/Web.E2ETests/Pages/LocalAuthority/CompareYourCostsPage.cs
web/tests/Web.E2ETests/Pages/School/BenchmarkCensusPage.cs
web/tests/Web.E2ETests/Pages/School/CompareYourCostsPage.cs
web/tests/Web.E2ETests/Pages/School/SpendingCostsPage.cs
web/tests/Web.E2ETests/Pages/Trust/BenchmarkCensusPage.cs
web/tests/Web.E2ETests/Pages/Trust/CompareYourCostsPage.cs
web/tests/Web.E2ETests/Regexes.cs

[AB#246743](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/246743) [AB#244349](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/244349)
CSS updates to `<Legend>` to support the modified height/margin when a title is appended to the chart cloned DOM when saving as an image.

Modified positioning of `<HistoricChart2>` legend to fix save-as-image functionality

---

web/src/Web.App/package-lock.json

[AB#246709](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/246709) [AB#242099](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/242099) https://github.com/DFE-Digital/education-benchmarking-and-insights/pull/1799
Bumped `front-end` to `1.1.36`

 Bumped `front-end` to `1.1.36`

---

platform/src/abstractions/Platform.Domain/Pipeline.cs
platform/src/apis/Platform.Orchestrator/PipelineDb.cs
platform/src/apis/Platform.Orchestrator/PipelineFunctions.cs

[AB#246761](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/246761) [AB#246760](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/246760)
- Custom event tracking in App Insights from the Orchestrator functions
Run Orchestrator locally - pointing to a known App Insights instance - and add some messages to the queue(s). If data pipeline not configured to pull messages off that queue, manually copy a 'start' message into the 'finished' queue appending `{ "success": true }` or `false` to the payload to validate the different scenarios. Inspect the Custom Events in App Insights.

Added custom telemetry events to Orchestrator

---

web/src/Web.App/AssetSrc/scss/main.scss
web/src/Web.App/Views/SchoolSpending/_Costs.cshtml
web/tests/Web.E2ETests/Pages/School/SpendingCostsPage.cs

[AB#244349](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/244349) - [AB#246623](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/246623)
Adds usage of the `ShareContentByElement` component to save the image for each chart on the spending priorities page.
Updates now failing E2E test - adds a test id to rag commentary
- New E2E tests to follow on a subsequent PR
- Only for the default spending priorities page, not custom data
- Possible further work required for this implementation following design crit.
- placement of button
- inclusion of rag commentary in this saved image.

feat: adds save as image functionality to spending priorities charts 

---

web/src/Web.App/package-lock.json

[AB#246997](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/246997) [AB#242101](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/242101) #1813
Bumped `front-end` to `1.1.39`

Bumped `front-end` to `1.1.39`

---

front-end-components/src/views/compare-your-costs/partials/accordion-sections/utilities.tsx
front-end-components/src/views/compare-your-trust/partials/accordion-sections/utilities.tsx
web/tests/Web.E2ETests/Features/LocalAuthority/CompareYourCosts.feature
web/tests/Web.E2ETests/Features/School/CompareYourCosts.feature
web/tests/Web.E2ETests/Features/Trust/CompareYourCosts.feature
web/tests/Web.E2ETests/Pages/LocalAuthority/CompareYourCostsPage.cs
web/tests/Web.E2ETests/Pages/School/CompareYourCostsPage.cs
web/tests/Web.E2ETests/Pages/Trust/CompareYourCostsPage.cs
web/tests/Web.E2ETests/Selectors.cs
web/tests/Web.E2ETests/Steps/LocalAuthority/CompareYourCostsSteps.cs
web/tests/Web.E2ETests/Steps/School/CompareYourCostsSteps.cs
web/tests/Web.E2ETests/Steps/Trust/CompareYourCostsSteps.cs

[AB#248237](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/248237) - [AB#248239](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/248239)
- pass `PremisesCategories` as `dimensions` in the first chart in `charts` prop to `AccordionSection` in `views/compare-your-costs/partials/accordion-sections/utilities.tsx` so it does not fallback to `CostCategories` when passed to `ChartDimensions` in `DimensionedChart`
- Add new E2E tests for la, trust and school versions of this page.
Will require a bump to `front-end` package following this PR

fix: compare your costs utilities dimension

---

web/src/Web.App/package-lock.json

[AB#248237](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/248237) - [AB#248283](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/248283)
#1879 #1880 
update `front-end` package to `1.1.41`
Failing e2e tests should now pass

chore: bump `front-end` to `1.1.41`

---

web/tests/Web.E2ETests/Features/Trust/Comparators.feature
web/tests/Web.E2ETests/Pages/Trust/Benchmarking/TrustBenchmarkSpendingPage.cs
web/tests/Web.E2ETests/Selectors.cs
web/tests/Web.E2ETests/Steps/Trust/ComparatorsSteps.cs

[AB#248827](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/248827) [AB#248789](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/248789) #1895 
Additional test coverage as a follow-up to #1895. `£0.00` values are expected due to `NULL`s for all `xxxCS` columns across all `TrustFinancial` rows in `d02`

E2E for Trust-to-Trust comparison tables

---

web/tests/Web.E2ETests/Features/Trust/Comparators.feature

[AB#248827](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/248827) [AB#248789](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/248789) #1897
Fixed failing E2E test from #1897 due to concurrent test runs selecting different comparator Trusts.

Switched source Trust for user defined comparator set E2E tests

---

data-pipeline/src/pipeline/database.py
data-pipeline/tests/unit/database.py

Currently temp. table names are created as `{table_name}_temp`, meaning that should two jobs attempt to write to the same table, one will end up disrupting the other (which can legitimately happen if a `default` and `custom` run happen in parallel, for instance).
[AB#240689](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/240689)  
Firstly, include both the `RunId` value and the current epoch time in the table name (no two jobs occuring at the same time should ever have the same `RunId`).
Secondly, change the Pandas `DataFrame.to_sql()` call to `fail` if there _is_ a collision (this circumstance should never occur and should result in an error).
Thirdly, a refactor of the `pipeline.database` module to avoid the global `engine` variable:
- this was …

feat: make temp. table names unique

---

support-analytics/terraform/alerts.tf
support-analytics/terraform/queries/pipeline-messages-finished.kql

[AB#247562](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/247562) [AB#247561](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/247561) #1822
Fix to query and rules from #1822

Ensured `Failed finished pipeline messages alert` is triggered on failed finished messages only

---

front-end-components/src/components/modals/modal/component.tsx
web/tests/Web.E2ETests/Extensions/LocatorExtensions.cs
web/tests/Web.E2ETests/Features/SaveAllImagesModal.feature
web/tests/Web.E2ETests/Features/School/CompareYourCosts.feature
web/tests/Web.E2ETests/Features/School/SpendingCosts.feature
web/tests/Web.E2ETests/Features/Trust/CompareYourCosts.feature
web/tests/Web.E2ETests/Pages/School/CompareYourCostsPage.cs
web/tests/Web.E2ETests/Pages/School/SpendingCostsPage.cs
web/tests/Web.E2ETests/Pages/School/SpendingCostsPageModal.cs
web/tests/Web.E2ETests/Pages/Trust/CompareYourCostsPage.cs
web/tests/Web.E2ETests/Selectors.cs
web/tests/Web.E2ETests/Steps/SaveAllImagesModalSteps.cs
web/tests/Web.E2ETests/Steps/School/CompareYourCostsSteps.cs
web/tests/Web.E2ETests/Steps/School/SpendingCostsSteps.cs
web/tests/Web.E2ETests/Steps/Trust/CompareYourCostsSteps.cs

[AB#247366](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/247366) [AB#242099](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/242099) #1824
E2E test coverage.
Dependency on #1824. This will fail in the `Web` pipeline until `front-end` is bumped on a follow-up PR.

E2E tests for 'Save all chart images' button and modal

---

web/tests/Web.E2ETests/Extensions/PageExtensions.cs
web/tests/Web.E2ETests/Steps/SaveAllImagesModalSteps.cs

[AB#247366](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/247366) [AB#242099](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/242099) #1902
As per commentary on #1902, timeouts were occurring when running in the Azure pipeline. Locally this takes < 2,000 ms to complete, but timeout set to 60,000 ms here.

Extended time to wait for 'Save all' file download to complete in E2E test

---

front-end-components/index.html
front-end-components/src/components/charts/utils.test.ts
front-end-components/src/components/charts/utils.ts
web/tests/Web.E2ETests/Features/School/CompareYourCosts.feature
web/tests/Web.E2ETests/Features/Trust/Comparators.feature
web/tests/Web.E2ETests/Pages/School/CompareYourCostsPage.cs
web/tests/Web.E2ETests/Selectors.cs
web/tests/Web.E2ETests/Steps/School/CompareYourCostsSteps.cs

[AB#248694](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/248694) [AB#245786](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/245786)
Ensured values displayed in 'table' view on cost comparison pages follow similar formatting rules for currency decimal places.
Repro steps in related bug. In `d02` URN `777054` may be used to validate, as implemented in the E2E tests.

Chart vs Table value precision on Compare Costs pages

---

front-end-components/index.html
front-end-components/src/components/charts/horizontal-bar-chart/component.tsx
front-end-components/src/composed/horizontal-bar-chart-wrapper/composed.tsx
front-end-components/src/hooks/useDownloadImage.ts
web/src/Web.App/Views/SchoolSpending/_Costs.cshtml

[AB#248359](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/248359) [AB#247363](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/247363)
Also updated equivalent for Spending Priorities to use unique ID.

 Replaced `<HorizontalBarChartWrapper>` chart download by ref with selection by unique attribute

---

platform/src/apis/Platform.Orchestrator/host.json
platform/terraform/modules/functions/README.md
platform/terraform/modules/functions/main.tf
platform/terraform/modules/functions/variables.tf
web/src/Web.App/ViewComponents/AnalyticsViewComponent.cs
web/src/Web.App/ViewModels/Components/AnalyticsViewModel.cs
web/src/Web.App/Views/Shared/Components/Analytics/Default.cshtml
web/terraform/app-service.tf

[AB#248488](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/248488) [AB#246758](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/246758)
Environment variable changes in Terraform. Web change to App Insights JS SDK configuration to use connection string instead of instrumentation key. Log level change in Orchestrator to reduce noise.
Deployed to `d19` feature environment for validation. Data still feeds through to App Insights. Log level reduction in Orchestrator may also clearly be seen in effect over time:

Replaced `APPINSIGHTS_INSTRUMENTATIONKEY` with `APPLICATIONINSIGHTS_CONNECTION_STRING`

---

web/tests/Web.E2ETests/Extensions/LocatorExtensions.cs
web/tests/Web.E2ETests/Features/SaveImagesModal.feature
web/tests/Web.E2ETests/Pages/School/SpendingCostsPageModal.cs
web/tests/Web.E2ETests/Selectors.cs
web/tests/Web.E2ETests/Steps/SaveImagesModalSteps.cs

[AB#248192](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/248192) [AB#245257](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/245257) #1883
E2E for validation within 'save images' modal.
Dependency on #1883

E2E test coverage over changes from 'Save all' chart images to 'Save some'

---

web/Directory.Packages.props
web/terraform/README.md
web/terraform/provider.tf
web/tests/Web.Integration.Tests/packages.lock.json

[AB#248374](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/248374) [AB#248372](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/248372) #1888
Downgrade due to bug on newly introduced `js_challenge_cookie_expiration_in_minutes` (see [issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/28716)).

Downgraded `azurerm` to `4.17.0` in Web

---

web/Web.sln.DotSettings
web/src/Web.App/Extensions/MvcOptionsExtensions.cs
web/src/Web.App/ViewModels/ModelBinders/CustomModelBinderProvider.cs
web/src/Web.App/ViewModels/ModelBinders/ModelBinderWithRequestServices.cs
web/src/Web.App/ViewModels/ModelBinders/WorkforceDataCustomDataViewModelBinder.cs
web/src/Web.App/ViewModels/WorkforceDataCustomDataViewModel.cs
web/tests/Web.E2ETests/Features/School/CreateCustomData.feature
web/tests/Web.E2ETests/Pages/School/CustomData/ChangeWorkforceDataPage.cs
web/tests/Web.E2ETests/Steps/School/CreateCustomDataSteps.cs

[AB#246244](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/246244) [AB#246376](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/246376)
Backfilled workforce data with original values when custom values not provided, but are a validation dependency. This involved creating and registering a custom `IModelBinder` for the `WorkforceDataCustomDataViewModel` type that performs default model binding (i.e. parse the posted `FormCollection` as `WorkforceDataCustomDataViewModel` then perform model validation) before backfilling any missing `Census` data, and then re-validating.
Repro steps in the work item may be followed to validate the change. Integration and E2E test coverage is also present.

Backfilled original workforce data in custom data workforce validation

---

web/tests/Web.E2ETests/Features/School/CreateCustomData.feature
web/tests/Web.E2ETests/Pages/School/CustomData/RevertCustomDataPage.cs
web/tests/Web.E2ETests/Steps/School/CreateCustomDataSteps.cs

[AB#246244](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/246244) [AB#246376](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/246376) #1898
Fixed failing E2E tests from #1898.

Revert custom data before running each E2E scenario for this feature

---

web/src/Web.App/ActionResults/CsvResult.cs
web/src/Web.App/ActionResults/CsvResultActionResultExecutor.cs
web/src/Web.App/ActionResults/CsvResults.cs
web/src/Web.App/ActionResults/CsvResultsActionResultExecutor.cs
web/src/Web.App/Controllers/Api/CensusProxyController.cs
web/src/Web.App/Extensions/ServiceCollectionExtensions.cs
web/src/Web.App/Program.cs
web/src/Web.App/Services/CsvService.cs
web/tests/Web.Integration.Tests/Paths.cs
web/tests/Web.Integration.Tests/Proxy/WhenRequestingCensusDownload.cs
web/tests/Web.Tests/ActionResults/WhenCsvResultActionResultExecutorIsExecuted.cs
web/tests/Web.Tests/ActionResults/WhenCsvResultIsExecuted.cs
web/tests/Web.Tests/ActionResults/WhenCsvResultsActionResultExecutorIsExecuted.cs
web/tests/Web.Tests/ActionResults/WhenCsvResultsIsExecuted.cs
web/tests/Web.Tests/Services/WhenCsvServiceIsCalled.cs

[AB#249208](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249208) [AB#242097](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/242097)
- CSV download of School Census data via proxy controller, delivered in a ZIP archive
- Designed to honour whatever Pupil comparator set currently displayed for the current user
- Unit test and integration test coverage
- Iterative development included ability to download single CSV rather than via ZIP, which intentionally remains in this PR
To download the ZIP file locally, send a `GET` to (e.g.)  `https://localhost:7095/api/census/download?type=school&id=123456`.

CSV download of School Census data in a ZIP archive

---

data-pipeline/src/pipeline/database.py
data-pipeline/src/pipeline/main.py
data-pipeline/tests/unit/test_database.py

Currently we `MERGE` data from a data-pipeline job into each corresponding table. This has led to instances where rows from a previous job have persisted where they should have, in fact, been removed.
[AB#240689](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/240689)  
- replace `MERGE` with `INSERT`/`DELETE` pattern
- note: for `School`, `Trust`, etc. we not store a per-`RunId` version of the data so they remain as-is for now.
- write _all_ comparator-set/RAG data as a single dataset
- writing academy/maintained separately means a single `RunId` is spread across two transactions.
~WIP until #1884 is merged; this might need a touch of refactoring afterwards.~
I've run `default`, `custom-data` and `comparator-set` jobs locally and all run as intended. …

feat: replace MERGE statements

---

web/src/Web.App/Controllers/Api/CensusProxyController.cs
web/src/Web.App/Controllers/Api/ExpenditureProxyController.cs
web/src/Web.App/Controllers/SchoolCensusController.cs
web/src/Web.App/Controllers/SchoolComparisonController.cs
web/src/Web.App/Views/SchoolCensus/Index.cshtml
web/src/Web.App/Views/SchoolComparison/Index.cshtml
web/tests/Web.Integration.Tests/Pages/Schools/Census/WhenRequestingCensusDownload.cs
web/tests/Web.Integration.Tests/Pages/Schools/Census/WhenViewingCensus.cs
web/tests/Web.Integration.Tests/Pages/Schools/Comparison/WhenRequestingComparisonDownload.cs
web/tests/Web.Integration.Tests/Pages/Schools/Comparison/WhenViewingComparison.cs
web/tests/Web.Integration.Tests/Pages/Schools/CustomData/WhenViewingCustomDataFinancialData.cs
web/tests/Web.Integration.Tests/Pages/Schools/CustomData/WhenViewingCustomDataNonFinancialData.cs
web/tests/Web.Integration.Tests/Pages/Schools/CustomData/WhenViewingCustomDataWorkforceData.cs
web/tests/Web.Integration.Tests/Pages/Schools/FinancialPlanning/WhenViewingPlanningSelectYear.cs
web/tests/Web.Integration.Tests/Pages/Schools/WhenViewingFinancialBenchmarkingInsightsSummary.cs
web/tests/Web.Integration.Tests/Pages/Schools/WhenViewingHomeAsFederation.cs
web/tests/Web.Integration.Tests/Paths.cs

[AB#249574](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249574) [AB#242097](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/242097) #1932
- Moved `/api/census/download` endpoint to `/school/{urn}/census/download`
- Moved `/api/expenditure/download` endpoint to `/school/{urn}/comparison/download`
- Dependent on #1932

Moved `/download` endpoints from proxy to alongside actions to which they are relevant

---

front-end-components/src/components/cost-codes-list/component.tsx
front-end-components/src/components/cost-codes-list/index.tsx
front-end-components/src/components/cost-codes-list/types.tsx
front-end-components/src/composed/horizontal-bar-chart-wrapper/composed.tsx
front-end-components/src/contexts/contexts.tsx
front-end-components/src/contexts/hooks.tsx
front-end-components/src/main.tsx
front-end-components/src/views/compare-your-costs/types.tsx
front-end-components/src/views/compare-your-costs/view.tsx
web/src/Web.App/AssetSrc/scss/main.scss
web/src/Web.App/Domain/CostCodes.cs
web/src/Web.App/ViewModels/LocalAuthorityComparisonViewModel.cs
web/src/Web.App/ViewModels/SchoolComparisonViewModel.cs
web/src/Web.App/ViewModels/SchoolSpendingViewModel.cs
web/src/Web.App/ViewModels/TrustComparisonViewModel.cs
web/src/Web.App/Views/LocalAuthorityComparison/Index.cshtml
web/src/Web.App/Views/SchoolComparison/CustomData.cshtml
web/src/Web.App/Views/SchoolComparison/Index.cshtml
web/src/Web.App/Views/SchoolSpending/CustomData.cshtml
web/src/Web.App/Views/SchoolSpending/Index.cshtml
web/src/Web.App/Views/SchoolSpending/_Costs.cshtml
web/src/Web.App/Views/TrustComparison/Index.cshtml
web/tests/Web.E2ETests/Pages/School/SpendingCostsPage.cs
web/tests/Web.Integration.Tests/Pages/Schools/WhenViewingSpending.cs
web/tests/Web.Tests/Domain/GivenASubCategoryCostCodes.cs

[AB#242100](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/242100) - [AB#248759](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/248759)
Adds CostCodes class to generate the CFR and AAR cost codes and map them to sub category names
A dictionary is passed to the front-end with these cost codes as part of the dataset for the `CompareYourCosts` element for the benchmark spending pages
For spending prorities the sub categories are used to lookup valid values for display.
Adds unit tests and integration tests
Updates selectors on e2e tests following these changes
Note - added for all versions of school benchmark spending - LA, Trust, Custom Data and default School
A bump to front end will follow
E2E tests will be …

feat: add costs codes to spending priorities and benchmark spending page

---

data-pipeline/src/pipeline/log.py

Currently the data-pipeline uses a standard logger. While this is generally okay, messages which span multiple lines (e.g. stacktraces) appear over multiple log entries, not necessarily in the right order.
[AB#243778](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/243778)  
use JSON-formatted log messages throughout, courtesy of [Python JSON Logger](https://nhairs.github.io/python-json-logger/).
Regular log messages now look like:
```txt
{"asctime": "2025-02-13 13:23:09,457", "levelname": "INFO", "module": "database", "message": "Creating temp. table: _NonF…
```
While errors can look like:
```txt
{"asctime": "2025-02-13 13:23:43,917", "levelname": "ERROR", "module": "main", "message": "An exception occurred: KeyError", "exc_info": "Traceback (most …
```

feat: use JSON for logging

---

web/src/Web.App/package-lock.json

[AB#242100](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/242100)
Bump to front end following #1937 
n/A

chore: bump `front-end` to `1.1.53`

---

front-end-components/src/components/element-selector/component.tsx
front-end-components/src/components/element-selector/types.tsx
front-end-components/src/components/modals/modal-save-images/modal-save-images-modal/component.tsx
front-end-components/src/components/modals/modal-save-images/modal-save-images-modal/types.tsx
front-end-components/src/components/share-content-by-element/component.tsx
front-end-components/src/components/share-content/types.tsx
front-end-components/src/hooks/useDownloadImage.ts
front-end-components/src/main.tsx
web/src/Web.App/ViewComponents/PageActionsViewComponent.cs
web/src/Web.App/ViewModels/Components/PageActionsViewModel.cs
web/src/Web.App/Views/SchoolSpending/Index.cshtml
web/src/Web.App/Views/SchoolSpending/_Costs.cshtml
web/src/Web.App/Views/Shared/Components/PageActions/Default.cshtml

[AB#242100](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/242100) - [AB#249508](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249508)
Similar to how we create the chart titles for the spending priorities page the we pass the cost codes through the `html-dataset` so that they can be used in `onCloned` to create the required elements for the image and set styles.
Slight refactor around `onCloned` as it is too busy with the addition of creating cost codes as well but previous behaviour should be preserved.
Is there a better way to achieve this?

feat: include cost code list in saved image for spending priorities

---

web/src/Web.App/package-lock.json

[AB#242100](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/242100) / #1947 
bump to front end package following #1947 
N/A

chore: bump `front-end` to `1.1.54`

---

web/tests/Web.E2ETests/Features/School/CompareYourCosts.feature
web/tests/Web.E2ETests/Pages/School/CompareYourCostsPage.cs
web/tests/Web.E2ETests/Selectors.cs
web/tests/Web.E2ETests/Steps/School/CompareYourCostsSteps.cs

[AB#242100](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/242100) / [AB#249509](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249509)
Adds e2e tests to cover behaviour of displaying cost codes for the benchmark spending page
note spending prioritites in covered under integration tests

chore: add e2e test for cost codes on benchmark spending

---

web/terraform/app-service.tf

[AB#249878](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249878) [AB#246758](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/246758) #1893 
Included both App Insights configuration settings to allow release annotations to be set during web app service deployment due to [this issue](https://github.com/microsoft/azure-pipelines-tasks/issues/20857).

Reinstate `APPINSIGHTS_INSTRUMENTATIONKEY` alongside `APPLICATIONINSIGHTS_CONNECTION_STRING` in web app service

---

front-end-components/index.html
front-end-components/src/components/charts/establishment-tick/component.tsx
front-end-components/src/components/charts/establishment-tick/types.tsx
front-end-components/src/composed/horizontal-bar-chart-wrapper/composed.tsx

[AB#249970](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249970) [AB#249969](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249969)
Prevents incorrect rendering of y-axis establishment name/link/highlight in the case of multiple establishments with the same names being in the source data set.
May be reproduced / validated based on the default benchmarking for the school in the linked work item.

Resolved logic in `getEstablishmentKey()` that may have caused multiple matches when using `name` as collection lookup

---

web/src/Web.App/package-lock.json

[AB#249970](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249970) [AB#249969](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249969) #1954
Follow-up to #1954 to get the fix into Web

Bumped `front-end` to `1.1.56`

---

.github/dependabot.yml
front-end-components/package-lock.json
front-end-components/package.json

[AB#248372](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/248372) - [AB#249983](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249983)
See the description in task 249983. In newer versions of this package a change has been introduced where the styling for the charts is not being resolved correctly resulting in the charts displaying incorrectly as images. Worth noting `1.11.11` is the most popular version.
See below comment from @WolfyUK  for likely source.
pin the version for `html-to-image` to `1.11.11`
front-end component can be built locally and using that for the Web app the charts should display correctly when saved. Worth clearing broswer cache as that can preserve styles if you have generated images …

chore: pin `html-to-image` to `1.11.11`

---

web/src/Web.App/package-lock.json

bump to `front-end` following #1963 
bump `front-end` to `1.1.58`
Following this charts should display correctly when saved as image

chore: bump `front-end` to `1.1.58`

---

documentation/features/6_Orchestrator.md
platform/src/abstractions/Platform.Domain/Messages/PipelineFinish.cs
platform/src/abstractions/Platform.Domain/Pipeline.cs
platform/src/apis/Platform.Orchestrator/Functions/ActivityTriggerFunctions.cs
platform/src/apis/Platform.Orchestrator/Functions/OrchestratorFunctions.cs
platform/src/apis/Platform.Orchestrator/Functions/PipelineQueueTriggerFunctions.cs
platform/src/apis/Platform.Orchestrator/Sql/PipelineDb.cs
platform/tests/Platform.Orchestrator.Tests/Functions/ActivityTrigger/WhenRunIndexerTriggered.cs
platform/tests/Platform.Orchestrator.Tests/Functions/OrchestrationTrigger/WhenPipelineJobDefaultFinishedTriggered.cs
platform/tests/Platform.Orchestrator.Tests/Functions/OrchestrationTrigger/WhenPipelineJobOrchestrationTriggeredByDefaultJobType.cs
platform/tests/Platform.Orchestrator.Tests/Sql/WhenPipelineDbDeactivatesUserData.cs
platform/tests/Platform.Orchestrator.Tests/Sql/WhenPipelineDbUpdatesUserDataStatus.cs
platform/tests/Platform.Orchestrator.Tests/Telemetry/WhenTelemetryServiceTracksEvent.cs

[AB#249839](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249839) [AB#249104](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249104)
- Moved post default run completion activity triggers to sub-orchestrator
- Set `dbo.UserData.Active` to `0` from `PipelineJobDefaultFinished` orchestrator upon success message received
- Send error from `PipelineFinish` message with custom event
Deployed and validated in `d12` feature environment.

Set `dbo.UserData.Active` to `0` upon receipt of successful default pipeline finished message

---

front-end-components/src/composed/horizontal-bar-chart-wrapper/composed.tsx
web/src/Web.App/Views/SchoolComparison/Index.cshtml
web/src/Web.App/Views/SchoolSpending/Index.cshtml
web/src/Web.App/Views/SchoolSpending/_Costs.cshtml
web/src/Web.App/Views/TrustComparison/Index.cshtml

[AB#242100](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/242100) - [AB#250518](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/250518)
use `costs-chart-wrapper` class so the correct element is targeted for the "save chart images" (all) for the page.
data atrributes moved to that element so they are used for title and cost codes.
will require a bump to front end.
to test locally can build and copy front-end for use in web app

fix: include suppress negative and zero warning text and cost codes in save all images for page

---

web/src/Web.App/package-lock.json

[AB#242100](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/242100) #2009 
bump `front-end` to `1.1.59`
n/a

chore: bump `front-end` to `1.1.59`

---

web/tests/Web.E2ETests/Extensions/PageExtensions.cs
web/tests/Web.E2ETests/Steps/LocalAuthority/BenchmarkCensusSteps.cs
web/tests/Web.E2ETests/Steps/LocalAuthority/CompareYourCostsSteps.cs
web/tests/Web.E2ETests/Steps/SaveImagesModalSteps.cs
web/tests/Web.E2ETests/Steps/School/BenchmarkCensusSteps.cs
web/tests/Web.E2ETests/Steps/School/CompareYourCostsSteps.cs
web/tests/Web.E2ETests/Steps/Trust/BenchmarkCensusSteps.cs
web/tests/Web.E2ETests/Steps/Trust/CompareYourCostsSteps.cs

[AB#250717](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/250717) [AB#242097](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/242097) #2014
Attempt to resolve flaky E2E tests around file downloads.

Replaced `WaitForDownloadAsync` with `RunAndWaitForDownloadAsync` in E2E tests

---

support-analytics/terraform/queries/pipeline-runs-custom.kql
support-analytics/terraform/queries/pipeline-runs-default.kql

The data-pipeline now uses JSON for logging, allowing us to make better use of the data therein.
[AB#243778](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/243778)  
Following changes to format data-pipeline logs as JSON (#1944), update existing KQL queries to extract relevant fields.
Unabashedly stolen from @WolfyUK's suggestion.
I've run these against `d01` and the queries/output appear as expected.

feat: extract fields from data-pipeline logs

---

web/src/Web.App/AssetSrc/scss/main.scss
web/src/Web.App/Constants/DataSourceTypes.cs
web/src/Web.App/Constants/PageTitles.cs
web/src/Web.App/Controllers/LocalAuthorityHighNeedsBenchmarkingController.cs
web/src/Web.App/Controllers/LocalAuthorityHighNeedsHistoricDataController.cs
web/src/Web.App/Controllers/LocalAuthorityHighNeedsNationalRankingsController.cs
web/src/Web.App/ViewComponents/DataSourceViewComponent.cs
web/src/Web.App/Views/LocalAuthorityHighNeeds/Index.cshtml
web/src/Web.App/Views/LocalAuthorityHighNeedsBenchmarking/Index.cshtml
web/src/Web.App/Views/LocalAuthorityHighNeedsHistoricData/Index.cshtml
web/src/Web.App/Views/LocalAuthorityHighNeedsNationalRankings/Index.cshtml
web/src/Web.App/Views/Shared/Components/LocalAuthorityFinanceTools/Default.cshtml
web/tests/Web.A11yTests/Pages/LocalAuthority/WhenViewingHighNeedsHistoricData.cs
web/tests/Web.A11yTests/Pages/LocalAuthority/WhenViewingHighNeedsNationalRankings.cs
web/tests/Web.A11yTests/Pages/LocalAuthority/WhenViewingHighNeedsStartBenchmarking.cs
web/tests/Web.E2ETests/Features/LocalAuthority/HighNeedsBenchmarking.feature
web/tests/Web.E2ETests/Pages/LocalAuthority/HighNeedsBenchmarkingPage.cs
web/tests/Web.E2ETests/Pages/LocalAuthority/HighNeedsHistoricDataPage.cs
web/tests/Web.E2ETests/Pages/LocalAuthority/HighNeedsNationalRankingsPage.cs
web/tests/Web.E2ETests/Pages/LocalAuthority/HighNeedsStartBenchmarkingPage.cs
web/tests/Web.E2ETests/Selectors.cs
web/tests/Web.E2ETests/Steps/LocalAuthority/HighNeedsBenchmarkingSteps.cs
web/tests/Web.Integration.Tests/Pages/LocalAuthorities/WhenViewingHighNeeds.cs
web/tests/Web.Integration.Tests/Pages/LocalAuthorities/WhenViewingHome.cs
web/tests/Web.Integration.Tests/Paths.cs

[AB#250675](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/250675) [AB#249538](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249538) #2011
- New High needs target pages and links from High needs landing page
- Added summary card layout to High needs landing page
- Added placeholder data source content to High needs page
- E2E, a11y and integration tests
Dependency on #2011. Deployed to `d18` feature environment.

Added High needs target pages and CTAs from High needs landing page

---

data-pipeline/src/pipeline/main.py
data-pipeline/src/pipeline/pre_processing/__init__.py
data-pipeline/src/pipeline/pre_processing/academies/academies.py
data-pipeline/src/pipeline/pre_processing/ancillary/__init__.py
data-pipeline/src/pipeline/pre_processing/ancillary/gias.py
data-pipeline/src/pipeline/pre_processing/ancillary/schools.py
data-pipeline/tests/unit/pre_processing/test_gias_links.py

Some Academies in the 2024 data are missing pupil and/or floor-area data, leading to missing data, apportionment issues, etc.
Extend the Census data:
- AAR URNs may be missing from the Census data
- for those missing URNs, check for GIAS `Predecessor` links
- for those links, check for Census data via the `LinkURN`
- for those with Census data, duplicate those data for the GIAS-links' `URN` and `LinkURN` values
…and as per the above CDC/GIAS-links processing:
- refactor this to supplement _any_ dataset via GIAS-links
- pass the CDC data to this function
[AB#250420](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/250420)  
Ran locally and the URNs flagged initially now have `TotalPupils` and `TotalInternalFloorArea` populated as expected.

feat: supplement missing Census/CDC data via GIAS-links

---

platform/src/abstractions/Platform.Functions/Extensions/NameValueCollectionExtensions.cs
platform/src/abstractions/Platform.Functions/Extensions/QueryCollectionExtensions.cs
platform/src/abstractions/Platform.Functions/QueryParameters.cs
platform/src/abstractions/tests/Platform.Functions.Tests/Extensions/WhenNameValueCollectionExtensionsConvertsFromQuery.cs
platform/src/apis/Platform.Api.LocalAuthorityFinances/Configuration/Services.cs
platform/src/apis/Platform.Api.LocalAuthorityFinances/Constants.cs
platform/src/apis/Platform.Api.LocalAuthorityFinances/Features/HighNeeds/GetHighNeedsHistoryFunction.cs
platform/src/apis/Platform.Api.LocalAuthorityFinances/Features/HighNeeds/HighNeedsFeature.cs
platform/src/apis/Platform.Api.LocalAuthorityFinances/Features/HighNeeds/Models/History.cs
platform/src/apis/Platform.Api.LocalAuthorityFinances/Features/HighNeeds/Parameters/HighNeedsHistoryParameters.cs
platform/src/apis/Platform.Api.LocalAuthorityFinances/Features/HighNeeds/Routes.cs
platform/src/apis/Platform.Api.LocalAuthorityFinances/Features/HighNeeds/Services/HighNeedsHistoryService.cs
platform/src/apis/Platform.Api.LocalAuthorityFinances/Features/HighNeeds/Services/HighNeedsHistoryStubService.cs
platform/src/apis/Platform.Api.LocalAuthorityFinances/Features/Validators/HighNeedsHistoryParametersValidator.cs
platform/src/apis/Platform.Api.LocalAuthorityFinances/Program.cs
platform/tests/Platform.ApiTests/Features/LocalAuthoritiesHighNeeds.feature
platform/tests/Platform.ApiTests/Steps/LocalAuthoritiesHighNeedsSteps.cs
platform/tests/Platform.LocalAuthorityFinances.Tests/HighNeeds/HighNeedsHistoryParametersTests.cs
platform/tests/Platform.LocalAuthorityFinances.Tests/Validators/WhenHighNeedsHistoryParametersValidatorValidates.cs

[AB#251204](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/251204) [AB#249550](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249550)
- New endpoint with API test coverage over stubbed data
- Marked `QueryParameters.SetValues(IQueryCollection query)` as obsolete
To validate locally, debug the `LocalAuthorities` function app and run Swagger UI: `http://localhost:7074/api/swagger/ui#/High%20Needs/GetHighNeedsHistoryFunction`

LA high needs history endpoint with stubbed data

---

web/Web.sln.DotSettings
web/src/Web.App/Controllers/Api/HighNeedsProxyController.cs
web/src/Web.App/Controllers/Api/Mappers/LocalAuthorityHighNeedsHistoryResponseMapper.cs
web/src/Web.App/Controllers/Api/Responses/LocalAuthorityHighNeedsHistoryResponse.cs
web/src/Web.App/Domain/LocalAuthorities/HighNeedsAmount.cs
web/src/Web.App/Domain/LocalAuthorities/History.cs
web/src/Web.App/Domain/LocalAuthorities/LocalAuthorityHighNeeds.cs
web/src/Web.App/Domain/LocalAuthorities/PlaceFunding.cs
web/src/Web.App/Domain/LocalAuthorities/TopFunding.cs
web/src/Web.App/Extensions/ServiceCollectionExtensions.cs
web/src/Web.App/Infrastructure/Apis/LocalAuthorities/Api.cs
web/src/Web.App/Infrastructure/Apis/LocalAuthorities/LocalAuthoritiesApi.cs
web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
web/tests/Web.Integration.Tests/Paths.cs
web/tests/Web.Integration.Tests/Proxy/WhenRequestingHighNeedsHistory.cs
web/tests/Web.Integration.Tests/Proxy/WhenRequestingNationalRanking.cs
web/tests/Web.Tests/Controllers/Api/Mappers/WhenLocalAuthorityHighNeedsHistoryResponseMapperMapsWithCode.cs

[AB#251206](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/251206) [AB#249550](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249550) #2030
Proxy endpoint and integration test coverage. Includes mapping API response to flattened type expected by consuming charts/tables.
Dependent on #2030. May be validated locally from `https://localhost:7095/swagger/index.html#operations-tag-HighNeedsProxy`

Added Web proxy for High needs history endpoint

---

data-pipeline/src/pipeline/database.py

Writing of `MetricRAG` to the temp. table is taking 60 minutes+.
[AB#250420](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/250420)  
Use the [`chunksize` parameter](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_sql.html) of Pandas' `to_sql()` method to reduce the batch size (configurable by an environment variable but with a default of 10,000).
Verified locally that data are still correctly written to the DB.

fix: use chunksize for df.to_sql

---

data-pipeline/src/pipeline/database.py

Currently, we've little insight into the actual queries being made to the DB (some of which are obfuscated by Pandas' `to_sql()` calls).
Log (at a `DEBUG` level) every query to the database: as queries are now batched, this should be minimal but may highlight instances where this is _not_ occuring.
Similar to the previous use of `fast_executemany`, this will trigger before each DB-cursor use.
Note: this logs the _statement_ only, not any params. passed.
By way of evidence:
```sh
{"asctime": "2025-02-27 08:51:46,443", "levelname": "DEBUG", "module": "database", "message": "DROP TABLE _Financial_2021_1740646300_temp;"}
{"asctime": "2025-02-27 08:51:46,452", "levelname": "INFO", "module": "database", "message": "Wrote 22,420 rows to Financial:2021 in 1 seconds."}
{"asctime": "2025-02-27 …
```

feat: add debug logging for SQL logging

---

front-end-components/index.html
front-end-components/src/components/charts/historic-data-section-251-tooltip/component.tsx
front-end-components/src/components/charts/historic-data-section-251-tooltip/index.tsx
front-end-components/src/components/charts/historic-data-section-251-tooltip/types.tsx
front-end-components/src/components/charts/resolved-stat/component.tsx
front-end-components/src/components/charts/resolved-stat/types.tsx
front-end-components/src/composed/historic-chart-section-251-composed/component.tsx
front-end-components/src/composed/historic-chart-section-251-composed/index.tsx
front-end-components/src/composed/historic-chart-section-251-composed/styles.scss
front-end-components/src/composed/historic-chart-section-251-composed/types.tsx
front-end-components/src/constants.tsx
front-end-components/src/main.tsx
front-end-components/src/services/high-needs-api.tsx
front-end-components/src/services/types.tsx
front-end-components/src/views/historic-data-high-needs/index.tsx
front-end-components/src/views/historic-data-high-needs/partials/index.tsx
front-end-components/src/views/historic-data-high-needs/partials/section-251-section.tsx
front-end-components/src/views/historic-data-high-needs/partials/send-2-section.tsx
front-end-components/src/views/historic-data-high-needs/types.tsx
front-end-components/src/views/historic-data-high-needs/view.tsx

[AB#251207](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/251207) [AB#249550](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249550)
- Created new view containing two tabs
- Implemented Section 251 tab, leaving SEND 2 tab empty for now
- Added chart section and multi-series configuration
- Mapped to charts and tables from API response
- Added tooltips and stats to charts (subject to design crit)
- Added explicit error logging and correlation ID to underlying function app
May be validated locally using Vite dev server with the stubbed data from the API. e.g.:

Added Section 251 historical charts to new `<HistoricDataHighNeeds>` view

---

web/src/Web.App/ViewComponents/LocalAuthorityHighNeedsNationalRankingsViewComponent.cs
web/src/Web.App/Views/LocalAuthorityHighNeeds/Index.cshtml
web/src/Web.App/Views/Shared/Components/LocalAuthorityHighNeedsNationalRankings/Default.cshtml
web/src/Web.App/Views/Shared/Components/LocalAuthorityHighNeedsNationalRankings/MissingData.cshtml
web/tests/Web.Integration.Tests/Pages/LocalAuthorities/WhenViewingHighNeeds.cs

[AB#251215](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/251215) [AB#249550](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249550) #2038
- Added warning message with integration test coverage
- Conditionally rendered national rankings CTA based on successful retrieval of underlying data
Dependent on #2038. Published to `d18` feature environment for validation.

Warning message on High need dashboard if national ranking could not be loaded

---

platform/src/apis/Platform.Api.LocalAuthorityFinances/Features/HighNeeds/HighNeedsFeature.cs
platform/src/apis/Platform.Api.LocalAuthorityFinances/Features/HighNeeds/Validators/HighNeedsHistoryParametersValidator.cs
platform/tests/Platform.Establishment.Tests/LocalAuthorities/GetLocalAuthoritiesNationalRankFunctionTests.cs
platform/tests/Platform.LocalAuthorityFinances.Tests/HighNeeds/GetHighNeedsHistoryFunctionTests.cs
platform/tests/Platform.LocalAuthorityFinances.Tests/HighNeeds/Parameters/HighNeedsHistoryParametersTests.cs
platform/tests/Platform.LocalAuthorityFinances.Tests/HighNeeds/Validators/WhenHighNeedsHistoryParametersValidatorValidates.cs
platform/tests/Platform.LocalAuthorityFinances.Tests/Platform.LocalAuthorityFinances.Tests.csproj
platform/tests/Platform.LocalAuthorityFinances.Tests/packages.lock.json

[AB#251901](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/251901) [AB#249550](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249550)
- Moved `HighNeedsHistoryParametersValidator` into correct namespace
- Unit test coverage over recently added functions

QC pass over recent Platform API additions that support High needs

---

web/src/Web.App/Domain/LocalAuthorities/History.cs
web/src/Web.App/ViewComponents/LocalAuthorityHighNeedsHistoryViewComponent.cs
web/src/Web.App/Views/LocalAuthorityHighNeeds/Index.cshtml
web/src/Web.App/Views/Shared/Components/LocalAuthorityHighNeedsHistory/Default.cshtml
web/src/Web.App/Views/Shared/Components/LocalAuthorityHighNeedsHistory/MissingData.cshtml
web/tests/Web.Integration.Tests/Pages/LocalAuthorities/WhenViewingHighNeeds.cs

[AB#251214](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/251214) [AB#249539](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249539)
- Added warning message with integration test coverage
- Conditionally rendered High needs history CTA based on successful retrieval of underlying data
Published to `d18` feature environment for validation.

Warning message on High need dashboard if High needs history could not be loaded

---

web/src/Web.App/AssetSrc/scss/main.scss
web/src/Web.App/Views/LocalAuthorityHighNeeds/Index.cshtml
web/src/Web.App/Views/Shared/Components/LocalAuthorityHighNeedsHistory/Default.cshtml
web/src/Web.App/Views/Shared/Components/LocalAuthorityHighNeedsNationalRankings/Default.cshtml

[AB#251915](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/251915) [AB#251916](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/251916) [AB#249539](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249539) [AB#249540](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249540)
- CSS changes to dashboard tables to better support long headings and cell values
- CSS changes to dashboard summary cards to better support low-resolution clients
Deployed to `d18` for validation.

High needs dashboard summary card and table formatting responsiveness

---

platform/src/apis/Platform.Api.LocalAuthorityFinances/Features/HighNeeds/Models/History.cs
platform/src/apis/Platform.Api.LocalAuthorityFinances/Features/HighNeeds/Services/HighNeedsHistoryStubService.cs
platform/tests/Platform.ApiTests/Features/LocalAuthoritiesHighNeeds.feature
web/src/Web.App/Controllers/Api/Mappers/LocalAuthorityHighNeedsHistoryResponseMapper.cs
web/src/Web.App/Domain/LocalAuthorities/LocalAuthorityHighNeeds.cs
web/tests/Web.Integration.Tests/Pages/LocalAuthorities/WhenViewingHighNeeds.cs
web/tests/Web.Integration.Tests/packages.lock.json
web/tests/Web.Tests/Controllers/Api/Mappers/WhenLocalAuthorityHighNeedsHistoryResponseMapperMapsToDashboardWithCode.cs
web/tests/Web.Tests/packages.lock.json

[AB#251922](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/251922) [AB#249540](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249540)
- Added new `Total` property to source model in Platform
- Stubbed `Total` value in the short term
- Mapped `Total` property in Web
- Updated affected tests
Deployed to `d18` for validation

Added and wired up Budget vs spend (historical view) dashboard content to new `Total` field on `LocalAuthorityHighNeeds`

---

front-end-components/package-lock.json

[AB#251360](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/251360) [AB#251353](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/251353)
- `@typescript-eslint/parser` has peer dependency on `typescript@">=4.8.4 <5.8.0"`, so `typescript@5.8.2` has been excluded here

Updated `front-end` dependencies

---

front-end-components/index.html
front-end-components/src/services/education-health-care-plans-api.tsx
front-end-components/src/services/types.tsx
front-end-components/src/views/historic-data-high-needs/partials/index.tsx
front-end-components/src/views/historic-data-high-needs/partials/send-2-section.tsx
front-end-components/src/views/historic-data-high-needs/types.tsx

[AB#249550](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249550) - [AB#251208](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/251208)
- using existing `HistoricChart` component. 
- `EducationHealthCarePlanApi` created to support this.
Currently `axisLabel` is not included but can be added quickly if later required.
Can run locally using Vite or copy and build `front-end` to Web to verify.
Will require a bump to `front-end` and then can be deployed to `d18`

feat: add content to `Send2Section` component

---

web/src/Web.App/package-lock.json

[AB#249550](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249550) - #2060 
bump `front-end` to `1.1.65`
n/a

chore: bump `front-end` to `1.1.65`

---

platform/src/apis/Platform.Api.Establishment/Features/LocalAuthorities/Services/LocalAuthoritiesService.cs
platform/tests/Platform.ApiTests/Features/EstablishmentLocalAuthorities.feature
web/src/Web.App/AssetSrc/scss/main.scss
web/src/Web.App/Constants/PageTitles.cs
web/src/Web.App/Controllers/LocalAuthorityHighNeedsBenchmarkingController.cs
web/src/Web.App/Domain/Establishment/LocalAuthorityStatisticalNeighbours.cs
web/src/Web.App/Infrastructure/Apis/Establishment/Api.cs
web/src/Web.App/Infrastructure/Apis/Establishment/EstablishmentApi.cs
web/src/Web.App/ViewModels/LocalAuthorityStatisticalNeighboursViewModel.cs
web/src/Web.App/Views/LocalAuthorityHighNeedsBenchmarking/Index.cshtml
web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
web/tests/Web.Integration.Tests/Pages/LocalAuthorities/WhenViewingHighNeeds.cs
web/tests/Web.Integration.Tests/Pages/LocalAuthorities/WhenViewingHighNeedsStartBenchmarking.cs
web/tests/Web.Tests/Infrastructure/GivenAnEstablishmentApi.cs

[AB#252040](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/252040) [AB#249552](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249552)
- List of statistical neighbours for LA using stubbed endpoint
- Integration tests for ordered list on benchmarking page
Deployed to `d18` for validation.

Displayed statistical neighbours on High needs Start benchmarking page

---

platform/Platform.sln.DotSettings
platform/src/abstractions/Platform.Sql/DatabaseConnection.cs
platform/src/abstractions/Platform.Sql/QueryBuilders/LocalAuthorityQueries.cs
platform/src/abstractions/Platform.Sql/QueryBuilders/PlatformQuery.cs
platform/src/abstractions/tests/Platform.Sql.Tests/Builders/LocalAuthorityQueryTests.cs
platform/src/abstractions/tests/Platform.Sql.Tests/Builders/PlatformQueryTests.cs
platform/src/apis/Platform.Api.Establishment/Features/LocalAuthorities/GetLocalAuthoritiesFunction.cs
platform/src/apis/Platform.Api.Establishment/Features/LocalAuthorities/Routes.cs
platform/src/apis/Platform.Api.Establishment/Features/LocalAuthorities/Services/LocalAuthoritiesService.cs
platform/tests/Platform.ApiTests/Features/EstablishmentLocalAuthorities.feature
platform/tests/Platform.ApiTests/Steps/EstablishmentLocalAuthoritiesSteps.cs
platform/tests/Platform.Establishment.Tests/LocalAuthorities/GetLocalAuthoritiesFunctionTests.cs
platform/tests/Platform.Establishment.Tests/LocalAuthorities/GetLocalAuthorityStatisticalNeighboursFunctionTests.cs
platform/tests/Platform.Establishment.Tests/LocalAuthorities/WhenLocalAuthoritiesServiceQueriesAsync.cs

[AB#252078](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/252078) [AB#249552](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249552)
- New endpoint that returns an array of all LA Code/Names only
- API test coverage
Maybe validated locally in Swagger UI, e.g.: `http://localhost:7073/api/swagger/ui#/Local%20Authorities/GetLocalAuthoritiesFunction`

New endpoint in Establishment API to return all Local Authorities, ordered by name

---

web/src/Web.App/Constants/SessionKeys.cs
web/src/Web.App/Domain/Benchmark/LocalAuthorityComparatorSet.cs
web/src/Web.App/Program.cs
web/src/Web.App/Services/LocalAuthorityComparatorSetService.cs
web/tests/Web.Tests/Services/WhenLocalAuthorityComparatorSetServiceIsCalled.cs
web/tests/Web.Tests/Stubs/SessionStub.cs

[AB#252037](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/252037) [AB#249552](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249552)
- New service to persist comparator set to session
To be consumed as part of future work on this story.

Added `LocalAuthorityComparatorSetService` for persisting comparators to session

---

web/src/Web.App/package-lock.json

[AB#249550](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249550) - #2074 
bump `front-end` to `1.1.66`
n/a

chore: bump `front-end` to `1.1.66`

---

web/Web.sln.DotSettings
web/src/Web.App/AssetSrc/scss/main.scss
web/src/Web.App/Constants/TrackedRequestType.cs
web/src/Web.App/Controllers/LocalAuthorityHighNeedsBenchmarkingController.cs
web/src/Web.App/Controllers/LocalAuthorityHighNeedsController.cs
web/src/Web.App/Controllers/LocalAuthorityHighNeedsHistoricDataController.cs
web/src/Web.App/Controllers/LocalAuthorityHighNeedsNationalRankingsController.cs
web/src/Web.App/Infrastructure/Apis/Establishment/Api.cs
web/src/Web.App/Infrastructure/Apis/Establishment/EstablishmentApi.cs
web/src/Web.App/ViewComponents/LocalAuthorityComparatorsViewComponent.cs
web/src/Web.App/ViewModels/Components/LocalAuthorityComparatorsViewModel.cs
web/src/Web.App/ViewModels/LocalAuthorityComparatorViewModel.cs
web/src/Web.App/ViewModels/LocalAuthorityHighNeedsBenchmarkingViewModel.cs
web/src/Web.App/Views/LocalAuthorityHighNeedsBenchmarking/Index.cshtml
web/src/Web.App/Views/Shared/Components/LocalAuthorityComparators/Default.cshtml
web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
web/tests/Web.Integration.Tests/Pages/LocalAuthorities/WhenViewingHighNeeds.cs
web/tests/Web.Integration.Tests/Pages/LocalAuthorities/WhenViewingHighNeedsStartBenchmarking.cs

[AB#252038](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/252038) [AB#249552](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249552)
- Select/add/remove LAs (via `<select>` only in current iteration)
- Validation for selection and min/max items
- Save to session or cancel
- Integration tests
Deployed to `d18` feature environment for validation. Progressive enhancement to follow as part of future work. Copy review as part of future work (especially around validation messages).

Management and persistence of comparator LAs for High needs benchmarking

---

support-analytics/terraform/README.md
support-analytics/terraform/alerts.tf
support-analytics/terraform/queries.tf
support-analytics/terraform/queries/functions/get-web-warnings.kql
support-analytics/terraform/queries/polly-warnings.kql
web/src/Web.App/Extensions/HttpClientBuilderExtensions.cs
web/src/Web.App/Properties/launchSettings.json
web/src/Web.App/appsettings.Development.json

[AB#252424](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/252424) [AB#249246](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249246)
- Extended structured logging for Polly and created query to return warnings from `AppTraces`
- Log query alert rule for excessive `429` status codes from logged Polly warnings
- Log query alert rule for excessive Polly warnings over previous 24 hours
Deployed to `d18`, along with sample endpoint that returns `429`. To test, GET `.../api/429`. Alerts should be sent to the Development Teams channel, e.g.:

Extended Polly logging and alerting

---

front-end-components/src/views/historic-data-high-needs/partials/index.tsx
web/tests/Web.E2ETests/Features/LocalAuthority/HighNeedsHistoricData.feature

[AB#249550](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249550)
incorrect chart title flagged in QA
Corrects chart name
Updates E2E tests (for table values assertion)
Running locally with Vite or copying front end to web should now show the correct chart heading on the send 2 tab lead chart
Was Number aged up to 25 with SEN statement or EHC plan (per 1000 2 to 18 population)
Now Number aged up to 25 with SEN statement or EHC plan
Will require a bump to front end following this PR

Fix chart heading for historic data high needs send 2 lead chart

---

front-end-components/index.html
front-end-components/src/components/charts/horizontal-bar-chart/component.tsx
front-end-components/src/components/charts/table-chart/component.tsx
front-end-components/src/components/charts/table-chart/types.tsx
front-end-components/src/components/charts/types.tsx
front-end-components/src/composed/benchmark-chart-section-251/component.tsx
front-end-components/src/composed/benchmark-chart-section-251/index.tsx
front-end-components/src/composed/benchmark-chart-section-251/types.tsx
front-end-components/src/composed/benchmark-chart-send-2/component.tsx
front-end-components/src/composed/benchmark-chart-send-2/index.tsx
front-end-components/src/composed/benchmark-chart-send-2/types.tsx
front-end-components/src/composed/horizontal-bar-chart-multi-series/composed.tsx
front-end-components/src/composed/horizontal-bar-chart-multi-series/index.tsx
front-end-components/src/composed/horizontal-bar-chart-multi-series/styles.scss
front-end-components/src/composed/horizontal-bar-chart-multi-series/types.tsx
front-end-components/src/constants.tsx
front-end-components/src/main.tsx
front-end-components/src/services/education-health-care-plans-api.tsx
front-end-components/src/services/high-needs-api.tsx
front-end-components/src/services/types.tsx
front-end-components/src/views/benchmark-data-high-needs/index.tsx
front-end-components/src/views/benchmark-data-high-needs/partials/benchmark-high-needs-accordion.tsx
front-end-components/src/views/benchmark-data-high-needs/partials/index.tsx
front-end-components/src/views/benchmark-data-high-needs/partials/section-251-section.tsx
front-end-components/src/views/benchmark-data-high-needs/partials/send-2-section.tsx
front-end-components/src/views/benchmark-data-high-needs/types.tsx
front-end-components/src/views/benchmark-data-high-needs/view.tsx
front-end-components/src/views/index.tsx
web/src/Web.App/Controllers/Api/HighNeedsProxyController.cs

[AB#252630](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/252630) [AB#249557](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249557)
- New view that calls proxy endpoints to display S251 and SEND2 data for the LAs in the comparator set
- Layout, colours, etc. likely to need tweaking based on feedback/design crit (especially for multi-series outturn vs budget charts)
Run the local Vite dev server to preview the new components after having first created a comparator set during the current Web session.

Created front-end view for Benchmarking High needs data

---

web/tests/Web.E2ETests/Features/LocalAuthority/HighNeedsBenchmarking.feature
web/tests/Web.E2ETests/Features/LocalAuthority/HighNeedsDashboard.feature
web/tests/Web.E2ETests/Features/LocalAuthority/HighNeedsStartBenchmarking.feature
web/tests/Web.E2ETests/Pages/LocalAuthority/HighNeedsBenchmarkingPage.cs
web/tests/Web.E2ETests/Pages/LocalAuthority/HighNeedsDashboardPage.cs
web/tests/Web.E2ETests/Pages/LocalAuthority/HighNeedsStartBenchmarkingPage.cs
web/tests/Web.E2ETests/Pages/LocalAuthority/HomePage.cs
web/tests/Web.E2ETests/Selectors.cs
web/tests/Web.E2ETests/Steps/LocalAuthority/HighNeedsBenchmarkingSteps.cs
web/tests/Web.E2ETests/Steps/LocalAuthority/HighNeedsDashboardSteps.cs
web/tests/Web.E2ETests/Steps/LocalAuthority/HighNeedsStartBenchmarkingSteps.cs
web/tests/Web.E2ETests/Steps/LocalAuthority/HomeSteps.cs

[AB#252632](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/252632) [AB#249557](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249557) [AB#251848](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/251848) [AB#249552](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249552)
E2E test coverage
It is known that another pass will be required once the accordions have been removed from the benchmarking page.

Remaining E2E test coverage over High needs benchmarking pages

---

platform/src/apis/Platform.Api.LocalAuthorityFinances/Features/HighNeeds/GetHighNeedsFunction.cs
platform/src/apis/Platform.Api.NonFinancial/Features/EducationHealthCarePlans/GetEducationHealthCarePlansLocalAuthoritiesFunction.cs
web/src/Web.App/Controllers/Api/EducationHealthCarePlansProxyController.cs
web/src/Web.App/Controllers/Api/HighNeedsProxyController.cs

[AB#252982](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/252982) [AB#249575](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249575)
Also marked `dimension` as required in OpenAPI spec in dimensioned endpoints.
No functional changes to Benchmarking functionality after this change - even if stubbed data was not in use. Subsequent work items will call High needs endpoints with newly defined dimensions at which point the stubbed data will be modified.

Added explicit dimensions to High needs comparator requests

---

platform/src/abstractions/Platform.Domain/Dimensions.cs
platform/src/abstractions/tests/Platform.Domain.Tests/WhenDimensionsChecksIsValid.cs
platform/src/apis/Platform.Api.LocalAuthorityFinances/Features/HighNeeds/Parameters/HighNeedsDimensionedParameters.cs
platform/src/apis/Platform.Api.LocalAuthorityFinances/Features/HighNeeds/Services/HighNeedsStubService.cs
platform/src/apis/Platform.Api.NonFinancial/Features/EducationHealthCarePlans/Parameters/EducationHealthCarePlansDimensionedParameters.cs
platform/src/apis/Platform.Api.NonFinancial/Features/EducationHealthCarePlans/Services/EducationHealthCarePlansStubService.cs
platform/tests/Platform.ApiTests/Features/LocalAuthoritiesHighNeeds.feature
platform/tests/Platform.ApiTests/Features/NonFinancialEducationHealthCarePlansLocalAuthorities.feature
web/tests/Web.E2ETests/Features/LocalAuthority/HighNeedsBenchmarking.feature

[AB#253062](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/253062) [AB#249575](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249575) #2101
Also updated affected tests.
Dependency on #2101. There are changes to Benchmarking figures here due to modified stubbed data with the `Actuals` dimensions being made significantly larger than the corresponding `PerXXX` values. E2E coverage has been updated accordingly in anticipation of a future sweep once proper test data is available and stubs dropped.

Set `Actuals` as default dimension for High needs endpoints and extended stubbed data

---

data-pipeline/README.md
documentation/data/4_Releases.md
platform/src/abstractions/Platform.Domain/Messages/PipelineStartDefault.cs
platform/src/abstractions/tests/Platform.Domain.Tests/Messages/WhenPipelineStartDefaultCreatesFromPending.cs
platform/tests/Platform.Orchestrator.Tests/Functions/ActivityTrigger/WhenPipelineStartDefaultJobTriggered.cs

[AB#253140](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/253140) [AB#250667](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/250667)
Updated `default` message format processed and forwarded by Orchestrator
May be validated by running Orchestrator and placing message of the new format onto the attached `pending` queue. Once moved to the `start-default` queue the new field should still be present.

Added `s251` to default pipeline message years schema in Orchestrator

---

platform/src/abstractions/Platform.Sql/QueryBuilders/LocalAuthorityQueries.cs
platform/src/abstractions/tests/Platform.Sql.Tests/Builders/LocalAuthorityQueryTests.cs
platform/src/apis/Platform.Api.NonFinancial/Features/EducationHealthCarePlans/EducationHealthCarePlansFeature.cs
platform/src/apis/Platform.Api.NonFinancial/Features/EducationHealthCarePlans/Models/LocalAuthorityNumberOfPlans.cs
platform/src/apis/Platform.Api.NonFinancial/Features/EducationHealthCarePlans/Services/EducationHealthCarePlansService.cs
platform/src/apis/Platform.Api.NonFinancial/Features/EducationHealthCarePlans/Services/EducationHealthCarePlansStubService.cs
platform/tests/Platform.NonFinancial.Tests/EducationHealthCarePlans/Services/WhenEducationHealthCarePlansServiceQueriesAsync.cs

[AB#253442](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/253442) [AB#253282](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/253282)
- Replaced stubbed version of the above service method
- Used correct database view dependent on dimension using new `PlatformQuery`, with test coverage
- Remaining stubbed service implementations with dependency on LA non-financials to be resolve as part of other work items.
- E2E and API tests will be in a failing state until seed data added as part of other work items. These are currently excluded from pipeline runs anyway, so this change should not block upstream deployments.

Wire up `EducationHealthCarePlansService.Get()` to underlying database views to replace stubbed version

---

data-pipeline/src/pipeline/main.py
data-pipeline/src/pipeline/pre_processing/local_authority.py
data-pipeline/tests/unit/pre_processing/local_authorities/conftest.py

Previously we were manually exporting the worksheet of interest as a CSV, rather than processing the "raw" file.
[AB#250505](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/250505)
process the single worksheet in the Statistical Neighbours Excel file, rather than exporting as a CSV.
Re. the tests, Pandas' [`to_excel`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_excel.html) is slightly less elegant than it's `to_csv` counterpart, insofar as you have to pass it a writer/sink.

feat: process LA Statistical Neighbours Excel file

---

front-end-components/src/components/charts/data-warning/component.tsx
front-end-components/src/components/charts/data-warning/types.tsx
front-end-components/src/components/charts/establishment-tick/component.tsx
front-end-components/src/components/charts/types.tsx
front-end-components/src/composed/benchmark-chart-section-251/component.tsx
front-end-components/src/composed/benchmark-chart-send-2/component.tsx
front-end-components/src/composed/horizontal-bar-chart-multi-series/composed.tsx
front-end-components/src/composed/horizontal-bar-chart-multi-series/types.tsx
front-end-components/src/composed/horizontal-bar-chart-wrapper/composed.tsx
front-end-components/src/composed/horizontal-bar-chart-wrapper/types.tsx

[AB#253550](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/253550) [AB#249557](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249557)
Updated front-end components to render warning on horizontal bar charts when expected data is missing. e.g.:

Display missing data warning on LA benchmarking

---

data-pipeline/src/pipeline/config/__init__.py
data-pipeline/src/pipeline/config/local_authority.py
data-pipeline/src/pipeline/database.py
data-pipeline/src/pipeline/main.py

The `LocalAuthorityNonFinancial` table needs to be populated with the Local Authority SEN2-derived data.
[AB#253282](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/253282)
store Local Authority SEN2 data in the `LocalAuthorityNonFinancial` table.
Following previous patterns; validated locally.

feat: persist Local Authority SEN2 data

---

data-pipeline/src/pipeline/config/__init__.py
data-pipeline/src/pipeline/config/local_authority.py
data-pipeline/src/pipeline/database.py
data-pipeline/src/pipeline/main.py
data-pipeline/tests/unit/test_database.py

The `LocalAuthorityStatisticalNeighbour` needs to be populated with data derived from the stat. neighbours data.
[AB#253286](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/253286)
un-pivot and store Local Authority Statistical Neighbour data in the `LocalAuthorityStatisticalNeighbour` table.
Un-pivoting the the data from the various `SN`-prefixed columns is more complicated that previous Local Authority data but otherwise, this follows previous patterns.

feat: persist Local Authority Statistical Neighbour data

---

data-pipeline/src/pipeline/input_schemas/local_authority.py

Error when running 2021/2022 in d01: `An exception occurred: UndefinedVariableError`.
[AB#251853](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/251853)
- the data held for 2021/2022 differs slightly from that of 2023/2024, resulting in different requirements for the `EHCPOther` field.
- update the config. for deriving the columns to accommodate the format for 2021/2022.
- assuming that the 2023/2024 format will be the "default" going forwards.
I've run 2021—2024 locally and SEN2 data are successfully parsed.

fix: update Local Authority SEN2 column mappings

---

front-end-components/index.html
front-end-components/package-lock.json
front-end-components/src/composed/benchmark-chart-send-2/component.tsx
web/src/Web.App/package-lock.json
web/tests/Web.E2ETests/Features/LocalAuthority/HighNeedsBenchmarking.feature
web/tests/Web.E2ETests/Pages/LocalAuthority/HighNeedsBenchmarkingPage.cs

[AB#254031](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/254031) [AB#249557](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249557)
- Updated units
- Updated E2E tests
- Bumped `@babel/runtime`
`front-end` will need to be bumped in `Web` once its pipeline has completed

Set correct `valueUnit` for SEND2 benchmarking charts

---

front-end-components/src/components/charts/utils.test.ts
front-end-components/src/components/charts/utils.ts
front-end-components/src/composed/historic-chart-section-251-composed/component.tsx

[AB#254085](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/254085) [AB#253802](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/253802)
- Number formatting fix for <kbd>Stat</kbd>s in High needs history.
- Number formatting fix for <kbd>LabelList</kbd> currency values
`front-end` will need to be bumped in `Web` after the build pipeline publishes the new artefact.

Modified `<Stat>` and `<LabelList>` value formatting on High needs charts

---

web/src/Web.App/ViewComponents/LocalAuthorityHighNeedsHeadlinesViewComponent.cs
web/src/Web.App/Views/Shared/Components/LocalAuthorityHighNeedsHeadlines/Default.cshtml
web/src/Web.App/Views/Shared/Components/LocalAuthorityHighNeedsHeadlines/MissingData.cshtml
web/src/Web.App/Views/Shared/Components/LocalAuthorityHighNeedsNationalRankings/Default.cshtml

[AB#254429](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/254429) [AB#249575](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/249575)
- Included warning message in the case that some, but not all, headline figures missing
- Set default value for national ranking percentage
Both of the above issues were observed for new LAs without S251 submissions for the most recent academic year. Follow-up work  may alter the way affected LAs are viewed within the High needs dashboard.

Show warning message if partial High needs headline figures available

---

web/src/Web.App/Controllers/LocalAuthorityHighNeedsHistoricDataController.cs
web/src/Web.App/ViewModels/LocalAuthorityHighNeedsHistoricDataViewModel.cs
web/src/Web.App/Views/LocalAuthorityHighNeedsHistoricData/Index.cshtml
web/tests/Web.Integration.Tests/Pages/LocalAuthorities/WhenViewingHighNeedsHistoricData.cs
web/tests/Web.Tests/ViewModels/GivenALocalAuthorityHighNeedsHistoricDataViewModel.cs

[AB#254461](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/254461) [AB#253802](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/253802)
- Check for valid data when building historical data view model
- If missing display warning banner instead of client-resolved `<div>` for the charts
LAs `825`, `838` and `839` may be used to validate this behaviour.

Display warning banner instead of historical High needs when historical data missing

---

data-pipeline/src/pipeline/pre_processing/academies/academies.py

the casing for an `ACADEMYTRUSTSTATUS` of `1 day` has changed in the most recent AAR data.
the casing for an `ACADEMYTRUSTSTATUS` of `1 day` has changed in the most recent AAR data: lower-case the value to avoid any mis-matches.

fix: lower-case "1 day" Academies check

---

platform/src/abstractions/Platform.Search/Requests/SearchRequest.cs
platform/src/abstractions/Platform.Search/SearchService.cs
platform/src/abstractions/Platform.Search/Validators/PostSearchRequestValidator.cs
platform/src/abstractions/tests/Platform.Search.Tests/SearchSearchTests.cs
platform/src/abstractions/tests/Platform.Search.Tests/WhenPostSearchRequestValidatorValidates.cs
platform/src/apis/Platform.Api.Establishment/Features/Schools/PostSchoolsSearchFunction.cs
platform/src/apis/Platform.Api.Establishment/Features/Schools/Routes.cs
platform/src/apis/Platform.Api.Establishment/Features/Schools/SchoolsFeature.cs
platform/src/apis/Platform.Api.Establishment/Features/Schools/Services/SchoolsService.cs
platform/src/apis/Platform.Api.Establishment/Features/Schools/Validators/SchoolsSearchValidator.cs
platform/tests/Platform.Establishment.Tests/Schools/PostSchoolsSearchFunctionTests.cs
platform/tests/Platform.Establishment.Tests/Schools/PostSchoolsSuggestFunctionTests.cs
platform/tests/Platform.Establishment.Tests/Schools/Services/WhenSchoolsServiceIsCalled.cs
platform/tests/Platform.Establishment.Tests/Schools/Validators/WhenSchoolsSearchValidatorValidates.cs

[AB#250281](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/250281) - [AB#255009](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/255009)
Adds new endpoint to establishment `/schools/search`
- facet as `OverallPhase`
- sort ascending or descending on `SchoolName`
- Updates to `abstractions/Platform.Search`
- `SearchService` to use `OrderBy` for sorting
- test coverage for the above
- renames `SchoolsService` method `SuggestAsync` to `SchoolSuggestAsync` and adds some unit tests
Platform API tests to follow on a future PR

feat: add endpoint to establishment for `/schools/search` for faceted school search

---

core-infrastructure/src/db/Core.Database/Views/020-SchoolSummary.sql
core-infrastructure/src/db/Core.Database/Views/021-SchoolSummary.sql
front-end-components/src/main.tsx
front-end-components/src/views/find-organisation/partials/school-input.tsx
front-end-components/src/views/find-organisation/types.tsx
platform/Platform.sln.DotSettings
platform/src/abstractions/Platform.Domain/Characteristics.cs
platform/src/abstractions/tests/Platform.Domain.Tests/WhenExpressionBuilderAddsFilterToList.cs
platform/src/apis/Platform.Api.Establishment/Features/Schools/Requests/SchoolComparatorsRequest.cs
platform/src/apis/Platform.Api.Establishment/Features/Schools/Requests/SchoolSuggestRequest.cs
platform/src/apis/Platform.Api.Establishment/Features/Schools/Services/SchoolsService.cs
platform/src/search/Platform.Search.Resources/School/SchoolDataSourceConnectionBuilder.cs
platform/src/search/Platform.Search.Resources/School/SchoolIndex.cs
platform/src/search/Platform.Search.Resources/SchoolComparators/SchoolComparatorsIndex.cs
web/src/Web.App/Controllers/Api/SuggestProxyController.cs
web/src/Web.App/Infrastructure/Apis/ApiRequests/SchoolSuggestRequest.cs
web/src/Web.App/Infrastructure/Apis/Establishment/EstablishmentApi.cs
web/src/Web.App/Services/SuggestService.cs
web/src/Web.App/Views/SchoolComparatorsCreateBy/Name.cshtml
web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
web/tests/Web.Tests/Infrastructure/GivenAnEstablishmentApi.cs
web/tests/Web.Tests/Services/WhenSchoolSuggestionsIsCalled.cs

[AB#256180](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/256180) [AB#256183](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/256183) [AB#254434](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/254434)
- New `VW_SchoolSummary` view that includes `PeriodCoveredByReturn`
- Included `PeriodCoveredByReturn` in `SchoolIndex` and `SchoolComparatorsIndex`
- Ensured `PeriodCoveredByReturn ne null` for specific `SchoolIndex` suggest requests
- Ensured `PeriodCoveredByReturn ne null` for all `SchoolComparatorsIndex` search requests
- Wired up Web/proxy/component to ensure financial exclusions only set on Suggest requests from 'add comparator by name' page
`front-end` will need to be …

Exclude schools with missing financial data from user defined comparator set creation

---

core-infrastructure/src/db/Core.Database/Views/021-SchoolSummary.sql
platform/src/apis/Platform.Api.Establishment/Features/Schools/Models/SchoolSummary.cs
platform/src/apis/Platform.Api.Establishment/Features/Schools/Services/SchoolsService.cs
platform/src/search/Platform.Search.Resources/School/SchoolIndex.cs
platform/tests/Platform.Establishment.Tests/Schools/PostSchoolsSearchFunctionTests.cs
platform/tests/Platform.Establishment.Tests/Schools/PostSchoolsSuggestFunctionTests.cs
platform/tests/Platform.Establishment.Tests/Schools/Services/WhenSchoolsServiceIsCalled.cs
web/src/Web.App/AssetSrc/scss/main.scss
web/src/Web.App/Controllers/SchoolSearchController.cs
web/src/Web.App/Domain/Insight/SchoolSummary.cs
web/src/Web.App/Services/SearchService.cs
web/src/Web.App/Services/SuggestService.cs
web/src/Web.App/ViewModels/Search/SchoolSearchResultViewModel.cs
web/src/Web.App/Views/Shared/Search/_SchoolSearchResults.cshtml
web/src/Web.App/Views/Shared/Search/_SchoolSearchResultsOptions.cshtml
web/tests/Web.Tests/Services/WhenSchoolSearchServiceIsCalled.cs
web/tests/Web.Tests/Services/WhenSchoolSuggestionsIsCalled.cs
web/tests/Web.Tests/ViewModels/Search/GivenASchoolSearchResultViewModel.cs

[AB#256517](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/256517) [AB#250281](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/250281) #2227 
- Included `TotalPupils` in `SearchIndex` and related results
- Included total pupils and education phase in results listing
Dependent on #2227.

Included total pupils and education phase in results listing

---

pipelines/web/steps/run-e2e-tests.yaml
web/tests/Web.E2ETests/Features/FindOrganisation.feature
web/tests/Web.E2ETests/Pages/FindOrganisationPage.cs
web/tests/Web.E2ETests/Pages/School/SearchPage.cs
web/tests/Web.E2ETests/Steps/FindOrganisationSteps.cs

[AB#255274](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/255274) [AB#250281](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/250281)
E2E for organisation faceted search, toggle-able via category

Added and categorised Find Organisation E2E tests with/out feature flag

---

web/src/Web.App/AssetSrc/scss/main.scss
web/src/Web.App/Controllers/LocalAuthorityHighNeedsBenchmarkingController.cs
web/src/Web.App/ViewModels/LocalAuthorityComparatorSetViewModel.cs
web/src/Web.App/ViewModels/LocalAuthorityComparatorViewModel.cs
web/src/Web.App/ViewModels/LocalAuthorityHighNeedsBenchmarkingViewModel.cs
web/src/Web.App/Views/LocalAuthorityHighNeedsBenchmarking/Comparators.cshtml
web/tests/Web.E2ETests/Features/LocalAuthority/HighNeedsStartBenchmarking.feature
web/tests/Web.E2ETests/Pages/LocalAuthority/HighNeedsStartBenchmarkingPage.cs
web/tests/Web.E2ETests/Steps/LocalAuthority/HighNeedsStartBenchmarkingSteps.cs
web/tests/Web.Integration.Tests/Pages/LocalAuthorities/WhenViewingHighNeedsStartBenchmarking.cs
web/tests/Web.Integration.Tests/Paths.cs

[AB#256803](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/256803) [AB#255674](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/255674)
- Move content to within details component
- Conditional 'cancel' button logic based on referrer query string
- E2E and integration test updates
Follow-up work to wire up the `referrer` query string from the benchmarking page in #2237.

Update content on High needs 'start benchmarking' page

---

front-end-components/index.html
front-end-components/src/main.tsx
front-end-components/src/services/education-health-care-plans-api.tsx
front-end-components/src/services/high-needs-api.tsx
front-end-components/src/views/benchmark-data-high-needs/partials/benchmark-high-needs.tsx
front-end-components/src/views/benchmark-data-high-needs/types.tsx
front-end-components/src/views/benchmark-data-high-needs/view.tsx
web/src/Web.App/Controllers/Api/EducationHealthCarePlansProxyController.cs
web/src/Web.App/Controllers/Api/HighNeedsProxyController.cs
web/src/Web.App/Controllers/LocalAuthorityHighNeedsBenchmarkingController.cs
web/src/Web.App/ViewModels/LocalAuthorityComparatorSetViewModel.cs
web/src/Web.App/ViewModels/LocalAuthorityHighNeedsBenchmarkingViewModel.cs
web/src/Web.App/ViewModels/LocalAuthorityHighNeedsStartBenchmarkingViewModel.cs
web/src/Web.App/Views/LocalAuthorityHighNeedsBenchmarking/Comparators.cshtml
web/src/Web.App/Views/LocalAuthorityHighNeedsBenchmarking/Index.cshtml
web/tests/Web.E2ETests/Features/LocalAuthority/HighNeedsBenchmarking.feature
web/tests/Web.E2ETests/Pages/LocalAuthority/HighNeedsBenchmarkingPage.cs
web/tests/Web.E2ETests/Steps/LocalAuthority/HighNeedsBenchmarkingSteps.cs
web/tests/Web.Integration.Tests/Pages/LocalAuthorities/WhenViewingHighNeedsBenchmarking.cs
web/tests/Web.Integration.Tests/Paths.cs
web/tests/Web.Integration.Tests/Proxy/WhenRequestingEducationHealthCarePlansComparison.cs
web/tests/Web.Integration.Tests/Proxy/WhenRequestingHighNeedsComparison.cs

[AB#256807](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/256807) [AB#255674](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/255674)
- Comparator count and CTA added to benchmarking page, along with 'Back' link
- Passed comparator set to `<BenchmarkDataHighNeeds>` component to prevent requesting again from session via proxy
- E2E and integration test updates
`referrer` query string implementation added in #2236, but there should not be any conflicts with this PR. This will require a `front-end` bump.

Commentary and CTA on High needs benchmarking page

---

web/src/Web.App/package-lock.json

[AB#255674](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/255674) - #2237 
bump `front-end` following changes on #2237 
n/a

chore: bump `front-end` to `1.1.83`

---

web/src/Web.App/package-lock.json

[AB#256840](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/256840) [AB#255683](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/255683) #2240 
following updates on #2240 bump to `front-end`
n/a

chore: bump `front-end` to `1.1.84`

---

documentation/features/7_Validation.md
web/src/Web.App/Constants/PageTitles.cs
web/src/Web.App/Controllers/FindOrganisationController.cs
web/src/Web.App/Controllers/TrustSearchController.cs
web/src/Web.App/ViewModels/Search/FindSchoolViewModel.cs
web/src/Web.App/ViewModels/Search/FindTrustViewModel.cs
web/src/Web.App/ViewModels/Search/ISearchTermViewModel.cs
web/src/Web.App/Views/SchoolSearch/Index.cshtml
web/src/Web.App/Views/SchoolSearch/Search.cshtml
web/src/Web.App/Views/Shared/Search/_SearchTerm.cshtml
web/src/Web.App/Views/TrustSearch/Index.cshtml
web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
web/tests/Web.Integration.Tests/Pages/Schools/Search/WhenViewingSchoolSearch.cs
web/tests/Web.Integration.Tests/Pages/Schools/Search/WhenViewingSchoolSearchResults.cs
web/tests/Web.Integration.Tests/Pages/Trusts/Search/WhenViewingTrustSearch.cs
web/tests/Web.Integration.Tests/Paths.cs

[AB#250287](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/250287) [AB#257771](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/257771)
- Display search form when 'Trust' radio selected on find organisation page when filtered search enabled
- Validation messages
- Documentation around model validation strategy
Intentionally resolves to `404` once form submitted successfully.

Trust search page

---

web/Directory.Packages.props
web/src/Web.App/Controllers/SchoolSearchController.cs
web/src/Web.App/Controllers/TrustSearchController.cs
web/src/Web.App/Infrastructure/Apis/Establishment/Api.cs
web/src/Web.App/Infrastructure/Apis/Establishment/EstablishmentApi.cs
web/src/Web.App/Services/SearchService.cs
web/src/Web.App/packages.lock.json
web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
web/tests/Web.Integration.Tests/Pages/Trusts/Search/WhenViewingTrustSearch.cs
web/tests/Web.Integration.Tests/packages.lock.json
web/tests/Web.Tests/Infrastructure/GivenAnEstablishmentApi.cs
web/tests/Web.Tests/Services/WhenSchoolSearchServiceIsCalled.cs
web/tests/Web.Tests/Services/WhenTrustSearchServiceIsCalled.cs
web/tests/Web.Tests/packages.lock.json

[AB#250287](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/250287) [AB#257773](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/257773) #2263
- Wired up Trust Filtered Search to API
- Tidied up `ISearchService` arguments
- Bumped Web dependencies (including #2220)
Intentionally resolves to `404` once form submitted successfully, even though search should be successful. Dependency on #2263.

Wired up Trust Filtered Search to API

---

web/src/Web.App/Domain/CostCodes.cs
web/tests/Web.Tests/Domain/GivenASubCategoryCostCodes.cs

[AB#258439](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/258439) [AB#258226](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/258226)
- Updated cost codes
- Additional unit tests

Removed `-T` suffix from cost codes

---

web/src/Web.App/Controllers/Api/HighNeedsProxyController.cs
web/src/Web.App/Controllers/Api/Mappers/EducationHealthCarePlansHistoryResponseMapper.cs
web/src/Web.App/Controllers/Api/Mappers/LocalAuthorityHighNeedsResponseMapper.cs
web/src/Web.App/Controllers/Api/Responses/EducationHealthCarePlansResponse.cs
web/src/Web.App/Controllers/Api/Responses/LocalAuthorityHighNeedsResponse.cs
web/src/Web.App/Domain/LocalAuthorities/LocalAuthority.cs
web/src/Web.App/Domain/NonFinancial/LocalAuthorityNumberOfPlans.cs
web/tests/Web.Integration.Tests/Proxy/WhenRequestingEducationHealthCarePlansComparison.cs
web/tests/Web.Integration.Tests/Proxy/WhenRequestingHighNeedsComparison.cs
web/tests/Web.Tests/Controllers/Api/Mappers/WhenEducationHealthCarePlansComparisonResponseMapperMaps.cs
web/tests/Web.Tests/Controllers/Api/Mappers/WhenLocalAuthorityHighNeedsComparisonResponseMapperMapsToApi.cs

[AB#258520](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/258520) [AB#258522](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/258522) #2270
- Added `Population2To18` to `GET /api/local-authorities/education-health-care-plans/comparison` response
- Added `Population2To18` to `GET /api/local-authorities/high-needs/comparison` response
- Unit and integration test updates
Dependency on #2270

Included `Population2To18` in local authority High needs Web proxy responses

---

front-end-components/src/components/context-codes-list/component.tsx
front-end-components/src/components/context-codes-list/index.tsx
front-end-components/src/components/context-codes-list/types.tsx
front-end-components/src/components/cost-codes-list/component.tsx
front-end-components/src/composed/benchmark-chart-section-251/component.tsx
front-end-components/src/composed/benchmark-chart-section-251/types.tsx
front-end-components/src/composed/horizontal-bar-chart-multi-series/composed.tsx
front-end-components/src/composed/horizontal-bar-chart-multi-series/types.tsx
front-end-components/src/views/benchmark-data-high-needs/partials/index.tsx
front-end-components/src/views/benchmark-data-high-needs/partials/section-251-section.tsx
front-end-components/src/views/benchmark-data-high-needs/types.tsx

[AB#258519](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/258519) - [AB#258528](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/258528)
Adds section 251 line codes to the section 251 charts on high needs benchmarking following the existing pattern used for schools as govuk tag components
Also a refactor of the component used for the schools cost codes so it can be reused.
Validate the codes are correct as per the ticket description.
Copy front-end assets to web locally to run and validate the codes appear correct on the high needs benchmarking page and there is no change to the schools spending priorities and comparison pages
E2E tests will follow on a separate PR after a bump to front end

feat: adds section 251 line codes to high needs benchmarking charts

---

front-end-components/src/components/charts/table-chart/component.tsx
front-end-components/src/components/charts/table-chart/partials/table-cell-establishment-name.tsx
front-end-components/src/components/charts/table-chart/types.tsx
front-end-components/src/composed/benchmark-chart-section-251/component.tsx
front-end-components/src/composed/benchmark-chart-send-2/component.tsx
front-end-components/src/services/types.tsx
web/tests/Web.E2ETests/Features/LocalAuthority/HighNeedsBenchmarking.feature
web/tests/Web.E2ETests/Pages/LocalAuthority/HighNeedsBenchmarkingPage.cs
web/tests/Web.Integration.Tests/Pages/LocalAuthorities/WhenViewingHighNeedsStartBenchmarking.cs

[AB#258520](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/258520) [AB#258523](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/258523)
- Rendered `2 to 18 Population` as additional column in High needs tables
- E2E updates for validation of Population data in High needs benchmarking tables
- Fixed compiler warning on `WhenViewingHighNeedsHistoricData`
`front-end` will need to be bumped in `Web` in order to validate changes and E2E to pass.

Added `2 to 18 Population` as additional column in High needs benchmarking tables

---

web/src/Web.App/Controllers/LocalAuthoritySearchController.cs
web/src/Web.App/Infrastructure/Apis/Establishment/Api.cs
web/src/Web.App/Infrastructure/Apis/Establishment/EstablishmentApi.cs
web/src/Web.App/Services/SearchService.cs
web/tests/Web.Tests/Infrastructure/GivenAnEstablishmentApi.cs
web/tests/Web.Tests/Services/WhenLocalAuthoritySearchServiceIsCalled.cs

[AB#250286](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/250286) [AB#257779](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/257779) #2279
- Consume LA search endpoint (but do nothing with the response in this PR)
Dependency on #2279. API call should succeed when searching, but `404` still displayed. This will be resolved in follow-up work.

Wired up Web to Local Authority Search API

---

web/src/Web.App/Middleware/CanonicalHeaderMiddleware.cs
web/src/Web.App/Middleware/MiddlewareOptions.cs
web/src/Web.App/Program.cs
web/src/Web.App/appsettings.Development.json
web/terraform/app-service.tf
web/tests/Web.E2ETests/Features/HomePage.feature
web/tests/Web.E2ETests/Pages/HomePage.cs
web/tests/Web.E2ETests/Steps/HomePageSteps.cs
web/tests/Web.Tests/Middleware/WhenCanonicalHeaderMiddlewareInvokes.cs

[AB#258781](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/258781) [AB#258789](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/258789)
- Added header via custom middleware
- Included new configuration in app service Terraform
- Unit and E2E test coverage 
If new configuration is resolved then new header should be observable in all responses from the web app, e.g.:

Added `rel="canonical"` `Link` header to all responses

---

web/tests/Web.A11yTests/README.md
web/tests/Web.E2ETests/README.md

added readme to e2e and a11y tests projects to make test documentation more structured and manageable.

Readme for test projects

---

web/tests/Web.E2ETests/Features/Trust/Comparators.feature
web/tests/Web.E2ETests/Features/Trust/CreateComparators.feature
web/tests/Web.E2ETests/Pages/Trust/Comparators/RevertComparatorsPage.cs
web/tests/Web.E2ETests/Steps/Trust/ComparatorsSteps.cs
web/tests/Web.E2ETests/Steps/Trust/CreateComparatorsSteps.cs

[AB#254608](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/254608) [AB#260042](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/260042)
Fix failing tests since #2337 merged and `d02` re-seeded.

Clear any previously selected comparator Trusts during E2E run

---

web/terraform/README.md
web/terraform/front-door.tf

[AB#260470](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/260470) [AB#260471](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/260471)
Created Front Door redirect rule to ensure all traffic to non-primary host names is sent to the root path of the primary host name.
Deployed to `d11` feature environment to validate behaviour. Additional endpoint manually associated with Front Door profile in order to test non-primary host name redirection logic.

Defined Front Door redirect rule 

---

web/src/Web.App/Attributes/ValidateArgumentAttribute.cs
web/src/Web.App/Controllers/Api/BalanceProxyController.cs
web/src/Web.App/Controllers/Api/BudgetForecastProxyController.cs
web/src/Web.App/Controllers/Api/CensusProxyController.cs
web/src/Web.App/Controllers/Api/EducationHealthCarePlansProxyController.cs
web/src/Web.App/Controllers/Api/ExpenditureProxyController.cs
web/src/Web.App/Controllers/Api/HighNeedsProxyController.cs
web/src/Web.App/Controllers/Api/IncomeProxyController.cs
web/src/Web.App/Controllers/Api/UserDataProxyController.cs
web/tests/Web.Integration.Tests/Proxy/WhenRequestingCensusHistoryComparison.cs
web/tests/Web.Integration.Tests/Proxy/WhenRequestingExpenditureHistoryComparison.cs
web/tests/Web.Integration.Tests/Proxy/WhenRequestingExpenditureUserDefined.cs
web/tests/Web.Tests/Attributes/GivenAValidateIdAttribute.cs

[AB#254608](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/254608) [AB#260043](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/260043) #2339 
- Implemented action filter above for School/Trust/LA identifiers and applied to proxy controllers actions
- Updated integration tests to ensure all dummy identifiers are of correct format
Dependency on #2339.
Any URL including a bad URN/Company Number/LA code for their respective organisation type should fail with `404` and the 'page not found' view. E2E/A11y should be unaffected.

Applied new `[ValidateId]` attribute to proxy controller actions that consume `id` and `type`

---

web/src/Web.App/Infrastructure/Apis/ApiResults/ApiResult.cs
web/src/Web.App/Infrastructure/Apis/ApiResults/CancelledApiResult.cs
web/src/Web.App/Infrastructure/Extensions/ApiResultExtensions.cs
web/tests/Web.Tests/Infrastructure/GivenAHttpResponseMessage.cs

[AB#260643](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/260643) [AB#260921](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/260921)
`499` errors from API should be treated as neutral and return an empty response rather than re-throw as an exception. The latter pollutes the logs and would never be observed by the client anyway due to that request having been cancelled (via `fetch` signals and `CancellationToken`s).
Easiest way to replicate the original issue is to [browse to a page with a dimension drop down](https://localhost:7095/school/777042/comparison) and quickly switch between dimensions a few times. The API should throw a `System.Threading.Tasks.TaskCanceledException` which is returned to the Web proxy …

Prevent exception being thrown from downstream API user-cancelled tasks

---

core-infrastructure/src/db/Core.Database/Scripts/114-CreateCommercialResourcesTable.sql
core-infrastructure/src/db/Core.Database/Views/024-CommercialResources.sql

[AB#259512](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/259512) [AB#260668](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/260668)
Creates a new table `CommercialResources` with the following columns
- ResourceID
- Category 
- SubCategory
- Title
- Url
- ValidTo
- ValidFrom
Creates a `VW_CommercialResources` view 
Tested scripts locally 
Adds ResourceID as a unique identifier as Category, SubCategory and Title are not guaranteed to be unique if used as a composite primary key (there is at least one occurance where they are not in the current data).

feat: create `CommercialResources` table and view

---

platform/src/abstractions/Platform.Sql/QueryBuilders/CommericalResourcesQueries.cs
platform/src/abstractions/Platform.Sql/QueryBuilders/PlatformQuery.cs
platform/src/apis/Platform.Api.Insight/Configuration/Services.cs
platform/src/apis/Platform.Api.Insight/Constants.cs
platform/src/apis/Platform.Api.Insight/Features/CommercialResources/CommercialResourcesFeature.cs
platform/src/apis/Platform.Api.Insight/Features/CommercialResources/GetCommercialResourcesFunction.cs
platform/src/apis/Platform.Api.Insight/Features/CommercialResources/Parameters/CommercialResourcesParameters.cs
platform/src/apis/Platform.Api.Insight/Features/CommercialResources/Responses/CommercialResourcesResponse.cs
platform/src/apis/Platform.Api.Insight/Features/CommercialResources/Routes.cs
platform/src/apis/Platform.Api.Insight/Features/CommercialResources/Services/CommercialResourcesService.cs
platform/src/apis/Platform.Api.Insight/Features/CommercialResources/Validators/CommericalResourcesParametersValidators.cs
platform/tests/Platform.Insight.Tests/CommercialResources/GetCommercialResourcesFunctionTest.cs
platform/tests/Platform.Insight.Tests/CommercialResources/Parameters/CommercialResourcesParametersTests.cs
platform/tests/Platform.Insight.Tests/CommercialResources/Services/WhenCommercialResourcesServiceQueriesAsync.cs
platform/tests/Platform.Insight.Tests/CommercialResources/Validators/WhenCommercialResourcesParametersValidatorValidates.cs

[AB#259512](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/259512) [AB#260669](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/260669)
Adds new insights endpoint `commercial-resources`
Optional parameter of `categories` a list of cost categories, if passed only records of those categories will be returned. If omitted the default behaviour is to return all commercial resources records from the view.
Temporarily seeded d01 with data for this table for use in development. This will be replaced once the commercial resources links are finalised 
Platform api tests to follow on a future PR

feat: create new insights endpoint `commercial-resources`

---

documentation/developers/11_Task_Cancellation.md
web/src/Web.App/Controllers/Api/ExpenditureProxyController.cs
web/src/Web.App/Controllers/Api/SuggestProxyController.cs
web/src/Web.App/Infrastructure/Extensions/ApiResultExtensions.cs
web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
web/tests/Web.Integration.Tests/Proxy/WhenRequestingExpenditure.cs
web/tests/Web.Integration.Tests/Proxy/WhenRequestingSuggest.cs
web/tests/Web.Tests/Infrastructure/GivenAHttpResponseMessage.cs

[AB#261909](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/261909) [AB#261910](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/261910) [AB#262158](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/262158) #2349
This has been added to known problematic proxy endpoints, but may be expanded to more as required and/or rolled out everywhere with a [global `IActionFilter`](https://learn.microsoft.com/en-us/aspnet/core/web-api/handle-errors?view=aspnetcore-9.0#use-exceptions-to-modify-the-response) instead of manually `try`/`catch`ing in each `ApiController`. This would be managed as new tech debt. As per #2349, this error never reaches the client in the case of a canceled request but …

Prevent error logging to App Insights when underlying task canceled upon client request

---

web/src/Web.App/Controllers/SchoolSpendingController.cs
web/src/Web.App/ViewComponents/ChartActionsSsrViewComponent.cs
web/src/Web.App/ViewComponents/PageActionsSsrViewComponent.cs
web/src/Web.App/ViewComponents/SchoolSpendingCostsSsrViewComponent.cs
web/src/Web.App/ViewComponents/SchoolSpendingCostsViewComponent.cs
web/src/Web.App/ViewModels/Components/ChartActionsViewModel.cs
web/src/Web.App/ViewModels/Components/PageActionsViewModel.cs
web/src/Web.App/ViewModels/SchoolSpendingViewModel.cs
web/src/Web.App/Views/SchoolSpending/CustomData.cshtml
web/src/Web.App/Views/SchoolSpending/CustomDataSsr.cshtml
web/src/Web.App/Views/SchoolSpending/IndexSsr.cshtml
web/src/Web.App/Views/Shared/Components/ChartActionsSsr/Default.cshtml
web/src/Web.App/Views/Shared/Components/PageActions/Default.cshtml
web/src/Web.App/Views/Shared/Components/PageActionsSsr/Default.cshtml
web/src/Web.App/Views/Shared/Components/SchoolSpendingCostsSsr/Default.cshtml
web/tests/Web.Integration.Tests/Pages/Schools/CustomData/WhenViewingCustomDataSpending.cs
web/tests/Web.Integration.Tests/Pages/Schools/WhenViewingSpending.cs

[AB#258039](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/258039) [AB#261663](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/261663)
- Return `Ssr` suffixed views if feature enabled, rather than determine in view components or partials
- This will allow the non-`Ssr` views to be deleted once the feature is enabled and rolled out rather than having to hand pick through code to delete
- Added warning message if SSR enabled but charts could not be loaded
- Updated integration tests
To test the warning message scenario make sure the SSR feature is enabled and then either do not run the `chart-rendering` function app if running locally, or change `appsettings.json` to point to a dummy endpoint. Polly will attempt to …

Return `Ssr` suffixed views if feature enabled

---

front-end-components/index.html
front-end-components/src/components/charts/line-chart/component.tsx

[AB#233948](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/233948) [AB#262258](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/262258)
Fix to y-axis domain under certain scenarios described in the related work item.
Run Web and Platform APIs locally (targeting `d01`) and spin up the Vite dev server to validate the fix for a new school in 2023-4 academic year. `Web` will need `front-end` bump in future PR to pull in the above fix.

Resolved y-axis domain issue when single value being rendered to line chart

---

web/tests/Web.E2ETests/Pages/School/SpendingCostsPage.cs
web/tests/Web.E2ETests/Pages/Trust/Benchmarking/TrustBenchmarkSpendingPage.cs
web/tests/Web.E2ETests/Selectors.cs

[AB#258039](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/258039) [AB#260352](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/260352)
E2E test updates to ensure successful runs with/without the feature flag.
Toggle state of feature flag locally and run the E2E test suite to validate. Most worked out-of-the box, bar some selector changes and whitespace trimming.

Ensured E2E tests pass when chart SSR flag enabled or disabled

---

web/src/Web.App/Constants/PageTitles.cs
web/src/Web.App/Controllers/StaticContentController.cs
web/src/Web.App/ViewModels/HighNeedsGlossaryViewModel.cs
web/src/Web.App/Views/Shared/Components/LocalAuthorityHighNeedsHelp/Default.cshtml
web/src/Web.App/Views/StaticContent/HighNeedsGlossary.cshtml
web/tests/Web.A11yTests/Pages/WhenViewingCostCategoriesGuidance.cs
web/tests/Web.A11yTests/Pages/WhenViewingHighNeedsGlossary.cs
web/tests/Web.E2ETests/Features/HighNeedsGlossary.feature
web/tests/Web.E2ETests/Features/LocalAuthority/HighNeedsDashboard.feature
web/tests/Web.E2ETests/Pages/HighNeedsGlossaryPage.cs
web/tests/Web.E2ETests/Pages/LocalAuthority/HighNeedsDashboardPage.cs
web/tests/Web.E2ETests/Steps/HighNeedsGlossarySteps.cs
web/tests/Web.E2ETests/Steps/LocalAuthority/HighNeedsDashboardSteps.cs

[AB#260743](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/260743) [AB#263948](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/263948)
- Added static High needs glossary page
- E2E and A11y coverage
This first pass adds the page and link from the High needs dashboard. Subsequent PR to populate the actual glossary with supplied content.

Added static High needs glossary page

---

web/src/Web.App/Domain/OverallPhaseTypes.cs
web/src/Web.App/ViewModels/ComparatorCharacteristicsCommentaryViewModel.cs
web/src/Web.App/ViewModels/SchoolComparatorsViewModel.cs
web/src/Web.App/Views/SchoolComparators/Index.cshtml
web/src/Web.App/Views/SchoolComparators/Workforce.cshtml
web/src/Web.App/Views/SchoolFinancialBenchmarkingInsightsSummary/_WhoYouAreComparedWith.cshtml
web/src/Web.App/Views/Shared/_ComparatorCharacteristicsCommentary.cshtml
web/src/Web.App/Views/Shared/_RunningCostCategoriesList.cshtml
web/tests/Web.Integration.Tests/Pages/Schools/Comparators/WhenViewingComparators.cs
web/tests/Web.Tests/Domain/GivenAnOverallPhaseTypes.cs

AB#260808 [AB#263969](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/263969)
- Conditional content change on affected partial view
Browse to `/school/<URN>/comparators` with URNs for schools with different overall phases to verify the existence or not of the SEND commentary.

Added conditional SEND content to 'how we chose schools' commentary

---

web/src/Web.App/Views/Shared/_ComparatorCharacteristicsCommentary.cshtml
web/tests/Web.Integration.Tests/Pages/Schools/Comparators/WhenViewingComparators.cs

[AB#260803](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/260803) [AB#263969](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/263969) #2450
Fix for incorrect implementation in #2450

 Always display all 'chosen based on' items, regardless of school overall phase

---

front-end-components/src/components/context-codes-list/component.tsx
front-end-components/src/components/context-codes-list/types.tsx
front-end-components/src/components/cost-codes-list/component.tsx
web/src/Web.App/package-lock.json
web/tests/Web.E2ETests/Features/School/CompareYourCosts.feature
web/tests/Web.E2ETests/Features/Trust/CompareYourCosts.feature
web/tests/Web.E2ETests/Pages/School/CompareYourCostsPage.cs
web/tests/Web.E2ETests/Pages/Trust/CompareYourCostsPage.cs
web/tests/Web.E2ETests/Steps/School/CompareYourCostsSteps.cs
web/tests/Web.E2ETests/Steps/Trust/CompareYourCostsSteps.cs

[AB#258231](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/258231) [AB#264306](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/264306)
E2E updates to validate cost codes on School/Academy/Trust
`front-end` changes will need to be bumped in `Web` in order for E2E to pass.

E2E test coverage over cost codes for School/Trust comparison

---

web/terraform/README.md
web/terraform/front-door.tf

[AB#263444](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/263444) [AB#264856](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/264856)
Post-SFB decommission tidy up:
- Drop SFB custom domain from Front Door
- Drop rule from Front Door ruleset
- Disassociate ruleset from Front Door route
- This does not actually perform the disassociation in Azure, even though Terraform suggests that this will happen
- Instead this should be done manually, as documented in the [release test plan](#2468) so that the subsequent `terraform plan` is happy
- Possibly a bug in the Azure RM Terraform provider, related to:
- https://github.com/hashicorp/terraform-provider-azurerm/issues/27312 
Deployed to `d18` feature environment for …

Disassociate Front Door rule set with route and remove custom domain

---

web/src/Web.App/Domain/Insight/Expenditure.cs

[AB#261891](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/261891) [AB#265053](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/265053)
Addition of `HighestSalaryEmolumentBandValue` property to `TrustExpenditure`, as already supplied by Insight API endpoints.

Added new property to `TrustExpenditure` model for returning from proxy endpoints

---

web/src/Web.App/package-lock.json

[AB#261891](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/261891) #2475 
bump to `front-end` following changes on #2475 
no impact expected on existing e2e tests.
A future PR will add new tests

chore: bump `front-end` to `1.1.100`

---

front-end-components/src/composed/dimensioned-chart/composed.tsx

[AB#261891](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/261891) #2475 
This PR fixes a regression introduced in #2475
When using the override to set up the context, it now falls back to the existing `SuppressNegativeOrZeroContext` values if the override prop is not provided.
`SchoolCompareYourCostFeature` `schools having 0 for a cost category in comparators set shouldn't display in the chart` tests should now pass after copying front-end assets to web.
Will need another bump to `front-end` following merging this PR to fix the tests.

fix: preserve existing context for suppression of negative and zero values

---

web/src/Web.App/Views/Shared/Components/LocalAuthorityHighNeedsHelp/Default.cshtml
web/src/Web.App/Views/Shared/Components/LocalAuthorityHighNeedsHistory/Default.cshtml
web/src/Web.App/Views/Shared/Components/LocalAuthorityHighNeedsNationalRankings/Default.cshtml
web/tests/Web.E2ETests/Pages/LocalAuthority/HighNeedsDashboardPage.cs
web/tests/Web.Integration.Tests/Pages/LocalAuthorities/WhenViewingHighNeedsDashboard.cs

[AB#265019](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/265019) [AB#265811](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/265811)
Resolves the following reported issues on High Needs dashboard (sic):
1. Buttoned mislabelled on 2nd tab (Planned expenditure vs. outturn). Should be "View full historical spending" as per the 1st tab.
1. Both tabs have a full stop next to vs i.e. DSG high needs funding allocation vs. outturn. Full stops should be removed
1. National view section: The CTA should be labelled 'View full national data' , currently it is 'View full national view'
1. ~~Key information: Can '2023-' be dropped a line so it sits on the same line as 2024? This is a knitpick , so please tell me to stop~~
1. …

Content update pass

---

data-pipeline/src/pipeline/input_schemas/local_authority.py

see the                                                                                                                                                                                                        [official guidance](https://www.gov.uk/government/publications/section-251-2025-to-2026/section-251-budget-guidance#dsg-carry-forward-to-2026-to-2027): we're deriving the `CarriedForwardBalance` from the negative form of the                                                                                                                                1.9.3/gross-expenditure.
[AB#265019](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/265019)  
[AB#265294](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/265294) …

Negate the CarriedForwardBalance

---

web/Directory.Packages.props
web/Web.sln.DotSettings
web/src/Web.App/AssetSrc/scss/main.scss
web/src/Web.App/Middleware/Markdown/GdsMarkdownExtension.cs
web/src/Web.App/Program.cs
web/src/Web.App/ViewModels/HighNeedsGlossaryViewModel.cs
web/src/Web.App/Views/StaticContent/HighNeedsGlossary.cshtml
web/src/Web.App/Web.App.csproj
web/src/Web.App/packages.lock.json
web/tests/Web.E2ETests/Features/HighNeedsGlossary.feature
web/tests/Web.E2ETests/Pages/HighNeedsGlossaryPage.cs
web/tests/Web.E2ETests/Steps/HighNeedsGlossarySteps.cs
web/tests/Web.Integration.Tests/WebAppClientBase.cs
web/tests/Web.Integration.Tests/packages.lock.json
web/tests/Web.Tests/Middleware/WhenGdsMarkdownExtensionIsProcessed.cs
web/tests/Web.Tests/packages.lock.json

[AB#260743](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/260743) [AB#263950](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/263950)
- Modified High Needs glossary page to render High Needs and general glossary in separate tables
- Added markdown support for custom formatted definitions
- Updated E2E tests
See user story for signed off glossary items included here.

 Populated High Needs and General glossary, rendering to view from markdown

---

web/src/Web.App/AssetSrc/scss/main.scss
web/src/Web.App/Constants/PageTitles.cs
web/src/Web.App/Views/Shared/Components/LocalAuthorityHighNeedsHeadlines/Default.cshtml
web/tests/Web.Integration.Tests/Pages/LocalAuthorities/WhenViewingHighNeedsBenchmarking.cs

[AB#265019](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/265019) [AB#265991](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/265991)
- Key information box - year information to be on the same line (i.e. 2023-2024)
- ~~National view CTA - needs to be labelled 'View full national data'~~
- Historical spending - table content should all be left aligned with the exception of the last column.
- Title 'Benchmark High needs' should be a lower case 'h' to be: 'Benchmark high needs'

Content and design pass over latest High Needs pages

---

core-infrastructure/src/db/Core.Database/Scripts/117-CreateBannerTable.sql
core-infrastructure/src/db/Core.Database/Views/025-Banners.sql

[AB#264114](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/264114) [AB#266408](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/266408)
- New table to store banner title, content, target pages and validity
- View over above to only return 'active' rows based on validity date range
Run migrations against a local database to validate.

New `Banner` table definition and 'active' rows view

---

pipelines/documentation/build.yaml
pipelines/documentation/generate-docs.yaml

[AB#266112](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/266112) [AB#266334](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/266334)
As part of `generate-docs.yaml` template extends the existing generate step to verify the correct file is found and exit if not
proposed fix should meet the ACs detailed in the parent work item. 
To validate behaviour, a pipeline was executed after disabling specific checks in commit faa68b6. The pipeline failed correctly when appropriate, and the existing logs appear sufficient for diagnosing issues. See description/comments for a link to the test run on [AB#266339](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/266339)

chore: add check to documentation pipeline to verify pdf created

---

data-pipeline/src/pipeline/main.py
data-pipeline/src/pipeline/pre_processing/ancillary/cdc.py
data-pipeline/src/pipeline/pre_processing/ancillary/census.py
data-pipeline/src/pipeline/pre_processing/ancillary/cfo.py
data-pipeline/src/pipeline/pre_processing/ancillary/gias.py
data-pipeline/src/pipeline/pre_processing/ancillary/high_exec_pay.py
data-pipeline/src/pipeline/pre_processing/ancillary/ilr.py
data-pipeline/src/pipeline/pre_processing/ancillary/ks2.py
data-pipeline/src/pipeline/pre_processing/ancillary/ks4.py
data-pipeline/src/pipeline/pre_processing/ancillary/sen.py
data-pipeline/src/pipeline/stats_collector.py
data-pipeline/tests/unit/test_stats_collector.py

[AB#266558](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/266558)
* Add a new StatsCollector object which is used to log stats across the pipeline run.
* Add relevant stats logic
* Add tests for StatsCollector
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
>Add any additional context or questions for reviewers. Include any dependencies that are required for this change. 
I've run the pipeline for 2023 and 2024 and I can see the stats formed correctly in the `msg_payload` in `stdout`. The orchestrator updates the `CompletedPipelineRun` table so this PR needs to be merged to …

Add pipeline run stats to CompletedPipelineRun table

---

documentation/quality-assurance/4_Performance-Testing.md
documentation/tools/build-docs.sh

[AB#266112](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/266112) [AB#266595](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/266595)
The failures in the documentation pipeline observed following #2515 are caused by a section in `quality-assurance/4_Performance-Testing.md` that is being intepreted as a command while running `pandoc` to generate the PDF.
To resolve this PR simply wraps the offending lines in a code block and the pipeline will now succeed.
This PR also adds additional logging that was helpful while pinpointing the issue.
<details>
</details>
<details>
</details>
<details>
</details>
<details> …

fix failing documentation pipeline

---

web/src/Web.App/Views/SchoolSpending/CustomDataSsr.cshtml
web/src/Web.App/Views/SchoolSpending/IndexSsr.cshtml
web/src/Web.App/Views/Shared/Components/SchoolSpendingCostsSsr/Default.cshtml

[AB#267134](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/267134) [AB#267294](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/267294)
Bug fix to include missing chart stat boxes when SSR charts are enabled on school spending and costs page.
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
Only Web needs to be rebuilt to validate. No changes to enhancements Vue components required.

Wrapped SSR chart and stat boxes in `costs-chart-container` with `uuid` in order to include missing content in saved images

---

front-end-components/index.html
front-end-components/src/components/charts/utils.test.ts
front-end-components/src/components/charts/utils.ts
front-end-components/src/composed/dimensioned-chart/types.tsx
front-end-components/src/composed/horizontal-bar-chart-wrapper/composed.tsx
front-end-components/src/views/compare-your-trust/partials/accordion-sections/non-educational-support-staff.tsx

[AB#265181](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/265181) [AB#267471](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/267471)
Following design input this PR updates the following
- Chart title.
- Adds summary below the title to explain the data.
- Updates the warning text for suppression of negative and zero values
- Updates the values used as part of the labels to display as abbreviated currency rather than just a range. ie `£190k-£200k` rather than `190-200`
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
This PR intentionally …

feat: updates to high executive pay chart

---

.github/dependabot.yml

[AB#227179](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/227179) [AB#270020](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/270020) #2600
Add this folder to dependabot config to ensure checks take place monthly rather than ad-hoc (such as #2600), whilst also allowing fine tuning of pinned/excluded package versions.
Also removed `FluentAssertions` from `ignore` blocks as this package is no longer referenced.
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
It is possible that merging this changed file will cause an immediate dependabot …

Included `/web/src/Web.Shutter` in dependabot config

---

web/src/Web.App/Constants/BreadcrumbNodes.cs
web/src/Web.App/Constants/FinanceTools.cs
web/src/Web.App/Constants/PageTitles.cs
web/src/Web.App/Constants/TrackedRequestType.cs
web/src/Web.App/Controllers/SchoolComparisonItSpendController.cs
web/src/Web.App/ViewModels/SchoolComparisonItSpendViewModel.cs
web/src/Web.App/Views/School/Index.cshtml
web/src/Web.App/Views/SchoolComparisonItSpend/CustomData.cshtml
web/src/Web.App/Views/SchoolComparisonItSpend/Index.cshtml
web/src/Web.App/Views/Shared/Components/SchoolFinanceTools/Default.cshtml
web/tests/Web.Integration.Tests/Pages/Schools/Comparison/WhenViewingComparisonItSpend.cs
web/tests/Web.Integration.Tests/Pages/Schools/WhenViewingHome.cs
web/tests/Web.Integration.Tests/Pages/Schools/WhenViewingHomeAsFederation.cs
web/tests/Web.Integration.Tests/Paths.cs

[AB#270078](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/270078) [AB#270291](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/270291)
- New empty page for School IT spend, behind feature flag
- Conditionally show link through to new page from School home based on finance type and feature flag
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
Intentionally do not perform a school lookup as part of this work item. Future work will cover this, and performing finance type check as required.
Browse to a maintained …

Skeleton school IT spending controller/action/model/view

---

core-infrastructure/src/db/Core.Database/Views/026-ItSpendSchool.sql

[AB#270078](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/270078)
[AB#270288](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/270288)
Adds migration script to core to create the required views to allow dimensioned queries of the IT spend data.
<details>
</details>
<details>
</details>
<details>
</details>
Confirmed basic functionality against a local database. Views are created without errors, and queries return data as expected when tested with mocked IT spend data alongside existing "dimension" data.

feat: add IT spend views

---

web/src/Web.App/Domain/Charts/SchoolComparisonItSpendHorizontalBarChartRequest.cs

[AB#270080](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/270080)
[AB#273906](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/273906)
With certain school names there is still clipping observed on this page
Rather than alter the logic to truncate these labels (see #2703) a minor adjustment to the width results in the desired behaviour.
<details>
</details>
<details>
</details>
<details>
</details>
See the results following this change

feat: update width for horizontal bar chart

---

web/src/Web.App/Controllers/SchoolComparisonItSpendController.cs
web/src/Web.App/Views/SchoolComparisonItSpend/Index.cshtml
web/tests/Web.Integration.Tests/Pages/Schools/Comparison/WhenViewingComparisonItSpend.cs

[AB#270080](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/270080) [AB#275418](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/275418)
Following design review, agreed that current warning banner is jarring within the new filter layout (especially when repeated across several charts).
Includes a refactor to only create the charts when needed.
<details>
</details>
<details>
</details>
<details>
</details>
Agreed with Suly then new layout. It's only application to Benchmark IT Spending.

feat: revised warning banner for postivie values only

---

data-pipeline/src/pipeline/main.py
data-pipeline/src/pipeline/rag/main.py
data-pipeline/src/pipeline/utils/message.py

* There are 2 functions `run_user_defined_rag` and `compute_user_defined_rag` - the incorrect function was being used
* I tested this with the payload, with which I've updated the example payload in the docs
```
{"runId":"a6db019c-d45f-44f3-8af0-71d82c1c6257","year":2025,"urn":"100449","payload":{"_type":"ComparatorSetPipelinePayload","kind":"ComparatorSetPayload","set":["100218","100240","102272","132266","100022","101258","100585","131871","102890","102830","102084","100852","100163","101526","102324","103072","101893","100023","101277","130302","102131","100449"]},"jobId":"7af1abc5-88a9-4447-bdf7-92f4f95dc772","type":"comparator-set","runType":"default"}
```

hotfix: resolve incorrect function names

---

data-pipeline/src/pipeline/rag/__init__.py

* Commit changes to __init__ which allow the correct function to import

hotfix: correct imports in init

---

web/src/Web.Shutter/package-lock.json
web/src/Web.Shutter/package.json

[AB#265000](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/265000) [AB#275477](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/275477)
Updates npm dependencies for `Web.Shutter`. Removes `@types/dotenv` as now [deprecated](https://www.npmjs.com/package/@types/dotenv)
This should close the following dependabot PRs
#2677
#2676 
#2675 
#2674 
<details>
</details>
<details>
</details>
<details>
</details>
Shutter site runs locally following package updates

chore: update `Web.Shutter` dependencies

---

web/src/Web.App/Controllers/NewsController.cs
web/src/Web.App/Domain/Content/News.cs
web/src/Web.App/Extensions/ServiceCollectionExtensions.cs
web/src/Web.App/Infrastructure/Apis/Content/Api.cs
web/src/Web.App/Infrastructure/Apis/Content/NewsApi.cs
web/src/Web.App/Middleware/Markdown/GdsMarkdownExtension.cs
web/src/Web.App/ViewModels/NewsArticleViewModel.cs
web/src/Web.App/Views/News/Article.cshtml
web/src/Web.App/appsettings.Development.json
web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
web/tests/Web.Integration.Tests/Pages/WhenAFeatureIsDisabled.cs
web/tests/Web.Integration.Tests/Pages/WhenViewingNewsArticle.cs
web/tests/Web.Integration.Tests/Paths.cs
web/tests/Web.Tests/Infrastructure/GivenANewsApi.cs
web/tests/Web.Tests/Middleware/WhenGdsMarkdownExtensionIsProcessed.cs

[AB#264127](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/264127) [AB#277309](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/277309) [AB#277316](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/277316) #2781 #2782
- Added Heading support to GDS markdown middleware
- View news article by rendering Body as markdown if API lookup using `slug` in route is successful
- View error/not found page according to unsuccessful API response type
- Integration and unit test coverage
Dependency on #2781 and #2782
<details>
</details>
<details>
</details>
<details>
</details>
<details> …

View news article page based on `slug` in route

---

web/src/Web.App/Views/Shared/_Layout.cshtml
web/tests/Web.Integration.Tests/Pages/WhenViewingLandingPage.cs
web/tests/Web.Integration.Tests/Paths.cs

[AB#265001](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/265001) [AB#277315](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/277315) [AB#277316](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/277316) #2851
- Added footer link only if feature flag is enabled
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
Dependency on #2851

Added 'News' link to site footer based off feature flag setting

---

web/src/Web.App/Constants/TrackedEvents.cs
web/src/Web.App/Extensions/ServiceCollectionExtensions.cs
web/src/Web.App/Extensions/TelemetryClientExtensions.cs
web/src/Web.App/Program.cs
web/src/Web.App/Telemetry/TelemetryClientWrapper.cs
web/tests/Web.Tests/Extensions/GivenATelemetryClient.cs

[AB#269145](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/269145) [AB#278825](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/278825)
- After a successful DSI login, track new event in App Insights with name `user-sign-in-success` and properties that include the user's auth ID and organisation
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
To test locally update `launchSettings.json` to include real AppInsights configuration and run the application. Then sign in as normal and check App Insights Custom Events after …

Track event telemetry after user successfully logs in via DSI

---

data-pipeline/src/pipeline/pre_processing/cfr/calculations.py
data-pipeline/tests/unit/pre_processing/test_maintained_schools.py

[AB#278246](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/278246)
Workforce aggregations for federations were previously not being done correctly - all schools in a federation should be benchmarked against the federation's aggregated workforce figures, just like how we do for pupil numbers.
* Workforce benchmarking numbers for federation schools go up as expected in the NonFinancial table

Tweak federation workforce aggregations

---

documentation/features/9_Commercial-Resources.md
support-analytics/terraform/README.md
support-analytics/terraform/alerts.tf
support-analytics/terraform/queries/commercial-resources-check.kql

[AB#266568](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/266568) [AB#279256](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/279256)
Adds a new alert to trigger on any failures following the nightly check on commercial resources see #2954 
The alert will trigger once daily if any failures are detected in the last 24 hours. The alert will continue to trigger daily as long as any commercial resource checks are failures.
The logs will show all failures and can be viewed quickly from the alert itself. View the alert in Azure Monitor > Query > View results in Logs
Also updates feature documentation for Commercial Resources and the terrform docs for support-analytics
<details> …

feat: new alert added to trigger on any failure on nightly commercial resources check

---

web/src/Web.App/AssetSrc/scss/main.scss
web/src/Web.App/Controllers/TrustComparisonItSpendController.cs
web/src/Web.App/Domain/Charts/TrustComparisonItSpendHorizontalBarChartRequest.cs
web/src/Web.App/Infrastructure/Apis/ApiRequests/PostHorizontalBarChartRequest.cs
web/src/Web.App/ViewModels/TrustComparisonItSpendViewModel.cs
web/src/Web.App/Views/TrustComparisonItSpend/Index.cshtml
web/src/Web.App/Views/TrustComparisonItSpend/_ItSpendChart.cshtml
web/tests/Web.Integration.Tests/Pages/Trusts/Comparison/WhenViewingComparisonItSpend.cs
web/tests/Web.Tests/Domain/Charts/GivenASchoolComparisonItSpendHorizontalBarChartRequest.cs
web/tests/Web.Tests/Domain/Charts/GivenATrustComparisonItSpendHorizontalBarChartRequest.cs
web/tests/Web.Tests/ViewModels/GivenATrustComparisonItSpendViewModel.cs

[AB#260041](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/260041) [AB#281180](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/281180)
- SSR chart `POST` and `SVG` rendering to Trust IT spend page (excluding sensitive charts)
- Unit and integration test coverage
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
Wired up to relatively new Platform API that currently returns only stubbed data.

Added non-sensitive charts to Trust IT spend

---

core-infrastructure/src/db/Core.Database/Views/028-ItSpendTrust.sql

[AB#266041](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/266041) [AB#283330](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/283330)
This PR introduces three views to support trust to trust IT spend benchmarking derived from the `BudgetForecastReturn` table.
- `VW_ItSpendTrustDefaultActual` pivots category values into columns for the IT spend values. Trust name included via a join to `Trust` table.
- `VW_ItSpendTrustCurrentAllYearsActual` filters for RunId for the `LatestBFRYear` and filters for the current, previous, and next years relative to the `LatestBFRYear`. Filtered via a join to the `Parameters` table. 
- `VW_ItSpendTrustCurrentPreviousYearActual` derived from the above view and filters specifically …

feat: create DB views for trust to trust IT spend benchmarking

---

web/src/Web.App/Controllers/TrustComparisonItSpendController.cs
web/src/Web.App/Views/TrustComparisonItSpend/_ItSpendFilter.cshtml
web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
web/tests/Web.Integration.Tests/Pages/Trusts/Comparison/WhenRequestingComparisonItSpendDownload.cs
web/tests/Web.Integration.Tests/Paths.cs

[AB#266041](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/266041) - [AB#281182](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/281182)
Adds download data functionality to the trust benchmark it spending page. Currently only for previous year but this will be extended to conditionally include another csv for forecast when the user has valid claim in a future task on this story
<details>
</details>
<details>
</details>
<details>
</details>

feat: add download data to trust to trust it spend benchmarking page

---

platform/src/apis/Platform.Api.ChartRendering/src/functions/utils.ts
platform/src/apis/Platform.Api.ChartRendering/tests/functions/utils.test.ts
web/src/Web.App/Attributes/TrustAuthorizationAttribute.cs
web/src/Web.App/Controllers/TrustComparisonItSpendController.cs
web/src/Web.App/Domain/Charts/GroupType.cs
web/src/Web.App/Domain/Charts/TrustComparisonItSpendHorizontalBarChartRequest.cs
web/src/Web.App/Domain/Insight/ItSpend.cs
web/src/Web.App/Extensions/ClaimsPrincipalExtensions.cs
web/src/Web.App/Infrastructure/Apis/ApiRequests/ChartRequest.cs
web/src/Web.App/Infrastructure/Apis/Insight/Api.cs
web/src/Web.App/Infrastructure/Apis/Insight/ItSpendApi.cs
web/src/Web.App/Program.cs
web/src/Web.App/Services/TrustItSpendChartService.cs
web/src/Web.App/ViewModels/TrustComparisonItSpendViewModel.cs
web/src/Web.App/ViewModels/TrustComparisonSubCategoriesViewModel.cs
web/src/Web.App/Views/TrustComparisonItSpend/_ItSpendChart.cshtml
web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
web/tests/Web.Integration.Tests/Pages/Trusts/Comparison/WhenViewingComparisonItSpend.cs
web/tests/Web.Tests/Attributes/GivenATrustAuthorizationAttribute.cs
web/tests/Web.Tests/Domain/Charts/GivenATrustComparisonItSpendHorizontalBarChartRequest.cs
web/tests/Web.Tests/Domain/Charts/GivenATrustForecastItSpendHorizontalBarChartRequest.cs
web/tests/Web.Tests/Extensions/GivenAClaimsPrincipal.cs
web/tests/Web.Tests/Infrastructure/GivenAnItSpendApi.cs
web/tests/Web.Tests/Services/WhenTrustItSpendChartServiceIsCalled.cs
web/tests/Web.Tests/ViewModels/GivenATrustComparisonItSpendViewModel.cs
web/tests/Web.Tests/ViewModels/GivenATrustComparisonSubCategoriesViewModel.cs

[AB#266041](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/266041) [AB#283432](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/283432)
- Refactored 'Trust authorisation' logic and evaluated on Trust IT spending page
- Build subcategories with result from Trust IT Forecast API call if authorised to do so
- Send additional API request for SSR charts for Trust IT Forecast if data available
- Modify SSR chart requests for Trust IT spend to include custom domain that matches extremes of forecast data, or spending data, based on the min/max across both data sets
- Prevent filtering out of negative or zero values from Trust IT spend data
- Fixed min/max domains in SSR charts when both evaluate to `0`
- Refactor SSR …

Display 'sensitive' Trust IT Spend data from BFR if authorised to do so

---

web/src/Web.App/Views/TrustComparisonItSpend/Index.cshtml
web/tests/Web.Integration.Tests/Pages/Trusts/Comparison/WhenViewingComparisonItSpend.cs

[AB#266041](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/266041) [AB#281184](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/281184)
- Added enhancement to show 'save' button and trigger existing modal behaviour
- Integration test coverage over existence of button (action to be validated via future E2E tests)
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>

Added 'Save images' button to Trust IT Spend page when viewing as charts

---

web/src/Web.App/Controllers/TrustComparisonItSpendController.cs
web/tests/Web.Integration.Tests/Pages/Trusts/Comparison/WhenRequestingComparisonItSpendDownload.cs

[AB#266041](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/266041) [AB#283847](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/283847)
Updates to allow download of forecast data only if user has valid claim for the selected trust.
Refactor to add new methods to remove duplicate code
- GetTrustUserContextAsync to obtain
- user data
- user defined comparator set
- trust authorisation
- GetTrustItSpendAsync
- bfr current year
- it spend data for the comparator set (previous year)
- it spend forecast data for the selected trust (conditional on trust authorisation)  
Also integration test coverage over this behaviour.
<details>
</details>
<details> …

feat: add download forecast data to trust it spend page

---

core-infrastructure/src/db/Core.Database/Views/028-ItSpendTrust.sql

[AB#266041](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/266041)
The existing implementation incorrectly created the "current" views based on the value of the `LatestBFRYear` row from the `Parameters` table this should be `CurrentYear` so it is always the latest `RunId`. Also updates those views to use sub queries for Parameters to match implementation elsewhere in the service.
<details>
</details>
<details>
</details>
<details>
</details>
Running the migration scripts against a local DB is successful and checking the values against the corresponding rows in the `BudgetForecast` table confirms the values are correct.

fix: updates views for trust it spend
